const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Скрий събитията от икономическия календар на графиката",
              show: "Покажи събитията от икономическия календар на графиката",
            },
          },
          controls: {
            reset: "Нулиране на графиката",
            scrollEnd: "Превърти до края",
            scrollLeft: "Превърти наляво",
            scrollRight: "Превърти надясно",
            zoomIn: "Увеличи",
            zoomOut: "Намали",
          },
          crosshair: "Кръст",
          delay: "забавяне {delay} мин.",
          indicators: {
            btnAddIndicator: "Добави индикатор",
            btnOpenPopup: "Добави индикатор",
            close: "Затвори индикатора",
            form: {
              applyTo: "Приложи за",
              background: {
                title: "Фон",
                down: "Фон down kumo",
                up: "Фон up kumo",
              },
              deviation: "Отклонение",
              enterDistance: "Период",
              enterShift: "Отместване",
              fastEma: "Бърза EMA",
              slowEma: "Бавна EMA",
              line: {
                base: "Базова линия",
                down: "Най-долна линия",
                minusDI: "-DI линия",
                null: "Нулева линия",
                plusDI: "+DI линия",
                style: "Стил на линията",
                cci: "CCI линия",
                up: "Най-горна линия",
                fi: "FI Линия",
              },
              maximum: "Максимум",
              method: {
                exponential: "Експоненциално",
                linearWeighted: "Линейно претеглено",
                simple: "Просто",
                smoothed: "Изгладено",
                title: "Метод",
              },
              opacity: "Прозрачност",
              period: {
                jaws: "Период на челюстите",
                lips: "Период на устните",
                teeth: "Период на зъбите",
                title: "Период",
                dPercent: "Период на %D",
                kPercent: "Период на %K",
              },
              selectApplyTo: "Избор",
              selectVolumesType: "Избор тип обем",
              shift: "Отместване",
              showTimeframes: "Покажи на всички периоди",
              slowing: "Забавяне",
              step: "Стъпка",
              style: {
                down: "Стил низходящ",
                jaws: "Стил на челюстите",
                lips: "Стил на устните",
                main: "Основен стил",
                signal: "Стил на Сигнала",
                teeth: "Стил на зъбите",
                title: "Стил",
                up: "Стил възходящ",
                rvi: "Стил на RVI",
              },
              volume: { down: "Обем надолу", up: "Обем нагоре" },
              volumes: "Обеми",
              mfiUp: "MFI нагоре",
              mfiDown: "MFI надолу",
              price: {
                title: "Цена",
                select: "Избер на цена",
                lowHigh: "Дъно/Връх",
                closeClose: "Затвори",
              },
            },
            search: {
              empty: "Няма намерени елементи",
              title: "Търсене",
              tryAnother: "Опитайте с друго запитване",
            },
            tabs: {
              all: "Всички",
              billWilliams: "Бил Уилямс",
              oscillators: "Осцилатори",
              trend: "Трендови",
              volumes: "Обеми",
            },
            title: "Избери индикатор",
            up: "Нагоре",
            down: "Надолу",
            chartControls: {
              show: "Покажи индикатора",
              hide: "Скрий",
              settings: "Настройки",
              remove: "Изтрий",
            },
          },
          loading: "Зареждане",
          marketWatch: {
            btnOpen: {
              hide: 'Скрий "Състояние на Пазара"',
              show: 'Покажи "Състояние на Пазара"',
            },
            columns: {
              closePrice: "Цена на затваряне",
              dailyChange: "Дневна промяна",
              openPrice: "Цена на отваряне",
              spread: "Спред",
              symbol: "Символ",
              time: "Време",
              high: "High",
              low: "Low",
              last: "Last",
              lastHigh: "Last High",
              lastLow: "Last Low",
              highLow: "High/Low",
              bidLow: "Bid Low",
              bidHigh: "Bid High",
              askHigh: "Ask High",
              askLow: "Ask Low",
              bid: "Bid",
              ask: "Ask",
              title: "Колонки",
            },
            menu: {
              chart: "Графика",
              columns: "Колони",
              dom: "Дълбочина на пазара",
              hide: "Скрий",
              newOrder: "Нова поръчка",
              specification: "Подробности",
            },
            search: "Търсене",
            searchSymbol: "Намери символ",
            nothingFound: "Няма намерен символ",
          },
          objects: {
            form: {
              statistics: "Статистика",
              arrows: "Стрелки",
              showAlways: "Показвай винаги",
              angle: "Ъгъл",
              distance: "Разстояние",
              bar: "Бар",
              price: "Цена",
              prices: "Цени",
              showPrice: "Показвай цената",
              showText: "Показвай текста",
              showDate: "Показвай датата",
              showTime: "Показвай времето",
              showAllTimeframes: "Показвай на всички периоди",
              showPearsonR: "Показвай  Pearson's R",
              showLabels: "Показвай етикетите",
              yourText: "Вашият текст",
              props: "Свойства",
              style: "Стил",
              rays: "Лъчи",
              background: "Фон",
              extends: "Продължение",
              extended: "Продължи линиите",
              pipsPerBar: "Пипса на бар",
              gannAngle: "Ъгъл на Ган",
              deviations: "Отклонения",
              labels: "Етикети",
              reverse: "Обратно",
              btn: { update: "Обнови", cancel: "Отмяна" },
              tabs: {
                style: "Стил",
                coordinates: "Координати",
                visualization: "Визуализация",
              },
              range: {
                price: "Диапазон на цените",
                bars: "Диапазон на баровете",
                date: "Диапазон на датите",
              },
              align: {
                horizontal: "Изравняване по хоризонталата",
                vertical: "Изравняване по вертикалата",
                left: "Ляво",
                right: "Дясно",
                center: "По центъра",
                top: "По върха",
                middle: "Средно",
                bottom: "По дъното",
              },
              line: {
                style: "Стил на линията",
                base: "Базова линия",
                up: "Горна линия",
                down: "Долна линия",
                middle: "Средна линия",
              },
            },
            visible: {
              hide: "Скрий всички обекти",
              show: "Покажи всички обекти",
            },
            lock: "Заключи всички обекти",
            unlock: "Отключи всички обекти",
            andrewsPitchforkChannel: "Вили на Андрюз",
            equidistantChannel: "Равноотдалечен канал",
            regressionChannel: "Регресионен канал",
            stdDevChannel: "Канал стандартно отклонение",
            fibonacciRetracement: "Линии на Фибоначи",
            gannFan: "Ветрило на Ган",
            gannGrid: "Мрежа на Ган",
            gannLine: "Линия на Ган",
            arrowLine: "Линия със стрелка",
            crossLine: "Кръстосани Линии",
            extendedLine: "Разширена Линия",
            horizontalRay: "Хоризонтален лъч",
            horizontalLine: "Хоризонтална линия",
            infoLine: "Линия с данни",
            rayLine: "Лъч",
            trendAngle: "Тренд линия по ъгъл",
            trendline: "Тренд линия",
            verticalLine: "Вертикална линия",
            disjointAngle: "Разходящ канал",
            flatTopBottom: "Плосък връх/дъно",
            rectangle: "Правоъгълник",
            circle: "Kръг",
            triangle: "Триъгълник",
            ellipse: "Елипса",
            text: "Текст",
            rulerLine: "Измерителна линия",
          },
          period: {
            full: {
              D1: "Дневна",
              H1: "1 час",
              H4: "4 часа",
              M1: "1 минута",
              M15: "15 минути",
              M30: "30 минути",
              M5: "5 минути",
              MN: "Месечна",
              Unknown: "Неизвестна",
              W1: "Седмична",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Неизвестна",
              W1: "W1",
            },
          },
          screenshot: "Запази графиката като изображение",
          symbolSpecs: {
            GTCmode: "Вид поръчки",
            calculation: "Изчисление",
            chartMode: "Строеж на графики",
            contractSize: "Размер на контракта",
            days: {
              friday: "Петък",
              monday: "Понеделник",
              saturday: "Събота",
              sunday: "Неделя",
              thursday: "Четвъртък",
              tuesday: "Вторник",
              wednesday: "Сряда",
            },
            digits: "Точност",
            empty: "Няма избран символ",
            execution: "Изпълнение",
            expiration: "Валидна до",
            filling: "Запълване",
            initial: "Първоначален",
            maintenance: "Поддържащ",
            marginCurrency: "Валута на марджин",
            marginRate: "Курс на маржа",
            maxVolume: "Максимален обем",
            minVolume: "Минимален обем",
            orders: "Поръчки",
            profitCurrency: "Валута на печалбата",
            schedule: { quotes: "Котировки", trade: "Търговия" },
            sector: "Сектор",
            spread: "Спред",
            stopsLevel: "Ниво на стоп",
            swapLong: "Суап по дълга позиция",
            swapShort: "Суап по къса позиция",
            swapType: "Вид на суапа",
            title: "Спецификация на договора {symbol}",
            tradeMode: "Търговия",
            volumeStep: "Стъпка на обема",
            volumeLimit: "Лимит на обема",
            tickSize: "Размер на тика",
            tickValue: "Стойност на тика",
            marginInitial: "Начален марж",
            marginHedged: "Хеджиран марж",
            commission: {
              daily: {
                volume: "Ежедневно за обема в лотове",
                turnoverVolume: "Дневен оборот в лотове",
                turnoverMoney: "Дневен оборот в пари",
                value: "Ежедневно за цената на сделките",
                profit: "Ежедневно за печалбата",
              },
              monthly: {
                volume: "Месечно за обема в лотове",
                turnoverVolume: "Месечен оборот в лотове",
                turnoverMoney: "Месечен оборот в пари",
                value: "Месечно за цената на сделките",
                profit: "Месечно за печалбата",
              },
              instant: {
                volume: "Незабавно за обема на сделката",
                value: "Незабавно за цената на сделката",
                profit: "Незабавно за печалбата от сделката",
              },
              entry: {
                in: "входни сделки",
                out: "изходни сделки",
                all: "вход/изход сделки",
              },
              tier: {
                mode: {
                  pips: "пунктове",
                  percent: "% в {currency}",
                  percentProfit: "% печалба {currency}",
                },
                type: { perDeal: "на сделка", perLot: "на лот" },
              },
              header: "Комисиони",
            },
          },
          tree: {
            close: "Затвори",
            empty: "Няма обекти на графиката",
            lock: "Заключи",
            remove: "Премахни",
            settings: "Настройки",
            title: "Управление на обекти",
            unlock: "Отключи",
          },
          types: {
            area: "Област",
            line: "Линеен",
            bars: "Барове",
            candlestick: "Свещи",
          },
          volumeTypes: {
            tickVolumes: "Тикови обеми",
            volumes: "Обеми",
            withoutVolumes: "Без Обеми",
            realVolumes: "Реални обеми",
          },
          zoom: { in: "Увеличи", out: "Намали" },
          hotkeys: {
            arrowLine: "Линия със стрелка",
            chartTypeArea: "Графика с области",
            chartTypeLine: "Линейна графика",
            chartTypeBar: "Графика с барове",
            chartTypeCandle: "Графика със свещи",
            crossLine: "Пресичащи се линии",
            extendedLine: "Разширена линия",
            horizontalLine: "Хоризонтална линия",
            infoLine: "Линия с данни",
            rayLine: "Лъч",
            realVolumes: "Реални обеми",
            tickVolumes: "Тикови обеми",
            trendline: "Тренд линия",
            verticalLine: "Вертикална линия",
            sections: {
              chartType: "Тип графика",
              drawing: "Чертане",
              volume: "Обем",
            },
            crosshairRuler: "Кръстосана линийка",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Създайте вашата сметка",
            newAccountOpened: "Създадена нова сметка",
          },
          brokerInformation: {
            company: "Компания",
            email: "Имейл",
            phone: "Телефон",
            registrationAddress: "Адресна регистрация",
            title: "Информация за компанията",
            website: "Уебсайт",
          },
          changePassword: {
            btnChange: "Промени Password",
            confirmPassword: "Подтвърди Password",
            newPassword: "Нова Password",
            title: "Промени Password",
          },
          connect: {
            btnConnect: "Свързване със сметка",
            contactBroker: "Свързване с компанията",
            forgotPassword: "Забравена Password ?",
            loginPlaceholder: "Въведи Login",
            passwordPlaceholder: "Въведи Password",
            savePassword: "Запази Password",
            title: "Свързване със сметката",
          },
          copyToClipboard: {
            copy: "Копиране в клипборда",
            unsupported: "Копирането не се поддържа",
          },
          demo: {
            accountOpeningWarning:
              "С откриването на сметка вие се съгласявате с условията за откриване на сметка и с политиката за защита на данните на {brokerName}",
            btnOpenDemo: "Отворете Демо сметка",
            title: "Отворете Демо сметка",
            tradeWithRealMoney:
              "За да търгувате с реални пари, трябва да сключите отделно споразумение с компания за финансови услуги.",
          },
          disclaimer: {
            btnAccept: "Потвърждение",
            headerTitle: "Добре дошли в MetaTrader 5",
            text: 'MetaQuotes Ltd е компания за разработка на софтуер и не предоставя никакви финансови, инвестиционни, брокерски услуги, услуги за търговия или подаване на данни, нито участва в плащания на базата на комисионни, свързани с каквито и да е търговски операции.<br /><br />Чрез натискане на Бутон ПРИЕМАМ се съгласяам с <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">правилата и условията на EULA</a>, <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Правила за поверителност</a> и отказ от отговорност.<br /><br /> Нищо от информацията налична в приложението не се явява инвестиционен съвет. Преди да използвате това приложение за търговия, трябва да потърсите съвет от квалифициран и регистриран професионалист по ценни книжа и да предприемете своя собствена надлежна проверка.',
            title: "Предупреждение за риск",
          },
          errors: {
            error: "Грешка",
            invalidCode: "Невалиден код",
            invalidEmail: "Невалиден имейл",
            invalidPhone: "Невалиден телефон",
            unknownError: "Неизвестна грешка",
          },
          form: {
            accountType: "Вид сметка",
            address: "Адрес",
            addressPlaceholder: "Въведете своя адрес",
            annualDeposit: "Годишен депозит",
            annualIncome: "Годишен доход",
            broker: "Компания",
            btn: {
              back: "Назад",
              cancel: "Откажи",
              next: "Следващ",
              openAccount: "Открий сметка",
              remove: "Премахни",
              signOut: "Изход",
            },
            city: "Град",
            cityPlaceholder: "Въведете вашия град",
            country: "Държава",
            dateBirth: "Дата на раждане",
            deposit: "Депозит",
            education: "Образование",
            email: {
              address: "Поща",
              code: "Код от имейл",
              placeholder: "Въведете имейл",
              title: "Имейл",
            },
            employement: "Заетост",
            forex: "Форекс",
            futures: "Фючърси",
            gender: { female: "Женски", male: "Мъжки", title: "Пол" },
            identity: "Личност",
            imageOrPdfFile: "Изображение или PDF файл",
            investor: "Инвеститор",
            language: "Език",
            leverage: "Ливъридж",
            login: "Login",
            min5chars: "Мин. 5 знака",
            name: {
              middle: "Презиме",
              surname: "Фамилия",
              title: "Име",
              yourName: "Вашето име",
            },
            nationality: "Гражданство",
            netWorth: "Нетни активи",
            optional: "Не е задължително",
            password: "Парола",
            passwordReadOnly: "Парола само за четене",
            phone: {
              mobile: "Мобилен телефон",
              number: "Телефонен номер",
              sms: "Код от sms",
            },
            pleaseSelect: "Изберете",
            policyCheckbox:
              "Съгласен съм с условията за откриване на сметка и политиката за защита на данните",
            server: "Сървър",
            side: { back: "Обратна страна", front: "Лицева страна" },
            sourceWealth: "Източник на доход",
            state: "Област",
            status: "Статус",
            stocks: "Акции",
            taxID: "Данъчен номер",
            type: "Вид",
            useHedge: "Използвай хедж в търговията",
            verificationCodes: {
              email: "Изпратихме код за потвърждение на вашия имейл",
              phone: "Изпратихме код за потвърждение на вашия телефон",
              phoneEmail:
                "Изпратихме кодове за потвърждение на вашия телефон и имейл",
            },
            zipCode: "Пощенски код",
          },
          mainForm: {
            title: "Търговски сметки",
            titleWithName: "Търговски сметки: {brokerName}",
          },
          otp: {
            disable2FA: "Деактивиране на 2FA/TOTP",
            disable2FAAccount: "Деактивиране на 2FA/TOTP за сметка {login}",
            disableEnterCode:
              "За деактивиране на 2FA/TOTP, моля въведете кода на вашата сметка, генериран от Authenticator.",
            downloadApp:
              "Моля, изтеглете приложението Google Authenticator / Microsoft Authenticator / Authy App на вашето мобилно устройство и сканирайте QR кода:",
            enable2FA: "Активиране на 2FA/TOTP",
            enable2FAAccount: "Активиране на 2FA/TOTP за сметка {login}",
            enterCode:
              "За да тествате работата на удостоверяването, въведете генерирания код от приложението.",
            oneTimePassword: "Еднократна парола:",
            placeholder: "Въведете OTP за сметката",
            required:
              "За допълнителна сигурност на сметката трябва да използвате 2FA удостоверяване.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Банково извлечение",
              utilityBill: "Сметка за комунални услуги",
            },
            conditionsForUploadingFiles: {
              documents:
                "Някои видове документи изискват две снимки: лицева и задна страна",
              proofAddress:
                "Сметките за мобилни услуги не се приемат като доказателство за адрес",
              utilityBill:
                "Сметката за комунални услуги трябва да съдържа вашето име и адрес и да не е по-стара от 3 месеца",
            },
            documentType: {
              driverLicense: "Шофьорска книжка",
              idCard: "Лична карта",
              passport: "Паспорт",
              residencePermit: "Разрешение за пребиваване",
            },
            educationLevel: {
              bachelor: "Бакалавърска степен или еквивалент",
              highScholl: "Гимназия",
              master: "Магистърска степен или еквивалент",
              none: "Отсътства",
              other: "Друг",
              phd: "PHD или еквивалент",
            },
            employment: {
              employed: "Трудоустроен(а)",
              other: "Друго",
              retired: "Пенсионер",
              selfEmployed: "Собственик или самозаето лице",
              student: "Студент(ка)",
              unemployed: "Безработен(а)",
            },
            experience: "Реален търговски опит",
            experienceLevel: {
              above3: "> 3 години",
              form1to3: "1 до 3 години",
              less1: "<1 година",
            },
            industry: {
              agriculture: "Селско стопанство, храни и природни ресурси",
              communication: "Изкуство, аудио / видео технологии и комуникации",
              construction: "Архитектура и строителство",
              education: "Образование и обучение",
              engineering: "Инженерство и математика",
              government: "Държавна и публичната администрация",
              healthcare: "Здравеопазване",
              it: "Информационни технологии",
              management: "Бизнес управление и администрация",
              manufacturing: "Производство",
              marketing: "Маркетинг и продажби",
              none: "Непоказан",
              other: "Друг",
              science: "Наука и технологии",
              security: "Правна и обществена сигурност, корекции и сигурност",
              tourism: "Хотелиерство и туризъм",
              transport: "Транспорт, дистрибуция и логистика",
            },
            policy:
              "Личните данни се използват за откриване на търговска сметка и не се предават на трети лица. Информацията се обработва сигурно и поверително.",
            takePhoto:
              "Моля, направете снимки на вашите документи и ги качете тук без никаква редакция",
            title: "Отвори Реална сметка",
            wealthSource: {
              employment: "Приходи от заетост или бизнес",
              inheritance: "Дарение или наследство",
              other: "Други",
              savings: "Спестявания или инвестиции",
            },
          },
          saveAccountData:
            "Моля, запазете вашето потребителско име и парола на сигурно място",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Затвори",
            empty: "Данните за обема не са налични за този символ",
            extendedBook: {
              hide: "Скрий разширената дълбочина на пазара",
              show: "Покажи разширената дълбочина на пазара",
            },
            menu: {
              amount: "Единици вместо лотове",
              extended: "Разширен режим",
              spread: "Спред",
            },
            spread: { hide: "Скрий спреда", show: "Покажи спреда" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Дълбочина на пазара",
          },
          errors: {
            accepted: "Приет",
            allowedOnlyLongPositions: "Разрешени са само дълги позиции",
            allowedOnlyPositionsClosing:
              "Разрешено е само затваряне на позиции",
            allowedOnlyShortPositions: "Разрешени са само къси позиции",
            automatedTradingDisabledClient:
              "Автоматичната търговия е изключена от клиентския терминал",
            automatedTradingDisabledServer:
              "Автоматичната търговия е изключена от сървъра",
            canceled: "Анулирана",
            common: "Обща грешка",
            demoAllocationDisabled: "Изборът на демо сметки е забранен",
            done: "Изпълнено",
            donePartially: "Частично изпълнено",
            frequentRequests: "Твърде чести заявки",
            invalidExpiration: "Невалидна дата на изтичане",
            invalidOrderType: "Невалиден вид на поръчка",
            invalidParameters: "Невалидни параметри",
            invalidPrices: "Невалидни цени",
            invalidSLTP: "Невалиден S/L или T/P",
            invalidVolume: "Невалиден обем",
            manyTradeRequests: "Твърде много заявки за търговия",
            marketClosed: "Пазарът е затворен",
            modificationFailed:
              "Промяната не е изпълнена, поради прекалена близост на поръчката или позицията до пазара",
            networkProblem: "Проблем с връзката",
            noConnection: "Няма връзка",
            notEnoughMoney: "Нямате достатъчно средства",
            offQuotes: "Няма котировки",
            ok: "ОК",
            onTheWay: "Изпратено",
            orderChanged: "Поръчката вече е била променена",
            orderClosePositionExists:
              "Вече съществува поръчка за закриване на тази позиция",
            ordersLimitReached: "Достигнат лимит на поръчките",
            permissions: "Недостатъчни права",
            placed: "Поставено",
            positionCloseProhibitedByFIFO:
              "Затварянето на поръчка е забранено от правилото FIFO",
            positionClosed: "Поръчката вече е затворена",
            positionsLimitReached: "Достигнат е лимит на поръчките",
            priceChanged: "Цената е променена",
            prices: "Цени",
            processed: "Обработена",
            rejected: "Отхвърлена",
            requestRejectedOrderWillCanceled:
              "Заявката е отхвърлена, поръчката е отменена",
            requoted: "Рекотирано",
            serverProblem: "Технически проблем със сървъра",
            timeout: "Времето изтече",
            tradeDisabled: "Търговията е забранена",
            unsupportedFillingMode: "Неподдържан режим на изпълнение",
            volumeLimitReached: "Достигнат лимит на обема",
          },
          form: {
            acceptNewQuotes: "Приемате ли новите котировки?",
            btnOpen: {
              hide: "Скрий формата за търговия",
              show: "Покажи формата за търговия",
              title: "Нова поръчка",
            },
            buttons: {
              accept: "Потвърди",
              delete: "Изтрий",
              modify: "Промени",
              ok: "ОК",
              placeOrder: "Подаване на поръчка",
              reject: "Откажи",
              request: "Заявка",
              requestPrice: "Поискай цена",
            },
            close: "Затвори",
            execution: {
              fillOrKill: "Всичко/Нищо",
              immediateOrCancel: "Всичко/Частично",
              bookOrCancel: "Пасивно",
              label: "Запълване",
              return: "Върни",
            },
            executionMode: {
              exchange: "Борсово изпълнение",
              instant: "Моментално изпълнение",
              market: "Пазарно изпълнение",
              request: "Поискано изпълнение",
            },
            expiration: {
              date: "Дата на изтичане",
              label: "Валидна до",
              types: {
                specified: "Дата и час",
                specifiedDay: "Посоченият ден",
                today: "Днес",
              },
            },
            fields: {
              closeBy: "Затвори с насрещна",
              comment: "Коментар",
              price: "Цена",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Обем",
              errors: {
                volume: {
                  min: "Минимален обем — {min}",
                  max: "Максимален обем — {max}",
                  required: "Volume is required",
                  step: "Обемът се задава със стъпка {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "История",
            deals: {
              columns: {
                comment: "Коментар",
                commission: "Комисионa",
                direction: "Посока",
                fee: "Такса",
                order: "Поръчка",
                price: "Цена",
                profit: "Печалба",
                swap: "Суап",
                symbol: "Символ",
                ticket: "Поръчка",
                time: "Време",
                type: "Вид",
                volume: "Обем",
              },
            },
            empty: "Все още нямате история на търговия",
            menu: {
              columns: {
                horizontalScroll: "Хоризонтално скролиране",
                resetAll: "Нулиране на всичко",
                title: "Колони",
              },
              deals: "Сделки",
              orders: "Поръчки",
              period: {
                all: "Цялата история",
                last3Months: "Последните 3 месеца",
                last6months: "Последните 6 месеца",
                lastMonth: "Последният месец",
                title: "Период",
                customPeriod: "Избран период",
                lastYear: "Последният година",
                lastWeek: "Последният седмица",
                today: "Днес",
              },
              positions: "Позиции",
              chart: "Графика",
              newOrder: "Нова поръчка",
            },
            orders: {
              columns: {
                comment: "Коментари",
                price: "Цена",
                slDescription: "Стоп",
                state: "Състояние",
                symbol: "Символ",
                ticket: "Поръчка",
                timeDone: "Време",
                timeSetup: "Време",
                tpDescription: "Take Profit",
                type: "Вид",
                volume: "Обем",
                timeSetupDescription: "Време на отваряне",
                timeDoneDescription: "Време на закриване",
              },
              total: {
                title: "Общо",
                filled: "Изпълнена",
                canceled: "Анулирана",
                rejected: "Отхвърлена",
              },
            },
            positions: {
              columns: {
                commission: "Комисиони",
                fee: "Такса",
                priceClose: "Цена",
                priceCloseDescription: "Цена на затваряне",
                priceOpen: "Цена",
                priceOpenDescription: "Цена на отваряне",
                profit: "Печалба",
                slDescription: "Стоп",
                swap: "Суап",
                symbol: "Символ",
                ticket: "Поръчка",
                timeClose: "Време",
                timeCloseDescription: "Време на затваряне",
                timeOpen: "Време",
                timeOpenDescription: "Време на отваряне",
                tpDescription: "Лимит",
                type: "Вид",
                volume: "Обем",
                comment: "Коментар",
              },
            },
            columns: { default: "По подразбиране" },
            total: {
              profit: "Печалба",
              credit: "Кредит",
              deposit: "Депозит",
              withdrawal: "Изтегляне",
              balance: "Баланс",
              commission: "Комисиона",
              fee: "Такса",
              swap: "Суап",
              grossProfit: "Брутна печалба",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Търговска история",
                orders: "Търговски поръчки",
                position: "Търговски позиции",
                sltp: "Нива SL/TP",
              },
              notification: "Търговски съобщения",
            },
            oneClick: "Търговия с един клик",
            tags: { demo: "Демо", readonly: "Само преглед" },
            oneClickBottom: "Панелът за търговия с един клик е под графиката",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Приемам тези условия",
            btnAccept: "Потвърждение",
            btnCancel: "Откажи",
            text: 'Желаете да активирате режима "Търговия с един клик". Избирайки "Приемам тези условия", вие потвърждавате, че сте прочели, разбрали и сте съгласни с всички от следните условия.<br /><br />Можете да включите или изключите режима "Търговия с един клик" в менюто на уеб терминала.<br /><br />Режимът за изпращане на търговска поръчка "Търговия с един клик" се състои от една стъпка. Вашата заявка за търговия ще бъде изпратена незабавно: &mdash; когато натиснете бутоните SELL или BUY на панела за търговия с един клик на графиката &mdash; при натискане на бутони "Sell", "Buy", "Close" и команди за даване на поръчки в прозореца "Дълбочина на пазара" &mdash; при затваряне на позиция и изтриване на поръчки в раздел "Търговия"<br /><br />НЯМА ДА БЪДЕТЕ ПОМОЛЕНИ ДА ПОТВЪРДИТЕ ПОРЪЧКАТА ЗА ТЪРГОВИЯ. НЯМА ДА МОЖЕТЕ ДА АНУЛИРАТЕ ИЛИ ДА ПРОМЕНИТЕ ПОРЪЧКАТА СИ СЛЕД КЛИКВАНЕ. ПРИ НОРМАЛНИ ПАЗАРНИ УСЛОВИЯ И ПРОИЗВОДИТЕЛНОСТ НА СИСТЕМАТА, ПАЗАРНАТА ПОРЪЧКА ЩЕ БЪДЕ ИЗПЪЛНЕНА НЕЗАБАВНО, СЛЕД КАТО ПОРЪЧКАТА БЪДЕ ПОДАДЕНА И ВИЕ ЩЕ БЪДЕТЕ ОБВЪРЗАНИ С ТРАНЗАКЦИЯТА.<br /><br />Вие се съгласявате да приемете всички рискове, свързани с използването на режима "Търговия с един клик“, включително, без ограничение, всички рискове от грешки, пропуски или погрешни изчисления, направени при подаване на такава търговска поръчка.<br /><br />Вие се съгласявате напълно да предпазите {companyName} от всякакви загуби, разходи или разноски, които могат да възникнат в резултат на такива грешки, пропуски или погрешни изчисления от вас или друго лице, търгуващо от ваше име.',
            title: "Търговия с един клик - отказ от отговорност",
          },
          quickTrade: {
            hide: "Скрий панела за търговия с един клик",
            show: "Покажи панела за търговия с един клик",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Осъзнавам риска и искам да търгувам с инвестиционни продукти",
            btnAccept: "Потвърди",
            btnCancel: "Откажи",
            text: "Информираме ви, че продължаването на използване на тази платформа за търговия предполага достъп до високорискови инвестиционни продукти, предоставени от финансовата институция по ваш избор. Инвестирането в такива продукти може да не е подходящо за всички инвеститори, тъй като носи риск от загуба на част или целия ви депозит.<br /><br />Преди да решите да търгувате с високорискови инвестиционни продукти, трябва внимателно да оцените своите инвестиционни цели, ниво на подготовка и приемливи рискове. Има вероятност да загубите повече от първоначалната си инвестиция, така че не трябва да инвестирате пари, които не можете да си позволите да загубите.<br /><br />Препоръчваме ви да разширите познанията си по отношение на всички рискови фактори, свързани с инвестирането в такива продукти, а също така, в случай на съмнение, да се консултирате с професионален финансов съветник.",
            title: "Предупреждение за висок риск",
          },
          table: {
            btnOpen: "Търговия",
            columns: {
              comment: "Коментари",
              priceClose: "Цена",
              priceCloseDescription: "Цена на затваряне",
              priceOpen: "Цена",
              priceOpenDescription: "Цена на отваряне",
              profit: "Печалба",
              slDescription: "Стоп",
              swap: "Суап",
              symbol: "Символ",
              ticket: "Поръчка",
              time: "Време",
              tpDescription: "Лимит",
              type: "Вид",
              volume: "Обем",
            },
            emptyPlug: {
              btnNewOrder: "Създай нова поръчка",
              title: "Нямате позиции",
            },
            menu: {
              chart: "Графика",
              closePosition: "Затваряне на позиция",
              columns: "Колони",
              modifyOrder: "Промени поръчка",
              modifyPosition: "Промяна на позиция",
              newOrder: "Нова поръчка",
              resetAll: "Нулиране на всичко",
              deleteOrder: "Изтрий поръчка",
            },
            oneClick: { deleteOrder: "Изтрий" },
            sections: {
              collateralPositions: "Collateral-позиции",
              orders: "Поръчки",
              positions: "Позиции",
            },
            total: {
              assets: "Активи",
              balance: "Баланс",
              collateral: "Обезпечение",
              commission: "Комисион",
              credit: "Кредит",
              equity: "Текущ баланс",
              liabilities: "Задължения",
              margin: "Марджин",
              marginFree: "Свободен марджин",
              marginLevel: "Ниво",
            },
          },
          timer: {
            marketWillOpen: "Пазарът ще бъде отворен след {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} дни",
            oneDay: "{numberOfDays} ден",
          },
          tradeIsDisabled: {
            account: "Търговията за тази сметка е изключена на сървъра",
            collateral: "Търговията е недостъпна за collateral-инструменти",
            disabled: "Търговията е изключена",
            investor:
              "Търговията е недостъпна, защото сте свързани с парола на инвеститор",
            readOnly:
              "Търговията е недостъпна, защото не сте приели предупреждението за риск",
            symbol: "Търговията е изключена за този символ",
          },
          hotkeys: {
            historyPanel: "Панел история",
            journalPanel: "Журнал",
            marketWatch: "Състояние на пазар",
            quickTrade: "Търговия с един клик",
            tradeForm: "Нова поръчка",
            tradePanel: "Панел търговия",
          },
          marketOpen: {
            time: "Пазарът е затворен - отваряне в {time}",
            afterSeconds: "Пазарът е затворен - отваряне след {time} сек",
          },
          expiredTimer: { seconds: "Изтича след {time} сек" },
          corporateLink: {
            type: {
              clientAgreement: "Клиентско споразумение",
              riskDisclosure: "Оповестяване на риска",
              fdmDisclaimer: "Отказ от отговорност FDM",
              clientAgreementAndRiskDisclosure:
                "Клиентско споразумение и разкриване на риска",
              complaintsHandlingProcedure: "Процедура за разглеждане на жалби",
              orderExecutionPolicy: "Правила за изпълнение на поръчките",
              clientCategorisationNotice: "Известие за категоризация на клиент",
              conflictsOfInterestPolicy: "Политика на конфликти на интереси",
              dataProtectionPolicy: "Политика за защита на данните",
            },
          },
          margin: {
            floating: "плаваща",
            mode: {
              marketBuy: "Пазарна поръчка Buy",
              marketSell: "Пазарна поръчка Sell",
            },
            rangeMode: {
              value: "номинална стойност",
              valuePerSymbol: "номинална стойност по символ",
              volume: "обем",
              volumePerSymbol: "обем по символ",
            },
            showValue: "Покажи стойностите в {currency} на лот",
            rates: "Марджин:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: { disable: "Нормален екран", enable: "Цял екран" },
          journal: {
            btnOpen: "Журнал",
            columns: {
              message: "Съобщение",
              source: "Източник",
              time: "Време",
            },
            menu: {
              clear: "Изчисти",
              debugMode: "Дебъг режим",
              exportFile: "Експортиране във файл",
            },
          },
          menu: {
            about: "За програмата",
            contact: "Свържете се с нас",
            brokerInformation: "Информация за компанията",
            chartSettings: {
              controls: "Управление на графиката",
              grid: "Мрежа",
              ohlc: "Покажи OHLC",
              title: "Настройки на графиката",
              askPrice: "Цена продава",
              crosshair: "Курсор с кръст",
            },
            connect: "Свързване със сметка",
            language: {
              title: "Език",
              search: "Търсене",
              nothingFound: "Езикът не е намерен",
            },
            openDemo: "Отвори демо сметка",
            openReal: "Отвори реална сметка",
            settings: "Настройки",
            shortcuts: "Бутони за бърз достъп",
            theme: {
              blackWhite: "Черно & Бяло",
              blueRed: "Синьо & Червено",
              dark: "Тъмна Тема",
              editor: "Редактор на теми",
              greenRed: "Зелено & Червено",
              light: "Светла Тема",
              neutral: "Неутрална",
              templates: "Цветни шаблони",
            },
            title: "Меню",
            tradingAccount: "Търговски сметки",
            terms: "Условия за ползване",
            desktopPlatforms: "Настолни платформи",
            qrCode: {
              install: "Сканирайте за инсталиране от {store}",
              downloadApk: "Сканирайте, за да получите APK файл за Android",
            },
            economicCalendar: "Икономически календар",
          },
          screen: { back: "Назад" },
          mobile: { bottomNav: { quotes: "Котировки" } },
          hotkeys: {
            sections: { navigation: "Навигация", view: "Изглед" },
            escape: "Откажи",
            indicators: "Индикатори",
            depthOfMarket: "Дълбочина на пазара",
            objectTreePanel: "Дърво на обекти",
            scrollRight: "Следваща свещ",
            scrollToStart: "Превърти графиката до начало",
            scrollLeft: "Предишна свещ",
            scrollToEnd: "Превърти графиката до край",
            resetChartView: "Нулиране на графиката",
            zoomIn: "Увеличи",
            zoomOut: "Намали",
            fullScreen: "Цял екран",
            screenshot: "Запази графиката като изображение",
            title: "Бутони за бърз достъп",
          },
          timezone: {
            title: "Часова зона",
            city: {
              cairo: "Кайро",
              casablanca: "Казабланка",
              johannesburg: "Йоханесбург",
              lagos: "Лагос",
              nairobi: "Найроби",
              tunis: "Тунис",
              anchorage: "Анкъридж",
              bogota: "Богота",
              buenosAires: "Буенос Айрес",
              caracas: "Каракас",
              chicago: "Чикаго",
              denver: "Денвър",
              elSalvador: "Ел Салвадор",
              juneau: "Джуно",
              lima: "Лима",
              losAngeles: "Лос Анжелис",
              mexicoCity: "Мексико сити",
              newYork: "Ню Йорк",
              phoenix: "Феникс",
              santiago: "Сантяго",
              saoPaulo: "Сао Пауло",
              toronto: "Торонто",
              vancouver: "Ванкувър",
              almaty: "Алмати",
              ashgabat: "Ашхабад",
              bahrain: "Бахрейн",
              bangkok: "Банкок",
              kolkata: "Колката",
              colombo: "Коломбо",
              dhaka: "Дака",
              dubai: "Дубай",
              hongKong: "Хонг Конг",
              jakarta: "Джакарта",
              jerusalem: "Йерусалим",
              karachi: "Карачи",
              kathmandu: "Катманду",
              kuwait: "Кувейт",
              manila: "Манила",
              muscat: "Мускат",
              nicosia: "Никозия",
              qatar: "Катар",
              rangoon: "Рангун",
              riyadh: "Рияд",
              saigon: "Сайгон",
              seoul: "Сеул",
              shanghai: "Шанхай",
              singapore: "Сингапур",
              taipei: "Тайпе",
              tehran: "Техеран",
              tokyo: "Токио",
              reykjavik: "Рейкявик",
              adelaide: "Аделаида",
              brisbane: "Бризбейн",
              perth: "Пърт",
              sydney: "Сидни",
              amsterdam: "Амстердам",
              athens: "Атина",
              belgrade: "Белград",
              berlin: "Берлин",
              bratislava: "Братислава",
              brussels: "Брюксел",
              bucharest: "Букурещ",
              budapest: "Будапеща",
              copenhagen: "Копенхаген",
              dublin: "Дъблин",
              helsinki: "Хелзинки",
              istanbul: "Истанбул",
              lisbon: "Лисабон",
              london: "Лондон",
              luxembourg: "Люксембург",
              madrid: "Мадрид",
              malta: "Малта",
              moscow: "Москва",
              oslo: "Осло",
              paris: "Париж",
              prague: "Прага",
              riga: "Рига",
              rome: "Рим",
              stockholm: "Стокхолм",
              tallinn: "Талин",
              vienna: "Виена",
              vilnius: "Вилнюс",
              warsaw: "Варшава",
              zurich: "Цюрих",
              auckland: "Окланд",
              chatham: "Чатъм",
              fakaofo: "Факаофо",
              honolulu: "Хонолулу",
              norfolk: "Норфолк",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, e as b, o as c, i as d };
