const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Ocultar los eventos del calendario económico del gráfico",
              show: "Mostrar los eventos del calendario económico en el gráfico",
            },
          },
          controls: {
            reset: "Resetear el gráfico",
            scrollEnd: "Desplazar hasta el final",
            scrollLeft: "Desplazar hacia la izquierda",
            scrollRight: "Desplazar hacia la derecha",
            zoomIn: "Acercar",
            zoomOut: "Alejar",
          },
          crosshair: "Cursor en cruz",
          delay: "retraso {delay} min",
          indicators: {
            btnAddIndicator: "Añadir un indicador",
            btnOpenPopup: "Añadir indicador",
            close: "Cerrar",
            form: {
              applyTo: "Aplicar a",
              background: {
                title: "Fondo",
                down: "Fondo down kumo",
                up: "Fondo up kumo",
              },
              deviation: "Desviación",
              enterDistance: "Periodo",
              enterShift: "Desplazamiento",
              fastEma: "EMA rápida",
              slowEma: "EMA lenta",
              line: {
                base: "Línea básica",
                down: "Línea descendente",
                minusDI: "Línea -DI",
                null: "Línea cero",
                plusDI: "Línea +DI",
                style: "Estilo de la línea",
                cci: "Línea CCI",
                up: "Línea ascendente",
                fi: "Línea FI",
              },
              maximum: "Máximo",
              method: {
                exponential: "Exponencial",
                linearWeighted: "Lineal Ponderado",
                simple: "Simple",
                smoothed: "Suavizado",
                title: "Método",
              },
              opacity: "Transparencia",
              period: {
                jaws: "Periodo de las mandíbulas",
                lips: "Periodo de los labios",
                teeth: "Periodo de los dientes",
                title: "Periodo",
                dPercent: "Período %D",
                kPercent: "Período %K",
              },
              selectApplyTo: "Seleccionar",
              selectVolumesType: "Seleccione el tipo de volumen",
              shift: "Desplazamiento",
              showTimeframes: "Mostrar en todos los periodos",
              slowing: "Ralentización",
              step: "Paso",
              style: {
                down: "Estilo descendente",
                jaws: "Estilo de las mandíbulas",
                lips: "Estilo de los labios",
                main: "Estilo principal",
                signal: "Estilo de la señal",
                teeth: "Estilo de los dientes",
                title: "Estilo",
                up: "Estilo ascendente",
                rvi: "Estilo RVI",
              },
              volume: { down: "Volumen descendente", up: "Volumen ascendente" },
              volumes: "Volúmenes",
              mfiUp: "MFI ascendente",
              mfiDown: "MFI descendente",
              price: {
                title: "Precio",
                select: "Seleccione precio",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No se ha encontrado nada",
              title: "Buscar",
              tryAnother: "Por favor, intente otra consulta",
            },
            tabs: {
              all: "Todos",
              billWilliams: "Bill Williams",
              oscillators: "Osciladores",
              trend: "De tendencia",
              volumes: "Volúmenes",
            },
            title: "Seleccione indicador",
            up: "Arriba",
            down: "Descendente",
            chartControls: {
              show: "Mostrar",
              hide: "Ocultar",
              settings: "Configuración",
              remove: "Eliminar",
            },
          },
          loading: "Cargando",
          marketWatch: {
            btnOpen: {
              hide: "Ocultar Observación de Mercado",
              show: "Mostrar Observación de Mercado",
            },
            columns: {
              closePrice: "Precio de cierre",
              dailyChange: "Cambio diario",
              openPrice: "Precio de apertura",
              spread: "Spread",
              symbol: "Símbolo",
              time: "Tiempo",
              high: "High",
              low: "Low",
              last: "Último",
              lastHigh: "Last High",
              lastLow: "Last Low",
              highLow: "High/Low",
              bidLow: "Bid Low",
              bidHigh: "Bid High",
              askHigh: "Ask High",
              askLow: "Ask Low",
              bid: "Bid",
              ask: "Ask",
              title: "Columnas",
            },
            menu: {
              chart: "Gráfico",
              columns: "Columnas",
              dom: "Profundidad del mercado",
              hide: "Ocultar",
              newOrder: "Nueva orden",
              specification: "Especificación",
            },
            search: "Buscar",
            searchSymbol: "Buscar símbolo",
            nothingFound: "No se han encontrado símbolos",
          },
          objects: {
            form: {
              statistics: "Estadísticas",
              arrows: "Flechas",
              showAlways: "Mostrar siempre",
              angle: "Ángulo",
              distance: "Distancia",
              bar: "Barra",
              price: "Precio",
              prices: "Precios",
              showPrice: "Mostrar precio",
              showText: "Mostrar texto",
              showDate: "Mostrar fecha",
              showTime: "Mostrar hora",
              showAllTimeframes: "Mostrar en todos los períodos",
              showPearsonR: "Mostrar coeficiente de Pearson",
              showLabels: "Mostrar etiquetas",
              yourText: "Su texto",
              props: "Propiedades",
              style: "Estilo",
              rays: "Rayos",
              background: "Fondo",
              extends: "Extensión",
              extended: "Modo extendido",
              pipsPerBar: "Pips por barra",
              gannAngle: "Ángulo de Gann",
              deviations: "Desviaciónes",
              labels: "Etiquetas",
              reverse: "Revertir",
              btn: { update: "Actualizar", cancel: "Cancelar" },
              tabs: {
                style: "Estilo",
                coordinates: "Coordenadas",
                visualization: "Visualización",
              },
              range: {
                price: "Rango de precios",
                bars: "Rango de barras",
                date: "Rango de fechas",
              },
              align: {
                horizontal: "Alineación horizontal",
                vertical: "Alineación vertical",
                left: "Izquierda",
                right: "Derecha",
                center: "Centro",
                top: "Superior",
                middle: "Media",
                bottom: "Inferior",
              },
              line: {
                style: "Estilo de la línea",
                base: "Línea básica",
                up: "Línea ascendente",
                down: "Línea descendente",
                middle: "Línea media",
              },
            },
            visible: {
              hide: "Ocultar todos los objetos",
              show: "Mostrar todos los objetos",
            },
            lock: "Bloquear todos los objetos",
            unlock: "Desbloquear todos los objetos",
            andrewsPitchforkChannel: "Tridente de Andrews",
            equidistantChannel: "Canal equidistante",
            regressionChannel: "Canal de Regresión",
            stdDevChannel: "Canal de Desviación Estándar",
            fibonacciRetracement: "Retrocesos de Fibonacci",
            gannFan: "Abanico de Gann",
            gannGrid: "Cuadrícula de Gann",
            gannLine: "Línea de Gann",
            arrowLine: "Línea con flecha",
            crossLine: "Líneas entrecruzadas",
            extendedLine: "Línea extendida",
            horizontalRay: "Rayo horizontal",
            horizontalLine: "Línea horizontal",
            infoLine: "Línea de datos",
            rayLine: "Rayo",
            trendAngle: "Tendencia por Ángulo",
            trendline: "Línea de tendencia",
            verticalLine: "Línea vertical",
            disjointAngle: "Canal divergente",
            flatTopBottom: "Plano superior/inferior",
            rectangle: "Rectángulo",
            circle: "Círculo",
            triangle: "Triángulo",
            ellipse: "Elipse",
            text: "Texto",
            rulerLine: "Línea de medición",
          },
          period: {
            full: {
              D1: "D1",
              H1: "1 hora",
              H4: "4 horas",
              M1: "1 minuto",
              M15: "15 minutos",
              M30: "30 minutos",
              M5: "5 minutos",
              MN: "Mensual",
              Unknown: "Desconocido",
              W1: "S1",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Desconocido",
              W1: "W1",
            },
          },
          screenshot: "Guardar gráfico como imagen",
          symbolSpecs: {
            GTCmode: "Tipo de órdenes",
            calculation: "Cálculo de beneficio",
            chartMode: "Construcción de gráficos",
            contractSize: "Tamaño del contrato",
            days: {
              friday: "Viernes",
              monday: "Lunes",
              saturday: "Sábado",
              sunday: "Domingo",
              thursday: "Jueves",
              tuesday: "Martes",
              wednesday: "Miércoles",
            },
            digits: "Precisión",
            empty: "Símbolo no seleccionado",
            execution: "Ejecución",
            expiration: "Expiración",
            filling: "Ejecución",
            initial: "Inicial",
            maintenance: "De mantenimiento",
            marginCurrency: "Divisa de margen",
            marginRate: "Ratio del margen",
            maxVolume: "Volumen máximo",
            minVolume: "Volumen mínimo",
            orders: "Órdenes",
            profitCurrency: "Divisa de beneficio",
            schedule: { quotes: "Cotizaciones", trade: "Trading" },
            sector: "Sector",
            spread: "Spread",
            stopsLevel: "Niveles de Stop",
            swapLong: "Swap de posiciones largas",
            swapShort: "Swap de posiciones cortas",
            swapType: "Tipo de Swap",
            title: "Especificación del contrato {symbol}",
            tradeMode: "Trading",
            volumeStep: "Paso del volumen",
            volumeLimit: "Volumen límite",
            tickSize: "Tamaño del tick",
            tickValue: "Valor del tick",
            marginInitial: "Margen inicial",
            marginHedged: "Margen de cobertura",
            commission: {
              daily: {
                volume: "Volumen diario en lotes",
                turnoverVolume: "A diario en la circulación en lotes",
                turnoverMoney: "A diario en la circulación en dinero",
                value: "Valor diario de las transacciones",
                profit: "Beneficio diario",
              },
              monthly: {
                volume: "Volumen mensual en lotes",
                turnoverVolume: "Al mes en la circulación en lotes",
                turnoverMoney: "Al mes en la circulación en dinero",
                value: "Valor mensual de las transacciones",
                profit: "Beneficio mensual",
              },
              instant: {
                volume: "Instantánea por volumen de transacción",
                value: "Instantánea por valor de transacción",
                profit: "Instantánea por beneficio de transacción",
              },
              entry: {
                in: "transacciones de entrada",
                out: "transacciones de salida",
                all: "transacciones de entrada/salida",
              },
              tier: {
                mode: {
                  pips: "puntos",
                  percent: "% en {currency}",
                  percentProfit: "% del beneficio {currency}",
                },
                type: { perDeal: "por transacción", perLot: "por lote" },
              },
              header: "Comisiones",
            },
          },
          tree: {
            close: "Cerrar",
            empty: "No hay objetos en el gráfico",
            lock: "Bloquear",
            remove: "Eliminar",
            settings: "Ajustes",
            title: "Gestionar el dibujado",
            unlock: "Desbloquear",
          },
          types: {
            area: "Área",
            line: "Lineal",
            bars: "Barras",
            candlestick: "Velas",
          },
          volumeTypes: {
            tickVolumes: "Volúmenes de tick",
            volumes: "Volúmenes",
            withoutVolumes: "Sin volúmenes",
            realVolumes: "Volúmenes reales",
          },
          zoom: { in: "Acercar", out: "Alejar" },
          hotkeys: {
            arrowLine: "Línea con flecha",
            chartTypeArea: "Gráfico con áreas",
            chartTypeLine: "Gráfico lineal",
            chartTypeBar: "Gráfico con barras",
            chartTypeCandle: "Gráfico con velas",
            crossLine: "Líneas entrecruzadas",
            extendedLine: "Línea extendida",
            horizontalLine: "Línea horizontal",
            infoLine: "Línea de datos",
            rayLine: "Rayo",
            realVolumes: "Volúmenes reales",
            tickVolumes: "Volúmenes de tick",
            trendline: "Línea de tendencia",
            verticalLine: "Línea vertical",
            sections: {
              chartType: "Tipo de gráfico",
              drawing: "Marcado",
              volume: "Volumen",
            },
            crosshairRuler: "Regla-retícula",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Comience a utilizar su cuenta",
            newAccountOpened: "Nueva cuenta abierta",
          },
          brokerInformation: {
            company: "Empresa",
            email: "Email",
            phone: "Teléfono",
            registrationAddress: "Dirección de Registro",
            title: "Información sobre la compañía",
            website: "Sitio web",
          },
          changePassword: {
            btnChange: "Cambiar contraseña",
            confirmPassword: "Confirmar contraseña",
            newPassword: "Nueva contraseña",
            title: "Cambiar contraseña",
          },
          connect: {
            btnConnect: "Conectarse a la cuenta",
            contactBroker: "Contacte con la compañía",
            forgotPassword: "¿Olvidó su contraseña?",
            loginPlaceholder: "Introduzca login",
            passwordPlaceholder: "Introduzca contraseña",
            savePassword: "Guardar contraseña",
            title: "Conectarse a la cuenta",
          },
          copyToClipboard: {
            copy: "Copiar al portapapeles",
            unsupported: "No se admite el copiado",
          },
          demo: {
            accountOpeningWarning:
              "Al abrir una cuenta, usted acepta las condiciones de apertura de la cuenta y la política de protección de datos de {brokerName}.",
            btnOpenDemo: "Abrir cuenta demo",
            title: "Abrir cuenta demo",
            tradeWithRealMoney:
              "Para comerciar con dinero real, deberá suscribir un acuerdo independiente con una empresa de servicios financieros.",
          },
          disclaimer: {
            btnAccept: "Aceptar",
            headerTitle: "¡Bienvenido a MetaTrader 5",
            text: 'MetaQuotes Ltd es una empresa de desarrollo de software y no ofrece ningún servicio financiero, de inversión, de corretaje, comercial o de suministro de datos, ni participa en ningún pago basado en comisiones con respecto a ninguna operación comercial.<br /><br />Presionando el botón ACEPTAR, acepto los <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">términos y condiciones de EULA</a>, la <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Política de Privacidad</a> y el Descargo de Responsabilidad.<br /><br /> Ninguna información de la disponible en la aplicación pretende ser un consejo de inversión. Antes de usar esta aplicación para comerciar, deberá buscar el consejo de profesionales de valores cualificados y registrados y ejercer la debida responsabilidad.',
            title: "Renuncia de responsabilidad",
          },
          errors: {
            error: "Error",
            invalidCode: "Código no válido",
            invalidEmail: "Email no válido",
            invalidPhone: "Teléfono no válido",
            unknownError: "Error desconocido",
          },
          form: {
            accountType: "Tipo de cuenta",
            address: "Dirección",
            addressPlaceholder: "Indique su dirección",
            annualDeposit: "Depositar anuales",
            annualIncome: "Ingresos anuales",
            broker: "Empresa",
            btn: {
              back: "Atrás",
              cancel: "Cancelar",
              next: "Siguiente",
              openAccount: "Abrir una cuenta",
              remove: "Eliminar",
              signOut: "Salir",
            },
            city: "Ciudad",
            cityPlaceholder: "Indique su ciudad",
            country: "País",
            dateBirth: "Fecha de nacimiento",
            deposit: "Depósito",
            education: "Formación",
            email: {
              address: "Email",
              code: "Código del email",
              placeholder: "Indique su email",
              title: "Email",
            },
            employement: "Empleo",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Femenino", male: "Masculino", title: "Género" },
            identity: "Identidad",
            imageOrPdfFile: "Imagen o archivo PDF",
            investor: "Inversor",
            language: "Idioma",
            leverage: "Apalancamiento",
            login: "Login",
            min5chars: "Mínimo 5 caracteres",
            name: {
              middle: "Segundo nombre",
              surname: "Apellido",
              title: "Nombre",
              yourName: "Indique su nombre",
            },
            nationality: "Nacionalidad",
            netWorth: "Patrimonio neto",
            optional: "Opcional",
            password: "Contraseña",
            passwordReadOnly: "Contraseña de solo lectura",
            phone: {
              mobile: "Teléfono móvil",
              number: "Número de teléfono",
              sms: "Código del SMS",
            },
            pleaseSelect: "Seleccione",
            policyCheckbox:
              "Acepto los términos y condiciones para abrir una cuenta y la política de protección de datos",
            server: "Servidor",
            side: { back: "Parte trasera", front: "Parte delantera" },
            sourceWealth: "Fuente de ingresos",
            state: "Estado",
            status: "Estatus",
            stocks: "Acciones",
            taxID: "NIF",
            type: "Tipo",
            useHedge: "Utilizar cobertura en el comercio",
            verificationCodes: {
              email: "El código de confirmación ha sido enviado a su email.",
              phone: "El código de confirmación ha sido enviado a su teléfono.",
              phoneEmail:
                "Los códigos de confirmación han sido enviados a su email y teléfono.",
            },
            zipCode: "Índice",
          },
          mainForm: {
            title: "Cuentas comerciales",
            titleWithName: "Cuentas comerciales: {brokerName}",
          },
          otp: {
            disable2FA: "Desactivar 2FA/TOTP",
            disable2FAAccount: "Desactivar 2FA/TOTP para la cuenta {login}",
            disableEnterCode:
              "Para desactivar la autenticación 2FA, introduzca el código generado en la aplicación Authenticator para su cuenta.",
            downloadApp:
              "Instale la aplicación Google Authenticator / Microsoft Authenticator / Authy en su teléfono y escanee el código QR:",
            enable2FA: "Activar 2FA/TOTP",
            enable2FAAccount: "Activar 2FA/TOTP para la cuenta {login}",
            enterCode:
              "Para comprobar que la autenticación funciona, introduzca el código generado desde la aplicación.",
            oneTimePassword: "Contraseña de un solo uso:",
            placeholder: "Introduzca la OTP de la cuenta",
            required:
              "La autenticación 2FA es necesaria para proporcionar seguridad adicional a la cuenta.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Extracto bancario",
              utilityBill: "Factura de servicios",
            },
            conditionsForUploadingFiles: {
              documents:
                "Algunos tipos de documentos requieren dos fotos: una para el anverso y otra para el reverso.",
              proofAddress:
                "Las facturas de teléfono móvil no se aceptan como prueba del domicilio",
              utilityBill:
                "La factura de servicios públicos deberá contener su nombre y dirección y no tener más de tres meses de antigüedad.",
            },
            documentType: {
              driverLicense: "Permiso de conducir",
              idCard: "Identificación",
              passport: "Pasaporte",
              residencePermit: "Permiso de residencia",
            },
            educationLevel: {
              bachelor: "Licenciatura o equivalente",
              highScholl: "Bachillerato",
              master: "Máster o equivalente",
              none: "No establecido",
              other: "Otros",
              phd: "Doctorado o equivalente",
            },
            employment: {
              employed: "Empleado(а)",
              other: "Otros",
              retired: "Jubilado(a)",
              selfEmployed: "Empresario(a) o autónomo(a)",
              student: "Estudiante",
              unemployed: "Desempleado(a)",
            },
            experience: "Experiencia comercial real:",
            experienceLevel: {
              above3: "> 3 años",
              form1to3: "1 - 3 años",
              less1: "< 1 año",
            },
            industry: {
              agriculture: "Agricultura",
              communication: "Arte, tecnologías audiovisuales y comunicaciones",
              construction: "Arquitectura y construcción",
              education: "Formación",
              engineering: "Ingeniería y matemáticas",
              government: "Administración gubernamental y pública",
              healthcare: "Sanidad",
              it: "Tecnologías de la información",
              management: "Gestión y administración de empresas",
              manufacturing: "Industria",
              marketing: "Marketing y ventas",
              none: "No establecido",
              other: "Otros",
              science: "Ciencia y tecnología",
              security:
                "Seguridad pública, jurídica, administración penitenciaria y seguridad",
              tourism: "Hospitalidad y turismo",
              transport: "Transporte, distribución y logística",
            },
            policy:
              "Los datos personales se usan solo para abrir la cuenta comercial y no se transmiten a terceros. La información se trata de forma segura y confidencial.",
            takePhoto:
              "Por favor, haga fotografías de sus documentos y súbalas aquí sin editarlas",
            title: "Abrir una cuenta real",
            wealthSource: {
              employment: "Ocupación",
              inheritance: "Donación o herencia",
              other: "Otros",
              savings: "Ahorros o inversiones",
            },
          },
          saveAccountData: "Guarde su login y contraseña en un lugar seguro",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Cerrar",
            empty: "No tenemos datos de volumen para este símbolo",
            extendedBook: {
              hide: "Ocultar profundidad de mercado ampliada",
              show: "Mostrar profundidad de mercado ampliada",
            },
            menu: {
              amount: "Unidades en lugar de lotes",
              extended: "Modo extendido",
              spread: "Spread",
            },
            spread: { hide: "Ocultar spread", show: "Mostrar spread" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Profundidad del mercado",
          },
          errors: {
            accepted: "Aceptada",
            allowedOnlyLongPositions: "Solo se permiten posiciones largas",
            allowedOnlyPositionsClosing:
              "Solo se permite el cierre de posición",
            allowedOnlyShortPositions: "Solo se permiten posiciones cortas",
            automatedTradingDisabledClient:
              "El Trading Automático está desabilitado en el terminal de cliente",
            automatedTradingDisabledServer:
              "El Trading Automático está deshabilitado en el servidor",
            canceled: "Cancelada",
            common: "Error general",
            demoAllocationDisabled:
              "La asignación de cuentas demo está desactivada",
            done: "Terminado",
            donePartially: "Realizada parcialmente",
            frequentRequests: "Solicitudes demasiado frecuentes",
            invalidExpiration: "Expiración inválida",
            invalidOrderType: "Tipo de orden inválida",
            invalidParameters: "Parámetros inválidos",
            invalidPrices: "Precios inválidos",
            invalidSLTP: "S/L o T/P inválidos",
            invalidVolume: "Volumen inválido",
            manyTradeRequests: "Demasiadas solicitudes comerciales",
            marketClosed: "Mercado cerrado",
            modificationFailed:
              "Modificación fallida debido a que la orden o la posición se encuentre muy cerca al precio de mercado",
            networkProblem: "Problema con la red",
            noConnection: "Sin conexión",
            notEnoughMoney: "Dinero insuficiente",
            offQuotes: "No hay cotizaciones",
            ok: "OK",
            onTheWay: "Enviado",
            orderChanged: "La orden ya ha sido cambiada",
            orderClosePositionExists:
              "La orden de cierre para la posición indicada ya existe",
            ordersLimitReached: "Límite de órdenes alcanzado",
            permissions: "Derechos insuficientes",
            placed: "Colocada",
            positionCloseProhibitedByFIFO:
              "Cierre de posición prohibido por la regla FIFO",
            positionClosed: "Posición ya cerrada",
            positionsLimitReached: "Límite de posiciones alcanzado",
            priceChanged: "Cambio de precio",
            prices: "Precios",
            processed: "Procesado",
            rejected: "Rechazada",
            requestRejectedOrderWillCanceled:
              "Pedido rechazado, orden cancelada",
            requoted: "Recotizado",
            serverProblem: "Problema técnico del servidor",
            timeout: "Tiempo agotado",
            tradeDisabled: "El trading está deshabilitado",
            unsupportedFillingMode: "Modo de ejecución no soportado",
            volumeLimitReached: "Límite de volumen alcanzado",
          },
          form: {
            acceptNewQuotes: "¿Acepta estas nuevas cotizaciones?",
            btnOpen: {
              hide: "Ocultar formulario comercial",
              show: "Mostrar formulario comercial",
              title: "Nueva orden",
            },
            buttons: {
              accept: "Aceptar",
              delete: "Eliminar",
              modify: "Modificar",
              ok: "OK",
              placeOrder: "Colocar orden",
              reject: "Rechazar",
              request: "Solicitar",
              requestPrice: "Solicitar precio",
            },
            close: "Cerrar",
            execution: {
              fillOrKill: "Todo/Nada",
              immediateOrCancel: "Todo/Parte",
              bookOrCancel: "Pasiva",
              label: "Ejecución",
              return: "Volver",
            },
            executionMode: {
              exchange: "Ejecución por Bolsa",
              instant: "Ejecución Instantánea",
              market: "Ejecución por Mercado",
              request: "Ejecución por Pedido",
            },
            expiration: {
              date: "Fecha de expiración",
              label: "Expiración",
              types: {
                specified: "Fecha y hora",
                specifiedDay: "Día especificado",
                today: "Hoy",
              },
            },
            fields: {
              closeBy: "Cerrar por",
              comment: "Comentario",
              price: "Precio",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Volumen",
              errors: {
                volume: {
                  min: "Volumen mínimo— {min}",
                  max: "Volumen máximo — {max}",
                  required: "Volume is required",
                  step: "El volumen se puede establecer con un paso de {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Historial",
            deals: {
              columns: {
                comment: "Comentario",
                commission: "Comisión",
                direction: "Dirección",
                fee: "Tasa",
                order: "Orden",
                price: "Precio",
                profit: "Beneficio",
                swap: "Swap",
                symbol: "Símbolo",
                ticket: "Ticket",
                time: "Tiempo",
                type: "Tipo",
                volume: "Volumen",
              },
            },
            empty: "Aún no tiene historia comercial",
            menu: {
              columns: {
                horizontalScroll: "Desplazamiento horizontal",
                resetAll: "Resetear todo",
                title: "Columnas",
              },
              deals: "Transacciones",
              orders: "Órdenes",
              period: {
                all: "Todo el historial",
                last3Months: "Últimos 3 meses",
                last6months: "Últimos 6 meses",
                lastMonth: "Último mes",
                title: "Período",
                customPeriod: "Seleccionar período",
                lastYear: "Último año",
                lastWeek: "Última semana",
                today: "Hoy",
              },
              positions: "Posiciones",
              chart: "Gráfico",
              newOrder: "Nueva orden",
            },
            orders: {
              columns: {
                comment: "Comentario",
                price: "Precio",
                slDescription: "Stop Loss",
                state: "Estado",
                symbol: "Símbolo",
                ticket: "Ticket",
                timeDone: "Tiempo",
                timeSetup: "Tiempo",
                tpDescription: "Take Profit",
                type: "Tipo",
                volume: "Volumen",
                timeSetupDescription: "Hora de apertura",
                timeDoneDescription: "Hora de cierre",
              },
              total: {
                title: "Total",
                filled: "Lleno",
                canceled: "Cancelado",
                rejected: "Rechazada",
              },
            },
            positions: {
              columns: {
                commission: "Comisión",
                fee: "Tasa",
                priceClose: "Precio",
                priceCloseDescription: "Precio de cierre",
                priceOpen: "Precio",
                priceOpenDescription: "Precio de apertura",
                profit: "Beneficio",
                slDescription: "Stop Loss",
                swap: "Swap",
                symbol: "Símbolo",
                ticket: "Ticket",
                timeClose: "Tiempo",
                timeCloseDescription: "Hora de cierre",
                timeOpen: "Tiempo",
                timeOpenDescription: "Hora de apertura",
                tpDescription: "Take Profit",
                type: "Tipo",
                volume: "Volumen",
                comment: "Comentario",
              },
            },
            columns: { default: "Por defecto" },
            total: {
              profit: "Beneficio",
              credit: "Crédito",
              deposit: "Recarga",
              withdrawal: "Retirada",
              balance: "Balance",
              commission: "Comisión",
              fee: "Tasa",
              swap: "Swap",
              grossProfit: "Beneficio bruto",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Historia comercial",
                orders: "Órdenes comerciales",
                position: "Posiciones de trading",
                sltp: "Niveles de SL/TP",
              },
              notification: "Notificaciones comerciales",
            },
            oneClick: "Trading con un clic",
            tags: { demo: "Demo", readonly: "Solo lectura" },
            oneClickBottom:
              "Panel de trading en un solo clic debajo del gráfico",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Acepto estas condiciones",
            btnAccept: "Aceptar",
            btnCancel: "Cancelar",
            text: 'Está a punto de activar el modo "Trading en un clic". Pulsando "Acepto estos términos", reconoce que ha leído, comprendido y aceptado todos los siguientes términos.<br /><br />Puede activar o desactivar "Trading en un clic" en el menú del terminal web.<br /><br />El modo de envío de órdenes comerciales "Trading en un clic" consta de una etapa. Su solicitud comercial se enviará de inmediato: &mdash; pulsando los botones con el precio de oferta (SELL) o compra (BUY) en el panel de trading en un clic en el gráfico &mdash; pulsando los botones y comandos "Sell", "Buy", "Cerrar" y los comandos para colocar órdenes en la ventana "Profundidad del mercado" &mdash; al cerrar una posición y eliminar órdenes en la pestaña "Comercio"<br /><br />NO SE LE PEDIRÁ QUE CONFIRME LA ORDEN COMERCIAL. NO PODRÁ CANCELAR O MODIFICAR SU ORDEN DESPUÉS DE HACER CLIC. BAJO UNAS CONDICIONES DE MERCADO Y UN RENDIMIENTO DEL SISTEMA NORMALES, LA ORDEN DE MERCADO SE EJECUTARÁ INMEDIATAMENTE DESPUÉS DE SU ENVÍO Y USTED ESTARÁ OBLIGADO POR LA TRANSACCIÓN.<br /><br />Usted acepta todos los riesgos asociados con el uso de " Trading en un clic" ", incluidos, entre otros, todos los riesgos derivados de errores, omisiones o errores de cálculo en el envío de dicha orden comercial.<br /><br />Usted acepta eximir completamente a {companyName} de cualquier pérdida, coste o gasto en el que se pueda incurrir como resultado de tales errores, omisiones o errores de cálculo realizados por usted o cualquier otra persona que comercie en su nombre.',
            title: "Trading en un clic - Descargo de responsabilidad",
          },
          quickTrade: {
            hide: "Ocultar panel de trading en un clic",
            show: "Mostrar panel de trading en un clic",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Reconozco los riesgos y deseo tradear con los productos de inversión",
            btnAccept: "Aceptar",
            btnCancel: "Cancelar",
            text: "Le informamos que el uso sucesivo de esta plataforma comercial implica el acceso a productos de inversión de alto riesgo proporcionados por la institución financiera de su elección. Es posible que invertir en dichos productos no resulte adecuado para todos los inversores, ya que conlleva el riesgo de perder una parte o la totalidad de su depósito.<br /><br />Antes de decidirse a comerciar con productos de inversión de alto riesgo, deberá evaluar cuidadosamente su objetivos de inversión, su nivel de preparación y los riesgos admisibles. Existe la posibilidad de perder cantidades superiores a su inversión inicial, por lo que no deberá invertir dinero que no pueda permitirse perder.<br /><br />Le animamos a ampliar su enfoque respecto a todos los factores de riesgo asociados a la inversión en este tipo de productos, y también, en caso de duda, a consultar con un asesor financiero profesional.",
            title: "Advertencia sobre los riesgos del inversor",
          },
          table: {
            btnOpen: "Trading",
            columns: {
              comment: "Comentario",
              priceClose: "Precio",
              priceCloseDescription: "Precio de cierre",
              priceOpen: "Precio",
              priceOpenDescription: "Precio de apertura",
              profit: "Beneficio",
              slDescription: "Stop Loss",
              swap: "Swap",
              symbol: "Símbolo",
              ticket: "Ticket",
              time: "Tiempo",
              tpDescription: "Take Profit",
              type: "Tipo",
              volume: "Volumen",
            },
            emptyPlug: {
              btnNewOrder: "Crear una nueva orden",
              title: "Usted no tiene posiciones",
            },
            menu: {
              chart: "Gráfico",
              closePosition: "Cerrar posición",
              columns: "Columnas",
              modifyOrder: "Modificar orden",
              modifyPosition: "Modificar posición",
              newOrder: "Nueva orden",
              resetAll: "Resetear todas",
              deleteOrder: "Eliminar orden",
            },
            oneClick: { deleteOrder: "Eliminar" },
            sections: {
              collateralPositions: "Posiciones colaterales",
              orders: "Órdenes",
              positions: "Posiciones",
            },
            total: {
              assets: "Activos",
              balance: "Balance",
              collateral: "Colateral",
              commission: "Comisión",
              credit: "Crédito",
              equity: "Equidad",
              liabilities: "Obligaciones",
              margin: "Margen",
              marginFree: "Margen libre",
              marginLevel: "Nivel",
            },
          },
          timer: {
            marketWillOpen: "El mercado abrirá en {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} días",
            oneDay: "{numberOfDays} día",
          },
          tradeIsDisabled: {
            account:
              "El comercio está deshabilitado para su cuenta en el servidor",
            collateral:
              "El comercio no está disponible para instrumentos colaterales",
            disabled: "El trading está deshabilitado",
            investor:
              "El comercio no está disponible porque está conectado con una contraseña de inversor",
            readOnly:
              "El comercio no está disponible porque no ha aceptado el acuerdo sobre riesgos",
            symbol: "El comercio está deshabilitado para este símbolo",
          },
          hotkeys: {
            historyPanel: "Panel de la historia",
            journalPanel: "Diario",
            marketWatch: "Observación de mercado",
            quickTrade: "Trading con un clic",
            tradeForm: "Nueva orden",
            tradePanel: "Panel comercial",
          },
          marketOpen: {
            time: "Mercado cerrado - abrirá a las {hora}",
            afterSeconds: "Mercado cerrado - abrirá en {time} seg",
          },
          expiredTimer: { seconds: "Expira en {time} seg" },
          corporateLink: {
            type: {
              clientAgreement: "Acuerdo con el cliente",
              riskDisclosure: "Comunicación de riesgos",
              fdmDisclaimer: "Renuncia de responsabilidad de FDM",
              clientAgreementAndRiskDisclosure:
                "Acuerdo con el cliente y comunicación de riesgos",
              complaintsHandlingProcedure:
                "Procedimiento de gestión de reclamaciones",
              orderExecutionPolicy: "Política de ejecución de órdenes",
              clientCategorisationNotice: "Aviso de categorización de clientes",
              conflictsOfInterestPolicy: "Política de conflicto de intereses",
              dataProtectionPolicy: "Política de protección de datos",
            },
          },
          margin: {
            floating: "flotante",
            mode: {
              marketBuy: "Orden de mercado Buy",
              marketSell: "Orden de mercado Sell",
            },
            rangeMode: {
              value: "valor nominal",
              valuePerSymbol: "valor nominal del símbolo",
              volume: "volumen",
              volumePerSymbol: "volumen del símbolo",
            },
            showValue: "Mostrar valores en {currency} por lote",
            rates: "Margen:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Deshabilitar pantalla completa",
            enable: "Habilitar pantalla completa",
          },
          journal: {
            btnOpen: "Diario",
            columns: { message: "Mensaje", source: "Fuente", time: "Tiempo" },
            menu: {
              clear: "Borrar",
              debugMode: "Modo de depuración",
              exportFile: "Exportar a un archivo",
            },
          },
          menu: {
            about: "Sobre el programa",
            contact: "Contacta con nosotros",
            brokerInformation: "Información sobre la compañía",
            chartSettings: {
              controls: "Gestionar el gráfico",
              grid: "Cuadrícula",
              ohlc: "Mostrar OHLC",
              title: "Ajustes del gráfico",
              askPrice: "Precio Ask",
              crosshair: "Cursor con retícula",
            },
            connect: "Conectarse a la cuenta",
            language: {
              title: "Idioma",
              search: "Buscar",
              nothingFound: "Idioma no encontrado",
            },
            openDemo: "Abrir cuenta demo",
            openReal: "Abrir cuenta real",
            settings: "Ajustes",
            shortcuts: "Teclas de acceso rápido",
            theme: {
              blackWhite: "Blanco y Negro",
              blueRed: "Azul y rojo",
              dark: "Tema oscuro",
              editor: "Editor de temas",
              greenRed: "Verde y rojo",
              light: "Tema claro",
              neutral: "Neutro",
              templates: "Esquemas de color",
            },
            title: "Menú",
            tradingAccount: "Cuentas comerciales",
            terms: "Condiciones de uso",
            desktopPlatforms: "Plataformas de escritorio",
            qrCode: {
              install: "Escanear para instalar desde {store}",
              downloadApk: "Escanee para obtener un archivo APK para Android",
            },
            economicCalendar: "Calendario económico",
          },
          screen: { back: "Atrás" },
          mobile: { bottomNav: { quotes: "Cotizaciones" } },
          hotkeys: {
            sections: { navigation: "Navegación", view: "Vista" },
            escape: "Cancelar",
            indicators: "Indicadores",
            depthOfMarket: "Profundidad del mercado",
            objectTreePanel: "Árbol de objetos",
            scrollRight: "Vela siguiente",
            scrollToStart: "Desplazar gráfico hasta el inicio",
            scrollLeft: "Vela anterior",
            scrollToEnd: "Desplazar gráfico hasta el final",
            resetChartView: "Resetear gráfico",
            zoomIn: "Acercar",
            zoomOut: "Alejar",
            fullScreen: "Pantalla completa",
            screenshot: "Guardar gráfico como imagen",
            title: "Teclas de acceso rápido",
          },
          timezone: {
            title: "Zona horaria",
            city: {
              cairo: "El Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburgo",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Túnez",
              anchorage: "Anclaje",
              bogota: "Bogotá",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Ciudad de México",
              newYork: "Nueva York",
              phoenix: "Fénix",
              santiago: "santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almatý",
              ashgabat: "Asjabad",
              bahrain: "Baréin",
              bangkok: "Bangkok",
              kolkata: "Calcuta",
              colombo: "colombo",
              dhaka: "Daca",
              dubai: "Dubái",
              hongKong: "Hong Kong",
              jakarta: "Jacarta",
              jerusalem: "Jerusalén",
              karachi: "Karachi",
              kathmandu: "Katmandú",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Moscatel",
              nicosia: "Nicosia",
              qatar: "Catar",
              rangoon: "Rangún",
              riyadh: "Riad.",
              saigon: "Saigón",
              seoul: "Seúl",
              shanghai: "Shanghái.",
              singapore: "Singapur",
              taipei: "Taipéi",
              tehran: "Teherán",
              tokyo: "Tokio",
              reykjavik: "Reikiavik",
              adelaide: "Adelaida",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sídney",
              amsterdam: "Ámsterdam",
              athens: "Atenas",
              belgrade: "Belgrado",
              berlin: "Berlina",
              bratislava: "Bratislava",
              brussels: "Bruselas",
              bucharest: "Bucarest",
              budapest: "Budapest",
              copenhagen: "Copenhague",
              dublin: "Dublín",
              helsinki: "Helsinki",
              istanbul: "Estanbul",
              lisbon: "Lisboa",
              london: "Londres",
              luxembourg: "Luxemburgo",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscú",
              oslo: "Oslo",
              paris: "París",
              prague: "Praga",
              riga: "Riga",
              rome: "Roma",
              stockholm: "Estocolmo",
              tallinn: "Tallin",
              vienna: "Vena",
              vilnius: "Vilna",
              warsaw: "Varsovia",
              zurich: "Zúrich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulú",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { o as a, a as b, i as c, e };
