const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Nascondi gli Eventi del Calendario Economico dal Grafico",
              show: "Mostra gli Eventi del Calendario Economico sul Grafico",
            },
          },
          controls: {
            reset: "Resettare il Grafico",
            scrollEnd: "Scorrere alla Fine",
            scrollLeft: "Scorrere a Sinistra",
            scrollRight: "Scorrere a Destra",
            zoomIn: "Ingrandisci",
            zoomOut: "Riduci",
          },
          crosshair: "Mirino",
          delay: "{delay} ritardo minimo",
          indicators: {
            btnAddIndicator: "Aggiungi indicatore",
            btnOpenPopup: "Aggiungi Indicatore",
            close: "Chiudi",
            form: {
              applyTo: "Applica a",
              background: {
                title: "Sfondo",
                down: "Sfondo kumo che scende",
                up: "Sfondo kumo che sale",
              },
              deviation: "Deviazione",
              enterDistance: "Periodo",
              enterShift: "Scostamento",
              fastEma: "Ema Veloce",
              slowEma: "Ema Lenta",
              line: {
                base: "Linea base",
                down: "Linea in giù",
                minusDI: "Linea -DI",
                null: "Linea nulla",
                plusDI: "Linea +DI",
                style: "Stile della linea",
                cci: "Linea CCI",
                up: "Linea in sù",
                fi: "Linea FI",
              },
              maximum: "Massimo",
              method: {
                exponential: "Esponenziale",
                linearWeighted: "Lineare Ponderata",
                simple: "Semplice",
                smoothed: "Adattiva",
                title: "Metodo",
              },
              opacity: "Opacità",
              period: {
                jaws: "Periodo Fauci",
                lips: "Periodo Labbra",
                teeth: "Periodo Denti",
                title: "Periodo",
                dPercent: "%D periodo",
                kPercent: "%K periodo",
              },
              selectApplyTo: "Seleziona",
              selectVolumesType: "Seleziona il tipo di volume",
              shift: "Scostamento",
              showTimeframes: "Mostra su tutti i timeframes",
              slowing: "Rallentamento",
              step: "Passo",
              style: {
                down: "Stile in discesa",
                jaws: "Stile Fauci",
                lips: "Stile Labbra",
                main: "Stile della Main",
                signal: "Stile della signal",
                teeth: "Stile Denti",
                title: "Stile",
                up: "Stile in salita",
                rvi: "Stile RVI",
              },
              volume: { down: "Volume Giù", up: "Volume Su" },
              volumes: "Volumi",
              mfiUp: "MFI Su",
              mfiDown: "MFI Giù",
              price: {
                title: "Prezzo",
                select: "Selezionare prezzo",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "Nessun elemento trovato",
              title: "Ricerca",
              tryAnother: "Si prega di provare un'altra query",
            },
            tabs: {
              all: "Tutti",
              billWilliams: "Bill Williams",
              oscillators: "Oscillatori",
              trend: "Trend",
              volumes: "Volumi",
            },
            title: "Selezionare l'indicatore",
            up: "Su",
            down: "Giù",
            chartControls: {
              show: "Mostra",
              hide: "Nascondi",
              settings: "Impostazioni",
              remove: "Rimuovi",
            },
          },
          loading: "Caricamento",
          marketWatch: {
            btnOpen: {
              hide: "Nascondi il Market Watch",
              show: "Mostra il Market Watch",
            },
            columns: {
              closePrice: "Prezzo di Chiusura",
              dailyChange: "Cambio giornaliero",
              openPrice: "Prezzo di Apertura",
              spread: "Spread",
              symbol: "Simbolo",
              time: "Orario",
              high: "High",
              low: "Low",
              last: "Ultimo",
              lastHigh: "Ultimo High",
              lastLow: "Ultimo Low",
              highLow: "High/Low",
              bidLow: "Bid Basso",
              bidHigh: "Bid Alto",
              askHigh: "Ask Alto",
              askLow: "Ask Basso",
              bid: "Offerta",
              ask: "Richiesta",
              title: "Colonne",
            },
            menu: {
              chart: "Grafico",
              columns: "Colonne",
              dom: "Depth Of Market",
              hide: "Nascondi",
              newOrder: "Nuovo ordine",
              specification: "Specifiche",
            },
            search: "Ricerca",
            searchSymbol: "Ricerca simbolo",
            nothingFound: "Nessun simbolo trovato",
          },
          objects: {
            form: {
              statistics: "Statistiche",
              arrows: "Frecce",
              showAlways: "Mostra sempre",
              angle: "Angolo",
              distance: "Distanza",
              bar: "Barra",
              price: "Prezzo",
              prices: "Prezzi",
              showPrice: "Mostra prezzo",
              showText: "Mostra testo",
              showDate: "Visualizza data",
              showTime: "Mostra ora",
              showAllTimeframes: "Mostra tutti gli intervalli temporali",
              showPearsonR: "Visualizza Pearson's R",
              showLabels: "Visualizza etichette",
              yourText: "Il tuo testo",
              props: "Proprietà",
              style: "Stile",
              rays: "Raggi",
              background: "Sfondo",
              extends: "Estensione",
              extended: "Esteso",
              pipsPerBar: "Pips per barra",
              gannAngle: "Angolo di Gann",
              deviations: "Deviazioni",
              labels: "Etichette",
              reverse: "Inverso",
              btn: { update: "Aggiorna", cancel: "Annulla" },
              tabs: {
                style: "Stile",
                coordinates: "Coordinate",
                visualization: "Visualizzazione",
              },
              range: {
                price: "Intervallo di prezzo",
                bars: "Intervallo delle barre",
                date: "Intervallo di tempo",
              },
              align: {
                horizontal: "Allineamento orizzontale",
                vertical: "Allineamento verticale",
                left: "Sinistra",
                right: "Destra",
                center: "Centro",
                top: "Superiore",
                middle: "Centro",
                bottom: "Inferiore",
              },
              line: {
                style: "Stile della linea",
                base: "Linea base",
                up: "Linea superiore",
                down: "Linea inferiore",
                middle: "Linea centrale",
              },
            },
            visible: {
              hide: "Nascondi tutti gli oggetti",
              show: "Mostra tutti gli oggetti",
            },
            lock: "Blocca Tutti gli Oggetti",
            unlock: "Sblocca tutti gli oggetti",
            andrewsPitchforkChannel: "Forchette di Andrews",
            equidistantChannel: "Canale Equidistante",
            regressionChannel: "Canale di Regressione",
            stdDevChannel: "Canale Deviazione Standard",
            fibonacciRetracement: "Ritracciamento di Fibonacci",
            gannFan: "Ventaglio di Gann",
            gannGrid: "Griglia di Gann",
            gannLine: "Linea di Gann",
            arrowLine: "Linea con freccia",
            crossLine: "Linea Trasversale",
            extendedLine: "Linea Estesa",
            horizontalRay: "Raggio Orizzontale",
            horizontalLine: "Linea Orizzontale",
            infoLine: "Linea con Informazioni",
            rayLine: "Raggio",
            trendAngle: "Trend per Angolo",
            trendline: "Trendline",
            verticalLine: "Linea Verticale",
            disjointAngle: "Canale Divergente",
            flatTopBottom: "Triangolo Ascendente/Discendente",
            rectangle: "Rettangolo",
            circle: "Cerchio",
            triangle: "Triangolo",
            ellipse: "Ellisse",
            text: "Testo",
            rulerLine: "Righello",
          },
          period: {
            full: {
              D1: "Giornaliero",
              H1: "1 Ora",
              H4: "4 Ore",
              M1: "1 Minuto",
              M15: "15 Minuti",
              M30: "30 Minuti",
              M5: "5 Minuti",
              MN: "Mensile",
              Unknown: "Sconosciuto",
              W1: "Settimanale",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Sconosciuto",
              W1: "W1",
            },
          },
          screenshot: "Salva il grafico come immagine",
          symbolSpecs: {
            GTCmode: "modalità GTC",
            calculation: "Calcoli",
            chartMode: "Modalità Chart",
            contractSize: "Dimensione contratto",
            days: {
              friday: "Venerdì",
              monday: "Lunedì",
              saturday: "Sabato",
              sunday: "Domenica",
              thursday: "Giovedì",
              tuesday: "Martedì",
              wednesday: "Mercoledì",
            },
            digits: "Cifre",
            empty: "Nessun simbolo selezionato",
            execution: "Esecuzione",
            expiration: "Espirazione",
            filling: "La Politica di Riempimento",
            initial: "Iniziale",
            maintenance: "Mantenimento",
            marginCurrency: "Valuta del margine",
            marginRate: "Tasso Margine",
            maxVolume: "Volume massimale",
            minVolume: "Volume minimale",
            orders: "Ordini",
            profitCurrency: "Valuta profitto",
            schedule: { quotes: "Quotazioni", trade: "Trade" },
            sector: "Settore",
            spread: "Spread",
            stopsLevel: "Livello degli Stops",
            swapLong: "Swap long",
            swapShort: "Swap short",
            swapType: "Tipo di Swap",
            title: "{symbol} specifica del contratto",
            tradeMode: "Trade",
            volumeStep: "Step Volume",
            volumeLimit: "Limite Volume",
            tickSize: "Dimensione del Tick",
            tickValue: "Valore del Tick",
            marginInitial: "Margine Iniziale",
            marginHedged: "Margine hedge",
            commission: {
              daily: {
                volume: "Volume giornaliero in lotti",
                turnoverVolume: "Fatturato giornaliero in lotti",
                turnoverMoney: "Fatturato giornaliero in denaro",
                value: "Valore giornaliero delle offerte",
                profit: "Guadagno giornaliero",
              },
              monthly: {
                volume: "Volume mensile in lotti",
                turnoverVolume: "Fatturato mensile in lotti",
                turnoverMoney: "Fatturato mensile in denaro",
                value: "Valore mensile delle operazioni",
                profit: "Guadagno mensile",
              },
              instant: {
                volume: "Istantaneo per volume delle operazioni",
                value: "Istantaneo per valore dell'operazione",
                profit: "Profitto istantaneo per operazione",
              },
              entry: {
                in: "deals in ingresso",
                out: "deals in uscita",
                all: "deals in/out",
              },
              tier: {
                mode: {
                  pips: "punti",
                  percent: "% in {currency}",
                  percentProfit: "% di profitto {currency}",
                },
                type: { perDeal: "per affare", perLot: "per lotto" },
              },
              header: "Commissioni",
            },
          },
          tree: {
            close: "Chiudi",
            empty: "Non hai oggetti sul grafico",
            lock: "Blocca",
            remove: "Rimuovi",
            settings: "Impostazioni",
            title: "Gestione Oggetti Grafici",
            unlock: "Sblocca",
          },
          types: {
            area: "Area",
            line: "Linea",
            bars: "Barre",
            candlestick: "Candele",
          },
          volumeTypes: {
            tickVolumes: "Volumi Tick",
            volumes: "Volumi",
            withoutVolumes: "Senza Volumi",
            realVolumes: "Volume reale",
          },
          zoom: { in: "Ingrandisci", out: "Riduci" },
          hotkeys: {
            arrowLine: "Linea con freccia",
            chartTypeArea: "Grafico ad Area",
            chartTypeLine: "Grafico a Linea",
            chartTypeBar: "Grafico a Barre",
            chartTypeCandle: "Grafico a Candele",
            crossLine: "Linea Trasversale",
            extendedLine: "Linea Estesa",
            horizontalLine: "Linea Orizzontale",
            infoLine: "Linea con Informazioni",
            rayLine: "Raggio",
            realVolumes: "Volume Reale",
            tickVolumes: "Volumi Tick",
            trendline: "Trendline",
            verticalLine: "Linea Verticale",
            sections: {
              chartType: "Tipo di Grafico",
              drawing: "Disegno",
              volume: "Volume",
            },
            crosshairRuler: "Mirino",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Inizia a utilizzare il tuo account",
            newAccountOpened: "Nuovo account aperto",
          },
          brokerInformation: {
            company: "Società",
            email: "Email",
            phone: "Telefono",
            registrationAddress: "Indirizzo di Registrazione",
            title: "Informazioni sull'Azienda",
            website: "Sito Web",
          },
          changePassword: {
            btnChange: "Cambia Password",
            confirmPassword: "Conferma Password",
            newPassword: "Nuova Password",
            title: "Cambia Password",
          },
          connect: {
            btnConnect: "Collegati all'account",
            contactBroker: "Contatta azienda",
            forgotPassword: "Password dimenticata?",
            loginPlaceholder: "Inserire Login",
            passwordPlaceholder: "Inserire Password",
            savePassword: "Salva password",
            title: "Collegati all'account",
          },
          copyToClipboard: {
            copy: "Copia negli appunti",
            unsupported: "La copia non è supportata",
          },
          demo: {
            accountOpeningWarning:
              "Aprendo un conto, accetti i termini di apertura del conto e la politica di protezione dei dati di {brokerName}",
            btnOpenDemo: "Apri un conto Demo",
            title: "Apri un conto Demo",
            tradeWithRealMoney:
              "Per il trading con denaro reale, è necessario stipulare un accordo separato con una società di servizi finanziari.",
          },
          disclaimer: {
            btnAccept: "Accetta",
            headerTitle: "Benvenuto a MetaTrader 5",
            text: 'MetaQuotes Ltd è una società di sviluppo software e non fornisce servizi finanziari, di investimento, di intermediazione, di negoziazione o di flusso di dati, né è coinvolto in eventuali pagamenti basati su commissioni riguardanti operazioni di trading.<br /><br />Premendo il tasto ACCETTA sono d\'accordo con i <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">termini e condizioni dell\'EULA</a>, l\'<a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Informativa sulla Privacy</a> e il Disclaimer.<br /><br /> Nessuna delle informazioni disponibili nell\'applicazione è intesa come consiglio di investimento. Prima di utilizzare questa applicazione per il trading, dovresti chiedere il parere di un professionista di titoli qualificato e registrato e intraprendere la tua due diligence.',
            title: "Disclaimer",
          },
          errors: {
            error: "Errore",
            invalidCode: "Codice non valido",
            invalidEmail: "Email non valida",
            invalidPhone: "Numero di telefono non valido",
            unknownError: "Errore sconosciuto",
          },
          form: {
            accountType: "Tipo di conto",
            address: "Indirizzo",
            addressPlaceholder: "Inserisci il tuo indirizzo",
            annualDeposit: "Deposito annuo",
            annualIncome: "Reddito annuo",
            broker: "Azienda",
            btn: {
              back: "Indietro",
              cancel: "Annulla",
              next: "Prossimo",
              openAccount: "Apri Conto",
              remove: "Rimuovi",
              signOut: "Disconnettersi",
            },
            city: "Città",
            cityPlaceholder: "Inserisci la tua città",
            country: "Paese",
            dateBirth: "Data di nascita",
            deposit: "Deposito",
            education: "Istruzione",
            email: {
              address: "Email",
              code: "Codice postale",
              placeholder: "Inserisci email",
              title: "Email",
            },
            employement: "Occupazione",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Femmina", male: "Maschio", title: "Genere" },
            identity: "Identità",
            imageOrPdfFile: "Immagine o file PDF",
            investor: "Investitore",
            language: "Lingua",
            leverage: "Leva",
            login: "Login",
            min5chars: "Minimo 5 caratteri",
            name: {
              middle: "Secondo nome",
              surname: "Cognome",
              title: "Nome",
              yourName: "Il Tuo Nome",
            },
            nationality: "Nazionalità",
            netWorth: "Valore netto",
            optional: "Facoltativo",
            password: "Password",
            passwordReadOnly: "Password di solo lettura",
            phone: {
              mobile: "Telefono mobile",
              number: "Numero di telefono",
              sms: "Codice da SMS",
            },
            pleaseSelect: "Seleziona",
            policyCheckbox:
              "Acconsento ai termini e condizioni per aprire un account e policy protezione dati",
            server: "Server",
            side: { back: "Retro", front: "Fronte" },
            sourceWealth: "Fonte di guadagno",
            state: "Stato",
            status: "Stato",
            stocks: "Azioni",
            taxID: "Codice fiscale",
            type: "Tipo",
            useHedge: "Usa l'hedge nel trading",
            verificationCodes: {
              email: "Abbiamo inviato un codice di verifica alla tua email",
              phone: "Abbiamo inviato un codice di verifica al tuo telefono",
              phoneEmail:
                "Abbiamo inviato i codici di verifica al tuo telefono e alla tua email",
            },
            zipCode: "Codice di Avviamento Postale",
          },
          mainForm: {
            title: "Conti di trading",
            titleWithName: "Conti di trading: {brokerName}",
          },
          otp: {
            disable2FA: "Disabilita 2FA/TOTP",
            disable2FAAccount: "Disabilita 2FA/TOTP per l'account {login}",
            disableEnterCode:
              "Per disabilitare 2FA/TOTP, inserisci il codice del tuo account generato dall'Autenticatore.",
            downloadApp:
              "Scarica l'app Google Authenticator / Microsoft Authenticator / Authy sul tuo dispositivo mobile ed esegui la scansione del codice QR:",
            enable2FA: "Abilita 2FA/TOTP",
            enable2FAAccount: "Abilita 2FA/TOTP per l'account {login}",
            enterCode:
              "Per verificare il funzionamento dell'Autenticatore, inserisci il tuo codice account generato dall'App.",
            oneTimePassword: "Password monouso:",
            placeholder: "Inserisci OTP account",
            required:
              "L'autenticazione 2FA è necessaria per garantire la sicurezza dell'account.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Estratto conto",
              utilityBill: "Bolletta",
            },
            conditionsForUploadingFiles: {
              documents:
                "Alcuni tipi di documenti richiedono due foto: fronte e retro",
              proofAddress:
                "Le fatture per i servizi mobili non sono accettate come prova di domicilio",
              utilityBill:
                "La bolletta deve contenere il tuo nome e indirizzo e non avere più di 3 mesi",
            },
            documentType: {
              driverLicense: "Patente",
              idCard: "Carta ID",
              passport: "Passaporto",
              residencePermit: "Permesso di soggiorno",
            },
            educationLevel: {
              bachelor: "Laurea o equivalente",
              highScholl: "Scuola superiore",
              master: "Laurea e Master o equivalente",
              none: "Nessuno",
              other: "Altro",
              phd: "Ricercatore o equivalente",
            },
            employment: {
              employed: "Occupato",
              other: "Altro",
              retired: "Pensionato",
              selfEmployed: "Imprenditore o lavoratore autonomo",
              student: "Studente",
              unemployed: "Disoccupato",
            },
            experience: "Esperienza di trading reale:",
            experienceLevel: {
              above3: "> 3 anni",
              form1to3: "Da 1 a 3 anni",
              less1: "< 1 anno",
            },
            industry: {
              agriculture: "Agricoltura",
              communication: "Arti, Tecnologia Audio/Video e Comunicazione",
              construction: "Architettura e Costruzione",
              education: "Istruzione",
              engineering: "Ingegneria e Matematica",
              government: "Governo e Pubblica Amministrazione",
              healthcare: "Assistenza Sanitaria",
              it: "Informatica",
              management: "Gestione aziendale e Amministrazione",
              manufacturing: "Manifatturiero",
              marketing: "Marketing e Vendite",
              none: "Nessuno",
              other: "Altro",
              science: "Scienze e Tecnologia",
              security: "Legale, Pubblica sicurezza, Correzioni e Security",
              tourism: "Ospitalità e Turismo",
              transport: "Trasporto, Distribuzione e Logistica",
            },
            policy:
              "I dati personali vengono utilizzati per l'apertura di un conto di trading e non vengono trasmessi a terzi. Le informazioni vengono gestite in modo sicuro e confidenziale.",
            takePhoto:
              "Per favore, scatta le foto dei tuoi documenti e caricali qui senza alcuna modifica",
            title: "Apri un conto Reale",
            wealthSource: {
              employment: "Occupazione o Proventi di attività",
              inheritance: "Regali o Eredità",
              other: "Altro",
              savings: "Risparmio o Investimenti",
            },
          },
          saveAccountData:
            "Si prega di mantenere il login e la password in un luogo sicuro",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Chiudi",
            empty: "Non abbiamo dati sul volume per questo simbolo",
            extendedBook: {
              hide: "Nascondi il Book esteso",
              show: "Mostra il Book Esteso",
            },
            menu: {
              amount: "Ammontare invece che Lotti",
              extended: "Esteso",
              spread: "Spread",
            },
            spread: { hide: "Nascondi Spread", show: "Mostra Spread" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Depth Of Market",
          },
          errors: {
            accepted: "Accettato",
            allowedOnlyLongPositions: "Sono consentite solo posizioni long",
            allowedOnlyPositionsClosing:
              "E' consentita solo la chiusura delle posizioni",
            allowedOnlyShortPositions: "Sono consentite solo posizioni short",
            automatedTradingDisabledClient:
              "AutoTrading disabilitato sul terminale client",
            automatedTradingDisabledServer:
              "AutoTrading disabilitato dal lato server",
            canceled: "Annullato",
            common: "Errore comune",
            demoAllocationDisabled: "Allocazione conto demo disabilitata",
            done: "Fatto",
            donePartially: "Eseguito parzialmente",
            frequentRequests: "Richieste troppo frequenti",
            invalidExpiration: "Espirazione non valida",
            invalidOrderType: "Tipo di ordine non valido",
            invalidParameters: "Parametri non validi",
            invalidPrices: "Prezzi non validi",
            invalidSLTP: "S/L o T/P non validi",
            invalidVolume: "Volume non valido",
            manyTradeRequests: "Troppe richieste di trading",
            marketClosed: "Mercato chiuso",
            modificationFailed:
              "Modifica fallita a causa del fatto che l'orine o la posizione sono vicine al mercato",
            networkProblem: "Problema di Rete",
            noConnection: "Nessuna connessione",
            notEnoughMoney: "Denaro insufficiente",
            offQuotes: "Fuori quotazione",
            ok: "OK",
            onTheWay: "Inviato",
            orderChanged: "L'ordine è già stato cambiato",
            orderClosePositionExists:
              "L'ordine per chiudere questa posizione già esiste",
            ordersLimitReached: "Raggiunto il limite ordini",
            permissions: "Permessi insufficienti",
            placed: "Piazzato",
            positionCloseProhibitedByFIFO:
              "Chiusura posizione proibita da regole FIFO",
            positionClosed: "Posizione già chiusa",
            positionsLimitReached: "Raggiunto limite delle posizioni",
            priceChanged: "Prezzo cambiato",
            prices: "Prezzi",
            processed: "Elaborato",
            rejected: "Rigettato",
            requestRejectedOrderWillCanceled:
              "Richiesta rigettata, ordine annullato",
            requoted: "Riquotato",
            serverProblem: "Problema tecnico sul server",
            timeout: "Timeout",
            tradeDisabled: "Il trading è disabilitato",
            unsupportedFillingMode: "Modalità di riempimento non supportata",
            volumeLimitReached: "Limite Volume raggiunto",
          },
          form: {
            acceptNewQuotes: "Accetti queste nuove quotazioni?",
            btnOpen: {
              hide: "Nascondi la Scheda Trade",
              show: "Mostra la Scheda Trade",
              title: "Nuovo ordine",
            },
            buttons: {
              accept: "Accetta",
              delete: "Elimina",
              modify: "Modifica",
              ok: "OK",
              placeOrder: "Piazza ordine",
              reject: "Rigetta",
              request: "Richiesto",
              requestPrice: "Prezzo Richiesto",
            },
            close: "Chiudi",
            execution: {
              fillOrKill: "Tutto o Elimina",
              immediateOrCancel: "Immediato o Cancella",
              bookOrCancel: "Passivo",
              label: "Criterio di Inserimento",
              return: "Ritorna",
            },
            executionMode: {
              exchange: "Esecuzione di Scambio",
              instant: "Esecuzione istantanea",
              market: "Esecuzione a Mercato",
              request: "Richiedi Esecuzione",
            },
            expiration: {
              date: "Data di Espirazione",
              label: "Espirazione",
              types: {
                specified: "Specificato",
                specifiedDay: "Giorno Specifico",
                today: "Oggi",
              },
            },
            fields: {
              closeBy: "Chiudi entro",
              comment: "Commento",
              price: "Prezzo",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Volume",
              errors: {
                volume: {
                  min: "Il volume minimo è {min}",
                  max: "Il volume massimo è {max}",
                  required: "Volume is required",
                  step: "Il volume può essere impostato con un passo di {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Storico",
            deals: {
              columns: {
                comment: "Commento",
                commission: "Commissione",
                direction: "Direzione",
                fee: "Spese",
                order: "Ordine",
                price: "Prezzo",
                profit: "Profitto",
                swap: "Swap",
                symbol: "Simbolo",
                ticket: "Ticket",
                time: "Orario",
                type: "Tipo",
                volume: "Volume",
              },
            },
            empty: "Non hai ancora uno storico di trading",
            menu: {
              columns: {
                horizontalScroll: "Scorrimento Orizzontale",
                resetAll: "Resetta tutto",
                title: "Colonne",
              },
              deals: "Affari",
              orders: "Ordini",
              period: {
                all: "Cronologia Completa",
                last3Months: "Ultimi 3 Mesi",
                last6months: "Ultimi 6 Mesi",
                lastMonth: "Ultimo Mese",
                title: "Periodo",
                customPeriod: "Periodo Personalizzato",
                lastYear: "Ultimo Anno",
                lastWeek: "Ultima Settimana",
                today: "Oggi",
              },
              positions: "Posizioni",
              chart: "Chart",
              newOrder: "Nuovo ordine",
            },
            orders: {
              columns: {
                comment: "Commento",
                price: "Prezzo",
                slDescription: "Stop Loss",
                state: "Stato",
                symbol: "Simbolo",
                ticket: "Ticket",
                timeDone: "Orario",
                timeSetup: "Orario",
                tpDescription: "Take Profit",
                type: "Tipo",
                volume: "Volume",
                timeSetupDescription: "Orario di Apertura",
                timeDoneDescription: "Orario di Chiusura",
              },
              total: {
                title: "Totale",
                filled: "Riempito",
                canceled: "Annullato",
                rejected: "Rigettato",
              },
            },
            positions: {
              columns: {
                commission: "Commissione",
                fee: "Spese",
                priceClose: "Prezzo",
                priceCloseDescription: "Prezzo di Chiusura",
                priceOpen: "Prezzo",
                priceOpenDescription: "Prezzo di Apertura",
                profit: "Profitto",
                slDescription: "Stop Loss",
                swap: "Swap",
                symbol: "Simbolo",
                ticket: "Ticket",
                timeClose: "Orario",
                timeCloseDescription: "Orario di Chiusura",
                timeOpen: "Orario",
                timeOpenDescription: "Orario di Apertura",
                tpDescription: "Take Profit",
                type: "Tipo",
                volume: "Volume",
                comment: "Commento",
              },
            },
            columns: { default: "Predefinito" },
            total: {
              profit: "Profitto",
              credit: "Credito",
              deposit: "Deposito",
              withdrawal: "Prelievo",
              balance: "Bilancio",
              commission: "Commissione",
              fee: "Spese",
              swap: "Swap",
              grossProfit: "Profitto Lordo",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Cronistoria Trade",
                orders: "Ordini di Trading",
                position: "Posizioni di Trading",
                sltp: "Livelli SL/TP",
              },
              notification: "Notifica di Trade",
            },
            oneClick: "One Click Trading",
            tags: { demo: "Demo", readonly: "Solo-lettura" },
            oneClickBottom: "Pannello One Click in Basso",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Accetto questi Termini e Condizioni",
            btnAccept: "Accetta",
            btnCancel: "Annulla",
            text: "Stai per attivare la modalità One Click Trading. Facendo clic su \"Accetto i presenti Termini e Condizioni \" di seguito, l'utente riconosce di aver letto e compreso i seguenti termini e condizioni e accetta di essere vincolato con la presente.<br /><br />Puoi attivare o disattivare la modalità One Click Trading dal menu del tuo terminale web.<br /><br />La modalità One Click Trading per l'invio degli ordini è un processo in un'unica fase. Il tuo ordine verrà inviato quando:&mdash; premi entrambi i pulsanti di bid (SELL) o ask (BUY) sul pannello One Click Trading di un grafico &mdash; premi Sell, Close, Buy o il pulsante per piazzare un ordine nella finestra del Depth of Market &mdash; chiudere le posizioni o eliminare gli ordini nella scheda Trade<br /><br />NON CI SARA' ALCUNA RICHIESTA DI CONFERMA SUCCESSIVA SU CUI FARE CLIC. NON SARAI IN GRADO DI RITIRARE O MODIFICARE L'ORDINE UNA VOLTA FATTO CLIC. IN NORMALI CONDIZIONI DI MERCATO E PRESTAZIONI DI SISTEMA, UN ORDINE DI MERCATO SARA' PRONTAMENTE INSERITO DOPO LA TRASMISSIONE E SI ENTRERA' IN UNA TRANSAZIONE VINCOLANTE.<br /><br />L'utente concorda nell'accettare tutti i rischi associati all'uso della modalità One Click Trading, incluso, senza limitazione, il rischio di errori, omissioni o errori commessi nell'invio di tale ordine.<br /><br />L'utente accetta di indennizzare completamente e tenere indenne {companyName} da tutte le perdite, i costi e le spese che potrebbero derivare da tali errori, omissioni o errori da parte dell'utente o di qualsiasi altra persona che opera per suo conto.",
            title: "Avvertenza - One Click Trading",
          },
          quickTrade: {
            hide: "Nascondi Pannello One Click Trading",
            show: "Mostra Pannello One Click Trading",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Sono consapevole della dichiarazione soprastante e desidero fare trade con prodotti di investimento ad alto rischio",
            btnAccept: "Accetta",
            btnCancel: "Annulla",
            text: "Desideriamo informarti che utilizzando ulteriormente questa piattaforma di trading avrai accesso a prodotti di investimento ad alto rischio, forniti dall'istituto finanziario di tua scelta. Investire in tali prodotti potrebbe non essere adatto a tutti gli investitori, perché comporta il rischio di perdere una parte o tutto l'importo depositato.<br /><br />Prima di decidere di fare trading con prodotti di investimento ad alto rischio, dovresti considerare attentamente gli obiettivi di investimento, il livello di esperienza e il rischio accettabile. Esiste la possibilità che tu possa sostenere una perdita superiore al tuo investimento iniziale e quindi non dovresti investire denaro che non puoi permetterti di perdere.<br /><br />Ti invitiamo ad ampliare le tue conoscenze su tutti i fattori di rischio che riguardano l'investimento in questi prodotti e, in caso di dubbi, chiedi consiglio a un consulente finanziario professionista.",
            title: "Avviso di Investimento ad Alto Rischio",
          },
          table: {
            btnOpen: "Trade",
            columns: {
              comment: "Commento",
              priceClose: "Prezzo",
              priceCloseDescription: "Prezzo di chiusura",
              priceOpen: "Prezzo",
              priceOpenDescription: "Prezzo di apertura",
              profit: "Profitto",
              slDescription: "Stop Loss",
              swap: "Swap",
              symbol: "Simbolo",
              ticket: "Ticket",
              time: "Orario",
              tpDescription: "Take Profit",
              type: "Tipo",
              volume: "Volume",
            },
            emptyPlug: {
              btnNewOrder: "Crea Nuovo Ordine",
              title: "Non hai nessuna posizione",
            },
            menu: {
              chart: "Chart",
              closePosition: "Chiudi Posizione",
              columns: "Colonne",
              modifyOrder: "Modifica Ordine",
              modifyPosition: "Modifica Posizione",
              newOrder: "Nuovo ordine",
              resetAll: "Resetta tutto",
              deleteOrder: "Cancella Ordine",
            },
            oneClick: { deleteOrder: "Elimina" },
            sections: {
              collateralPositions: "Posizioni collaterali",
              orders: "Ordini",
              positions: "Posizioni",
            },
            total: {
              assets: "Assetti",
              balance: "Bilancio",
              collateral: "Collateral",
              commission: "Commissione",
              credit: "Credito",
              equity: "Disponibilità",
              liabilities: "Passività",
              margin: "Margine",
              marginFree: "Margine Libero",
              marginLevel: "Livello",
            },
          },
          timer: {
            marketWillOpen: "Il mercato sarà aperto in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} giorni",
            oneDay: "{numberOfDays} giorno",
          },
          tradeIsDisabled: {
            account: "Il trading per questo account è disabilitato sul server",
            collateral:
              "Trading non disponibile, perché questo simbolo è collaterale",
            disabled: "Il trading è disabilitato",
            investor:
              "Il trading non è disponibile, perché sei connesso con una password investitore",
            readOnly:
              "Il trading non è disponibile, perché non hai accettato l'avviso di rischio",
            symbol: "Trading disabilitato per questo simbolo",
          },
          hotkeys: {
            historyPanel: "Pannello Cronologia",
            journalPanel: "Registro",
            marketWatch: "Market Watch",
            quickTrade: "One Click Trading",
            tradeForm: "Nuovo ordine",
            tradePanel: "Pannello di Trading",
          },
          marketOpen: {
            time: "Mercato chiuso - aprirà alle {time}",
            afterSeconds: "Mercato chiuso - aprirà in {time} secondi",
          },
          expiredTimer: { seconds: "Scade tra {time} secondi" },
          corporateLink: {
            type: {
              clientAgreement: "Accordo con il cliente",
              riskDisclosure: "Rivelazione del rischio",
              fdmDisclaimer: "Esclusione di responsabilità di FDM",
              clientAgreementAndRiskDisclosure:
                "Accordo con il cliente e rivelazione del rischio",
              complaintsHandlingProcedure: "Procedura di gestione dei reclami",
              orderExecutionPolicy: "Le Policy di esecuzione degli Ordine",
              clientCategorisationNotice:
                "Avviso di categorizzazione del cliente",
              conflictsOfInterestPolicy: "Le Policy di conflitto di interessi",
              dataProtectionPolicy: "Policy protezione dati",
            },
          },
          margin: {
            floating: "fluttuante",
            mode: { marketBuy: "Market buy", marketSell: "Market sell" },
            rangeMode: {
              value: "valore nozionale",
              valuePerSymbol: "valore nozionale per simbolo",
              volume: "volume",
              volumePerSymbol: "volume per simbolo",
            },
            showValue: "Mostra i valori in {currency} per lotto",
            rates: "Tasso di margine:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Disattiva Schermo Intero",
            enable: "Attiva Schermo Intero",
          },
          journal: {
            btnOpen: "Registro",
            columns: {
              message: "Messaggio",
              source: "Sorgente",
              time: "Orario",
            },
            menu: {
              clear: "Ripulisci",
              debugMode: "Modalità Debug",
              exportFile: "Esporta su File",
            },
          },
          menu: {
            about: "Riguardo al programma",
            contact: "Contattaci",
            brokerInformation: "Informazioni sull'azienda",
            chartSettings: {
              controls: "Controlli grafici",
              grid: "Griglia",
              ohlc: "Mostra OHLC",
              title: "Impostazioni grafico",
              askPrice: "Prezzo Ask",
              crosshair: "Cursore mirino",
            },
            connect: "Collegarsi all'account",
            language: {
              title: "Lingua",
              search: "Cerca",
              nothingFound: "Lingua non trovata",
            },
            openDemo: "Apri conto Demo",
            openReal: "Apri conto Reale",
            settings: "Impostazioni",
            shortcuts: "Scorciatoie",
            theme: {
              blackWhite: "Nero & Bianco",
              blueRed: "Blu & Rosso",
              dark: "Tema Scuro",
              editor: "Editor di Temi",
              greenRed: "Verde & Rosso",
              light: "Tema Chiaro",
              neutral: "Neutrale",
              templates: "Modelli di colori",
            },
            title: "Menu",
            tradingAccount: "Conti di trading",
            terms: "Termini e Condizioni",
            desktopPlatforms: "Piattaforma Desktop",
            qrCode: {
              install: "Scansione per installare dal {store}",
              downloadApk: "Scansiona per ottenere il file APK Android",
            },
            economicCalendar: "Calendario Economico",
          },
          screen: { back: "Indietro" },
          mobile: { bottomNav: { quotes: "Quotazioni" } },
          hotkeys: {
            sections: { navigation: "Navigazione", view: "Vista" },
            escape: "Annulla",
            indicators: "Indicatori",
            depthOfMarket: "Depth Of Market",
            objectTreePanel: "Albero degli Oggetti",
            scrollRight: "Candela Successiva",
            scrollToStart: "Scorrere il Grafico all'Inizio",
            scrollLeft: "Candela Precedente",
            scrollToEnd: "Scorrere il Grafico alla Fine",
            resetChartView: "Ripristina Grafico",
            zoomIn: "Ingrandisci",
            zoomOut: "Riduci",
            fullScreen: "Schermo Pieno",
            screenshot: "Salva il grafico come immagine",
            title: "Scorciatoie",
          },
          timezone: {
            title: "Fuso orario",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunisi",
              anchorage: "Ancoraggio",
              bogota: "Bogotà",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "città del Messico",
              newYork: "New York",
              phoenix: "Fenice",
              santiago: "Santiago",
              saoPaulo: "San Paolo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrein",
              bangkok: "Bangkok",
              kolkata: "Calcutta",
              colombo: "Colombo",
              dhaka: "Dacca",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Giakarta",
              jerusalem: "Gerusalemme",
              karachi: "Karachi",
              kathmandu: "Katmandu",
              kuwait: "Kuwait",
              manila: "manila",
              muscat: "Moscato",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riad",
              saigon: "Saigon",
              seoul: "Seul",
              shanghai: "Shangai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Teheran",
              tokyo: "Tokio",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Atene",
              belgrade: "Belgrado",
              berlin: "Berlino",
              bratislava: "Bratislava",
              brussels: "Bruxelles",
              bucharest: "Bucarest",
              budapest: "Budapest",
              copenhagen: "Copenaghen",
              dublin: "Dublino",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbona",
              london: "Londra",
              luxembourg: "Lussemburgo",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Mosca",
              oslo: "Oslo",
              paris: "Parigi",
              prague: "Praga",
              riga: "Riga",
              rome: "Roma",
              stockholm: "Stoccolma",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Varsavia",
              zurich: "Zurigo",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { i as a, o as b, a as c, e as i };
