const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Didinti",
            zoomOut: "Mažinti",
          },
          crosshair: "Kryžmė",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Pridėti indikatorių",
            btnOpenPopup: "Add Indicator",
            close: "Uždaryti",
            form: {
              applyTo: "Taikyti",
              background: {
                title: "Fonas",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Nuokrypis",
              enterDistance: "Periodas",
              enterShift: "Slinkti",
              fastEma: "Greitas EMA",
              slowEma: "Lėtas EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Maksumumas",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Paprastai",
                smoothed: "Smoothed",
                title: "Metodas",
              },
              opacity: "Opacity",
              period: {
                jaws: "Žandikaulių laikotarpis",
                lips: "Lūpų laikotarpis",
                teeth: "Dantų laikotarpis",
                title: "Periodas",
                dPercent: "%D periodas",
                kPercent: "%K periodas",
              },
              selectApplyTo: "Pasirinkti",
              selectVolumesType: "Select volume type",
              shift: "Slinkti",
              showTimeframes: "Rodyti visuose laikotarpiuose",
              slowing: "Lėtėjimas",
              step: "Žingsnis",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Stilius",
                up: "Up style",
                rvi: "RVI stilius",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Apimties",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Kaina",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Paieška",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Viskas",
              billWilliams: "Bill Williams",
              oscillators: "Osciliatoriai",
              trend: "Tendencija",
              volumes: "Apimties",
            },
            title: "Select indicator",
            up: "Į viršų",
            down: "Į apačią",
            chartControls: {
              show: "Rodyti",
              hide: "Slėpti",
              settings: "Nustatymai",
              remove: "Pašalinti",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Uždarymo kaina",
              dailyChange: "Dienos skirtumas",
              openPrice: "Atidarymo kaina",
              spread: "Spredas",
              symbol: "Simbolis",
              time: "Laikas",
              high: "Aukščiausia",
              low: "Žemiausia",
              last: "Paskutinis",
              lastHigh: "Paskutinis aukštas",
              lastLow: "Paskutinis žemas",
              highLow: "Aukščiausia/Žemiausia",
              bidLow: "Statymas žema",
              bidHigh: "Statymas aukšta",
              askHigh: "Prašymo aukšta",
              askLow: "Prašymo žema",
              bid: "Statymas",
              ask: "Prašymo",
              title: "Stulpeliai",
            },
            menu: {
              chart: "Grafikas",
              columns: "Stulpeliai",
              dom: "Rinkos gylis",
              hide: "Slėpti",
              newOrder: "Naujas pavedimas",
              specification: "Specifikacija",
            },
            search: "Paieška",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Rodyklės",
              showAlways: "Show always",
              angle: "Kampas",
              distance: "Distance",
              bar: "Stulpelis",
              price: "Kaina",
              prices: "Kainos",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Rodyti visuose laikotarpiuose",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Jūsų tekstas",
              props: "Savybės",
              style: "Stilius",
              rays: "Rays",
              background: "Fonas",
              extends: "Extension",
              extended: "Išplėstinis režimas",
              pipsPerBar: "Punktų juostoje",
              gannAngle: "Gann kampas",
              deviations: "Nuokrypiai",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Atnaujinti", cancel: "Atšaukti" },
              tabs: {
                style: "Stilius",
                coordinates: "Coordinates",
                visualization: "Vizualizacija",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Kairė",
                right: "Dešinė",
                center: "Centras",
                top: "Viršus",
                middle: "Middle",
                bottom: "Apačia",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Vienodų atstumų kanalas",
            regressionChannel: "Regresijos Kanalas",
            stdDevChannel: "Standartinio Nuokrypio Kanalas",
            fibonacciRetracement: "Fibonačio analizė",
            gannFan: "Ganno Vėduoklė",
            gannGrid: "Ganno Grotelės",
            gannLine: "Ganno Linija",
            arrowLine: "Strėle pažymėta linija",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Horizontali linija",
            infoLine: "Info Line",
            rayLine: "Spindulys",
            trendAngle: "Tendencija pagal kampą",
            trendline: "Tendencijos linija",
            verticalLine: "Vertikali linija",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Stačiakampis",
            circle: "Circle",
            triangle: "Trikampis",
            ellipse: "Elipsė",
            text: "Tekstas",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "1 d.",
              H1: "1 val.",
              H4: "4 val.",
              M1: "1 min.",
              M15: "15 min.",
              M30: "30 min.",
              M5: "5 min.",
              MN: "1 mėn.",
              Unknown: "Unknown",
              W1: "1 sav.",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "GTC režimas",
            calculation: "Pelno apskaičiavimo būdas",
            chartMode: "Diagramos režimas",
            contractSize: "Sutaries dydis",
            days: {
              friday: "Penktadienis",
              monday: "Pirmadienis",
              saturday: "Šeštadienis",
              sunday: "Sekmadienis",
              thursday: "Ketvirtadienis",
              tuesday: "Antradienis",
              wednesday: "Trečiadienis",
            },
            digits: "Skaitmenys",
            empty: "No symbol selected",
            execution: "Vykdymas",
            expiration: "Pasibaigęs",
            filling: "Užpildyti",
            initial: "Pradinė",
            maintenance: "Palaikomoji",
            marginCurrency: "Maržos valiuta",
            marginRate: "Maržos santykis",
            maxVolume: "Didž. kiekis",
            minVolume: "Maž. kiekis",
            orders: "Pavedimai",
            profitCurrency: "Pelno valiuta",
            schedule: { quotes: "Kotiruotės", trade: "Prekiauti" },
            sector: "Sektorius",
            spread: "Spredas",
            stopsLevel: "Sustojimo lygis",
            swapLong: "Ilgas keitimas",
            swapShort: "Trumpas keitimas",
            swapType: "Keitimosi tipas",
            title: "{symbol} contract specification",
            tradeMode: "Prekiauti",
            volumeStep: "Apimties žingsnis",
            volumeLimit: "Apimties limitas",
            tickSize: "Momentinis dydis",
            tickValue: "Momentinė reikšmė",
            marginInitial: "Pradinė marža",
            marginHedged: "Apdrausta marža",
            commission: {
              daily: {
                volume: "Dienos apimtis lotais",
                turnoverVolume: "Kasdieninė apyvarta lotais",
                turnoverMoney: "Kasdieninė apyvarta pinigais",
                value: "Dienos sandorių vertė",
                profit: "Dienos pajamos",
              },
              monthly: {
                volume: "Mėnesio apimtis lotais",
                turnoverVolume: "Mėnesinė apyvarta lotais",
                turnoverMoney: "Mėnesinė apyvarta pinigais",
                value: "Mėnesio sandorių vertė",
                profit: "Mėnesio pajamos",
              },
              instant: {
                volume: "Momentinė pagal sandorių apimtį",
                value: "Momentinė pagal sandorio vertę",
                profit: "Momentinė pagal sandorio pajamas",
              },
              entry: {
                in: "sandoriuose",
                out: "išoriniai sandoriai",
                all: "vidiniai/išoriniai sandoriai",
              },
              tier: {
                mode: {
                  pips: "punktai",
                  percent: "% - {currency}",
                  percentProfit: "% pajamų {currency}",
                },
                type: { perDeal: "už sandorį", perLot: "už lotą" },
              },
              header: "Komisiniai mokesčiai",
            },
          },
          tree: {
            close: "Uždaryti",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Pašalinti",
            settings: "Nustatymai",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Stulpeliai",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Tick apimtys",
            volumes: "Apimties",
            withoutVolumes: "Without Volumes",
            realVolumes: "Realios apimtys",
          },
          zoom: { in: "Didinti", out: "Mažinti" },
          hotkeys: {
            arrowLine: "Strėle pažymėta linija",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Linijinė diagrama",
            chartTypeBar: "Juostos diagrama",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Horizontali linija",
            infoLine: "Info Line",
            rayLine: "Spindulys",
            realVolumes: "Real Volumes",
            tickVolumes: "Tick apimtys",
            trendline: "Tendencijos linija",
            verticalLine: "Vertikali linija",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Apimtis",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Atidaryta nauja sąskaita",
          },
          brokerInformation: {
            company: "Įmonė",
            email: "Paštas",
            phone: "Telefonas",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Keisti slaptažodį",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Keisti slaptažodį",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Išsaugoti slaptažodį",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Sutikti",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "RIZIKOS ATSKLEIDIMAS",
          },
          errors: {
            error: "Klaida",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Paskyros tipas",
            address: "Adresas",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Metinis įnašas",
            annualIncome: "Metinės pajamos",
            broker: "Įmonė",
            btn: {
              back: "Atgal",
              cancel: "Atšaukti",
              next: "Toliau",
              openAccount: "Open Account",
              remove: "Pašalinti",
              signOut: "Sign out",
            },
            city: "Miestas",
            cityPlaceholder: "Enter your city",
            country: "Šalis",
            dateBirth: "Gimimo data",
            deposit: "Depozitas",
            education: "Education",
            email: {
              address: "Paštas",
              code: "Code from email",
              placeholder: "Enter email",
              title: "Paštas",
            },
            employement: "Employement",
            forex: "Forex",
            futures: "Ateities kontraktai",
            gender: { female: "Moteris", male: "Vyras", title: "Lytis" },
            identity: "Tapatybė",
            imageOrPdfFile: "Image or PDF file",
            investor: "Investuotojas",
            language: "Kalba",
            leverage: "Svertas",
            login: "Įeiti",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Pavadinimas",
              yourName: "Your Name",
            },
            nationality: "Tautybė",
            netWorth: "Grynoji vertė",
            optional: "Optional",
            password: "Slaptažodis",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Sutinku su sąskaitos sukūrimo terminais ir sąlygomis bei duomenų apsaugos politika",
            server: "Serveris",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Pajamų šaltinis",
            state: "Valstija",
            status: "Būsena",
            stocks: "Akcijos",
            taxID: "Mokesčių mokėtojo ID",
            type: "Tipas",
            useHedge: "Naudoti hedge prekyboje",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "Išjungti 2FA/TOTP",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "Jungti 2FA/TOTP",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Norėdami patikrinti Authenticator veikimą, įveskite savo paskyros kodą, kurį sugeneravo programėlė.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "2FA autentifikavimas yra būtinas papildomam paskyros saugumui.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Banko ataskaita",
              utilityBill: "Sąskaita už komunalines paslaugas",
            },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Vairuotojo pažymėjimas",
              idCard: "Tapatybės kortelė",
              passport: "Pasas",
              residencePermit: "Leidimas gyventi",
            },
            educationLevel: {
              bachelor: "Bakalauro laipsnis arba lygiavertis",
              highScholl: "Gimnazija",
              master: "Magistro laipsnis arba lygiavertis",
              none: "Nė vienas",
              other: "Kitas",
              phd: "PHD arba lygiavertis",
            },
            employment: {
              employed: "Įdarbintas",
              other: "Kitas",
              retired: "Nebegalioja",
              selfEmployed: "Verslininkas arba savarankiškai dirbantis",
              student: "Studentas",
              unemployed: "Bedarbis",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "> 3 metai",
              form1to3: "1 iki 3 metų",
              less1: "< 1 metai",
            },
            industry: {
              agriculture: "Žemės ūkis, maistas ir gamtiniai ištekliai",
              communication:
                "Menai, garso ir vaizdo technologija ir komunikacija",
              construction: "Architektūra ir statyba",
              education: "Edukacija ir mokymai",
              engineering: "Inžinerija ir matematika",
              government: "Valdymas ir viešasis administravimas",
              healthcare: "Sveikatos apsauga",
              it: "Informacinės technologijos",
              management: "Verslo valdymas ir administravimas",
              manufacturing: "Gamyba",
              marketing: "Rinkodara ir pardavimai",
              none: "Nė vienas",
              other: "Kitas",
              science: "Mokslas ir technologija",
              security:
                "Teisė, Visuomenės saugumas, Baudžiamoji teisė ir Apsauga",
              tourism: "Svetingumas ir turizmas",
              transport: "Transportavimas, platinimas ir logistika",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Pajamos iš darbo ar verslo",
              inheritance: "Dovanos arba paveldėjimas",
              other: "Kitas",
              savings: "Santaupos arba investicijos",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Uždaryti",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Vienetai vietoje Lotų",
              extended: "Išplėstinis režimas",
              spread: "Spredas",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Rinkos gylis",
          },
          errors: {
            accepted: "Priimta",
            allowedOnlyLongPositions: "Leidžiamos tik ilgos pozicijos",
            allowedOnlyPositionsClosing: "Leidžiamas tik pozicijos uždarymas",
            allowedOnlyShortPositions: "Leidžiamos tik trumpos pozicijos",
            automatedTradingDisabledClient:
              "Automatinė prekyba kliento terminale išjungta",
            automatedTradingDisabledServer:
              "Automatinė prekyba šiame serveryje negalima",
            canceled: "Nutraukta",
            common: "Bendra klaida",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Atlikta",
            donePartially: "Įvykdytas dalinai",
            frequentRequests: "Per dažnos užklausos",
            invalidExpiration: "Neleidžiamas galiojimo laikas",
            invalidOrderType: "Neteisingas pavedimo tipas",
            invalidParameters: "Neteisingi parametrai",
            invalidPrices: "Netesingos kainos",
            invalidSLTP: "Neteisingi S/L ar T/P",
            invalidVolume: "Neteisingas kiekis",
            manyTradeRequests: "Per daug užklausų",
            marketClosed: "Rinka uždaryta",
            modificationFailed:
              "Pakeitimas nepavyko nes pavedimas arba pozicija per daug arti rinkos kainos",
            networkProblem: "Tinklo problemos",
            noConnection: "Nėra ryšio",
            notEnoughMoney: "Nepakanka lėšų",
            offQuotes: "Už kainos ribų",
            ok: "Gerai",
            onTheWay: "Išsiųsta",
            orderChanged: "Pavedimas jau buvo pakeistas",
            orderClosePositionExists:
              "Pavedimas šios pozicijos uždarymui jau yra",
            ordersLimitReached: "Pavedimų riba pasiekta",
            permissions: "Neužtenka teisių",
            placed: "Įvykdytas",
            positionCloseProhibitedByFIFO:
              "Pozicijos uždarymas draudžiamas FIFO taisyklės",
            positionClosed: "Pozicija jau uždaryta",
            positionsLimitReached: "Pasiektas pozicijų limitas",
            priceChanged: "Kaina pasikeitė",
            prices: "Kainos",
            processed: "Apdorojama",
            rejected: "Atmesta",
            requestRejectedOrderWillCanceled:
              "Užklausa atmesta, pavedimas atšauktas",
            requoted: "Perkainavimas",
            serverProblem: "Techninė serverio problema",
            timeout: "Pertrauka",
            tradeDisabled: "Prekyba išjungta",
            unsupportedFillingMode: "Nepalaikomas įvykdymo režimas",
            volumeLimitReached: "Apimties lygis pasiektas",
          },
          form: {
            acceptNewQuotes: "Ar priimti šią naują kainą?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Naujas pavedimas",
            },
            buttons: {
              accept: "Sutikti",
              delete: "Šalinti",
              modify: "Keisti",
              ok: "Gerai",
              placeOrder: "Place order",
              reject: "Atmesti",
              request: "Užklausti",
              requestPrice: "Request Price",
            },
            close: "Uždaryti",
            execution: {
              fillOrKill: "Užpildyti arba anuliuoti",
              immediateOrCancel: "Dalinai arba anuliuoti",
              bookOrCancel: "Užsakyti arba atšaukti",
              label: "Užpildymo elgsena",
              return: "Grįžti",
            },
            executionMode: {
              exchange: "Įvykdymas Biržoje ",
              instant: "Vykdyti nedelsiant",
              market: "Įvykdymas Rinkoje",
              request: "Prašyti vykdyti",
            },
            expiration: {
              date: "Expiration Date",
              label: "Pasibaigęs",
              types: {
                specified: "Data ir laikas",
                specifiedDay: "Specified Day",
                today: "Šios dienos",
              },
            },
            fields: {
              closeBy: "Uždaryti pagal",
              comment: "Pastaba",
              price: "Kaina",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Apimtis",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Istorija",
            deals: {
              columns: {
                comment: "Pastaba",
                commission: "Komisiniai",
                direction: "Kryptis",
                fee: "Mokestis",
                order: "Pavedimas",
                price: "Kaina",
                profit: "Pelnas",
                swap: "Keitimas",
                symbol: "Simbolis",
                ticket: "Kortelė",
                time: "Laikas",
                type: "Tipas",
                volume: "Apimtis",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Stulpeliai",
              },
              deals: "Sandoriai",
              orders: "Pavedimai",
              period: {
                all: "Visa istorija",
                last3Months: "Paskutiniai 3 mėn.",
                last6months: "Paskutiniai 6 mėn.",
                lastMonth: "Paskutinis mėn.",
                title: "Periodas",
                customPeriod: "Nestandartinis periodas",
                lastYear: "Paskutiniai metai",
                lastWeek: "Paskutinės savaitės",
                today: "Šios dienos",
              },
              positions: "Pozicija",
              chart: "Grafikas",
              newOrder: "Naujas pavedimas",
            },
            orders: {
              columns: {
                comment: "Pastaba",
                price: "Kaina",
                slDescription: "Stop Loss",
                state: "Valstija",
                symbol: "Simbolis",
                ticket: "Kortelė",
                timeDone: "Laikas",
                timeSetup: "Laikas",
                tpDescription: "Take Profit",
                type: "Tipas",
                volume: "Apimtis",
                timeSetupDescription: "Atidaryti laiką",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Visas",
                filled: "Užpildyta",
                canceled: "Nutraukta",
                rejected: "Atmesta",
              },
            },
            positions: {
              columns: {
                commission: "Komisiniai",
                fee: "Mokestis",
                priceClose: "Kaina",
                priceCloseDescription: "Uždarymo kaina",
                priceOpen: "Kaina",
                priceOpenDescription: "Atidarymo kaina",
                profit: "Pelnas",
                slDescription: "Stop Loss",
                swap: "Keitimas",
                symbol: "Simbolis",
                ticket: "Kortelė",
                timeClose: "Laikas",
                timeCloseDescription: "Close Time",
                timeOpen: "Laikas",
                timeOpenDescription: "Atidaryti laiką",
                tpDescription: "Take Profit",
                type: "Tipas",
                volume: "Apimtis",
                comment: "Komentaras",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Pelnas",
              credit: "Kreditas",
              deposit: "Įnašas",
              withdrawal: "Persivedimas",
              balance: "Balansas",
              commission: "Komisiniai mokesčiai",
              fee: "Mokestis",
              swap: "Svopas",
              grossProfit: "Bendrasis pelnas",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Prekybos istorija",
                orders: "Trade Orders",
                position: "Trade Positions",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Prekyba vienu spustelėjimu",
            tags: { demo: "Demo", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Sutinku su šiomis sąlygomis",
            btnAccept: "Sutikti",
            btnCancel: "Atšaukti",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Aš suvokiu visas galimas rizikas ir noriu prekiauti aukštos rizikos investiciniais produktais",
            btnAccept: "Sutikti",
            btnCancel: "Atšaukti",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Perspėjimas investuotojui. Aukštas rizikingumas",
          },
          table: {
            btnOpen: "Prekiauti",
            columns: {
              comment: "Pastaba",
              priceClose: "Kaina",
              priceCloseDescription: "Uždarymo kaina",
              priceOpen: "Kaina",
              priceOpenDescription: "Atidarymo kaina",
              profit: "Pelnas",
              slDescription: "Stop Loss",
              swap: "Keitimas",
              symbol: "Simbolis",
              ticket: "Kortelė",
              time: "Laikas",
              tpDescription: "Take Profit",
              type: "Tipas",
              volume: "Apimtis",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Grafikas",
              closePosition: "Uždaryti poziciją",
              columns: "Stulpeliai",
              modifyOrder: "Keisti tvarką",
              modifyPosition: "Pozicijos modifikavimas",
              newOrder: "Naujas pavedimas",
              resetAll: "Reset all",
              deleteOrder: "Šalinti pavedimą",
            },
            oneClick: { deleteOrder: "Šalinti" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Pavedimai",
              positions: "Pozicija",
            },
            total: {
              assets: "Aktyvai",
              balance: "Balansas",
              collateral: "Įkaitas",
              commission: "Komisiniai",
              credit: "Kreditas",
              equity: "Turtas",
              liabilities: "Isipareigojimai",
              margin: "Marža",
              marginFree: "Laisvoji marža",
              marginLevel: "Lygis",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Žurnalas",
            marketWatch: "Rinkos apžvalga",
            quickTrade: "Prekyba vienu spustelėjimu",
            tradeForm: "Naujas pavedimas",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Kliento sutartis",
              riskDisclosure: "Rizikos atskleidimas",
              fdmDisclaimer: "FDM atsakomybės atsisakymas",
              clientAgreementAndRiskDisclosure:
                "Kliento sutartis ir rizikos atskleidimas",
              complaintsHandlingProcedure: "Nusiskundimo sprendimų procedūra",
              orderExecutionPolicy: "Įsakymų vykdymo politika",
              clientCategorisationNotice: "Kliento kategorizacijos pastaba",
              conflictsOfInterestPolicy: "Interesų politikos konfliktas",
              dataProtectionPolicy: "Duomenų apsaugos politika",
            },
          },
          margin: {
            floating: "plaukiojantis",
            mode: {
              marketBuy: "Pirkimas rinkoje",
              marketSell: "Pardavimas rinkoje",
            },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Išjungti visą ekraną",
            enable: "Įjungti visą ekraną",
          },
          journal: {
            btnOpen: "Žurnalas",
            columns: { message: "Žinutė", source: "Šaltinis", time: "Laikas" },
            menu: {
              clear: "Išvalyti",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Tinklelis",
              ohlc: "Rodyti OHLC",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Kalba",
              search: "Paieška",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Nustatymai",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Sąlygos",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Ekonominis kalendorius",
          },
          screen: { back: "Atgal" },
          mobile: { bottomNav: { quotes: "Kotiruotės" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Rodinys" },
            escape: "Atšaukti",
            indicators: "Rodikliai",
            depthOfMarket: "Rinkos gylis",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Didinti",
            zoomOut: "Mažinti",
            fullScreen: "Visas ekranas",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { a, i as b, t as c, e as l };
