const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "경제 달력을 차트에서 숨기기",
              show: "경제 달력을 차트에 보이기",
            },
          },
          controls: {
            reset: "차트 재설정",
            scrollEnd: "마지막까지 스크롤",
            scrollLeft: "왼쪽으로 스크롤",
            scrollRight: "오른쪽으로 스크롤",
            zoomIn: "확대",
            zoomOut: "축소",
          },
          crosshair: "십자선",
          delay: "{delay}분 딜레이",
          indicators: {
            btnAddIndicator: "지표 추가",
            btnOpenPopup: "지표 추가",
            close: "청산",
            form: {
              applyTo: "다음에 적용",
              background: {
                title: "배경",
                down: "하락 구름 배경",
                up: "상승 구름 배경",
              },
              deviation: "편차",
              enterDistance: "주기",
              enterShift: "이동",
              fastEma: "빠른 EMA",
              slowEma: "느린 EMA",
              line: {
                base: "베이스 라인",
                down: "다운 라인",
                minusDI: "-DI 라인",
                null: "Null 라인",
                plusDI: "+DI 라인",
                style: "라인 스타일",
                cci: "CCI 라인",
                up: "Up 라인",
                fi: "FI 라인",
              },
              maximum: "최대",
              method: {
                exponential: "지수",
                linearWeighted: "가중 리니어",
                simple: "간단",
                smoothed: "평활화",
                title: "메소드",
              },
              opacity: "불투명",
              period: {
                jaws: "Jaws 기간",
                lips: "Lips 기간",
                teeth: "Teeth 기간",
                title: "주기",
                dPercent: "%D 주기",
                kPercent: "%K 주기",
              },
              selectApplyTo: "선택",
              selectVolumesType: "볼륨 타입 선택",
              shift: "이동",
              showTimeframes: "모든 시간대 보이기",
              slowing: "느린",
              step: "단계",
              style: {
                down: "하락시 스타일",
                jaws: "Jaws 스타일",
                lips: "Lips 스타일",
                main: "메인 스타일",
                signal: "시그널 스타일",
                teeth: "Teeth 스타일",
                title: "스타일",
                up: "상승시 스타일",
                rvi: "RVI 스타일",
              },
              volume: { down: "볼륨 다운", up: "볼륨 업" },
              volumes: "볼륨",
              mfiUp: "MFI 업",
              mfiDown: "MFI 다운",
              price: {
                title: "가격",
                select: "가격 선택",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "아이템이 없습니다",
              title: "검색",
              tryAnother: "다른 쿼리를 시도해 보세요",
            },
            tabs: {
              all: "모든",
              billWilliams: "빌 윌리엄스",
              oscillators: "오실레이터",
              trend: "추세",
              volumes: "거래량",
            },
            title: "지표 선택",
            up: "상향",
            down: "아래로",
            chartControls: {
              show: "보이기",
              hide: "숨기기",
              settings: "설정",
              remove: "삭제",
            },
          },
          loading: "로딩",
          marketWatch: {
            btnOpen: { hide: "시장 심도 숨기기", show: "시장심도 보이기" },
            columns: {
              closePrice: "청산 가격",
              dailyChange: "매일의 변화",
              openPrice: "진입 가격",
              spread: "스프레드",
              symbol: "통화",
              time: "시간",
              high: "고가",
              low: "저가",
              last: "체결 종가",
              lastHigh: "체결 고가",
              lastLow: "체결 저가",
              highLow: "고가/저가",
              bidLow: "현재가 저가",
              bidHigh: "현재가 고가",
              askHigh: "호가 고가",
              askLow: "호가 저가",
              bid: "현재가",
              ask: "호가",
              title: "열",
            },
            menu: {
              chart: "차트",
              columns: "열",
              dom: "시장심도",
              hide: "숨기기",
              newOrder: "새 주문",
              specification: "설명",
            },
            search: "검색",
            searchSymbol: "심볼 검색",
            nothingFound: "심볼이 없습니다",
          },
          objects: {
            form: {
              statistics: "통계",
              arrows: "그림상자",
              showAlways: "항상 보이기",
              angle: "우측 하단",
              distance: "거리",
              bar: "바",
              price: "가격",
              prices: "가격들",
              showPrice: "가격 보이기",
              showText: "텍스트 보이기",
              showDate: "날짜 보이기",
              showTime: "시간 보이기",
              showAllTimeframes: "모든 시간대 보이기",
              showPearsonR: "Pearson's R 보이기",
              showLabels: "라벨 보이기",
              yourText: "메시지 입력",
              props: "속성",
              style: "스타일",
              rays: "Rays",
              background: "배경",
              extends: "늘이기",
              extended: "늘이기",
              pipsPerBar: "봉 당 핍",
              gannAngle: "Gann 각도",
              deviations: "편차",
              labels: "라벨",
              reverse: "거꾸로",
              btn: { update: "비교상태 업데이트", cancel: "취소" },
              tabs: {
                style: "스타일",
                coordinates: "좌표",
                visualization: "정보표시",
              },
              range: { price: "가격 범위", bars: "바 범위", date: "날짜 범위" },
              align: {
                horizontal: "수평 정렬",
                vertical: "수직 정렬",
                left: "왼쪽",
                right: "오른쪽",
                center: "중앙",
                top: "상단",
                middle: "가운데",
                bottom: "아래",
              },
              line: {
                style: "라인 스타일",
                base: "베이스 라인",
                up: "업 라인",
                down: "다운 라인",
                middle: "미들 라인",
              },
            },
            visible: { hide: "모든 객체 숨기기", show: "모든 객체 보이기" },
            lock: "모든 객체 잠그기",
            unlock: "모든 객체 잠금 해제",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "등거리채널",
            regressionChannel: "회귀 채널",
            stdDevChannel: "분산 채널",
            fibonacciRetracement: "피보나치 되돌림",
            gannFan: "간 fan",
            gannGrid: "간 그리드",
            gannLine: "간 선",
            arrowLine: "기호화된 선",
            crossLine: "크로스 라인",
            extendedLine: "확장선",
            horizontalRay: "수평 레이",
            horizontalLine: "수평선",
            infoLine: "인포 라인",
            rayLine: "선",
            trendAngle: "각도 추세선",
            trendline: "추세선",
            verticalLine: "수직선",
            disjointAngle: "수렴 확산 채널",
            flatTopBottom: "수평 대각",
            rectangle: "직사각형",
            circle: "원",
            triangle: "삼각형",
            ellipse: "타원",
            text: "텍스트",
            rulerLine: "눈금자 라인",
          },
          period: {
            full: {
              D1: "1 일",
              H1: "1 시간",
              H4: "4 시간",
              M1: "1 분",
              M15: "15 분",
              M30: "30 분",
              M5: "5 분",
              MN: "1 개월",
              Unknown: "알려지지 않은",
              W1: "1 주",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "알려지지 않은",
              W1: "W1",
            },
          },
          screenshot: "차트를 이밎로 저장",
          symbolSpecs: {
            GTCmode: "지속주문 모드",
            calculation: "계산",
            chartMode: "차트 모드",
            contractSize: "거래 단위",
            days: {
              friday: "금요일",
              monday: "월요일",
              saturday: "토요일",
              sunday: "일요일",
              thursday: "목요일",
              tuesday: "목요일",
              wednesday: "수요일",
            },
            digits: "자리수",
            empty: "심볼이 선택되지 않았습니다",
            execution: "실행",
            expiration: "만료",
            filling: "체결 방법",
            initial: "초기증거금",
            maintenance: "유지증거금",
            marginCurrency: "마진 통화",
            marginRate: "마진 비율",
            maxVolume: "최대 거래량",
            minVolume: "최소 거래량",
            orders: "주문",
            profitCurrency: "수익 통화",
            schedule: { quotes: "가격", trade: "거래" },
            sector: "부문",
            spread: "스프레드",
            stopsLevel: "스톱레벨",
            swapLong: "스왑 매수",
            swapShort: "스왑 매도",
            swapType: "스왑 타입",
            title: "{symbol} 계약 상세 내용",
            tradeMode: "거래",
            volumeStep: "거래량 단위",
            volumeLimit: "볼륨 제한",
            tickSize: "틱사이즈",
            tickValue: "틱밸류",
            marginInitial: "초기입금액",
            marginHedged: "헤지증거금",
            commission: {
              daily: {
                volume: "랏 기준의 일간 거래량",
                turnoverVolume: "랏 일별 매출",
                turnoverMoney: "자금 일별 매출",
                value: "거래의 일간 환산 가치",
                profit: "일간 수익",
              },
              monthly: {
                volume: "랏 기준의 월간 거래량",
                turnoverVolume: "랏 월별 매출",
                turnoverMoney: "자금 월별 매출",
                value: "거래의 월간 환산 가치",
                profit: "월간 수익",
              },
              instant: {
                volume: "거래량 기준 인스턴트",
                value: "거래의 환산 가치 기준 인스턴트",
                profit: "거래 수익 기준 인스턴트",
              },
              entry: { in: "in 거래", out: "out 거래", all: "in/out 거래" },
              tier: {
                mode: {
                  pips: "포인트",
                  percent: "% {currency}",
                  percentProfit: "% 수익의 {currency}",
                },
                type: { perDeal: "거래 별", perLot: "랏 별" },
              },
              header: "수수료",
            },
          },
          tree: {
            close: "청산",
            empty: "차트에 객체가 없습니다",
            lock: "잠그기",
            remove: "삭제",
            settings: "세팅",
            title: "그리기 관리",
            unlock: "잠금 해제",
          },
          types: {
            area: "영역",
            line: "라인",
            bars: "봉수",
            candlestick: "캔들스틱",
          },
          volumeTypes: {
            tickVolumes: "틱 거래량",
            volumes: "거래량",
            withoutVolumes: "볼륨 없이",
            realVolumes: "실제 볼륨",
          },
          zoom: { in: "확대", out: "축소" },
          hotkeys: {
            arrowLine: "기호화된 선",
            chartTypeArea: "영역 차트",
            chartTypeLine: "라인 차트",
            chartTypeBar: "바 차트",
            chartTypeCandle: "캔들 차트",
            crossLine: "크로스 라인",
            extendedLine: "확장선",
            horizontalLine: "수평선",
            infoLine: "인포 라인",
            rayLine: "선",
            realVolumes: "실제 볼륨",
            tickVolumes: "틱 거래량",
            trendline: "추세선",
            verticalLine: "수직선",
            sections: {
              chartType: "차트 타입",
              drawing: "그리기",
              volume: "거래량",
            },
            crosshairRuler: "십자선 눈금자",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "계정을 만들고 시작해 보세요",
            newAccountOpened: "새 계좌 개설됨",
          },
          brokerInformation: {
            company: "회사",
            email: "이메일",
            phone: "전화번호",
            registrationAddress: "주소 등록",
            title: "회사명",
            website: "웹사이트",
          },
          changePassword: {
            btnChange: "비밀번호 변경",
            confirmPassword: "비밀번호 확인",
            newPassword: "새로운 비밀번호",
            title: "비밀번호 변경",
          },
          connect: {
            btnConnect: "계정에 연결",
            contactBroker: "브로커 연락하기",
            forgotPassword: "비밀번호를 잊었나요?",
            loginPlaceholder: "로그인 입력",
            passwordPlaceholder: "비밀번호 입력",
            savePassword: "비밀번호 저장",
            title: "계정에 연결",
          },
          copyToClipboard: {
            copy: "클립보드에 복사",
            unsupported: "복사는 지원되지 않습니다",
          },
          demo: {
            accountOpeningWarning:
              "계좌를 개설함으로써 귀하는 계좌 개설 약관 및 {brokerName}의 데이터 보호 정책에 동의하는 것입니다.",
            btnOpenDemo: "데모 계좌 개설",
            title: "데모 계좌 개설",
            tradeWithRealMoney:
              "실제 돈으로 거래하려면 금융 서비스 회사와 별도의 계약을 체결해야 합니다.",
          },
          disclaimer: {
            btnAccept: "수락",
            headerTitle: "MetaTrader 5에 오신 것을 환영합니다",
            text: 'MetaQuotes Ltd는 소프트웨어 개발 회사로 금융, 투자, 중개, 거래 또는 데이터 피드 서비스를 제공하지 않으며 거래와 관련된 수수료 기반의 결제에 관여하지 않습니다.<br /><br /> ACCEPT 버튼을 누름과 동시에 저는 <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">EULA 이용약관</a>, <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">개인정보 보호정책</a> 및 고지 사항에 동의합니다.<br /><br /> 응용 프로그램에서 얻을 수 있는 어떠한 정보도 투자 조언을 위한 것이 아닙니다. 거래를 위해 이 응용 프로그램을 사용하기 전에 자격을 갖춘 등록된 증권 전문가의 조언을 구하고 스스로 실사를 수행해야 합니다.',
            title: "면책",
          },
          errors: {
            error: "에러",
            invalidCode: "유효하지 않은 코드",
            invalidEmail: "유효하지 않은 이메일",
            invalidPhone: "유효하지 않은 전화",
            unknownError: "알려지지 않은 에러",
          },
          form: {
            accountType: "계좌 타입",
            address: "주소",
            addressPlaceholder: "주소을 기입하세요",
            annualDeposit: "연간 입금액",
            annualIncome: "연간 수입",
            broker: "회사명 브로커명",
            btn: {
              back: "뒤로",
              cancel: "취소",
              next: "다음",
              openAccount: "계좌 개설",
              remove: "삭제",
              signOut: "로그 아웃",
            },
            city: "도시",
            cityPlaceholder: "도시를 입력하세요",
            country: "국가",
            dateBirth: "생년월일",
            deposit: "입금",
            education: "교육",
            email: {
              address: "이메일",
              code: "메일의 코드",
              placeholder: "이메일을 입력하세요",
              title: "이메일",
            },
            employement: "직업",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "여", male: "남", title: "성" },
            identity: "ID번호",
            imageOrPdfFile: "이미지 혹은 PDF 파일",
            investor: "관전자",
            language: "언어",
            leverage: "레버리지",
            login: "로그인",
            min5chars: "최소 5 문자",
            name: {
              middle: "중간 이름",
              surname: "성",
              title: "이름",
              yourName: "귀하의 이름",
            },
            nationality: "국가",
            netWorth: "순자산",
            optional: "선택적인",
            password: "비밀번호",
            passwordReadOnly: "읽기 전용 비밀번호",
            phone: {
              mobile: "모바일 폰",
              number: "전화 번호",
              sms: "문자로 받은 코드",
            },
            pleaseSelect: "선택하세요",
            policyCheckbox:
              "저는 계좌 개설을 위한 이용 약관 및 데이터 보호 정책에 동의합니다",
            server: "서버",
            side: { back: "뒷면", front: "앞면" },
            sourceWealth: "자금 원천",
            state: "상태",
            status: "상태",
            stocks: "주식",
            taxID: "납세자번호",
            type: "입력",
            useHedge: "거래 시 헤징 사용",
            verificationCodes: {
              email: "이메일로 인증 코드를 보냈습니다.",
              phone: "귀하의 전화로 인증 코드를 보냈습니다.",
              phoneEmail: "귀하의 전화와 이메일로 인증 코드를 보냈습니다.",
            },
            zipCode: "우편번호",
          },
          mainForm: {
            title: "거래 계정",
            titleWithName: "거래 계정: {brokerName}",
          },
          otp: {
            disable2FA: "2FA/TOTP 인증 비활성",
            disable2FAAccount: "어카운트 {login}을 위해 2FA/TOTP 인증을 비활성",
            disableEnterCode:
              "2FA/TOTP를 비활성화하려면 Authenticator 가 생성한 계정 코드를 입력하십시오.",
            downloadApp:
              "Google Authenticator / Microsoft Authenticator / Authy 앱을 모바일 장치에 다운로드하고 QR 코드를 스캔하세요:",
            enable2FA: "2FA/TOTP 인증 활성화",
            enable2FAAccount: "어카운트 {login}을 위해 2FA/TOTP 인증 활성화",
            enterCode:
              "Authenticator의  작동을 확인하려면 앱에서 생성한 계정 코드를 입력하세요.",
            oneTimePassword: "일회성 비밀번호",
            placeholder: "계정 OTP 입력",
            required: "추가 계정 보안을 위해 2FA 인증이 필요합니다.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "통장입출금내역서",
              utilityBill: "전기, 가스, 수도 요금",
            },
            conditionsForUploadingFiles: {
              documents: "어떤 종류의 문서는 사진 두개가 필요합니다: 앞과 뒤",
              proofAddress:
                "모바일 서비스와 관련한 요금 청구서는 거주지 증명으로 인정되지 않습니다.",
              utilityBill:
                "공과금 청구서는 귀하의 이름과 주소를 포함해야 하며 3개월 이내여야 합니다.",
            },
            documentType: {
              driverLicense: "운전면허증",
              idCard: "신분증",
              passport: "여권",
              residencePermit: "거주 허가증",
            },
            educationLevel: {
              bachelor: "학사 및 동급 교육",
              highScholl: "고등학교",
              master: "석사 및 동급 교육",
              none: "없음",
              other: "기타",
              phd: "박사 및 동급 교육",
            },
            employment: {
              employed: "취업자",
              other: "기타",
              retired: "퇴직자",
              selfEmployed: "사업 운영 또는 자영업자",
              student: "학생",
              unemployed: "미취업",
            },
            experience: "실제 거래 경험:",
            experienceLevel: {
              above3: "> 3 년 이상",
              form1to3: "1 - 3 년 사이",
              less1: "< 1 년 이상",
            },
            industry: {
              agriculture: "농업",
              communication: "예술, 오디오/영상 기술 및 커뮤니케이션",
              construction: "건축 및 건설",
              education: "교육",
              engineering: "공학 & 수학",
              government: "정부 및 공무",
              healthcare: "보건",
              it: "IT 분야",
              management: "비지니스 경영 및 행정",
              manufacturing: "제조업",
              marketing: "마케팅 & 영업",
              none: "없음",
              other: "기타",
              science: "과학 및 기술",
              security: "법, 치안, 보안",
              tourism: "서비스 및 관광업",
              transport: "운송 및 유통, 물류",
            },
            policy:
              "개인 정보는 거래 계좌 개설에 사용되며 제3자에게 전달되지 않습니다. 정보는 안전하고 기밀로 처리됩니다.",
            takePhoto:
              "귀하의 문서를 사진으로 찍어 편집하지 말고 여기에 업로드하세요.",
            title: "실제 계정 개설",
            wealthSource: {
              employment: "고용",
              inheritance: "상속 또는 선물",
              other: "기타",
              savings: "저축 또는  투자",
            },
          },
          saveAccountData: "로그인 및 비밀번호를 안전한 곳에 보관하십시오",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "청산",
            empty: "이 심볼과 관련한 볼륨이 없습니다",
            extendedBook: {
              hide: "확장된 시장 심도 숨기기",
              show: "확장된 시장 심도 보이기",
            },
            menu: {
              amount: "랏 대신 총액",
              extended: "확장",
              spread: "스프레드",
            },
            spread: { hide: "스프레드 숨기기", show: "스프레드 보이기" },
            stopLoss: "SL",
            takeProfit: "TP",
            title: "시장심도",
          },
          errors: {
            accepted: "수락됨",
            allowedOnlyLongPositions: "롱 포지션만 허용됩니다",
            allowedOnlyPositionsClosing: "포지션 청산만 허용됩니다",
            allowedOnlyShortPositions: "숏 포지션만 허용됩니다",
            automatedTradingDisabledClient:
              "클라이언트에서 자동거래가 안되도록 설정되어 있습니다",
            automatedTradingDisabledServer: "서버에서 자동거래를 거부합니다",
            canceled: "취소됨",
            common: "일반 에러",
            demoAllocationDisabled: "데모 계좌 할당이 비활성화 되었습니다",
            done: "완료",
            donePartially: "부분 완료",
            frequentRequests: "요청이 너무 많습니다",
            invalidExpiration: "잘못된 만료일",
            invalidOrderType: "잘못된 주문 타입",
            invalidParameters: "잘못된 속성",
            invalidPrices: "잘못된 가격",
            invalidSLTP: "잘못된 SL 또는 TP",
            invalidVolume: "잘못된 거래량",
            manyTradeRequests: "거래 요청이 너무 많습니다",
            marketClosed: "시장이 폐장되었습니다",
            modificationFailed:
              "주문이나 포지션이 시장가와 가까워서 수정이 실패하였습니다",
            networkProblem: "네트워크 문제",
            noConnection: "연결안됨",
            notEnoughMoney: "자금이 충분하지 않습니다",
            offQuotes: "Off Quotes 에러",
            ok: "확인",
            onTheWay: "진행되는 중",
            orderChanged: "주문이 이미 변경되었습니다",
            orderClosePositionExists: "이 포지션의 청산 주문이 이미 존재합니다",
            ordersLimitReached: "주문 수가 초과되었습니다",
            permissions: "권한이 없습니다",
            placed: "예약됨",
            positionCloseProhibitedByFIFO:
              "FIFO 규칙에 의해 금지된 포지션 청산",
            positionClosed: "포지션이 이미 청산되었습니다",
            positionsLimitReached: "포지션 한도 도달",
            priceChanged: "가격 변경",
            prices: "가격",
            processed: "처리됨",
            rejected: "거절됨",
            requestRejectedOrderWillCanceled: "요청이 거부됨. 주문 취소됨",
            requoted: "Requote 가 발생하였습니다",
            serverProblem: "서버 기술적인 문제",
            timeout: "시간초과",
            tradeDisabled: "거래가 불가능합니다",
            unsupportedFillingMode: "지원되지 않는 체결 모드",
            volumeLimitReached: "거래량이 초과되었습니다",
          },
          form: {
            acceptNewQuotes: "새 가격으로 접수하시겠습니까?",
            btnOpen: {
              hide: "거래 폼 숨기기",
              show: "거래 폼 보이기",
              title: "새 주문",
            },
            buttons: {
              accept: "수락",
              delete: "삭제",
              modify: "수정",
              ok: "확인",
              placeOrder: "주문하기",
              reject: "거절",
              request: "요청",
              requestPrice: "가격 요청",
            },
            close: "청산",
            execution: {
              fillOrKill: "전부체결 혹은 취소",
              immediateOrCancel: "가능 거래량 진입 후 잔량 취소",
              bookOrCancel: "Book or Cancel",
              label: "체결 방법",
              return: "돌아가기",
            },
            executionMode: {
              exchange: "거래소 체결",
              instant: "즉시 체결",
              market: "시장 체결",
              request: "체결 요청",
            },
            expiration: {
              date: "만기 날짜",
              label: "만료",
              types: {
                specified: "지정됨",
                specifiedDay: "지정된 날짜",
                today: "오늘",
              },
            },
            fields: {
              closeBy: "확인",
              comment: "비고",
              price: "가격",
              stopLoss: "SL",
              takeProfit: "TP",
              volume: "거래량",
              errors: {
                volume: {
                  min: "최소 볼륨은 {min} 입니다",
                  max: "최대 볼륨은 {max} 입니다",
                  required: "Volume is required",
                  step: "볼륨은 {step} 단계로 설정할 수 있습니다",
                },
              },
            },
          },
          history: {
            btnOpen: "거래내역",
            deals: {
              columns: {
                comment: "비고",
                commission: "수수료",
                direction: "방향",
                fee: "수수료",
                order: "주문",
                price: "가격",
                profit: "수익",
                swap: "스왑",
                symbol: "통화",
                ticket: "티켓",
                time: "시간",
                type: "입력",
                volume: "거래량",
              },
            },
            empty: "귀하는 아직 거래 히스토리가 없습니다.",
            menu: {
              columns: {
                horizontalScroll: "수평 스크롤",
                resetAll: "모두 재설정",
                title: "열",
              },
              deals: "거래",
              orders: "주문",
              period: {
                all: "모든 거래내역",
                last3Months: "최근 3개월",
                last6months: "최근 6개월",
                lastMonth: "최근 1개월",
                title: "주기",
                customPeriod: "기간 지정",
                lastYear: "최근 1년",
                lastWeek: "1주일간",
                today: "오늘",
              },
              positions: "포지션",
              chart: "차트",
              newOrder: "새 주문",
            },
            orders: {
              columns: {
                comment: "비고",
                price: "가격",
                slDescription: "SL",
                state: "상태",
                symbol: "통화",
                ticket: "티켓",
                timeDone: "시간",
                timeSetup: "시간",
                tpDescription: "TP",
                type: "입력",
                volume: "거래량",
                timeSetupDescription: "진입 시간",
                timeDoneDescription: "청산 시간",
              },
              total: {
                title: "전체",
                filled: "체결됨",
                canceled: "취소됨",
                rejected: "거절됨",
              },
            },
            positions: {
              columns: {
                commission: "수수료",
                fee: "수수료",
                priceClose: "가격",
                priceCloseDescription: "종가",
                priceOpen: "가격",
                priceOpenDescription: "시가",
                profit: "수익",
                slDescription: "SL",
                swap: "스왑",
                symbol: "통화",
                ticket: "티켓",
                timeClose: "시간",
                timeCloseDescription: "청산 시간",
                timeOpen: "시간",
                timeOpenDescription: "진입 시간",
                tpDescription: "TP",
                type: "입력",
                volume: "거래량",
                comment: "비고",
              },
            },
            columns: { default: "디폴트로" },
            total: {
              profit: "수익",
              credit: "크래딧",
              deposit: "예치",
              withdrawal: "취소",
              balance: "잔액",
              commission: "커미션",
              fee: "수수료",
              swap: "스왑",
              grossProfit: "누적 수익",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "거래 내역",
                orders: "거래 주문",
                position: "포지션",
                sltp: "손절/익절 레벨",
              },
              notification: "거래 알림",
            },
            oneClick: "원클릭 거래",
            tags: { demo: "데모계좌", readonly: "일기 전용" },
            oneClickBottom: "원클릭 패널을 아래에 놓기",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "저는 이 조건과 조항들에 동의합니다",
            btnAccept: "수락",
            btnCancel: "취소",
            text: '귀하는 지금 원클릭 거래 모드를 활성화하려고 합니다. 아래의 "본 이용약관에 동의합니다"를 클릭하면 다음 이용약관을 읽고 이해했으며 이에 구속된다는 데 동의하는 것입니다.<br /><br />귀하는 웹 단말기의 메뉴에서 거래 모드를 클릭하여 원 클릭 거래 모드를 활성화하거나 비활성화할 수 있습니다. <br />           <br />주문 제출을 위한 원 클릭 거래 모드는 원스텝 프로세스입니다. 다음과 같은 경우 주문이 제출됩니다. 귀하가: &mdash; 차트의 원 클릭 거래 패널에서 bid(SELL) 또는 ask(BUY) 가격 버튼을 탭하는 경우 &mdash;    시장 ​​심도 창에서 매도, 청산, 매수, 주문 접수 버튼을 탭하는 경우 &mdash; 거래 탭에서 청산 주문 삭제하는 경우 <br /><br />이어서 클릭해야 하는 확인 메시지가 표시되지 않습니다. 클릭하면 주문을 철회하거나 변경할 수 없습니다. 정상적인 시장 조건 및 시스템 성능 하에서 시장 주문은 제출 후 즉시 체결되며 귀하는 구속력 있는 거래에 들어가게 됩니다.<br /><br />귀하는 원 클릭 거래 모드의 사용과 관련된 모든 위험을 수락하는 데 동의합니다. 이는 주문 제출 시 오류, 누락 또는 실수의 위험을 포함하되 이에 국한되지 않습니다.<br /><br />귀하는 귀하 또는 귀하를 대신하여 거래하는 다른 사람의 오류, 누락 또는 실수로 인해 발생할 수 있는 모든 손실, 비용 및 지출에 대해 {companyName}가 완전히 면책되고 배상받도록 하는데 동의합니다.',
            title: "원 클릭 거래 - 면책",
          },
          quickTrade: {
            hide: "원 클릭 거래 패널 숨기기",
            show: "원 클릭 거래 보이기",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "저는 상기 문서에 대해 잘 알고있으며, 고위험 투자상품에 거래할 것을 원합니다",
            btnAccept: "수락",
            btnCancel: "취소",
            text: "이 거래 플랫폼을 추가로 사용하면 귀하가 선택한 금융 기관에서 제공하는 레버리지 고위험 투자 상품에 액세스할 수 있음을 알려드립니다. 이러한 상품에 대한 투자는 예치금의 일부 또는 전부를 잃을 위험이 있기 때문에 투자자 모두에게 적합하지 않을 수 있습니다.<br /><br />고위험 투자 상품 거래를 결정하기 전에 투자 목적을 신중하게 고려해야 합니다. 경험의 수준 및 허용 가능한 위험. 초기 투자보다 더 큰 손실을 입을 가능성이 있으므로 손실을 감당할 수 없는 돈을 투자해서는 안 됩니다.<br /><br />이러한 상품에 대한 투자와 관련된 모든 위험 요소에 대한 지식을 넓히고 의문이 있는 경우 전문 재무 자문인에게 조언을 구하십시오.",
            title: "고위험 투자 경고",
          },
          table: {
            btnOpen: "거래",
            columns: {
              comment: "비고",
              priceClose: "가격",
              priceCloseDescription: "청산 가격",
              priceOpen: "가격",
              priceOpenDescription: "시가",
              profit: "수익",
              slDescription: "SL",
              swap: "스왑",
              symbol: "통화",
              ticket: "티켓",
              time: "시간",
              tpDescription: "TP",
              type: "타입",
              volume: "거래량",
            },
            emptyPlug: {
              btnNewOrder: "새로운 주문 생성",
              title: "보유중인 포지션이 없습니다",
            },
            menu: {
              chart: "차트",
              closePosition: "포지션 청산",
              columns: "열",
              modifyOrder: "주문 수정",
              modifyPosition: "포지션 수정",
              newOrder: "새 주문",
              resetAll: "모두 재설정",
              deleteOrder: "주문 삭제",
            },
            oneClick: { deleteOrder: "삭제" },
            sections: {
              collateralPositions: "담보 포지션",
              orders: "주문",
              positions: "포지션",
            },
            total: {
              assets: "자산",
              balance: "잔고",
              collateral: "담보",
              commission: "수수료",
              credit: "신용",
              equity: "총평가금액",
              liabilities: "부채",
              margin: "마진",
              marginFree: "사용가능 마진",
              marginLevel: "가격선",
            },
          },
          timer: {
            marketWillOpen: "시장은 {days} {leftTime}에 열릴 예정입니다",
            moreThenOneDay: "{numberOfDays} 날",
            oneDay: "{numberOfDays} 날",
          },
          tradeIsDisabled: {
            account: "이 계좌에서의 거래가 서버에서 비활성 되었습니다",
            collateral: "거래를 할 수 없습니다, 이 심볼이 담보이기 때문입니다",
            disabled: "거래가 불가능합니다",
            investor: "투자자 비밀번호로 연결되어 있어 거래가 불가능합니다.",
            readOnly:
              "귀하가 위험 경고를 수락하지 않았기 때문에 거래가 불가능합니다.",
            symbol: "이 심볼의 거래가 불가합니다.",
          },
          hotkeys: {
            historyPanel: "히스토리 패널",
            journalPanel: "저널",
            marketWatch: "시장 심도",
            quickTrade: "원클릭 거래",
            tradeForm: "새 주문",
            tradePanel: "거래 패널",
          },
          marketOpen: {
            time: "마켓이 폐장 했습니다 - {time}에 개장할 것입니다",
            afterSeconds: "폐장했습니다 - {time}초 안에 개장할 것입니다",
          },
          expiredTimer: { seconds: "{time}초 내에 만료됩니다" },
          corporateLink: {
            type: {
              clientAgreement: "고객 동의",
              riskDisclosure: "리스크 공시",
              fdmDisclaimer: "FDM 면책조항",
              clientAgreementAndRiskDisclosure: "고객 동의 및 리스크 공시",
              complaintsHandlingProcedure: "불만 처리 절차",
              orderExecutionPolicy: "주문 체결 정책",
              clientCategorisationNotice: "고객 분류 안내",
              conflictsOfInterestPolicy: "이해 상충 정책",
              dataProtectionPolicy: "데이터 보호 정책",
            },
          },
          margin: {
            floating: "유동",
            mode: { marketBuy: "시장가 매수", marketSell: "시장가 매도" },
            rangeMode: {
              value: "명목가치",
              valuePerSymbol: "심볼별 명목 가치",
              volume: "볼륨",
              volumePerSymbol: "심볼별 볼륨",
            },
            showValue: "로 금액 보기 {currency} 랏 별",
            rates: "마진:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: { disable: "전체화면 취소", enable: "전체화면" },
          journal: {
            btnOpen: "저널",
            columns: { message: "메시지", source: "소스코드", time: "시간" },
            menu: {
              clear: "비우기",
              debugMode: "디버그 모드",
              exportFile: "파일로 내보내기",
            },
          },
          menu: {
            about: "프로그램 소개",
            contact: "문의하기",
            brokerInformation: "회사 정보",
            chartSettings: {
              controls: "차트 컨트롤",
              grid: "그리드",
              ohlc: "시/고/저/종 보이기",
              title: "차트 세팅",
              askPrice: "호가 가격",
              crosshair: "십자선 커서",
            },
            connect: "계정에 연결",
            language: {
              title: "언어",
              search: "검색",
              nothingFound: "없는 언어입니다",
            },
            openDemo: "데모 계정 개설",
            openReal: "실 계정 개설",
            settings: "세팅",
            shortcuts: "단축키",
            theme: {
              blackWhite: "블랙 & 화이트",
              blueRed: "블루 & 레드",
              dark: "어두운 테마",
              editor: "테마 에디터",
              greenRed: "그린 & 레드",
              light: "밝은 테마",
              neutral: "중간",
              templates: "컬러 템플릿",
            },
            title: "메뉴",
            tradingAccount: "거래 계정",
            terms: "이용약관",
            desktopPlatforms: "데스크탑 플래폼",
            qrCode: {
              install: "{store}로부터 설치하려면 스캔하세요",
              downloadApk: "스캔 해서 안드로이드 APK 파일을 받으세요",
            },
            economicCalendar: "경제 달력",
          },
          screen: { back: "뒤로" },
          mobile: { bottomNav: { quotes: "코트" } },
          hotkeys: {
            sections: { navigation: "탐색", view: "보기" },
            escape: "취소",
            indicators: "지표",
            depthOfMarket: "시장심도",
            objectTreePanel: "객체 트리",
            scrollRight: "다음 캔들",
            scrollToStart: "차트를 시작점까지 스크롤",
            scrollLeft: "이전 캔들",
            scrollToEnd: "차트를 끝까지 스크롤",
            resetChartView: "차트 재설정",
            zoomIn: "확대",
            zoomOut: "축소",
            fullScreen: "풀스크린",
            screenshot: "차트를 이미지로 저장",
            title: "단축키",
          },
          timezone: {
            title: "시간대",
            city: {
              cairo: "카이로",
              casablanca: "카사블랑카",
              johannesburg: "요하네스버그",
              lagos: "라고스",
              nairobi: "나이로비",
              tunis: "튀니스",
              anchorage: "앵커리지",
              bogota: "보고타",
              buenosAires: "부에노스아이레스",
              caracas: "카라카스",
              chicago: "시카고",
              denver: "덴버",
              elSalvador: "엘살바도르",
              juneau: "Juneau",
              lima: "리마",
              losAngeles: "로스앤젤레스",
              mexicoCity: "멕시코 시티",
              newYork: "뉴욕",
              phoenix: "Phoenix",
              santiago: "산티아고",
              saoPaulo: "상파울루",
              toronto: "토론토",
              vancouver: "밴쿠버",
              almaty: "알마티",
              ashgabat: "Ashgabat",
              bahrain: "바레인",
              bangkok: "방콕",
              kolkata: "콜카타",
              colombo: "콜롬보",
              dhaka: "다카",
              dubai: "두바이",
              hongKong: "홍콩",
              jakarta: "자카르타",
              jerusalem: "예루살렘",
              karachi: "카라치",
              kathmandu: "카트만두",
              kuwait: "쿠웨이트",
              manila: "마닐라",
              muscat: "무스카트",
              nicosia: "니코시아",
              qatar: "카타르",
              rangoon: "랑군",
              riyadh: "리야드",
              saigon: "사이공",
              seoul: "서울",
              shanghai: "상하이",
              singapore: "싱가포르",
              taipei: "타이베이",
              tehran: "테헤란",
              tokyo: "도쿄",
              reykjavik: "레이캬비크",
              adelaide: "애들레이드",
              brisbane: "브리즈번",
              perth: "퍼스",
              sydney: "시드니",
              amsterdam: "암스테르담",
              athens: "아테네",
              belgrade: "베오그라드",
              berlin: "베를린",
              bratislava: "브라티슬라바",
              brussels: "브뤼셀",
              bucharest: "부쿠레슈티",
              budapest: "부다페스트",
              copenhagen: "코펜하겐",
              dublin: "더블린",
              helsinki: "헬싱키",
              istanbul: "이스탄불",
              lisbon: "리스본",
              london: "런던",
              luxembourg: "룩셈부르크",
              madrid: "마드리드",
              malta: "Malta",
              moscow: "모스크바",
              oslo: "오슬로",
              paris: "파리",
              prague: "프라하",
              riga: "리가",
              rome: "로마",
              stockholm: "스톡홀름",
              tallinn: "탈린",
              vienna: "비엔나",
              vilnius: "빌뉴스",
              warsaw: "바르샤바",
              zurich: "취리히",
              auckland: "오클랜드",
              chatham: "채텀",
              fakaofo: "파카오포",
              honolulu: "호놀룰루",
              norfolk: "노퍽",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e as k };
