const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Uvećaj",
            zoomOut: "Umanji",
          },
          crosshair: "Ciljnik",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Dodaj indikator",
            btnOpenPopup: "Add Indicator",
            close: "Zatvori",
            form: {
              applyTo: "Primijeni na",
              background: {
                title: "Pozadina",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Odstupanje",
              enterDistance: "Period",
              enterShift: "Pomak",
              fastEma: "Brzi EMA",
              slowEma: "Spori EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Maksimum",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Jednostavno",
                smoothed: "Smoothed",
                title: "Metoda",
              },
              opacity: "Opacity",
              period: {
                jaws: "Jaws period",
                lips: "Lips period",
                teeth: "Teeth period",
                title: "Period",
                dPercent: "%D period",
                kPercent: "%K period",
              },
              selectApplyTo: "Odaberi",
              selectVolumesType: "Select volume type",
              shift: "Pomak",
              showTimeframes: "Pokaži na svim periodima",
              slowing: "Usporavanje",
              step: "Razmak",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Stil",
                up: "Up style",
                rvi: "RVI stil",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Volumen",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Cijena",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Pretraživanje",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Sve",
              billWilliams: "Bill Williams",
              oscillators: "Oscilatori",
              trend: "Trend",
              volumes: "Volumen",
            },
            title: "Select indicator",
            up: "Gore",
            down: "Dolje",
            chartControls: {
              show: "Prikaži",
              hide: "Sakrij",
              settings: "Postavke",
              remove: "Ukloni",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Cijena na zatvaranju",
              dailyChange: "Dnevna promjena",
              openPrice: "Cijena kod otvaranja",
              spread: "Raspon",
              symbol: "Simboli",
              time: "Vrijeme",
              high: "Najviša",
              low: "Najniža",
              last: "Posljednje",
              lastHigh: "Posljednje - najviše",
              lastLow: "Posljednje - najniže",
              highLow: "Vrh/Dno",
              bidLow: "Bid - najniži",
              bidHigh: "Bid - najviši",
              askHigh: "Ask - najviši",
              askLow: "Ask - najniži",
              bid: "Ponuda",
              ask: "Potraznja",
              title: "Stupci",
            },
            menu: {
              chart: "Graf",
              columns: "Stupci",
              dom: "Dubina tržišta",
              hide: "Sakrij",
              newOrder: "Novi nalog",
              specification: "Specifikacija",
            },
            search: "Pretraživanje",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Strelice",
              showAlways: "Show always",
              angle: "Kut",
              distance: "Distance",
              bar: "Stupac",
              price: "Cijena",
              prices: "Cijene",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Pokaži na svim periodima",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Vaš tekst",
              props: "Svojstva",
              style: "Stil",
              rays: "Rays",
              background: "Pozadina",
              extends: "Extension",
              extended: "Prošireno",
              pipsPerBar: "Pipsa po stupcu",
              gannAngle: "Gann kut",
              deviations: "Devijacije",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Ažuriraj", cancel: "Otkaži" },
              tabs: {
                style: "Stil",
                coordinates: "Coordinates",
                visualization: "Vizualizacija",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Lijevo",
                right: "Desno",
                center: "Sredina",
                top: "Vrh",
                middle: "Middle",
                bottom: "Gumb",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Ekvidistantni kanal",
            regressionChannel: "Kanal Regresije",
            stdDevChannel: "Kanal Sa Standardnim Devijacijama",
            fibonacciRetracement: "Fibonaccijev retracement",
            gannFan: "Gann Lepeza",
            gannGrid: "Gann Mreza",
            gannLine: "Gann Linija",
            arrowLine: "Linija sa strelicom",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Zraka",
            trendAngle: "Trend po kutu",
            trendline: "Linija trenda",
            verticalLine: "Vertikalna linija",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Pravokutnik",
            circle: "Circle",
            triangle: "Trokut",
            ellipse: "Elipsa",
            text: "Tekst",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "Dnevno",
              H1: "1 sat",
              H4: "4 sata",
              M1: "1 minuta",
              M15: "15 minuta",
              M30: "30 minuta",
              M5: "5 minuta",
              MN: "Mjesečno",
              Unknown: "Unknown",
              W1: "Tjedno",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "GTC način",
            calculation: "Izračun",
            chartMode: "Način rada grafikona",
            contractSize: "Veličina ugovora",
            days: {
              friday: "Petak",
              monday: "Ponedjeljak",
              saturday: "Subota",
              sunday: "Nedjelja",
              thursday: "Četvrtak",
              tuesday: "Utorak",
              wednesday: "Srijeda",
            },
            digits: "Znamenke",
            empty: "No symbol selected",
            execution: "Izvršenje",
            expiration: "Istek",
            filling: "Ispunjenje",
            initial: "Početna vrijednost",
            maintenance: "Održavanje",
            marginCurrency: "Valuta margine",
            marginRate: "Tečaj margine",
            maxVolume: "Najveći iznos",
            minVolume: "Najmanji iznos",
            orders: "Nalozi",
            profitCurrency: "Valuta dobiti",
            schedule: { quotes: "Kotacije", trade: "Trgovanje" },
            sector: "Sektor",
            spread: "Raspon",
            stopsLevel: "Razine stopova",
            swapLong: "Swap dugog",
            swapShort: "Swap kratkog",
            swapType: "Vrsta swapa",
            title: "{symbol} contract specification",
            tradeMode: "Trgovanje",
            volumeStep: "Korak iznosa",
            volumeLimit: "Ograničenje obujma",
            tickSize: "Veličina tika",
            tickValue: "Vrijednost tika",
            marginInitial: "Početna margina",
            marginHedged: "Zaštićena margina",
            commission: {
              daily: {
                volume: "Dnevna količina u lotovima",
                turnoverVolume: "Dnevni promet u lotovima",
                turnoverMoney: "Dnevni promet u novcu",
                value: "Dnevna vrijednost ponuda",
                profit: "Dnevni profit",
              },
              monthly: {
                volume: "Mjesečna količina u lotovima",
                turnoverVolume: "Mjesečni promet u lotovima",
                turnoverMoney: "Mjesečni promet u novcu",
                value: "Mjesečna vrijednost ponuda",
                profit: "Mjesečni profit",
              },
              instant: {
                volume: "Instant prema količini ponude",
                value: "Instant prema vrijednosti ponude",
                profit: "Instant prema profitu ponude",
              },
              entry: {
                in: "ulazni poslovi",
                out: "izlazni poslovi",
                all: "ulazno/izlazni poslovi",
              },
              tier: {
                mode: {
                  pips: "bodova",
                  percent: "% u {currency}",
                  percentProfit: "% profita {currency}",
                },
                type: { perDeal: "po poslu", perLot: "po lotu" },
              },
              header: "Provizije",
            },
          },
          tree: {
            close: "Zatvori",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Ukloni",
            settings: "Postavke",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Stupci",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Iznosi iz tickova",
            volumes: "Volumen",
            withoutVolumes: "Without Volumes",
            realVolumes: "Stvarni iznosi",
          },
          zoom: { in: "Uvećaj", out: "Umanji" },
          hotkeys: {
            arrowLine: "Linija sa strelicom",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Linijski grafikon",
            chartTypeBar: "Stupčasti grafikon",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Zraka",
            realVolumes: "Real Volumes",
            tickVolumes: "Iznosi iz tickova",
            trendline: "Linija trenda",
            verticalLine: "Vertikalna linija",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Velicina",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Novi račun je otvoren",
          },
          brokerInformation: {
            company: "Kompanija",
            email: "Elektronička pošta",
            phone: "Telefon",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Promijeni lozinku",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Promijeni lozinku",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Spremi lozinku",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Prihvati",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "Odbacivanje odgovornosti",
          },
          errors: {
            error: "Greška",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Vrsta računa",
            address: "Adresa",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Godišnji depozit",
            annualIncome: "Godišnji prihodi",
            broker: "Kompanija",
            btn: {
              back: "Nazad",
              cancel: "Otkaži",
              next: "Sljed.",
              openAccount: "Open Account",
              remove: "Ukloni",
              signOut: "Sign out",
            },
            city: "Grad",
            cityPlaceholder: "Enter your city",
            country: "Država",
            dateBirth: "Datum rođenja",
            deposit: "Depozit",
            education: "Education",
            email: {
              address: "Elektronička pošta",
              code: "Code from email",
              placeholder: "Enter email",
              title: "Elektronička pošta",
            },
            employement: "Employement",
            forex: "Forex",
            futures: "Budućnosnice",
            gender: { female: "Žensko", male: "Muško", title: "Spol" },
            identity: "Identifikacija",
            imageOrPdfFile: "Image or PDF file",
            investor: "Investitor",
            language: "Jezik",
            leverage: "Poluga",
            login: "Prijava",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Naziv",
              yourName: "Your Name",
            },
            nationality: "Državljanstvo",
            netWorth: "Vrijednost neto imovine",
            optional: "Optional",
            password: "Lozinka",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Pristajem na uvjete i odredbe za otvaranje računa i pravila zaštite osobnih podataka",
            server: "Poslužitelj",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Izvor imovine",
            state: "Država",
            status: "Status",
            stocks: "Dionice",
            taxID: "Porezni ID",
            type: "Vrsta",
            useHedge: "Koristite hedging u trgovanju",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "Onemogući 2FA/TOTP",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "Omogući 2FA/TOTP",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Za provjeru rada aplikacije Authenticator, unesite kôd vašeg računa koji je generirala aplikacija.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "2FA provjera autentičnosti obvezna je za dodatnu sigurnost računa.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Izvod banke",
              utilityBill: "Račun za komunalne usluge",
            },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Vozačka dozvola",
              idCard: "Osobna iskaznica",
              passport: "Putovnica",
              residencePermit: "Dozvola boravka",
            },
            educationLevel: {
              bachelor: "Prvostupnik ili ekvivalentna",
              highScholl: "Srednja škola",
              master: "Magistar ili jednakovrijedno",
              none: "Bez pomicnog Stop Loss naloga",
              other: "Drugo",
              phd: "Dr.Sc. ili ekvivalent",
            },
            employment: {
              employed: "Zaposleni",
              other: "Drugo",
              retired: "Umirovljenik",
              selfEmployed: "Vlasnik poduzeća ili samozaposlen",
              student: "Student",
              unemployed: "Nezaposleni",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "> 3 godine",
              form1to3: "1 do 3 godine",
              less1: "< 1 godine",
            },
            industry: {
              agriculture: "Poljoprivreda hrana i prirodni resursi",
              communication: "Umjetnost, audio/video produkcija i komunikacije",
              construction: "Arhitektura i građevinarstvo",
              education: "Edukacija i obuka",
              engineering: "Tehničke znanosti i matematika",
              government: "Javna uprava i državna tijela",
              healthcare: "Zdravstvena skrb",
              it: "Informacijska tehnologija",
              management: "Poslovno upravljanje i administracija",
              manufacturing: "Proizvodnja",
              marketing: "Marketing i prodaja",
              none: "Bez pomicnog Stop Loss naloga",
              other: "Drugo",
              science: "Znanost i tehnologija",
              security: "Zakonske, javna sigurnost, ispravke i sigurnost",
              tourism: "Ugostiteljstvo i turizam",
              transport: "Prijevoz, distribucija i logistika",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Od zapošljavanja ili prihodi od poduzeća",
              inheritance: "Darovi ili nasljedstvo",
              other: "Drugo",
              savings: "Štednja ili ulaganja",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Zatvori",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Iznosi umjesto lotova",
              extended: "Prošireno",
              spread: "Raspon",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Stop loss",
            takeProfit: "Take profit",
            title: "Dubina tržišta",
          },
          errors: {
            accepted: "Prihvaćeno",
            allowedOnlyLongPositions: "Dopuštene samo duge pozicije",
            allowedOnlyPositionsClosing:
              "Dopušteno je samo zatvaranje pozicije",
            allowedOnlyShortPositions: "Dopuštene su samo kratke pozicije",
            automatedTradingDisabledClient:
              "Automatsko trgovanje je onemogućeno s na klijentskom terminalu",
            automatedTradingDisabledServer:
              "Automatsko trgovanje je onemogućeno s poslužiteljske strane",
            canceled: "Otkazano",
            common: "Uobičajena greška",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Završeno",
            donePartially: "Djelomično izvršeno",
            frequentRequests: "Previše učestali zahtjevi",
            invalidExpiration: "Nevažeći istek",
            invalidOrderType: "Nevažeća vrsta naloga",
            invalidParameters: "Nepravilni parametri",
            invalidPrices: "Nevažeće cijene",
            invalidSLTP: "Nevažeći S/L ili T/P",
            invalidVolume: "Nevažeći iznos",
            manyTradeRequests: "Previše zahtijeva za trgovanje",
            marketClosed: "Tržište je zatvoreno",
            modificationFailed:
              "Izmjena je bila neuspješna jer su nalog ili pozicija bili preblizu tržišnim vrijednostima",
            networkProblem: "Greška mreže",
            noConnection: "Nema veze",
            notEnoughMoney: "Nedovoljno novaca",
            offQuotes: "Netržišna cijena",
            ok: "U redu",
            onTheWay: "U prometu je",
            orderChanged: "Nalog je već bio izmijenjen",
            orderClosePositionExists:
              "Već postoji nalog za zatvaranje ove pozicije",
            ordersLimitReached: "Dosegnuto je ograničenje broja naloga",
            permissions: "Nedovoljne ovlasti",
            placed: "Zadano",
            positionCloseProhibitedByFIFO:
              "Zatvaranje pozicije zabranjeno je zbog FIFO pravila",
            positionClosed: "Pozicija je već zatvorena",
            positionsLimitReached: "Dosegnuto je ograničenje broja pozicija",
            priceChanged: "Cijena je promijenjena",
            prices: "Cijene",
            processed: "Obrađeno",
            rejected: "Odbijeno",
            requestRejectedOrderWillCanceled:
              "Zahtjev je odbijen, nalog je otkazan",
            requoted: "Ponovno kotirano",
            serverProblem: "Tehnička poteškoća poslužitelja",
            timeout: "Vrijeme isteklo",
            tradeDisabled: "Trgovanje je onemogućeno",
            unsupportedFillingMode: "Nepodržan način ispunjavanja",
            volumeLimitReached: "Dosegnuto je ograničenje iznosa",
          },
          form: {
            acceptNewQuotes: "Prihvaćate li novu kotaciju?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Novi nalog",
            },
            buttons: {
              accept: "Prihvati",
              delete: "Obriši",
              modify: "Izmijeni",
              ok: "U redu",
              placeOrder: "Place order",
              reject: "Odbiti",
              request: "Po zahtjevu",
              requestPrice: "Request Price",
            },
            close: "Zatvori",
            execution: {
              fillOrKill: "Ispuni ili ukini (kill or fill)",
              immediateOrCancel: "Odmah ili otkaz",
              bookOrCancel: "Rezerviraj ili otkaži",
              label: "Politika ispunjavanja",
              return: "Nazad",
            },
            executionMode: {
              exchange: "Izvršenje na burzi",
              instant: "Trenutno izvršenje",
              market: "Tržišno izvršenje",
              request: "Zatraži izvršenje",
            },
            expiration: {
              date: "Expiration Date",
              label: "Istek",
              types: {
                specified: "Određeni",
                specifiedDay: "Specified Day",
                today: "Danas",
              },
            },
            fields: {
              closeBy: "Zatvori suprotne pozicije",
              comment: "Komentar",
              price: "Cijena",
              stopLoss: "Stop loss",
              takeProfit: "Take profit",
              volume: "Velicina",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Povijest",
            deals: {
              columns: {
                comment: "Komentar",
                commission: "Provizija",
                direction: "Smjer",
                fee: "Pristojba",
                order: "Nalog",
                price: "Cijena",
                profit: "Dobit",
                swap: "Swap",
                symbol: "Simboli",
                ticket: "Ticket",
                time: "Vrijeme",
                type: "Vrsta",
                volume: "Velicina",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Stupci",
              },
              deals: "Dealovi",
              orders: "Nalozi",
              period: {
                all: "Cijela povijest",
                last3Months: "Posljednja 3 mjeseca",
                last6months: "Posljednja 6 mjeseci",
                lastMonth: "Posljednji mjesec",
                title: "Period",
                customPeriod: "Prilagođeno razdoblje",
                lastYear: "Posljednja godina",
                lastWeek: "Posljednji tjedan",
                today: "Danas",
              },
              positions: "Pozicija",
              chart: "Graf",
              newOrder: "Novi nalog",
            },
            orders: {
              columns: {
                comment: "Komentar",
                price: "Cijena",
                slDescription: "Stop loss",
                state: "Država",
                symbol: "Simboli",
                ticket: "Ticket",
                timeDone: "Vrijeme",
                timeSetup: "Vrijeme",
                tpDescription: "Take profit",
                type: "Vrsta",
                volume: "Velicina",
                timeSetupDescription: "Otvori vrijeme",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Ukupno",
                filled: "Ispunjeno",
                canceled: "Otkazano",
                rejected: "Odbijeno",
              },
            },
            positions: {
              columns: {
                commission: "Provizija",
                fee: "Pristojba",
                priceClose: "Cijena",
                priceCloseDescription: "Zaključna cijena",
                priceOpen: "Cijena",
                priceOpenDescription: "Početna cijena",
                profit: "Dobit",
                slDescription: "Stop loss",
                swap: "Swap",
                symbol: "Simboli",
                ticket: "Ticket",
                timeClose: "Vrijeme",
                timeCloseDescription: "Close Time",
                timeOpen: "Vrijeme",
                timeOpenDescription: "Otvori vrijeme",
                tpDescription: "Take profit",
                type: "Vrsta",
                volume: "Velicina",
                comment: "Komentar",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Zarada",
              credit: "Kredit",
              deposit: "Depozit",
              withdrawal: "Isplata",
              balance: "Saldo",
              commission: "Provizija",
              fee: "Pristojba",
              swap: "Prekonocna kamata",
              grossProfit: "Bruto profit",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Povijest trgovanja",
                orders: "Trade Orders",
                position: "Trade Positions",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Trgovanje jednim klikom",
            tags: { demo: "Demo", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Prihvaćam ove Uvjete i odredbe",
            btnAccept: "Prihvati",
            btnCancel: "Otkaži",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Razumijem navedeno i želim trgovati visokorizičnim ulagačkim instrumentima",
            btnAccept: "Prihvati",
            btnCancel: "Otkaži",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Upozorenje na visoko rizičnu investiciju",
          },
          table: {
            btnOpen: "Trgovanje",
            columns: {
              comment: "Komentar",
              priceClose: "Cijena",
              priceCloseDescription: "Cijena na zatvaranju",
              priceOpen: "Cijena",
              priceOpenDescription: "Cijena kod otvaranja",
              profit: "Dobit",
              slDescription: "Stop loss",
              swap: "Swap",
              symbol: "Simboli",
              ticket: "Ticket",
              time: "Vrijeme",
              tpDescription: "Take profit",
              type: "Vrsta",
              volume: "Velicina",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Graf",
              closePosition: "Zatvori poziciju",
              columns: "Stupci",
              modifyOrder: "Izmijeni nalog",
              modifyPosition: "Izmijeni poziciju",
              newOrder: "Novi nalog",
              resetAll: "Reset all",
              deleteOrder: "Obriši nalog",
            },
            oneClick: { deleteOrder: "Obriši" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Nalozi",
              positions: "Pozicija",
            },
            total: {
              assets: "Imovina",
              balance: "Saldo",
              collateral: "Kolateral",
              commission: "Provizija",
              credit: "Kredit",
              equity: "Neto vrijednost",
              liabilities: "Obveze",
              margin: "Margina",
              marginFree: "Neiskorištena margina",
              marginLevel: "Razina",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Žurnal",
            marketWatch: "Praćenje tržišta",
            quickTrade: "Trgovanje jednim klikom",
            tradeForm: "Novi nalog",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Ugovor o korištenju",
              riskDisclosure: "Upozorenje o rizicima",
              fdmDisclaimer: "FDM odricanje od odgovornosti",
              clientAgreementAndRiskDisclosure:
                "Ugovor o korištenju i upozorenje o rizicima",
              complaintsHandlingProcedure: "Postupak rješavanja pritužbi",
              orderExecutionPolicy: "Pravila izvršavanja naloga",
              clientCategorisationNotice:
                "Obavijest o kategorizaciji klijenata",
              conflictsOfInterestPolicy:
                "Pravila za sprječavanje sukoba interesa",
              dataProtectionPolicy: "Pravila o zaštiti podataka",
            },
          },
          margin: {
            floating: "plivajuće",
            mode: {
              marketBuy: "Tržišna kupnja",
              marketSell: "Tržišna prodaja",
            },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Onemogući prikaz na cijelom zaslonu",
            enable: "Omogući prikaz na cijelom zaslonu",
          },
          journal: {
            btnOpen: "Žurnal",
            columns: { message: "Poruka", source: "Izvor", time: "Vrijeme" },
            menu: {
              clear: "Očisti",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Rešetka",
              ohlc: "Prikaži OHLC",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Jezik",
              search: "Pretraživanje",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Postavke",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Odredbe i uvjeti",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Ekonomski kalendar",
          },
          screen: { back: "Nazad" },
          mobile: { bottomNav: { quotes: "Kotacije" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Pogled" },
            escape: "Otkaži",
            indicators: "Indikatori",
            depthOfMarket: "Dubina tržišta",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Uvećaj",
            zoomOut: "Umanji",
            fullScreen: "Cijeli ekran",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { a, o as b, i as c, e as h };
