const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Ukryj Wydarzenia Kalendarza Ekonomicznego z Wykresu",
              show: "Pokaż Wydarzenia Kalendarza Ekonomicznego na Wykresie",
            },
          },
          controls: {
            reset: "Zresetuj Wykres",
            scrollEnd: "Przewiń do Końca",
            scrollLeft: "Przewiń w Lewo",
            scrollRight: "Przewiń w Prawo",
            zoomIn: "Powiększ",
            zoomOut: "Pomniejsz",
          },
          crosshair: "Krzyżyk",
          delay: "{opóźnienie} min opóźnienia",
          indicators: {
            btnAddIndicator: "Dodaj wskaźnik",
            btnOpenPopup: "Dodaj Wskaźnik",
            close: "Zamknij",
            form: {
              applyTo: "Zastosuj do",
              background: {
                title: "Tło",
                down: "Chmura Kumo w górę",
                up: "Chmura Kumo w dół",
              },
              deviation: "Odstępstwo",
              enterDistance: "Okres",
              enterShift: "Zmiana",
              fastEma: "Szybkie EMA",
              slowEma: "Wolne EMA",
              line: {
                base: "Linia Bazowa",
                down: "Linia Dolna",
                minusDI: "Linia -DI",
                null: "Linia Zerowa",
                plusDI: "Linia +DI",
                style: "Styl Linii",
                cci: "Linia CCI",
                up: "Linia Górna",
                fi: "Linia FI",
              },
              maximum: "Maksymalny",
              method: {
                exponential: "Wykładniczy",
                linearWeighted: "Ważona liniowo",
                simple: "Prosty",
                smoothed: "Wygładzony",
                title: "Metoda",
              },
              opacity: "Przezroczystość",
              period: {
                jaws: "Okres Jaws",
                lips: "Okres Lips",
                teeth: "Okres Teeth:",
                title: "Okres",
                dPercent: "Okres %D",
                kPercent: "Okres %K",
              },
              selectApplyTo: "Zaznacz",
              selectVolumesType: "Wybierz rodzaj wolumenu",
              shift: "Zmiana",
              showTimeframes: "Pokaż na wszystkich ramach czasowych",
              slowing: "Slowing",
              step: "Krok",
              style: {
                down: "Styl w dół",
                jaws: "Styl Szczęk",
                lips: "Styl Ust",
                main: "Główny styl",
                signal: "Styl Sygnału",
                teeth: "Styl Zębów",
                title: "Styl",
                up: "Styl w górę",
                rvi: "Styl RVI",
              },
              volume: { down: "Wolumen w dół", up: "Wolumen w górę" },
              volumes: "Wolumeny",
              mfiUp: "MFI w górę",
              mfiDown: "MFI w dół",
              price: {
                title: "Cena",
                select: "Wybierz cenę",
                lowHigh: "Low/High",
                closeClose: "Zamknij/Zamknij",
              },
            },
            search: {
              empty: "Nie znaleziono elementów",
              title: "Szukaj",
              tryAnother: "Spróbuj innego zapytania",
            },
            tabs: {
              all: "Wszystko",
              billWilliams: "Bill Williams",
              oscillators: "Oscylatory",
              trend: "Trend",
              volumes: "Wolumeny",
            },
            title: "Wybierz wskaźnik",
            up: "Góra",
            down: "W dół",
            chartControls: {
              show: "Pokaż",
              hide: "Ukryj",
              settings: "Ustawienia",
              remove: "Usuń",
            },
          },
          loading: "Ładowanie",
          marketWatch: {
            btnOpen: {
              hide: "Ukryj Obserwację Rynku",
              show: "Pokaż Obserwację Rynku",
            },
            columns: {
              closePrice: "Cena Zamknięcia",
              dailyChange: "Dzienna Zmiana",
              openPrice: "Cena Otwarcia",
              spread: "Spread",
              symbol: "Symbol",
              time: "Czas",
              high: "High",
              low: "Low",
              last: "Ostatni",
              lastHigh: "Ostatni High",
              lastLow: "Ostatni Low",
              highLow: "High/Low",
              bidLow: "Bid Low",
              bidHigh: "Bid High",
              askHigh: "Ask High",
              askLow: "Ask Low",
              bid: "Bid",
              ask: "Ask",
              title: "Kolumny",
            },
            menu: {
              chart: "Wykres",
              columns: "Kolumny",
              dom: "Depth Of Market",
              hide: "Ukryj",
              newOrder: "Nowe Zlecenie",
              specification: "Specyfikacja",
            },
            search: "Szukaj",
            searchSymbol: "Szukaj symbolu",
            nothingFound: "Nie znaleziono symboli",
          },
          objects: {
            form: {
              statistics: "Statystyki",
              arrows: "Znaki graficzne",
              showAlways: "Pokaż zawsze",
              angle: "Kąt",
              distance: "Odległość",
              bar: "Słupek",
              price: "Cena",
              prices: "Ceny",
              showPrice: "Pokaż cenę",
              showText: "Pokaż tekst",
              showDate: "Pokaż datę",
              showTime: "Pokaż czas",
              showAllTimeframes: "Pokaż na wszystkich ramach czasowych",
              showPearsonR: "Pokaż R Pearsona",
              showLabels: "Pokaż etykiety",
              yourText: "Twój tekst",
              props: "Właściwości",
              style: "Styl",
              rays: "Promienie",
              background: "Tło",
              extends: "Rozszerzenie",
              extended: "Rozszerzony",
              pipsPerBar: "Pipsy na pasku",
              gannAngle: "Kąt Gann",
              deviations: "Odchylenia",
              labels: "Etykiety",
              reverse: "Odwróć",
              btn: { update: "Aktualizacja", cancel: "Anuluj" },
              tabs: {
                style: "Styl",
                coordinates: "Współrzędne",
                visualization: "Wizualizacja",
              },
              range: {
                price: "Zakres ceny",
                bars: "Zakres słupków",
                date: "Zakres daty",
              },
              align: {
                horizontal: "Wyrównanie poziome",
                vertical: "Wyrównanie pionowe",
                left: "Lewy",
                right: "Prawy",
                center: "Środek",
                top: "Góra",
                middle: "Środek",
                bottom: "Spód",
              },
              line: {
                style: "Styl Linii",
                base: "Linia Bazowa",
                up: "Linia Górna",
                down: "Linia Dolna",
                middle: "Linia Środkowa",
              },
            },
            visible: {
              hide: "Ukryj Wszystkie Obiekty",
              show: "Pokaż Wszystkie Obiekty",
            },
            lock: "Zablokuj Wszystkie Obiekty",
            unlock: "Odblokuj Wszystkie Obiekty",
            andrewsPitchforkChannel: "Widły Andrews",
            equidistantChannel: "Kanał Równoległy",
            regressionChannel: "Kanał Regresji",
            stdDevChannel: "Kanał StdDev",
            fibonacciRetracement: "Fibonacci Retracement",
            gannFan: "Wachlarz Ganna",
            gannGrid: "Siatka Ganna",
            gannLine: "Linia Ganna",
            arrowLine: "Linia Strzałki",
            crossLine: "Linia Krzyżowa",
            extendedLine: "Linia Przedłużona",
            horizontalRay: "Promień poziomy",
            horizontalLine: "Linia pozioma",
            infoLine: "Linia Informacyjna",
            rayLine: "Promień",
            trendAngle: "Trend Według Kąta",
            trendline: "Linia trendu",
            verticalLine: "Linia pionowa",
            disjointAngle: "Kanał Rozbieżny",
            flatTopBottom: "Płaska Góra/Dół",
            rectangle: "Prostokąt",
            circle: "Koło",
            triangle: "Trójkąt",
            ellipse: "Elipsa",
            text: "Tekst",
            rulerLine: "Linia Linijki",
          },
          period: {
            full: {
              D1: "Dzienny",
              H1: "1 Godzina",
              H4: "4 Godziny",
              M1: "1 Minuta",
              M15: "15 Minut",
              M30: "30 Minut",
              M5: "5 Minut",
              MN: "Miesięczny",
              Unknown: "Nieznany",
              W1: "Tygodniowy",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Nieznany",
              W1: "W1",
            },
          },
          screenshot: "Zapisz Wykres jako Obraz",
          symbolSpecs: {
            GTCmode: "tryb GTC",
            calculation: "Obliczenie",
            chartMode: "Tryb wykresu",
            contractSize: "Wielkość kontraktu",
            days: {
              friday: "Piątek",
              monday: "Poniedziałek",
              saturday: "Sobota",
              sunday: "Niedziela",
              thursday: "Czwartek",
              tuesday: "Wtorek",
              wednesday: "Środa",
            },
            digits: "Cyfry",
            empty: "Nie wybrano symbolu",
            execution: "Egzekucja",
            expiration: "Wygaśnięcie",
            filling: "Zasady",
            initial: "Początkowy",
            maintenance: "Właściwy",
            marginCurrency: "Waluta depozytu",
            marginRate: "Wskaźnik depozytu zabezpieczającego",
            maxVolume: "Maksymalny wolumen",
            minVolume: "Minimalny wolumen",
            orders: "Zlecenia",
            profitCurrency: "Waluta zysku",
            schedule: { quotes: "Notowania", trade: "Trade" },
            sector: "Branża",
            spread: "Spread",
            stopsLevel: "Stops level",
            swapLong: "Długi Swap",
            swapShort: "Krótki Swap",
            swapType: "Rodzaj Swap",
            title: "{symbol} specyfikacja kontraktu",
            tradeMode: "Trade",
            volumeStep: "Krok wolumenu",
            volumeLimit: "Limit wolumenu",
            tickSize: "Rozmiar ticków",
            tickValue: "Wartość ticków",
            marginInitial: "Depozyt początkowy",
            marginHedged: "Zabezpieczony depozyt",
            commission: {
              daily: {
                volume: "Dzienny volumen w lotach",
                turnoverVolume: "Dzienny obrót w lotach",
                turnoverMoney: "Dzienny obrót w pieniądzach",
                value: "Dzienna wartość transakcji",
                profit: "Dzienny zysk",
              },
              monthly: {
                volume: "Miesięczny wolumen w lotach",
                turnoverVolume: "Miesięczny obrót w lotach",
                turnoverMoney: "Miesięczny obrót w pieniądzach",
                value: "Miesięczna wartość transakcji",
                profit: "Miesięczny zysk",
              },
              instant: {
                volume: "Natychmiastowe wg wolumenu transakcji",
                value: "Natychmiastowe wg wartości transakcji",
                profit: "Natychmiastowe wg zysku z transakcji",
              },
              entry: {
                in: "transakcje przychodzące",
                out: "transakcje wychodzące",
                all: "transakcje typu in/out",
              },
              tier: {
                mode: {
                  pips: "punkty",
                  percent: "% w {currency}",
                  percentProfit: "% z zysku {currency}",
                },
                type: { perDeal: "na transakcję", perLot: "na lota" },
              },
              header: "Prowizje",
            },
          },
          tree: {
            close: "Zamknij",
            empty: "Na wykresie nie ma żadnych obiektów",
            lock: "Blokuj",
            remove: "Usuń",
            settings: "Ustawienia",
            title: "Zarządzaj Rysunkami",
            unlock: "Odblokuj",
          },
          types: {
            area: "Obszar",
            line: "Linia",
            bars: "Słupki",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Wolumen tick",
            volumes: "Wolumeny",
            withoutVolumes: "Bez Wolumentów",
            realVolumes: "Prawdziwe Wolumeny",
          },
          zoom: { in: "Powiększ", out: "Pomniejsz" },
          hotkeys: {
            arrowLine: "Linia Strzałki",
            chartTypeArea: "Wykres Warstwowy",
            chartTypeLine: "Wykres Liniowy",
            chartTypeBar: "Wykres Słupkowy",
            chartTypeCandle: "Wykres Świecowy",
            crossLine: "Linia Krzyżowa",
            extendedLine: "Linia Przedłużona",
            horizontalLine: "Linia Pozioma",
            infoLine: "Linia Informacyjna",
            rayLine: "Promień",
            realVolumes: "Prawdziwe Wolumeny",
            tickVolumes: "Wolumen tick",
            trendline: "Linia trendu",
            verticalLine: "Linia pionowa",
            sections: {
              chartType: "Rodzaj Wykresu",
              drawing: "Rysowanie",
              volume: "Wolumen",
            },
            crosshairRuler: "Linijka Krzyżowa",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Zacznij korzystać ze swojego rachunku",
            newAccountOpened: "Nowy rachunek został otwarty",
          },
          brokerInformation: {
            company: "Firma",
            email: "Email",
            phone: "Telefon",
            registrationAddress: "Adres Rejestracji",
            title: "Informacje o Firmie",
            website: "Strona internetowa",
          },
          changePassword: {
            btnChange: "Zmień Hasło",
            confirmPassword: "Potwierdź Hasło",
            newPassword: "Nowe Hasło",
            title: "Zmień Hasło",
          },
          connect: {
            btnConnect: "Połącz z rachunkiem",
            contactBroker: "Skontaktuj się z firmą",
            forgotPassword: "Zapomniałeś hasła?",
            loginPlaceholder: "Wprowadź Login",
            passwordPlaceholder: "Wprowadź Hasło",
            savePassword: "Zapisz hasło",
            title: "Połącz z rachunkiem",
          },
          copyToClipboard: {
            copy: "Kopiuj do schowka",
            unsupported: "Kopiowanie nie jest obsługiwane",
          },
          demo: {
            accountOpeningWarning:
              "Otwierając rachunek, wyrażasz zgodę na warunki otwarcia rachunku i politykę ochrony danych {brokerName}",
            btnOpenDemo: "Otwórz rachunek demo",
            title: "Otwórz rachunek demo",
            tradeWithRealMoney:
              "Aby handlować prawdziwymi pieniędzmi, musisz zawrzeć oddzielną umowę z firmą świadczącą usługi finansowe.",
          },
          disclaimer: {
            btnAccept: "Akceptuj",
            headerTitle: "Witamy w MetaTrader 5",
            text: 'MetaQuotes Ltd jest firmą zajmującą się tworzeniem oprogramowania i nie świadczy żadnych usług finansowych, inwestycyjnych, maklerskich, handlowych ani dostarczania danych, ani nie jest zaangażowana w żadne płatności prowizji dotyczące jakichkolwiek operacji handlowych.<br /><br />Naciskając przycisk Przycisk AKCEPTUJ zgadzam się z <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">warunkami umowy EULA</a>, <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Polityką prywatności</a> i wyłączeniem odpowiedzialności.<br /><br /> Żadne informacje dostępne w aplikacji nie mają charakteru porad inwestycyjnych. Przed użyciem tej aplikacji do handlu należy zasięgnąć porady wykwalifikowanego i zarejestrowanego specjalisty ds. papierów wartościowych i przeprowadzić własną analizę due diligence.',
            title: "Wyłączenie odpowiedzialności",
          },
          errors: {
            error: "Błąd",
            invalidCode: "Nieprawidłowy kod",
            invalidEmail: "Nieprawidłowy email",
            invalidPhone: "Nieprawidłowy telefon",
            unknownError: "Nieznany błąd",
          },
          form: {
            accountType: "Rodzaj Rachunku",
            address: "Serwer",
            addressPlaceholder: "Wprowadź swój adres",
            annualDeposit: "Roczny depozyt",
            annualIncome: "Roczny dochód",
            broker: "Firma",
            btn: {
              back: "Powrót",
              cancel: "Anuluj",
              next: "Następny",
              openAccount: "Otwórz Rachunek",
              remove: "Usuń",
              signOut: "Wyloguj się",
            },
            city: "Miasto",
            cityPlaceholder: "Wprowadź swoje miasto",
            country: "Kraj",
            dateBirth: "Data urodzenia",
            deposit: "Depozyt",
            education: "Edukacja ",
            email: {
              address: "Email",
              code: "Kod z maila",
              placeholder: "Wprowadź email",
              title: "Email",
            },
            employement: "Zatrudnienie",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Kobieta", male: "Mężczyzna", title: "Płeć" },
            identity: "ID",
            imageOrPdfFile: "Obraz lub plik PDF",
            investor: "Inwestor",
            language: "Język",
            leverage: "Dźwignia",
            login: "Login",
            min5chars: "Min 5 znaków",
            name: {
              middle: "Środkowe imię",
              surname: "Nazwisko",
              title: "Nazwa",
              yourName: "Twoje Imię",
            },
            nationality: "Narodowość",
            netWorth: "Wartość netto",
            optional: "Opcjonalne",
            password: "Hasło ",
            passwordReadOnly: "Hasło tylko do odczytu",
            phone: {
              mobile: "Telefon komórkowy",
              number: "Numer telefonu",
              sms: "Kod z SMS",
            },
            pleaseSelect: "Proszę Wybrać",
            policyCheckbox:
              "Zgadzam się z warunkami otwarcia rachunku i polityką ochrony danych",
            server: "Serwer",
            side: { back: "Tylna strona", front: "Przednia strona" },
            sourceWealth: "Źródło dochodu",
            state: "Stan",
            status: "Stan",
            stocks: "Akcje",
            taxID: "NIP",
            type: "Rodzaj",
            useHedge: "Użyj zabezpieczeń (hedge) w handlu",
            verificationCodes: {
              email: "Wysłaliśmy kod weryfikacyjny na Twój adres e-mail",
              phone: "Wysłaliśmy kod weryfikacyjny na Twój telefon",
              phoneEmail:
                "Wysłaliśmy kody weryfikacyjne na Twój telefon oraz e-mail",
            },
            zipCode: "Kod pocztowy",
          },
          mainForm: {
            title: "Rachunki handlowe",
            titleWithName: "Rachunki handlowe: {brokerName}",
          },
          otp: {
            disable2FA: "Wyłącz 2FA/TOTP",
            disable2FAAccount: "Wyłącz 2FA/TOTP dla rachunku {login}",
            disableEnterCode:
              "Aby wyłączyć 2FA/TOTP, wprowadź kod rachunku wygenerowany przez Authenticator.",
            downloadApp:
              "Pobierz na swoje urządzenie mobilne aplikację Google Authenticator / Microsoft Authenticator / Authy App i zeskanuj kod QR:",
            enable2FA: "Włącz 2FA/TOTP",
            enable2FAAccount: "Włącz 2FA/TOTP dla rachunku {login}",
            enterCode:
              "Aby sprawdzić działanie Authenticatora, wprowadź kod rachunku wygenerowany przez aplikację.",
            oneTimePassword: "Jednorazowe hasło:",
            placeholder: "Wprowadź OTP rachunku",
            required:
              "Uwierzytelnianie 2FA jest wymagane dla dodatkowego zabezpieczenia rachunku.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Wyciąg bankowy",
              utilityBill: "Rachunek komunalny",
            },
            conditionsForUploadingFiles: {
              documents:
                "Niektóre rodzaje dokumentów wymagają dwóch zdjęć: przedniej i tylnej strony",
              proofAddress:
                "Rachunki za usługi komórkowe nie są akceptowane jako potwierdzenie adresu",
              utilityBill:
                "Rachunek za usługi komunalne musi zawierać Twoje imię i nazwisko oraz adres, i być nie starszy niż 3 miesiące",
            },
            documentType: {
              driverLicense: "Prawo jazdy",
              idCard: "Dowód osobisty",
              passport: "Paszport",
              residencePermit: "Karta pobytu",
            },
            educationLevel: {
              bachelor: "Licencjat lub odpowiednik",
              highScholl: "Liceum",
              master: "Magister lub odpowiednik",
              none: "Brak",
              other: "Inne",
              phd: "Doktor lub odpowiednik",
            },
            employment: {
              employed: "Zatrudniony",
              other: "Inne",
              retired: "Na emeryturze",
              selfEmployed: "Właściciel firmy lub samozatrudniony",
              student: "Student",
              unemployed: "Bezrobotny",
            },
            experience: "Doświadczenie w handlu rzeczywistym",
            experienceLevel: {
              above3: "> 3 lata",
              form1to3: "1 rok do 3 lata",
              less1: "< 1 rok",
            },
            industry: {
              agriculture: "Rolnictwo",
              communication: "Sztuka, Technologia Audio/Video i Komunikacja",
              construction: "Architektura i Budownictwo",
              education: "Edukacja ",
              engineering: "Inżynieria i Matematyka",
              government: "Rząd i Administracja Publiczna",
              healthcare: "Opieka zdrowotna",
              it: "IT",
              management: "Zarządzanie biznesowe i Administracja",
              manufacturing: "Produkcja",
              marketing: "Marketing i Sprzedaż",
              none: "Brak",
              other: "Inne",
              science: "Nauka i Technologia",
              security: "Prawo, Bezpieczeństwo publiczne, Bezpieczeństwo",
              tourism: "Hotelarstwo i Turystyka",
              transport: "Transport, Dystrybucja i Logistyka",
            },
            policy:
              "Dane osobowe są wykorzystywane do otwarcia rachunku handlowego i nie są przekazywane osobom trzecim. Informacje są przetwarzane w sposób bezpieczny i poufny.",
            takePhoto:
              "Zrób zdjęcia swoich dokumentów i załaduj je tutaj bez żadnej edycji",
            title: "Otwórz Rachunek rzeczywisty",
            wealthSource: {
              employment: "Zatrudnienie",
              inheritance: "Prezenty lub Dziedzictwo",
              other: "Inne",
              savings: "Oszczędności lub Inwestycje",
            },
          },
          saveAccountData: "Przechowywuj login i hasło w bezpiecznym miejscu",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Zamknij",
            empty: "Nie mamy danych wolumenu dla tego symbolu",
            extendedBook: {
              hide: "Ukryj Rozszerzone Okno",
              show: "Pokaż Rozszerzone Okno",
            },
            menu: {
              amount: "Ilość zamiast Lotów",
              extended: "Rozszerzony",
              spread: "Spread",
            },
            spread: { hide: "Ukryj Spread", show: "Pokaż Spread" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Depth Of Market",
          },
          errors: {
            accepted: "Zaakceptowano",
            allowedOnlyLongPositions: "Dozwolone tylko długie pozycje",
            allowedOnlyPositionsClosing: "Dozwolone tylko zamykanie pozycji",
            allowedOnlyShortPositions: "Dozwolone tylko krótkie pozycje",
            automatedTradingDisabledClient:
              "AutoTrading wyłączone na terminalu klienta",
            automatedTradingDisabledServer:
              "AutoTrading wyłączone po stronie serwera",
            canceled: "Anulowano",
            common: "Częsty błąd",
            demoAllocationDisabled: "Alokacja rachunku demo jest wyłączona",
            done: "Gotowe",
            donePartially: "Wykonano częściowo",
            frequentRequests: "Zbyt częste wnioski",
            invalidExpiration: "Nieprawidłowe wygaśnięcie",
            invalidOrderType: "Nieprawidłowe rodzaj zlecenia",
            invalidParameters: "Nieprawidłowe parametry",
            invalidPrices: "Nieprawidłowe ceny",
            invalidSLTP: "Nieprawidłowy S/L lub T/P",
            invalidVolume: "Nieprawidłowy wolumen",
            manyTradeRequests: "Zbyt wiele zleceń",
            marketClosed: "Rynek zamknięty",
            modificationFailed:
              "Modyfikacja nie powiodła się. Zlecenie lub pozycja za blisko rynku.",
            networkProblem: "Problem z siecią",
            noConnection: "Brak połączenia",
            notEnoughMoney: "Za mało pieniędzy",
            offQuotes: "Off quotes",
            ok: "OK",
            onTheWay: "W drodze",
            orderChanged: "Zlecenie został już zmienione",
            orderClosePositionExists:
              "Polecenie aby zamknąć tę pozycję już istnieje",
            ordersLimitReached: "Osiągnięto limit zlecen",
            permissions: "Niewystarczające zezwolenia",
            placed: "Umieszczony",
            positionCloseProhibitedByFIFO:
              "Zamknięcie pozycji zabronione przez regułę FIFO",
            positionClosed: "Pozycja już zamknięta",
            positionsLimitReached: "Osiągnięto limit pozycji",
            priceChanged: "Cena zmieniona",
            prices: "Ceny",
            processed: "Przetworzono",
            rejected: "Odrzucono",
            requestRejectedOrderWillCanceled:
              "Żądanie odrzucone, zlecenie anulowane",
            requoted: "Nowe kwotowanie",
            serverProblem: "Problem techniczny serwera",
            timeout: "Timeout",
            tradeDisabled: "Trade jest wyłączony",
            unsupportedFillingMode: "Nieobsługiwany tryb wypełniania",
            volumeLimitReached: "Osiągnięto limit wolumenu",
          },
          form: {
            acceptNewQuotes: "Czy akceptujesz nowe kwotowania?",
            btnOpen: {
              hide: "Ukryj Formularz Handlowy",
              show: "Pokaż Formularz Handlowy",
              title: "Nowe Zlecenie",
            },
            buttons: {
              accept: "Akceptuj",
              delete: "Usuń ",
              modify: "Modyfikuj",
              ok: "OK",
              placeOrder: "Złóż zlecenie",
              reject: "Odrzuć",
              request: "Żądanie",
              requestPrice: "Żądanie Ceny",
            },
            close: "Zamknij",
            execution: {
              fillOrKill: "Fill or Kill",
              immediateOrCancel: "Natychmiastowe lub Anuluj",
              bookOrCancel: "Zarezerwuj lub Anuluj",
              label: "Wypełnianie",
              return: "Powrót",
            },
            executionMode: {
              exchange: "Exchange Execution",
              instant: "Natychmiastowe Wykonanie",
              market: "Market Execution",
              request: "Żądanie Wykonania",
            },
            expiration: {
              date: "Data Wygaśnięcia",
              label: "Wygaśnięcie",
              types: {
                specified: "Określony",
                specifiedDay: "Określony Dzień",
                today: "Dziś",
              },
            },
            fields: {
              closeBy: "Zamknij przez",
              comment: "Komentarz",
              price: "Ceny",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Wolumen",
              errors: {
                volume: {
                  min: "Minimalny wolumen to {min}",
                  max: "Maksymalny wolumen to {max}",
                  required: "Volume is required",
                  step: "Wolumen można ustawić w krokach {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Historia",
            deals: {
              columns: {
                comment: "Komentarz",
                commission: "Prowizja",
                direction: "Kierunek",
                fee: "Opłata",
                order: "Zlecenie",
                price: "Ceny",
                profit: "Zysk",
                swap: "Swap",
                symbol: "Symbol",
                ticket: "Ticket",
                time: "Czas",
                type: "Rodzaj",
                volume: "Wolumen",
              },
            },
            empty: "Nie masz jeszcze historii transakcji",
            menu: {
              columns: {
                horizontalScroll: "Przewijanie Poziome",
                resetAll: "Resetuj wszystko",
                title: "Kolumny",
              },
              deals: "Deals",
              orders: "Zlecenia",
              period: {
                all: "Cała historia",
                last3Months: "Ostatnie 3 miesiące",
                last6months: "Ostatnie 6 miesięcy",
                lastMonth: "Ostatni miesiąc",
                title: "Okres",
                customPeriod: "Dostosuj Okres",
                lastYear: "Ostatni rok",
                lastWeek: "Ostatni tydzień",
                today: "Dziś",
              },
              positions: "Pozycje",
              chart: "Wykres",
              newOrder: "Nowe Zlecenie",
            },
            orders: {
              columns: {
                comment: "Komentarz",
                price: "Ceny",
                slDescription: "Stop Loss",
                state: "Stan",
                symbol: "Symbol",
                ticket: "Ticket",
                timeDone: "Czas",
                timeSetup: "Czas",
                tpDescription: "Take Profit",
                type: "Rodzaj",
                volume: "Wolumen",
                timeSetupDescription: "Czas Otwarcia",
                timeDoneDescription: "Czas Zamknięcia",
              },
              total: {
                title: "Łącznie",
                filled: "Wypełnione",
                canceled: "Anulowane",
                rejected: "Odrzucone",
              },
            },
            positions: {
              columns: {
                commission: "Prowizja",
                fee: "Opłata",
                priceClose: "Cena",
                priceCloseDescription: "Cena Zamknięcia",
                priceOpen: "Ceny",
                priceOpenDescription: "Cena Otwarcia",
                profit: "Zysk",
                slDescription: "Stop Loss",
                swap: "Swap",
                symbol: "Symbol",
                ticket: "Ticket",
                timeClose: "Czas",
                timeCloseDescription: "Czas Zamknięcia",
                timeOpen: "Czas",
                timeOpenDescription: "Czas Otwarcia",
                tpDescription: "Take Profit",
                type: "Rodzaj",
                volume: "Wolumen",
                comment: "Komentarz",
              },
            },
            columns: { default: "Domyślnie" },
            total: {
              profit: "Zysk",
              credit: "Kredyt",
              deposit: "Depozyt",
              withdrawal: "Wypłata",
              balance: "Saldo",
              commission: "Prowizja",
              fee: "Opłata",
              swap: "Swap",
              grossProfit: "Zysk Brutto",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Historia Handlu",
                orders: "Zlecenia Handlowe",
                position: "Pozycje",
                sltp: "Poziomy SL/TP",
              },
              notification: "Powiadomienie Handlowe",
            },
            oneClick: "One Click Trading",
            tags: { demo: "Demo", readonly: "Tylko do odczytu" },
            oneClickBottom: "Panel One Click na dole",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Akceptuję te Warunki",
            btnAccept: "Akceptuj",
            btnCancel: "Anuluj",
            text: "Zamierzasz aktywować tryb Handlu Jednym Kliknięciem (One Click Trading). Klikając „Akceptuję te warunki” poniżej, potwierdzasz, że przeczytałeś i zrozumiałeś poniższe warunki i wyrażasz zgodę na ich przestrzeganie.<br /><br />Możesz aktywować lub dezaktywować tryb Handlu Jednym Kliknięciem w menu Twojego web terminala.<br /><br />Tryb Handlu Jednym Kliknięciem służący do składania zleceń to proces jednoetapowy. Twoje zlecenie zostanie przesłane, gdy: &mdash; przyciśniesz przycisk bid (SPRZEDAJ) lub ask (KUPUJ) na panelu Handlu Jednym Kliknięciem na wykresie &mdash; przyciśniesz przycisk Sprzedaj, Zamknij, Kupuj lub przyciski składania zlecenia w oknie Głębia Rynku &mdash; zamkniesz pozycje lub usuniesz zlecenia w zakładce Handel<br /><br />NIE BĘDZIE ŻADNEJ KOLEJNEJ PROPOZYCJI POTWIERDZENIA DO KLIKNIĘCIA. NIE BĘDZIESZ MÓGŁ WYCOFAĆ ANI ZMIENIĆ ZLECENIA PO KLIKNIĘCIU. W NORMALNYCH WARUNKACH RYNKOWYCH I WYDAJNOŚCI SYSTEMU ZLECENIE RYNKOWE ZOSTANIE NIEZWŁOCZNIE WYPEŁNIONE PO ZŁOŻENIU I ZOSTANIE ZAWARTA WIĄŻĄCA TRANSAKCJA.<br /><br />Zgadzasz się zaakceptować wszelkie ryzyko związane z korzystaniem z trybu Handlu Jednym Kliknięciem, w tym między innymi ryzyko błędów, pominięć lub pomyłek popełnionych podczas składania takiego zlecenia.<br /><br />Zgadzasz się w pełni zabezpieczyć i zwolnić firmę {companyName} z odpowiedzialności za wszelkie straty, koszty i wydatki, które mogą powstać w wyniku jakichkolwiek takich błędów, pominięć lub błędów popełnionych przez Ciebie lub jakąkolwiek inną osobę dokonującą transakcji w Twoim imieniu.",
            title: "Handel Jednym Kliknięciem — Wyłączenie Odpowiedzialności",
          },
          quickTrade: {
            hide: "Ukryj Panel Handlu Jednym Kliknięciem",
            show: "Pokaż Panel Handlu Jednym Kliknięciem",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Zapoznałem się z komunikatem i chcę handlować na instrumentach o wysokim ryzyku. ",
            btnAccept: "Akceptuj",
            btnCancel: "Anuluj",
            text: "Pragniemy poinformować, że dalsze korzystanie z tej platformy transakcyjnej zapewni Państwu dostęp do lewarowanych produktów inwestycyjnych wysokiego ryzyka, dostarczanych przez wybraną przez Państwa instytucję finansową. Inwestowanie w takie produkty może nie być odpowiednie dla wszystkich inwestorów, ponieważ wiąże się z ryzykiem utraty części lub całości zdeponowanej kwoty.<br /><br />Przed podjęciem decyzji o handlu produktami inwestycyjnymi wysokiego ryzyka należy dokładnie rozważyć swoje cele inwestycyjne, poziom doświadczenia i akceptowalne ryzyko. Istnieje możliwość, że możesz ponieść stratę wyższą niż początkowa inwestycja i dlatego nie powinieneś inwestować pieniędzy, na stratę których nie możesz sobie pozwolić.<br /><br />Zapraszamy do poszerzenia wiedzy na temat wszystkich czynników ryzyka związanych z inwestowaniem w te produkty, oraz do zasięgnęcia porady u profesjonalnego doradcy finansowego.",
            title: "Ostrzeżenie o Wysokim Ryzyku Inwestycyjnym",
          },
          table: {
            btnOpen: "Trade",
            columns: {
              comment: "Komentarz",
              priceClose: "Ceny",
              priceCloseDescription: "Cena zamykania",
              priceOpen: "Ceny",
              priceOpenDescription: "Cena otwarcia",
              profit: "Zysk",
              slDescription: "Stop Loss",
              swap: "Swap",
              symbol: "Symbol",
              ticket: "Ticket",
              time: "Czas",
              tpDescription: "Take Profit",
              type: "Rodzaj",
              volume: "Wolumen",
            },
            emptyPlug: {
              btnNewOrder: "Utwórz Nowe Zlecenie",
              title: "Nie masz żadnych pozycji",
            },
            menu: {
              chart: "Wykres",
              closePosition: "Zamknij Pozycję",
              columns: "Kolumny",
              modifyOrder: "Modyfikuj Zlecenie",
              modifyPosition: "Modyfikuj Pozycję",
              newOrder: "Nowe Zlecenie",
              resetAll: "Resetuj wszystko",
              deleteOrder: "Usuń Zlecenie",
            },
            oneClick: { deleteOrder: "Usuń " },
            sections: {
              collateralPositions: "Pozycje Collateral",
              orders: "Zlecenia",
              positions: "Pozycje",
            },
            total: {
              assets: "Aktywa",
              balance: "Saldo Rachunku",
              collateral: "Collateral",
              commission: "Prowizja",
              credit: "Kredyt",
              equity: "Saldo rejestru operacyjnego",
              liabilities: "Pasywa",
              margin: "Depozyt",
              marginFree: "Free Margin",
              marginLevel: "Poziom",
            },
          },
          timer: {
            marketWillOpen: "Rynek zostanie otwarty za {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} dni",
            oneDay: "{numberOfDays} dzień",
          },
          tradeIsDisabled: {
            account: "Handel na tym rachunku jest wyłączony na serwerze",
            collateral:
              "Handel nie jest dostępny, ponieważ ten symbol jest collateral",
            disabled: "Trade jest wyłączony",
            investor:
              "Handel nie jest dostępny, ponieważ jesteś połączony z hasłem inwestora",
            readOnly:
              "Handel jest niedostępny, ponieważ nie zaakceptowałeś ostrzeżenia o ryzyku",
            symbol: "Handel jest wyłączony dla tego symbolu",
          },
          hotkeys: {
            historyPanel: "Panel Historii",
            journalPanel: "Dziennik",
            marketWatch: "Rynek",
            quickTrade: "One Click Trading",
            tradeForm: "Nowe Zlecenie",
            tradePanel: "Panel Handlu",
          },
          marketOpen: {
            time: "Rynek zamknięty — zostanie otwarty o {time}",
            afterSeconds: "Rynek zamknięty — zostanie otwarty za {time} sek",
          },
          expiredTimer: { seconds: "Wygasa za {time} sek" },
          corporateLink: {
            type: {
              clientAgreement: "Umowa klienta",
              riskDisclosure: "Ujawnienie ryzyka",
              fdmDisclaimer: "Zastrzeżenie FDM",
              clientAgreementAndRiskDisclosure:
                "Umowa z klientem i ujawnienie ryzyka",
              complaintsHandlingProcedure: "Procedura rozpatrywania skarg",
              orderExecutionPolicy: "Zasady realizacji zleceń",
              clientCategorisationNotice:
                "Powiadomienie o kategoryzacji klientów",
              conflictsOfInterestPolicy: "Zasady dot. konfliktu interesów",
              dataProtectionPolicy: "Polityka Ochrony Danych",
            },
          },
          margin: {
            floating: "zmienny",
            mode: {
              marketBuy: "Zlecenie rynkowe Buy",
              marketSell: "Zlecenie rynkowe Sell",
            },
            rangeMode: {
              value: "wartość nominalna",
              valuePerSymbol: "wartość nominalna w/g symbolu",
              volume: "wolumen",
              volumePerSymbol: "wolumen w/g symbolu",
            },
            showValue: "Pokaż wartości w {currency} na lota",
            rates: "Stopa depozytu:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Wyłącz Pełny Ekran",
            enable: "Włącz Pełny Ekran",
          },
          journal: {
            btnOpen: "Dziennik",
            columns: { message: "Wiadomość", source: "Źródło", time: "Czas" },
            menu: {
              clear: "Wyczyść",
              debugMode: "Tryb debugowania",
              exportFile: "Eksportuj do Pliku",
            },
          },
          menu: {
            about: "O programie",
            contact: "Skontaktuj się z nami",
            brokerInformation: "Informacje o firmie",
            chartSettings: {
              controls: "Kontrolki Wykresu",
              grid: "Siatka",
              ohlc: "Pokaż OHLC",
              title: "Ustawienia wykresu",
              askPrice: "Cena Ask",
              crosshair: "Kursor krzyżykowy",
            },
            connect: "Połącz z rachunkiem",
            language: {
              title: "Język",
              search: "Szukaj",
              nothingFound: "Nie znaleziono języka",
            },
            openDemo: "Otwórz rachunek Demo",
            openReal: "Otwórz rachunek Rzeczywisty",
            settings: "Ustawienia",
            shortcuts: "Skróty",
            theme: {
              blackWhite: "Czarno-Biały",
              blueRed: "Niebiesko-Czerwony",
              dark: "Ciemny Motyw",
              editor: "Edytor Motywów",
              greenRed: "Zielono-Czerwony",
              light: "Jasny Motyw",
              neutral: "Neutralny",
              templates: "Szablony Kolorów",
            },
            title: "Menu",
            tradingAccount: "Rachunki handlowe",
            terms: "Zasady i Warunki",
            desktopPlatforms: "Platformy desktopowe",
            qrCode: {
              install: "Zeskanuj, aby zainstalować z {store}",
              downloadApk: "Zeskanuj, aby uzyskać plik APK Android",
            },
            economicCalendar: "Kalendarz Ekonomiczny",
          },
          screen: { back: "Powrót" },
          mobile: { bottomNav: { quotes: "Notowania" } },
          hotkeys: {
            sections: { navigation: "Nawigacja", view: "Widok" },
            escape: "Anuluj",
            indicators: "Wskaźniki",
            depthOfMarket: "Depth Of Market",
            objectTreePanel: "Drzewo Obiektów",
            scrollRight: "Następna Świeca",
            scrollToStart: "Przewiń Wykres do Początku",
            scrollLeft: "Poprzednia Świeca",
            scrollToEnd: "Przewiń Wykres do Końca",
            resetChartView: "Zresetuj wykres",
            zoomIn: "Powiększ",
            zoomOut: "Pomniejsz",
            fullScreen: "Pełny ekran",
            screenshot: "Zapisz Wykres jako Obraz",
            title: "Skróty",
          },
          timezone: {
            title: "Strefa czasowa",
            city: {
              cairo: "Kair",
              casablanca: "Casablanka",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Zamocowanie",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Carakas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "Salwador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Meksyk",
              newYork: "Nowy Jork",
              phoenix: "Feniks",
              santiago: "Santiago",
              saoPaulo: "San Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Ałmaty",
              ashgabat: "Aszchabad",
              bahrain: "Bahrajn",
              bangkok: "Bangkok",
              kolkata: "Kalkuta",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hongkong",
              jakarta: "Djakarta",
              jerusalem: "Jerozolima",
              karachi: "Karaczi",
              kathmandu: "Katmandu",
              kuwait: "Kuwejt",
              manila: "Manila",
              muscat: "Muskat",
              nicosia: "Nikozja",
              qatar: "Katar",
              rangoon: "Rangun",
              riyadh: "Rijad",
              saigon: "Sajgon",
              seoul: "Seul",
              shanghai: "Szanghaj",
              singapore: "Singapur",
              taipei: "Tajpej",
              tehran: "Teheran",
              tokyo: "Tokio",
              reykjavik: "Reykjavik",
              adelaide: "Adelaida",
              brisbane: "Brisbane",
              perth: "Pert",
              sydney: "Sydnej",
              amsterdam: "Amsterdam",
              athens: "Ateny",
              belgrade: "Belgrad",
              berlin: "Berlin",
              bratislava: "Bratysława",
              brussels: "Bruksela",
              bucharest: "Bukareszt",
              budapest: "Budapeszt",
              copenhagen: "Kopenhaga",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Stambuł",
              lisbon: "Lizbona",
              london: "Londyn",
              luxembourg: "Luksemburg",
              madrid: "Madryt",
              malta: "Malta",
              moscow: "Moskwa",
              oslo: "Osło",
              paris: "Paryż",
              prague: "Praga",
              riga: "Ryga",
              rome: "Rzym",
              stockholm: "Sztokholm",
              tallinn: "Tallinn",
              vienna: "Wiedeń",
              vilnius: "Wilno",
              warsaw: "Warszawa",
              zurich: "Zurych",
              auckland: "Okland",
              chatham: "Chathama",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { a, o as b, i as c, e as p };
