const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Verberg de Economische Kalender Gebeurtenissen van de Grafiek",
              show: "Toon de Economische Kalender Gebeurtenissen van de Grafiek",
            },
          },
          controls: {
            reset: "Grafiek Resetten",
            scrollEnd: "Naar Einde Scrollen",
            scrollLeft: "Naar Links Scrollen",
            scrollRight: "Naar Rechts Scrollen",
            zoomIn: "Inzoomen",
            zoomOut: "Uitzoomen",
          },
          crosshair: "Focuspunt",
          delay: "{delay} minimale vertraging",
          indicators: {
            btnAddIndicator: "Indicator toevoegen",
            btnOpenPopup: "Indicator toevoegen",
            close: "Sluiten",
            form: {
              applyTo: "Toepassen op",
              background: {
                title: "Achtergrond",
                down: "Kumo achtergrond omlaag",
                up: "Kumo achtergrond omhoog",
              },
              deviation: "Afwijking",
              enterDistance: "Termijn",
              enterShift: "Verschuiving",
              fastEma: "Snelle EMA",
              slowEma: "Trage EMA",
              line: {
                base: "Basis lijn",
                down: "Lagere lijn",
                minusDI: "-DI lijn",
                null: "Null lijn",
                plusDI: "+DI lijn",
                style: "Lijn Style",
                cci: "CCI lijn",
                up: "Hogere lijn",
                fi: "FI line",
              },
              maximum: "Maximale",
              method: {
                exponential: "Exponentieel",
                linearWeighted: "Lineair Gewogen",
                simple: "Simpel",
                smoothed: "gladgestreken",
                title: "Methode",
              },
              opacity: "Doorzichtigheid",
              period: {
                jaws: "Jaws termijn",
                lips: "Lips termijn",
                teeth: "Teeth termijn",
                title: "Termijn",
                dPercent: "%D periode",
                kPercent: "%K periode",
              },
              selectApplyTo: "Selecteren",
              selectVolumesType: "Volume selecteren",
              shift: "Verschuiving",
              showTimeframes: "Op alle termijnen tonen",
              slowing: "Vertraging",
              step: "Stap",
              style: {
                down: "Omlaag stijl",
                jaws: "Jaws stijl",
                lips: "Lips stijl",
                main: "Basis stijl",
                signal: "Signaal stijl",
                teeth: "Teeth stijl",
                title: "Stijl",
                up: "Omhoog stijl",
                rvi: "RVI Stijl",
              },
              volume: { down: "Volume Omlaag", up: "Volume Omhoog" },
              volumes: "Volumes",
              mfiUp: "MFI Omhoog",
              mfiDown: "MFI Omlaag",
              price: {
                title: "Prijs",
                select: "Prijs selecteren",
                lowHigh: "Laag/Hoog",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "Geen items gevonden",
              title: "Zoeken",
              tryAnother: "Probeer een andere zoekopdracht",
            },
            tabs: {
              all: "Alle",
              billWilliams: "Bill Williams",
              oscillators: "Oscillatoren",
              trend: "Trend",
              volumes: "Volumes",
            },
            title: "Indicator selecteren",
            up: "Boven",
            down: "Naar beneden",
            chartControls: {
              show: "Tonen",
              hide: "Verbergen",
              settings: "Instellingen",
              remove: "Verwijderen",
            },
          },
          loading: "Laden",
          marketWatch: {
            btnOpen: {
              hide: "Market Watch Verbergen",
              show: "Market Watch Vertonen",
            },
            columns: {
              closePrice: "Sluit Prijs",
              dailyChange: "Dagelijkse verandering",
              openPrice: "Open Prijs",
              spread: "Spread",
              symbol: "Symbool",
              time: "Tijd",
              high: "Hoog",
              low: "Laag",
              last: "Laatste",
              lastHigh: "Laatste Hoog",
              lastLow: "Laatste Laag",
              highLow: "Hoog/Laag",
              bidLow: "Laag Bod",
              bidHigh: "Hoog Bod",
              askHigh: "Vraag Hoog",
              askLow: "Vraag Laag",
              bid: "Bied",
              ask: "Vraag",
              title: "Kolommen",
            },
            menu: {
              chart: "Grafiek",
              columns: "Kolommen",
              dom: "Diepte van de markt",
              hide: "Verbergen",
              newOrder: "Nieuwe Order",
              specification: "Specificatie",
            },
            search: "Zoeken",
            searchSymbol: "Symbool zoeken",
            nothingFound: "Geen symbolen gevonden",
          },
          objects: {
            form: {
              statistics: "Statistieken",
              arrows: "Pijlen",
              showAlways: "Altijd tonen",
              angle: "Hoek",
              distance: "Afstand",
              bar: "Staaf",
              price: "Prijs",
              prices: "Prijzen",
              showPrice: "Prijs tonen",
              showText: "Text tonen",
              showDate: "Datum tonen",
              showTime: "Tijd tonen",
              showAllTimeframes: "Op alle termijnen tonen",
              showPearsonR: "Pearson's R tonen",
              showLabels: "Labels tonen",
              yourText: "Uw tekst",
              props: "Eigenschappen",
              style: "Stijl",
              rays: "Stralen",
              background: "Achtergrond",
              extends: "Verlenging",
              extended: "Uitgebreid",
              pipsPerBar: "Pips per balk",
              gannAngle: "Gann hoek",
              deviations: "Afwijkingen",
              labels: "Labels",
              reverse: "Omkeren",
              btn: { update: "Updaten", cancel: "Annuleren" },
              tabs: {
                style: "Stijl",
                coordinates: "Coördinaten",
                visualization: "Visualisatie",
              },
              range: {
                price: "Prijs bereik",
                bars: "Bars bereik",
                date: "Datum bereik",
              },
              align: {
                horizontal: "Horizontale uitlijning",
                vertical: "Verticale uitlijning",
                left: "Links",
                right: "Rechts",
                center: "Midden",
                top: "Bovenaan",
                middle: "Midden",
                bottom: "Onderaan",
              },
              line: {
                style: "Lijn Stijl",
                base: "Basis Lijn",
                up: "Hoge Lijn",
                down: "Lage Lijn",
                middle: "Midden Lijn",
              },
            },
            visible: {
              hide: "Alle Objecten Verbergen",
              show: "Alle Objecten Weergeven",
            },
            lock: "Alle Objecten Vergrendelen",
            unlock: "Alle Objecten Ontgrendelen",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Equidistant kanaal",
            regressionChannel: "Regressie Kanaal",
            stdDevChannel: "Standaard Afwijkings Kanaal",
            fibonacciRetracement: "Fibonacci retracement",
            gannFan: "Gann Fan",
            gannGrid: "Gann Net",
            gannLine: "Gann Lijn",
            arrowLine: "Lijn met Pijl",
            crossLine: "Kruis Lijn",
            extendedLine: "Verlengde Lijn",
            horizontalRay: "Horizontale Straal",
            horizontalLine: "Horizontale lijn",
            infoLine: "Informatie Lijn",
            rayLine: "Straal",
            trendAngle: "Trend Op Hoek",
            trendline: "Trend lijn",
            verticalLine: "Verticale lijn",
            disjointAngle: "Disjunct Kanaal",
            flatTopBottom: "Platte Boven/Onderkant",
            rectangle: "Rechthoek",
            circle: "Cirkel",
            triangle: "Driehoek",
            ellipse: "Ellips",
            text: "Tekst",
            rulerLine: "Liniaal Lijn",
          },
          period: {
            full: {
              D1: "Dagelijks",
              H1: "1 uur",
              H4: "4 uur",
              M1: "1 minuut",
              M15: "15 minuten",
              M30: "30 minuten",
              M5: "5 minuten",
              MN: "Maandelijks",
              Unknown: "Onbekend",
              W1: "Wekelijks",
            },
            short: {
              D1: "Dag1",
              H1: "Uur1",
              H4: "Uur4",
              M1: "Min1",
              M15: "Min15",
              M30: "Min30",
              M5: "Min5",
              MN: "Mnd",
              Unknown: "Onbekend",
              W1: "Wk1",
            },
          },
          screenshot: "Grafiek opslaan als afbeelding",
          symbolSpecs: {
            GTCmode: "GTC modus",
            calculation: "Berekening",
            chartMode: "Grafiek modus",
            contractSize: "Contract grootte",
            days: {
              friday: "Vrijdag",
              monday: "Maandag",
              saturday: "Zaterdag",
              sunday: "Zondag",
              thursday: "Donderdag",
              tuesday: "Dinsdag",
              wednesday: "Woensdag",
            },
            digits: "Digits",
            empty: "Geen symbool geselecteerd",
            execution: "Uitvoering",
            expiration: "Vervaltijd",
            filling: "Vulbeleid",
            initial: "Initiële ",
            maintenance: "Onderhoud ",
            marginCurrency: "Marge valuta",
            marginRate: "Marge tarief",
            maxVolume: "Maximale volume",
            minVolume: "Minimale volume",
            orders: "Orders",
            profitCurrency: "Winst valuta",
            schedule: { quotes: "Quotes", trade: "Handel" },
            sector: "Sector",
            spread: "Spread",
            stopsLevel: "Stops niveau ",
            swapLong: "Swap long",
            swapShort: "Swap short",
            swapType: "Swap type",
            title: "{symbol} contract specificatie",
            tradeMode: "Handel",
            volumeStep: "Volume stap",
            volumeLimit: "Volume limiet",
            tickSize: "Tick grootte",
            tickValue: "Tick waarde",
            marginInitial: "Initiële marge",
            marginHedged: "Marge hedgen",
            commission: {
              daily: {
                volume: "Dagelijks volume in lots",
                turnoverVolume: "Dagelijkse omzet in lots",
                turnoverMoney: "Dagelijkse omzet in geld",
                value: "Dagelijkse waarde van deals",
                profit: "Dagelijkse winst",
              },
              monthly: {
                volume: "Maandelijks volume in lots",
                turnoverVolume: "Maandelijkse omzet in lots",
                turnoverMoney: "Maandelijkse omzet in geld",
                value: "Maandelijkse waarde van deals",
                profit: "Maandelijkse winst",
              },
              instant: {
                volume: "Direct op deal volume",
                value: "Direct op deal waarde",
                profit: "Directe winst per deal",
              },
              entry: { in: "in deals", out: "uit deals", all: "in/uit deals" },
              tier: {
                mode: {
                  pips: "punten",
                  percent: "% in {currency}",
                  percentProfit: "% van de winst {currency}",
                },
                type: { perDeal: "per deal", perLot: "per lot" },
              },
              header: "Commissies",
            },
          },
          tree: {
            close: "Sluiten",
            empty: "U heeft geen objecten op de grafiek",
            lock: "Vergrendelen",
            remove: "Verwijderen",
            settings: "Instellingen",
            title: "Tekeningen Beheren",
            unlock: "Ontgrendelen",
          },
          types: {
            area: "Gebied",
            line: "Lijn",
            bars: "Staven",
            candlestick: "Kaars Grafiek",
          },
          volumeTypes: {
            tickVolumes: "Tik Volumes",
            volumes: "Volumes",
            withoutVolumes: "Zonder Volumes",
            realVolumes: "Werkelijke volumes",
          },
          zoom: { in: "Inzoomen", out: "Uitzoomen" },
          hotkeys: {
            arrowLine: "Lijn met Pijl",
            chartTypeArea: "Gebieds Grafiek",
            chartTypeLine: "Lijn Grafiek",
            chartTypeBar: "Staaf Grafiek",
            chartTypeCandle: "Kaars Grafiek",
            crossLine: "Kruis Lijn",
            extendedLine: "Verlengde Lijn",
            horizontalLine: "Horizontale lijn",
            infoLine: "Informatie Lijn",
            rayLine: "Ray",
            realVolumes: "Echte Volumes",
            tickVolumes: "Tik Volumes",
            trendline: "Trend lijn",
            verticalLine: "Verticale lijn",
            sections: {
              chartType: "Grafiek Type",
              drawing: "Tekening",
              volume: "Volume",
            },
            crosshairRuler: "Kruisdraad Liniaal",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  n = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Ga aan de slag met uw account",
            newAccountOpened: "Nieuw account geopend",
          },
          brokerInformation: {
            company: "Bedrijf",
            email: "Email",
            phone: "Telefoon",
            registrationAddress: "Registratie Adres",
            title: "Bedrijfs Informatie",
            website: "Website",
          },
          changePassword: {
            btnChange: "Wijzig Wachtwoord",
            confirmPassword: "Wachtwoord Bevestigen",
            newPassword: "Nieuw Wachtwoord",
            title: "Wijzig Wachtwoord",
          },
          connect: {
            btnConnect: "Account Verbinden",
            contactBroker: "Contact Opnemen",
            forgotPassword: "Wachtwoord vergeten?",
            loginPlaceholder: "Login Invoeren",
            passwordPlaceholder: "Wachtwoord Invoeren",
            savePassword: "Bewaar wachtwoord",
            title: "Account Verbinden",
          },
          copyToClipboard: {
            copy: "Kopiëren naar klembord",
            unsupported: "Kopiëren wordt niet ondersteund",
          },
          demo: {
            accountOpeningWarning:
              "Door een account te openen, gaat u akkoord met de voorwaarden voor het openen van een account en het gegevens beschermingsbeleid van {brokerName}",
            btnOpenDemo: "Demo account openen",
            title: "Demo account openen",
            tradeWithRealMoney:
              "Om met echt geld te handelen, moet u een afzonderlijke overeenkomst aangaan met een financiële dienstverlener.",
          },
          disclaimer: {
            btnAccept: "Accepteren",
            headerTitle: "Welkom bij MetaTrader 5",
            text: 'MetaQuotes Ltd is een softwareontwikkelingsbedrijf en biedt geen financiële, investerings, broker, handels- of datafeed diensten, noch is het betrokken bij op commissie gebaseerde betalingen met betrekking tot handelsactiviteiten.<br /><br />Door op de Knop ACCEPTEREN Ik ga akkoord met de <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">algemene voorwaarden van de EULA</a>, de <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacybeleid</a> en de Disclaimer.<br /><br /> Geen van de informatie beschikbaar in de applicatie is bedoeld als beleggingsadvies. Voordat u deze applicatie gebruikt om te handelen, dient u het advies in te winnen van een gekwalificeerde en geregistreerde effectenprofessional en uw eigen due diligence uit te voeren.',
            title: "Disclaimer",
          },
          errors: {
            error: "Fout",
            invalidCode: "Ongeldige code",
            invalidEmail: "Ongeldige email",
            invalidPhone: "Ongeldige telefoon",
            unknownError: "Onbekende error",
          },
          form: {
            accountType: "Rekeningsoort",
            address: "Adres",
            addressPlaceholder: "Voer uw adres in",
            annualDeposit: "Jaarlijks storting",
            annualIncome: "Jaarlijks inkomen",
            broker: "Bedrijf",
            btn: {
              back: "Terug",
              cancel: "Annuleren",
              next: "Volgende",
              openAccount: "Account Openen",
              remove: "Verwijderen",
              signOut: "Uitloggen",
            },
            city: "Stad",
            cityPlaceholder: "Voer uw stad in",
            country: "Land",
            dateBirth: "Geboortedatum",
            deposit: "Storting",
            education: "Onderwijs",
            email: {
              address: "Email",
              code: "Code uit email",
              placeholder: "Email invoeren",
              title: "Email",
            },
            employement: "Dienstverband",
            forex: "Forex",
            futures: "Futures ",
            gender: { female: "Vrouw", male: "Man", title: "Geslacht" },
            identity: "Identiteit",
            imageOrPdfFile: "Afbeelding of PDF titel",
            investor: "Investeerder ",
            language: "Taal",
            leverage: "Hefboom",
            login: "Inloggen",
            min5chars: "Minimaal 5 karakters",
            name: {
              middle: "Tussenvoegsel",
              surname: "Achternaam",
              title: "Naam",
              yourName: "Uw Naam",
            },
            nationality: "Nationaliteit",
            netWorth: "Netto waarde",
            optional: "Optioneel",
            password: "Wachtwoord",
            passwordReadOnly: "Alleen lezen wachtwoord",
            phone: {
              mobile: "Mobiel nummer",
              number: "Telefoon nummer",
              sms: "SMS code",
            },
            pleaseSelect: "Selecteer",
            policyCheckbox:
              "Ik ga akkoord met de algemene voorwaarden voor het openen van een account en het gegevensbeleid",
            server: "Server",
            side: { back: "Achterkant", front: "Voorkant" },
            sourceWealth: "Bron van rijkdom",
            state: "Staat",
            status: "Voortgang",
            stocks: "Aandelen",
            taxID: "Belasting-nummer",
            type: "Type",
            useHedge: "Gebruik hedge mogelijkheden.",
            verificationCodes: {
              email:
                "We hebben een verificatiecode naar uw emailadres gestuurd",
              phone: "We hebben een verificatiecode naar uw telefoon gestuurd",
              phoneEmail:
                "We hebben een verificatiecode naar uw telefoon en naar uw emailadres gestuurd",
            },
            zipCode: "Postcode",
          },
          mainForm: {
            title: "Handels Accounts",
            titleWithName: "Handels Accounts: {brokerName}",
          },
          otp: {
            disable2FA: "2FA Uitschakelen/TOTP",
            disable2FAAccount: "2FA Uitschakelen/TOTP voor account {login}",
            disableEnterCode:
              "Om 2FA/TOTP uit te schakelen, voert u uw accountcode in die door de Authenticator is gegenereerd.",
            downloadApp:
              "Download de Google Authenticator / Microsoft Authenticator / Authy App naar uw mobiele apparaat en scan de QR-code:",
            enable2FA: "2FA Inschakelen/TOTP",
            enable2FAAccount: "2FA Inschakelen/TOTP voor account {login}",
            enterCode:
              "Voer uw accountcode in die door de app is gegenereerd om de werking van de Authenticator te controleren.",
            oneTimePassword: "Eenmalig Wachtwoord OTP",
            placeholder: "Account OTP invoeren",
            required:
              "2FA authenticatie is vereist voor extra accountbeveiliging.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Bankafschrift",
              utilityBill: "Energierekening",
            },
            conditionsForUploadingFiles: {
              documents:
                "Sommige documenten vereisen twee foto's: voor en achterkant",
              proofAddress:
                "Rekeningen voor mobiele diensten worden niet geaccepteerd als bewijs van adres",
              utilityBill:
                "De energierekening moet uw naam en adres bevatten en mag niet ouder zijn dan 3 maanden",
            },
            documentType: {
              driverLicense: "Rijbewijs",
              idCard: "ID kaart",
              passport: "Paspoort",
              residencePermit: "Verblijfsvergunning",
            },
            educationLevel: {
              bachelor: "Bachelor diploma of gelijkwaardig",
              highScholl: "Middelbare school",
              master: "Master diploma of gelijkwaardig",
              none: "Geen",
              other: "Anders",
              phd: "PHD of gelijkwaardig",
            },
            employment: {
              employed: "In dienst",
              other: "Anders",
              retired: "Gepensioneerd",
              selfEmployed: "Bedrijfseigenaar of zelfstandige",
              student: "Student",
              unemployed: "Werkloos",
            },
            experience: "Werkelijke handels ervaring",
            experienceLevel: {
              above3: "> 3 jaar",
              form1to3: "1 tot 3 jaar",
              less1: "< 1 jaar",
            },
            industry: {
              agriculture: "Landbouw",
              communication: "Kunst, audio / videotechnologie en communicatie",
              construction: "Architectuur en constructie",
              education: "Onderwijs",
              engineering: "Engineering en wiskunde",
              government: "Overheid en openbaar bestuur",
              healthcare: "Gezondheidszorg",
              it: "Informatie Technologie",
              management: "Bedrijfsbeheer en administratie",
              manufacturing: "Producent",
              marketing: "Marketing en verkoop",
              none: "Geen",
              other: "Anders",
              science: "Wetenschap en technologie",
              security:
                "Juridisch, openbare veiligheid, correcties en beveiliging",
              tourism: "Gastvrijheid en toerisme",
              transport: "Transport, distributie en logistiek",
            },
            policy:
              "Persoonlijke gegevens worden gebruikt voor het openen van een handelsaccount en worden niet doorgegeven aan derden. De informatie wordt veilig en vertrouwelijk behandeld.Persoonlijke gegevens worden gebruikt voor het openen van een handelsaccount en worden niet doorgegeven aan derden. De informatie wordt veilig en vertrouwelijk behandeld.",
            takePhoto:
              "Maak alstublieft foto's van uw documenten en upload ze hier zonder enige bewerking",
            title: "Open een Real Account",
            wealthSource: {
              employment: "Dienstverband of bedrijfsopbrengsten",
              inheritance: "Geschenken of Erfenis",
              other: "Anders",
              savings: "Gespaard of investeringen",
            },
          },
          saveAccountData:
            "Bewaar uw login en wachtwoord op een veilige plaats",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Sluiten",
            empty: "We hebben geen volumegegevens voor dit symbool",
            extendedBook: {
              hide: "Uitgebreid Boek Verbergen",
              show: "Uitgebreid Boek Vertonen",
            },
            menu: {
              amount: "Hoeveelheid in plaats van Lots",
              extended: "Uitgebreid",
              spread: "Spread",
            },
            spread: { hide: "Spread Verbergen", show: "Spread Vertonen" },
            stopLoss: "Stop Loss",
            takeProfit: "Neem Winst",
            title: "Diepte van de markt",
          },
          errors: {
            accepted: "Geaccepteerd",
            allowedOnlyLongPositions: "Alleen long posities zijn toegestaan",
            allowedOnlyPositionsClosing:
              "Alleen het sluiten van posities is toegestaan",
            allowedOnlyShortPositions: "Aleen short posities zijn toegestaan",
            automatedTradingDisabledClient:
              "Automatisch handelen is gedeactiveerd aan de klant zijde",
            automatedTradingDisabledServer:
              "Automatisch handelen is gedeactiveerd aan de server zijde",
            canceled: "Geannuleerd",
            common: "Error",
            demoAllocationDisabled:
              "Toewijzen van demo accounts is uitgeschakeld",
            done: "Gereed",
            donePartially: "Gedeelteijk voltooid",
            frequentRequests: "Te veelvuldige verzoeken",
            invalidExpiration: "Ongeldige vervaltijd",
            invalidOrderType: "Ongeldig order type",
            invalidParameters: "Ongeldige parameters",
            invalidPrices: "Ongeldige prijzen",
            invalidSLTP: "Ongeldige S/L of T/P",
            invalidVolume: "Ongeldig volume",
            manyTradeRequests: "Te veel handelsverzoeken",
            marketClosed: "Markt gesloten",
            modificationFailed:
              "Wijzigen mislukt, order of positie te dicht op de markt ",
            networkProblem: "Netwerk probleem",
            noConnection: "Geen verbinding",
            notEnoughMoney: "Onvoldoende middelen",
            offQuotes: "Off quotes",
            ok: "OK",
            onTheWay: "Onderweg",
            orderChanged: "Order werd reeds gewijzigd",
            orderClosePositionExists:
              "De order om deze positie te sluiten bestaat al",
            ordersLimitReached: "Orderlimiet bereikt",
            permissions: "Niet genoeg permissies",
            placed: "Geplaatst",
            positionCloseProhibitedByFIFO:
              "Positie sluiten is verboden door FIFO regel",
            positionClosed: "Positie is reeds gesloten",
            positionsLimitReached: "Positie limiet bereikt",
            priceChanged: "Prijs veranderd",
            prices: "Prijzen",
            processed: "Verwerkt ",
            rejected: "Afgewezen",
            requestRejectedOrderWillCanceled:
              "Verzoek afgewezen, order geannuleerd ",
            requoted: "Requoted",
            serverProblem: "Server probleem",
            timeout: "Timeout",
            tradeDisabled: "Handelen is uitgeschakeld",
            unsupportedFillingMode: "Ongeldige vulmodus",
            volumeLimitReached: "Volume limiet bereikt",
          },
          form: {
            acceptNewQuotes: "Accepteerd u deze nieuwe quotes?",
            btnOpen: {
              hide: "Handelsformulier Verbergen",
              show: "Handelsformulier Vertonen",
              title: "Nieuwe Order",
            },
            buttons: {
              accept: "Accepteren",
              delete: "Verwijderen",
              modify: "Wijzigen",
              ok: "OK",
              placeOrder: "Order Plaatsen",
              reject: "Afwijzen",
              request: "Verzoek",
              requestPrice: "Prijs Verzoeken",
            },
            close: "Sluiten",
            execution: {
              fillOrKill: "Vullen of Vernietigen",
              immediateOrCancel: "Onmiddelijk of Annuleren",
              bookOrCancel: "Boeken of Annuleren",
              label: "Vul beleid",
              return: "Terug",
            },
            executionMode: {
              exchange: "Exchange Execution",
              instant: "Onmiddelijk Uitvoeren",
              market: "Markt Executie",
              request: "Verzoek Uitvoering",
            },
            expiration: {
              date: "Varvaldatum",
              label: "Vervaltijd",
              types: {
                specified: "Gespecificeerd ",
                specifiedDay: "Gespecificeerd Dag",
                today: "Vandaag",
              },
            },
            fields: {
              closeBy: "Sluiten Bij",
              comment: "Commentaar",
              price: "Prijs",
              stopLoss: "Stop Loss",
              takeProfit: "Neem Winst",
              volume: "Volume",
              errors: {
                volume: {
                  min: "Minimaal volume is {min}",
                  max: "Maximaal volume is {max}",
                  required: "Volume is required",
                  step: "Het volume kan worden ingesteld met een stap van {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Geschiedenis",
            deals: {
              columns: {
                comment: "Commentaar",
                commission: "Commissie",
                direction: "Richting",
                fee: "Vergoeding",
                order: "Order",
                price: "Prijs",
                profit: "Winst",
                swap: "Swap",
                symbol: "Symbool",
                ticket: "Ticket",
                time: "Tijd",
                type: "Type",
                volume: "Volume",
              },
            },
            empty: "U heeft nog geen handelsgeschiedenis",
            menu: {
              columns: {
                horizontalScroll: "Horizontale Scroll",
                resetAll: "Alles Resetten",
                title: "Kolommen",
              },
              deals: "Deals",
              orders: "Orders",
              period: {
                all: "Gehele geschiedenis",
                last3Months: "Laatste 3 Maanden",
                last6months: "Laatste 6 Maanden",
                lastMonth: "Laatste Maand",
                title: "Termijn",
                customPeriod: "Aangepaste Periode",
                lastYear: "Laatste jaar",
                lastWeek: "Laatste week",
                today: "Vandaag",
              },
              positions: "Posities",
              chart: "Grafiek",
              newOrder: "Nieuwe Order",
            },
            orders: {
              columns: {
                comment: "Commentaar",
                price: "Prijs",
                slDescription: "Stop Loss",
                state: "Staat",
                symbol: "Symbool",
                ticket: "Ticket",
                timeDone: "Tijd",
                timeSetup: "Tijd",
                tpDescription: "Neem Winst",
                type: "Type",
                volume: "Volume",
                timeSetupDescription: "Open Tijd",
                timeDoneDescription: "Sluit Tijd",
              },
              total: {
                title: "Totaal",
                filled: "Gevuld",
                canceled: "Geannuleerd",
                rejected: "Afgewezen",
              },
            },
            positions: {
              columns: {
                commission: "Commissie",
                fee: "Vergoeding",
                priceClose: "Prijs",
                priceCloseDescription: "Sluitings Prijs",
                priceOpen: "Prijs",
                priceOpenDescription: "Openings Prijs",
                profit: "Winst",
                slDescription: "Stop Loss",
                swap: "Swap",
                symbol: "Symbool",
                ticket: "Ticket",
                timeClose: "Tijd",
                timeCloseDescription: "Sluitings Tijd",
                timeOpen: "Tijd",
                timeOpenDescription: "Openings Tijd",
                tpDescription: "Neem Winst",
                type: "Type",
                volume: "Volume",
                comment: "Opmerkingen",
              },
            },
            columns: { default: "Standaard" },
            total: {
              profit: "Winst",
              credit: "Krediet",
              deposit: "Storting",
              withdrawal: "Opname",
              balance: "Saldo",
              commission: "Commissie",
              fee: "Vergoeding",
              swap: "Swap",
              grossProfit: "Bruto Winst",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Handelsgeschiedenis",
                orders: "Handels Orders",
                position: "Transactie Posities",
                sltp: "SL/TP Niveaus",
              },
              notification: "Trade Notificatie",
            },
            oneClick: "Eén-kliktrading",
            tags: { demo: "Demo", readonly: "Alleen Lezen" },
            oneClickBottom: "Paneel met één klik onderaan",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Ik accepteer deze Voorwaarden en Condities",
            btnAccept: "Accepteren",
            btnCancel: "Annuleren",
            text: 'U staat op het punt om One Click Trading modus te activeren. Door hieronder op "Ik ga akkoord met deze algemene voorwaarden" te klikken, bevestigt u dat u de volgende algemene voorwaarden hebt gelezen en begrepen en gaat u ermee akkoord hieraan gebonden te zijn.<br /><br />U kunt One Click Trading activeren of deactiveren Klik op de handelsmodus in het menu van uw webterminal.<br /><br />De One Click Trading modus voor het indienen van orders is een proces van één stap. Uw order wordt verzonden wanneer u: &mdash; tikt op de bid (VERKOPEN) of ask (KOPEN) prijsknoppen op het One Click Trading paneel van een grafiek &mdash; tik op de knoppen Verkopen, Sluiten, Kopen of order in het venster Diepte van de Markt &mdash; sluit posities of verwijder orders in het tabblad Handelen<br /><br />ER ZAL GEEN VERDERE BEVESTIGINGSPROMPT ZIJN DIE U MOET KLIKKEN. U KUNT UW BESTELLING NIET TERUGTREKKEN OF WIJZIGEN ALS U EENMAAL HEEFT GEKLIKT. ONDER NORMALE MARKTOMSTANDIGHEDEN EN SYSTEEMPRESTATIES WORDT EEN MARKTORDER ONMIDDELLIJK UITGEVULD NA INDIENING EN GAAT U EEN BINDENDE TRANSACTIE AAN.<br /><br />U stemt ermee in alle risico\'s te aanvaarden die verbonden zijn aan het gebruik van de One Click Trading modus , inclusief maar niet beperkt tot het risico van fouten, weglatingen of vergissingen bij het plaatsen van een dergelijke bestelling.<br /><br />U stemt ermee in {companyName} volledig schadeloos te stellen en te vrijwaren van alle verliezen, kosten en uitgaven die oplopen als gevolg van dergelijke fouten, omissies of vergissingen door u of een andere persoon die namens u handelt.',
            title: "Handelen met één klik - Disclaimer",
          },
          quickTrade: {
            hide: "One Click Handels Paneel Verbergen",
            show: "One Click Handles Paneel Vertonen",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Ik ben me bewust van de bovenstaande verklaring en ik wil deze beleggingsproducten met een hoog risico verhandelen",
            btnAccept: "Accepteren",
            btnCancel: "Annuleren",
            text: "We willen u informeren dat u door verder gebruik te maken van dit handelsplatform toegang krijgt tot risicovolle beleggingsproducten met hefboomwerking, aangeboden door de financiële instelling van uw keuze. Beleggen in dergelijke producten is mogelijk niet geschikt voor alle beleggers, omdat het risico van verlies van een deel of het gehele gestorte bedrag met zich meebrengt.<br /><br />Voordat u besluit om beleggingsproducten met een hoog risico te verhandelen, dient u uw beleggingsdoelstellingen zorgvuldig te overwegen, ervaringsniveau en aanvaardbaar risico. De mogelijkheid bestaat dat u een verlies lijdt dat hoger is dan uw initiële investering en daarom moet u geen geld beleggen dat u zich niet kunt veroorloven te verliezen.<br /><br />We nodigen u uit om uw kennis te verbreden over alle risicofactoren die betrokken bent bij het beleggen in deze producten, en vraag bij twijfel advies aan een professionele financieel adviseur.",
            title: "Hoge Risico Investerings Waarschuwing",
          },
          table: {
            btnOpen: "Handel",
            columns: {
              comment: "Commentaar",
              priceClose: "Prijs",
              priceCloseDescription: "Sluit Prijs",
              priceOpen: "Prijs",
              priceOpenDescription: "Open Prijs",
              profit: "Winst",
              slDescription: "Stop Loss",
              swap: "Swap",
              symbol: "Symbool",
              ticket: "Ticket",
              time: "Tijd",
              tpDescription: "Neem Winst",
              type: "Type",
              volume: "Volume",
            },
            emptyPlug: {
              btnNewOrder: "Nieuwe Order Creëren",
              title: "U heeft geen posities",
            },
            menu: {
              chart: "Grafiek",
              closePosition: "Positie Sluiten",
              columns: "Kolommen",
              modifyOrder: "Wijzig Order",
              modifyPosition: "Wijzig Positie",
              newOrder: "Nieuwe Order",
              resetAll: "Alles Resetten",
              deleteOrder: "Order verwijderen",
            },
            oneClick: { deleteOrder: "Verwijderen" },
            sections: {
              collateralPositions: "Onderpand Posities",
              orders: "Orders",
              positions: "Posities",
            },
            total: {
              assets: "Activa",
              balance: "Balans",
              collateral: "Collateral",
              commission: "Commissie",
              credit: "Credit",
              equity: "Vermogen",
              liabilities: "Passiva",
              margin: "Marge",
              marginFree: "Vrije marge:",
              marginLevel: "Niveau",
            },
          },
          timer: {
            marketWillOpen: "De markt is open over {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} dagen",
            oneDay: "{numberOfDays} dagen",
          },
          tradeIsDisabled: {
            account: "Handelen is voor dit account uitgeschakeld op de server",
            collateral:
              "Handelen is niet mogelijk, omdat dit symbool onderpand is",
            disabled: "Handelen is uitgeschakeld",
            investor:
              "Handelen is niet mogelijk, omdat u bent verbonden met een investeerders wachtwoord",
            readOnly:
              "Handelen is niet mogelijk, omdat u de risico waarschuwing niet geaccepteerd heeft",
            symbol: "Handelen is uitgeschakeld voor dit symbool",
          },
          hotkeys: {
            historyPanel: "Geschiedenis Paneel",
            journalPanel: "Dagboek",
            marketWatch: "Markt Monitor",
            quickTrade: "Eén-kliktrading",
            tradeForm: "Nieuwe Order",
            tradePanel: "Handels Paneel",
          },
          marketOpen: {
            time: "Markt gesloten - gaat open om {time}",
            afterSeconds: "Markt gesloten - gaat open over {time} sec",
          },
          expiredTimer: { seconds: "Verloopt over {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Klant overeenkomst",
              riskDisclosure: "Risico vrijgave",
              fdmDisclaimer: "FDM vrijwaring",
              clientAgreementAndRiskDisclosure:
                "Klantovereenkomst en vrijgave van risico's",
              complaintsHandlingProcedure: "Klachtenbehandeling",
              orderExecutionPolicy: "Orderuitvoeringsbeleid",
              clientCategorisationNotice: "Kennisgeving klantcategorisatie",
              conflictsOfInterestPolicy: "Belangenconflictenbeleid",
              dataProtectionPolicy: "Gegevensbeschermingsbeleid",
            },
          },
          margin: {
            floating: "zwevend",
            mode: { marketBuy: "Markt kopen", marketSell: "Markt verkopen" },
            rangeMode: {
              value: "notionele waarde",
              valuePerSymbol: "notionele waarde per symbool",
              volume: "volume",
              volumePerSymbol: "volume per symbool",
            },
            showValue: "Waardes tonen in {currency} per lot",
            rates: "Marge:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Volledig scherm deactiveren",
            enable: "Volledig scherm activeren",
          },
          journal: {
            btnOpen: "Dagboek",
            columns: { message: "Bericht", source: "Bron", time: "Tijd" },
            menu: {
              clear: "Opruimen",
              debugMode: "Debug Modus",
              exportFile: "Naar bestand Exporteren",
            },
          },
          menu: {
            about: "Over dit Programma",
            contact: "Neem contact met ons op",
            brokerInformation: "Bedrijfs Informatie",
            chartSettings: {
              controls: "Grafiek Instellingen",
              grid: "Raster",
              ohlc: "OHLC tonen",
              title: "Grafiek Instellingen",
              askPrice: "Vraagprijs",
              crosshair: "Kruiscursor",
            },
            connect: "Maak verbinding met een account",
            language: {
              title: "Taal",
              search: "Zoeken",
              nothingFound: "Taal niet gevonden",
            },
            openDemo: "Demo account openen",
            openReal: "Real account openen",
            settings: "Instellingen",
            shortcuts: "Snelkoppelingen",
            theme: {
              blackWhite: "Zwart & Wit",
              blueRed: "Blauw & Rood",
              dark: "Donker Thema",
              editor: "Thema Editor",
              greenRed: "Groen & Rood",
              light: "Licht Thema",
              neutral: "Neutraal",
              templates: "Kleur Sjablonen",
            },
            title: "Menu",
            tradingAccount: "Trading Accounts",
            terms: "Algemene Voorwaarden",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scannen om te installeren vanuit {store}",
              downloadApk: "Scannen om Android APK bestand te verkrijgen",
            },
            economicCalendar: "Economische Kalender",
          },
          screen: { back: "Terug" },
          mobile: { bottomNav: { quotes: "Quotes" } },
          hotkeys: {
            sections: { navigation: "Navigatie", view: "Bekijken" },
            escape: "Annuleren",
            indicators: "Indicatoren",
            depthOfMarket: "Diepte van de markt",
            objectTreePanel: "Object Weergave",
            scrollRight: "Volgende Kaars",
            scrollToStart: "Scroll Grafiek naar Start",
            scrollLeft: "Vorige Kaars",
            scrollToEnd: "Grafiek naar einde Scrollen",
            resetChartView: "Grafiek Resetten",
            zoomIn: "Inzoomen",
            zoomOut: "Uitzoomen",
            fullScreen: "Volledig Scherm",
            screenshot: "Grafiek opslaan als Afbeelding",
            title: "Snelkoppelingen",
          },
          timezone: {
            title: "Tijdzone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Ankerplaats",
              bogota: "Bogotá",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico Stad",
              newYork: "New York",
              phoenix: "Feniks",
              santiago: "Santiago",
              saoPaulo: "São Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Asjchabad",
              bahrain: "Bahrein",
              bangkok: "Bangkok",
              kolkata: "Calcutta",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hongkong",
              jakarta: "Jakarta",
              jerusalem: "Jeruzalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Koeweit",
              manila: "Manilla",
              muscat: "Muskaat",
              nicosia: "Nicosia",
              qatar: "Katar",
              rangoon: "Rangoon",
              riyadh: "Riyad",
              saigon: "Saigon",
              seoul: "Seoel",
              shanghai: "Sjanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Teheran",
              tokyo: "Tokio",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athene",
              belgrade: "Belgrado",
              berlin: "Berlijn",
              bratislava: "Bratislava",
              brussels: "Brussel",
              bucharest: "Boekarest",
              budapest: "Boedapest",
              copenhagen: "Kopenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lissabon",
              london: "Londen",
              luxembourg: "Luxemburg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moskou",
              oslo: "Oslo",
              paris: "Parijs",
              prague: "Praag",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Wenen",
              vilnius: "Vilnius",
              warsaw: "Warschau",
              zurich: "Zürich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { n as a, i as b, o as c, e as n };
