const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Uvećaj",
            zoomOut: "Umanji",
          },
          crosshair: "Nišan",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Dodaj indikator",
            btnOpenPopup: "Add Indicator",
            close: "Zatvori",
            form: {
              applyTo: "Primeni na",
              background: {
                title: "Pozadina",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Devijacija",
              enterDistance: "Period",
              enterShift: "Pomeranje",
              fastEma: "Brzi EMA",
              slowEma: "Spori EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Maximum",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Prosto",
                smoothed: "Smoothed",
                title: "Metoda",
              },
              opacity: "Opacity",
              period: {
                jaws: "Jaws period",
                lips: "Lips period",
                teeth: "Teeth period",
                title: "Period",
                dPercent: "%D period",
                kPercent: "%K period",
              },
              selectApplyTo: "Izaberi",
              selectVolumesType: "Select volume type",
              shift: "Pomeranje",
              showTimeframes: "Prikaži na svim vremenskim periodima",
              slowing: "Usporavanje",
              step: "Korak",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Stil",
                up: "Up style",
                rvi: "RVI stil",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Volumeni",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Cena",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Pretraži",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Sve",
              billWilliams: "Bill Williams",
              oscillators: "Oscilatori",
              trend: "Verovatnoća",
              volumes: "Volumeni",
            },
            title: "Select indicator",
            up: "Gore",
            down: "Dole",
            chartControls: {
              show: "Prikaži",
              hide: "Sakrij",
              settings: "Postavljanje",
              remove: "Ukloni",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Cena na zatvaranju",
              dailyChange: "Dnevna promena",
              openPrice: "Cena na otvaranju",
              spread: "Raspon",
              symbol: "Simbol",
              time: "Vreme",
              high: "Najveća",
              low: "Najmanja",
              last: "Poslednje",
              lastHigh: "Poslednji najveći",
              lastLow: "Poslednji najmanji",
              highLow: "Najviša/najniža vrednost",
              bidLow: "Najmanji Bid",
              bidHigh: "Najveći Bid",
              askHigh: "Najveći Ask",
              askLow: "Najmanji Ask",
              bid: "Ponuda",
              ask: "Tražnja",
              title: "Stupovi",
            },
            menu: {
              chart: "Grafikon",
              columns: "Kolone",
              dom: "Dubina tržišta",
              hide: "Sakrij",
              newOrder: "Novi nalog",
              specification: "Specifikacija",
            },
            search: "Pretraži",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Strelice",
              showAlways: "Show always",
              angle: "Ugao",
              distance: "Distance",
              bar: "Bar",
              price: "Cena",
              prices: "Cene",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Prikaži na svim vremenskim periodima",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Vaš tekst",
              props: "Svojstva",
              style: "Stil",
              rays: "Rays",
              background: "Pozadina",
              extends: "Extension",
              extended: "Prošireno",
              pipsPerBar: "Pips po stubcu ",
              gannAngle: "Gann ugao",
              deviations: "Odstupanja",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Ažuriranje", cancel: "Otkaži" },
              tabs: {
                style: "Stil",
                coordinates: "Coordinates",
                visualization: "Vizuelizacija",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Levo",
                right: "Desno",
                center: "Sredina",
                top: "Vrh",
                middle: "Middle",
                bottom: "Dno",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Ekvidistantni kanal",
            regressionChannel: "Kanal Regresije",
            stdDevChannel: "Kanal Standardne Devijacije",
            fibonacciRetracement: "Fibonačijev retracement",
            gannFan: "Gann Lepeza",
            gannGrid: "Gann Mreža",
            gannLine: "Gann Linija",
            arrowLine: "Linija sa strelicom",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Zrak",
            trendAngle: "Trend prema uglu",
            trendline: "Linija verovatnoće",
            verticalLine: "Uspravna linija",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Pravougaonik",
            circle: "Circle",
            triangle: "Trougao",
            ellipse: "Elipsa",
            text: "Tekst",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "Dnevno",
              H1: "1 sat",
              H4: "4 sata",
              M1: "1 minut",
              M15: "15 minuta",
              M30: "30 minuta",
              M5: "5 minuta",
              MN: "Mesečno",
              Unknown: "Unknown",
              W1: "Nedeljno",
            },
            short: {
              D1: "D1",
              H1: "60 minuta",
              H4: "240 minuta",
              M1: "1 minut",
              M15: "15 minuta",
              M30: "30 minuta",
              M5: "5 minuta",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "GTC način rada",
            calculation: "Kalkulacija",
            chartMode: "Način rada grafikona",
            contractSize: "Veličina ugovora",
            days: {
              friday: "Petak",
              monday: "Ponedeljak",
              saturday: "Subota",
              sunday: "Nedelja",
              thursday: "Četvrtak",
              tuesday: "Utorak",
              wednesday: "Sreda",
            },
            digits: "Brojke",
            empty: "No symbol selected",
            execution: "Izvršenje",
            expiration: "Isticanje",
            filling: "Ispunjenje",
            initial: "Početna vrednost",
            maintenance: "Održavanje",
            marginCurrency: "Valuta margine",
            marginRate: "Stopa margine",
            maxVolume: "Maksimalni iznos",
            minVolume: "Minimalni iznos",
            orders: "Nalozi",
            profitCurrency: "Valuta dobitka",
            schedule: { quotes: "Navodi", trade: "Trgovanje" },
            sector: "Sektor",
            spread: "Raspon",
            stopsLevel: "Nivoi stopa",
            swapLong: "Razmena dugog",
            swapShort: "Razmena kratkog",
            swapType: "Vrsta razmene",
            title: "{symbol} contract specification",
            tradeMode: "Trgovanje",
            volumeStep: "Korak iznosa",
            volumeLimit: "Ograničenje obima",
            tickSize: "Veličina tikera",
            tickValue: "Vrednost tikera",
            marginInitial: "Početna margina",
            marginHedged: "Zaštićena margina",
            commission: {
              daily: {
                volume: "Dnevna količina u lotovima",
                turnoverVolume: "Dnevni promet u lotovima",
                turnoverMoney: "Dnevni promet u novcu",
                value: "Dnevna vrednost ponuda",
                profit: "Dnevni profit",
              },
              monthly: {
                volume: "Mesečna količina u lotovima",
                turnoverVolume: "mesečni promet u lotovima",
                turnoverMoney: "mesečni promet u novcu",
                value: "Mesečna vrednost ponuda",
                profit: "Mesečni profit",
              },
              instant: {
                volume: "Instant po količini ponuda",
                value: "Instant po vrednosti ponude",
                profit: "Instant po profitu ponude",
              },
              entry: {
                in: "ulazni poslovi",
                out: "izlazni poslovi",
                all: "ulazno/izlazni poslovi",
              },
              tier: {
                mode: {
                  pips: "poena",
                  percent: "% i {currency}",
                  percentProfit: "% profita {currency}",
                },
                type: { perDeal: "po poslu", perLot: "po lotu" },
              },
              header: "Provizije",
            },
          },
          tree: {
            close: "Zatvori",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Ukloni",
            settings: "Postavljanje",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Barovi",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Tick Volumeni",
            volumes: "Volumeni",
            withoutVolumes: "Without Volumes",
            realVolumes: "Pravi volumeni",
          },
          zoom: { in: "Uvećaj", out: "Umanji" },
          hotkeys: {
            arrowLine: "Linija sa strelicom",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Linijski graf",
            chartTypeBar: "Trakasti graf",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Zrak",
            realVolumes: "Real Volumes",
            tickVolumes: "Tick Volumeni",
            trendline: "Linija verovatnoće",
            verticalLine: "Uspravna linija",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Volumen",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Novi račun je otvoren",
          },
          brokerInformation: {
            company: "Kompanija",
            email: "E-pošta",
            phone: "Telefon",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Promijena lozinke",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Promijena lozinke",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Sačuvaj šifru",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Prihvati",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "Odbacivanje odgovornosti",
          },
          errors: {
            error: "Greška",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Vrsta naloga",
            address: "Adresa",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Godišnji depozit",
            annualIncome: "Godišnji prihod",
            broker: "Kompanija",
            btn: {
              back: "Nazad",
              cancel: "Otkaži",
              next: "Sledeći",
              openAccount: "Open Account",
              remove: "Ukloni",
              signOut: "Sign out",
            },
            city: "Grad",
            cityPlaceholder: "Enter your city",
            country: "Zemlja",
            dateBirth: "Datum rođenja",
            deposit: "Depozit",
            education: "Education",
            email: {
              address: "E-pošta",
              code: "Code from email",
              placeholder: "Enter email",
              title: "E-pošta",
            },
            employement: "Employement",
            forex: "Forex",
            futures: "Fjučersi",
            gender: { female: "Žene", male: "Muškarac", title: "Spol" },
            identity: "Identitet",
            imageOrPdfFile: "Image or PDF file",
            investor: "Investitor",
            language: "Jezik",
            leverage: "Poluga",
            login: "Ime",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Naziv",
              yourName: "Your Name",
            },
            nationality: "Državljanstvo",
            netWorth: "Neto imovina",
            optional: "Optional",
            password: "Lozinka",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Saglasan sam s uslovima i odredbama za otvaranje računa i s politkom zaštite podataka.",
            server: "Server",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Izvor imovine",
            state: "Država",
            status: "Status",
            stocks: "Akcije",
            taxID: "Porezni broj",
            type: "Vrsta",
            useHedge: "Koristi hedge u trgovanju",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "Onemogući 2FA/TOTP",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "Omogući 2FA/TOTP",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Da biste proverili rad aplikacije Authenticator, unesite kôd vašeg naloga koji je generisala aplikacija.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "2FA potvrda identiteta obavezna je zbog dodatne bezbednosti naloga.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Izvod iz banke",
              utilityBill: "Račun za komunalije",
            },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Vozačka dozvola",
              idCard: "Lična karta",
              passport: "Pasoš",
              residencePermit: "Boravišna dozvola",
            },
            educationLevel: {
              bachelor: "Bejčlor ili ekvivalent",
              highScholl: "Srednja škola",
              master: "Master ili ekvivalent",
              none: "Nema",
              other: "Drugo",
              phd: "Dr. nauka or equivalent",
            },
            employment: {
              employed: "Zaposlen/a",
              other: "Drugo",
              retired: "Penzioner",
              selfEmployed: "Vlasnik preduzeća ili samozaposlen",
              student: "Student",
              unemployed: "Nezaposlen",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "preko 3 godine",
              form1to3: "1 - 3 godine",
              less1: "do 1 godine",
            },
            industry: {
              agriculture: "Poljoprivreda, hrana i prirodni resursi",
              communication: "Umetnost, audio/video produkcija i komunikacije",
              construction: "Arhitektura i građevinarstvo",
              education: "Edukacija i obuka",
              engineering: "Tehničke nauke i matematika",
              government: "Javna uprava i državna tela",
              healthcare: "Zdravstvena zaštita",
              it: "Informacijska tehnologija",
              management: "Poslovno upravljanje i administracija",
              manufacturing: "Proizvođač",
              marketing: "Marketing i prodaja",
              none: "Nema",
              other: "Drugo",
              science: "Nauka i tehnologija",
              security: "Pravo, javna sigurnost, zatvori i bezbednost",
              tourism: "Ugostiteljstvo i turizam",
              transport: "Transport, distribucija i logistika",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Zaposlenje ili prihodi od preduzeća",
              inheritance: "Poklon ili nasledstvo",
              other: "Drugo",
              savings: "Štednja ili investicije",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Zatvori",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Iznost umesto lotova",
              extended: "Prošireno",
              spread: "Raspon",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Ograniči gubitak",
            takeProfit: "Preuzmi dobitak",
            title: "Dubina tržišta",
          },
          errors: {
            accepted: "Prihvaćeno",
            allowedOnlyLongPositions: "Dopuštene su samo duge pozicije",
            allowedOnlyPositionsClosing:
              "Dozvoljeno je samo zatvaranje pozicije",
            allowedOnlyShortPositions: "Dozvoljene su samo kratke pozicije",
            automatedTradingDisabledClient:
              "Automatizovano Trgovanje onemogućeno na terminalu klijenta",
            automatedTradingDisabledServer:
              "Automatizovano Trgovanje onemogućeno od strane servera",
            canceled: "Otkazano",
            common: "Uobičajena greška",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Gotovo",
            donePartially: "Delimično urađeno",
            frequentRequests: "Previše česti zahtevi",
            invalidExpiration: "Nepravilno isticanje",
            invalidOrderType: "Nepravilna vrsta naloga",
            invalidParameters: "Nepravilni parametri",
            invalidPrices: "Nevažeće cene",
            invalidSLTP: "Nevažeći S/L ili T/P",
            invalidVolume: "Nevažeći volumen",
            manyTradeRequests: "Previše zahteva za trgovanje",
            marketClosed: "Tržište zatvoreno",
            modificationFailed:
              "Izmena nije uspela zbog naloga ili pozicije blizu tržišne cene",
            networkProblem: "Problem sa mrežom",
            noConnection: "Nema konekcije",
            notEnoughMoney: "Nedovoljno novaca",
            offQuotes: "Bez kotacije",
            ok: "OK",
            onTheWay: "Stiže",
            orderChanged: "Nalog je već izmenjen",
            orderClosePositionExists:
              "Već postoji nalog za zatvaranje ove pozicije",
            ordersLimitReached: "Dostigli ste ograničenje za naloge",
            permissions: "Nema dovoljno dozvola",
            placed: "Postavljeno",
            positionCloseProhibitedByFIFO:
              "Zatvaranje pozicije zabranjeno je zbog FIFO pravila",
            positionClosed: "Pozicija već zatvorena",
            positionsLimitReached: "Dosegnuto je ograničenje broja pozicija",
            priceChanged: "Cena je promenjena",
            prices: "Cene",
            processed: "Obrađeno",
            rejected: "Odbijeno",
            requestRejectedOrderWillCanceled:
              "Zahtev je odbijen, nalog je otkazan",
            requoted: "Ponovo kotirano",
            serverProblem: "Tehnički problem sa serverom",
            timeout: "Pauza",
            tradeDisabled: "Trgovanje je onemogućeno",
            unsupportedFillingMode: "Način rada ispunjavanja nije podržan",
            volumeLimitReached: "Dostigli ste ograničenje za volumen",
          },
          form: {
            acceptNewQuotes: "Da li prihvatate ovo novo kotiranje?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Novi nalog",
            },
            buttons: {
              accept: "Prihvati",
              delete: "Obriši",
              modify: "Izmeni",
              ok: "OK",
              placeOrder: "Place order",
              reject: "Odbij",
              request: "Po zahtevu",
              requestPrice: "Request Price",
            },
            close: "Zatvori",
            execution: {
              fillOrKill: "Ispuni ili ukini",
              immediateOrCancel: "Odmah ili otkaži",
              bookOrCancel: "Bukiraj ili otkaži",
              label: "Pravilo ispunjavanja",
              return: "Nazad",
            },
            executionMode: {
              exchange: "Izvršenje na berzi",
              instant: "Trenutno izvršenje",
              market: "Tržišno izvršenje",
              request: "Zatraži izvršenje",
            },
            expiration: {
              date: "Expiration Date",
              label: "Isticanje",
              types: {
                specified: "Određeni",
                specifiedDay: "Specified Day",
                today: "Danas",
              },
            },
            fields: {
              closeBy: "Zatvori",
              comment: "Komentar",
              price: "Cena",
              stopLoss: "Ograniči gubitak",
              takeProfit: "Preuzmi dobitak",
              volume: "Volumen",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Istorija",
            deals: {
              columns: {
                comment: "Komentar",
                commission: "Provizija",
                direction: "Smer",
                fee: "Naknada",
                order: "Nalog",
                price: "Cena",
                profit: "Dobitak",
                swap: "Razmena",
                symbol: "Simbol",
                ticket: "Tiket",
                time: "Vreme",
                type: "Vrsta",
                volume: "Volumen",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Kolone",
              },
              deals: "Dogovori",
              orders: "Nalozi",
              period: {
                all: "Cela istorija",
                last3Months: "Poslednja 3 meseca",
                last6months: "Poslednja 6 meseci",
                lastMonth: "Poslednji mesec",
                title: "Period",
                customPeriod: "Prilagođeni period",
                lastYear: "Prethodna godina",
                lastWeek: "Prošla nedjelja",
                today: "Danas",
              },
              positions: "Pozicija",
              chart: "Grafikon",
              newOrder: "Novi nalog",
            },
            orders: {
              columns: {
                comment: "Komentar",
                price: "Cena",
                slDescription: "Ograniči gubitak",
                state: "Država",
                symbol: "Simbol",
                ticket: "Tiket",
                timeDone: "Vreme",
                timeSetup: "Vreme",
                tpDescription: "Preuzmi dobitak",
                type: "Vrsta",
                volume: "Volumen",
                timeSetupDescription: "Radno vreme",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Ukupan",
                filled: "Ispunjeno",
                canceled: "Otkazano",
                rejected: "Odbijeno",
              },
            },
            positions: {
              columns: {
                commission: "Provizija",
                fee: "Naknada",
                priceClose: "Cena",
                priceCloseDescription: "Zaključna cena",
                priceOpen: "Cena",
                priceOpenDescription: "Početna cijena",
                profit: "Dobitak",
                slDescription: "Ograniči gubitak",
                swap: "Razmena",
                symbol: "Simbol",
                ticket: "Tiket",
                timeClose: "Vreme",
                timeCloseDescription: "Close Time",
                timeOpen: "Vreme",
                timeOpenDescription: "Radno vreme",
                tpDescription: "Preuzmi dobitak",
                type: "Vrsta",
                volume: "Volumen",
                comment: "Komentar",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Profit",
              credit: "Kredit",
              deposit: "Depozit",
              withdrawal: "Isplata",
              balance: "Saldo",
              commission: "Provizija",
              fee: "Naknada",
              swap: "Svop",
              grossProfit: "Bruto profit",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Istorija trgovine",
                orders: "Trade Orders",
                position: "Trade Positions",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Trgovanje jednim klikom",
            tags: { demo: "Demo", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Prihvatam ove uslove i odredbe",
            btnAccept: "Prihvati",
            btnCancel: "Otkaži",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Svestan sam gore navedene izjave i želim da trgujem produktima za visoko rizične investicije",
            btnAccept: "Prihvati",
            btnCancel: "Otkaži",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Upozorenje na investiciju visokog rizika",
          },
          table: {
            btnOpen: "Trgovanje",
            columns: {
              comment: "Komentar",
              priceClose: "Cena",
              priceCloseDescription: "Cena na zatvaranju",
              priceOpen: "Cena",
              priceOpenDescription: "Cena na otvaranju",
              profit: "Dobitak",
              slDescription: "Ograniči gubitak",
              swap: "Razmena",
              symbol: "Simbol",
              ticket: "Tiket",
              time: "Vreme",
              tpDescription: "Preuzmi dobitak",
              type: "Vrsta",
              volume: "Volumen",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Grafikon",
              closePosition: "Zatvori poziciju",
              columns: "Kolone",
              modifyOrder: "Izmeni nalog",
              modifyPosition: "Izmeni Poziciju",
              newOrder: "Novi nalog",
              resetAll: "Reset all",
              deleteOrder: "Izbriši nalog",
            },
            oneClick: { deleteOrder: "Obriši" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Nalozi",
              positions: "Pozicija",
            },
            total: {
              assets: "Imovina",
              balance: "Saldo",
              collateral: "Kolateral",
              commission: "Provizija",
              credit: "Kredit",
              equity: "Neto vrednost",
              liabilities: "Obaveze",
              margin: "Margina",
              marginFree: "Slobodna margina",
              marginLevel: "Nivo",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Žurnal",
            marketWatch: "Praćenje tržišta",
            quickTrade: "Trgovanje jednim klikom",
            tradeForm: "Novi nalog",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Ugovor o korišćenju",
              riskDisclosure: "Izjava o rizicima",
              fdmDisclaimer: "FDM odricanje odgovornosti",
              clientAgreementAndRiskDisclosure:
                "Ugovor o korišćenju i upozorenje o rizicima",
              complaintsHandlingProcedure: "Postupak rešavanja prigovora",
              orderExecutionPolicy: "Pravila izvršenja naloga",
              clientCategorisationNotice:
                "Obaveštenje o kategorizaciji klijenata",
              conflictsOfInterestPolicy:
                "Pravila za sprečavanje konflikta interesa",
              dataProtectionPolicy: "Politika zaštita podataka",
            },
          },
          margin: {
            floating: "promnenjivo",
            mode: {
              marketBuy: "Tržišna kupnja",
              marketSell: "Tržišna prodaja",
            },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Onemogući prikaz na celom ekranu",
            enable: "Omogući prikaz na celom ekranu",
          },
          journal: {
            btnOpen: "Žurnal",
            columns: { message: "Poruka", source: "Izvor", time: "Vreme" },
            menu: {
              clear: "Očisti",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Mreža",
              ohlc: "Prikaži OHLC",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Jezik",
              search: "Pretraži",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Postavljanje",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Uslovi i odredbe",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Ekonomski kalendar",
          },
          screen: { back: "Nazad" },
          mobile: { bottomNav: { quotes: "Navodi" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Pregled" },
            escape: "Otkaži",
            indicators: "Indikatori",
            depthOfMarket: "Dubina tržišta",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Uvećaj",
            zoomOut: "Umanji",
            fullScreen: "Ceo ekran",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { a, o as b, i as c, e as s };
