const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "चार्ट से आर्थिक कैलेंडर ईवेंट छुपाएं",
              show: "चार्ट पर आर्थिक कैलेंडर ईवेंट दिखाएं",
            },
          },
          controls: {
            reset: "चार्ट रीसेट करें",
            scrollEnd: "अंत तक स्क्रॉल करें",
            scrollLeft: "बाईं ओर स्क्रोल करें",
            scrollRight: "दाईं ओर स्क्रोल करें",
            zoomIn: "ज़ूम इन ",
            zoomOut: "ज़ूम आउट",
          },
          crosshair: "क्रॉसहेयर",
          delay: "{delay} मिनट विलंब",
          indicators: {
            btnAddIndicator: "इंडिकेटर जोड़ें",
            btnOpenPopup: "सूचक जोड़ें",
            close: "बंद",
            form: {
              applyTo: "लागू करें",
              background: {
                title: "पृष्ठभूमि/बैकग्राउंड",
                down: "डाउन कुमो बैकग्राउंड",
                up: "अप कुमो बैकग्राउंड",
              },
              deviation: "विचलन",
              enterDistance: "अवधि",
              enterShift: "शिफ्ट",
              fastEma: "तीव्र EMA",
              slowEma: "धीमा EMA",
              line: {
                base: "बेस लाइन",
                down: "लोवर लाइन",
                minusDI: "-DI लाइन",
                null: "शून्य लाइन",
                plusDI: "+DI लाइन",
                style: "रेखा शैली",
                cci: "CCI लाइन",
                up: "ऊपरी लाइन",
                fi: "FI ​​लाइन",
              },
              maximum: "अधिकतम",
              method: {
                exponential: "घातीय",
                linearWeighted: "लीनियर भारित",
                simple: " सामान्य",
                smoothed: "समानीय",
                title: "विधि",
              },
              opacity: "अस्पष्टता",
              period: {
                jaws: "Jaws अवधि",
                lips: "Lips अवधि",
                teeth: "Teeth अवधि",
                title: "अवधि",
                dPercent: "%D अवधि",
                kPercent: "%K अवधि",
              },
              selectApplyTo: "चुनें",
              selectVolumesType: "वॉल्यूम प्रकार का चयन करें",
              shift: "विस्थापन",
              showTimeframes: "सभी समय-सीमा पर दिखाएँ",
              slowing: "मंदीकरण",
              step: "चरण",
              style: {
                down: "डाउन शैली",
                jaws: "जॉज़ शैली",
                lips: "लिप्स शैली",
                main: "मुख्य शैली",
                signal: "संकेत शैली",
                teeth: "टीथ शैली",
                title: "शैली",
                up: "अप स्टाइल",
                rvi: "आरवीआई शैली",
              },
              volume: { down: "नीची मात्रा", up: "ऊपरी मात्रा" },
              volumes: "वॉल्यूम",
              mfiUp: "MFI ऊपर",
              mfiDown: "MFI नीचे",
              price: {
                title: "कीमत",
                select: "कीमत चुनें",
                lowHigh: "कम/ज्यादा",
                closeClose: "समाप्ति/समाप्ति",
              },
            },
            search: {
              empty: "कोई आइटम नहीं मिला",
              title: "खोज",
              tryAnother: "कृपया अन्य प्रश्न का प्रयास करें",
            },
            tabs: {
              all: "सभी",
              billWilliams: "बिल विलियम्स/Bill Williams",
              oscillators: "ऑसिलेटर्स",
              trend: "ट्रेण्ड",
              volumes: "वॉल्यूम",
            },
            title: "सूचक का चयन करें",
            up: "ऊपर",
            down: "नीचे",
            chartControls: {
              show: "दिखाए",
              hide: "छिपायें",
              settings: "सेटिंग",
              remove: "हटाये",
            },
          },
          loading: "लोड हो रहा है",
          marketWatch: {
            btnOpen: { hide: "मार्केट वॉच छुपाएं", show: "मार्केट वॉच दिखाएं" },
            columns: {
              closePrice: "बंद मूल्य",
              dailyChange: "दैनिक बदलाव",
              openPrice: "खुलने की कीमत",
              spread: "स्प्रेड",
              symbol: "प्रतीक",
              time: "समय",
              high: "उच्च",
              low: "निम्न",
              last: "अंतिम",
              lastHigh: "पिछला उच्च",
              lastLow: "पिछला निम्न",
              highLow: "उच्च/निम्न",
              bidLow: "बोली निम्न",
              bidHigh: "बोली उच्च",
              askHigh: "मांग उच्च",
              askLow: "मांग निम्न",
              bid: "बोली",
              ask: "मांग",
              title: "कॉलम",
            },
            menu: {
              chart: "चार्ट",
              columns: "कॉलम",
              dom: "डेप्थ ऑफ़ मार्किट(बाजार की गहराई)",
              hide: "छिपायें",
              newOrder: "नया आदेश",
              specification: "विशेष विवरण",
            },
            search: "खोज",
            searchSymbol: "खोज प्रतीक",
            nothingFound: "कोई प्रतीक नहीं मिला",
          },
          objects: {
            form: {
              statistics: "आंकड़े",
              arrows: "तीर(एरोज)",
              showAlways: "हमेशा दिखाएं",
              angle: "कोण",
              distance: "दूरी",
              bar: "बार",
              price: "कीमत",
              prices: "मूल्य",
              showPrice: "कीमत दिखाएं",
              showText: "टेक्स्ट दिखाएं",
              showDate: "तिथि दिखाएं",
              showTime: "समय दिखाएं",
              showAllTimeframes: "सभी समय-सीमा पर दिखाएँ",
              showPearsonR: "पियर्सन का R दिखाएँ",
              showLabels: "लेबल दिखाएं",
              yourText: "अपका संदेश",
              props: "विशेषतायें",
              style: "शैली",
              rays: "किरणें",
              background: "पृष्ठभूमि/बैकग्राउंड",
              extends: "एक्सटेंशन",
              extended: "विस्तृत",
              pipsPerBar: "पिप्स प्रति बार",
              gannAngle: "गान कोण",
              deviations: "विचलन",
              labels: "लेबल",
              reverse: "उलटें",
              btn: { update: "अपडेट", cancel: "रद्द करें" },
              tabs: {
                style: "शैली",
                coordinates: "कोऑर्डनैट्स",
                visualization: "मानसिक- दर्शन",
              },
              range: {
                price: "प्राइस रेंज",
                bars: "बार्स रेंज",
                date: "तिथि सीमा",
              },
              align: {
                horizontal: "क्षैतिज संरेखण",
                vertical: "ऊर्ध्वाधर संरेखण",
                left: "बाएं",
                right: "दाएँ",
                center: "मध्य",
                top: "शीर्ष",
                middle: "मध्य",
                bottom: "तल",
              },
              line: {
                style: "रेखा शैली",
                base: "बेस लाइन",
                up: "ऊपरी लाइन",
                down: "लोवर लाइन",
                middle: "मध्य लाइन",
              },
            },
            visible: {
              hide: "सभी वस्तुओं को छुपाएं",
              show: "सभी वस्तुएँ दिखाएँ",
            },
            lock: "सभी वस्तुओं को लॉक करें",
            unlock: "सभी वस्तुओं को अनलॉक करें",
            andrewsPitchforkChannel: "एंड्रयूज पिचफोर्क़",
            equidistantChannel: "समान दूरी चैनल",
            regressionChannel: "Regression चैनल",
            stdDevChannel: "StdDev चैनल",
            fibonacciRetracement: "फिबोनैकी रिट्रेसमेंट",
            gannFan: "गान फैन",
            gannGrid: "गान ग्रिड",
            gannLine: "गान रेखा",
            arrowLine: "एरोड रेखा ",
            crossLine: "क्रॉस लाइन",
            extendedLine: "विस्तारित रेखा",
            horizontalRay: "क्षैतिज किरण",
            horizontalLine: "क्षैतिज रेखा",
            infoLine: "जानकारी रेखा",
            rayLine: "किरण",
            trendAngle: "कोण से रूझान",
            trendline: "ट्रेन्डलाइन",
            verticalLine: "ऊर्ध्वाधर रेखा",
            disjointAngle: "असंबद्ध चैनल",
            flatTopBottom: "फ्लैट टॉप/बॉटम",
            rectangle: "आयत",
            circle: "घेरा",
            triangle: "त्रिकोण",
            ellipse: "दीर्घवृत्त",
            text: "पाठ",
            rulerLine: "रूलर लाइन",
          },
          period: {
            full: {
              D1: "प्रतिदिन",
              H1: "1 घंटा",
              H4: "4 घंटे",
              M1: "1 मिनट",
              M15: "15 मिनट्स",
              M30: "30 मिनट्स",
              M5: "5 मिनट्स",
              MN: "प्रतिमास",
              Unknown: "अज्ञात",
              W1: "साप्ताहिक",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "अज्ञात",
              W1: "W1",
            },
          },
          screenshot: "चार्ट को छवि के रूप में सहेजें",
          symbolSpecs: {
            GTCmode: "GTC प्रणाली",
            calculation: "गणना",
            chartMode: "चार्ट मोड",
            contractSize: "कॉन्ट्रैक्ट आकार",
            days: {
              friday: "शुक्रवार",
              monday: "सोमवार",
              saturday: "शनिवार",
              sunday: "रविवार",
              thursday: "बृहस्पतिवार",
              tuesday: "मंगलवार",
              wednesday: "बुधवार",
            },
            digits: "अंक",
            empty: "कोई प्रतीक नहीं चुना गया",
            execution: "निष्पादन",
            expiration: "समयसीमा समाप्ति",
            filling: "पूर्ति नीति",
            initial: "प्रारंभिक",
            maintenance: "रखरखाव",
            marginCurrency: "मार्जिन मुद्रा",
            marginRate: "मार्जिन दर",
            maxVolume: "अधिकतम वॉल्यूम",
            minVolume: "न्यूनतम वॉल्यूम",
            orders: "आदेश",
            profitCurrency: "लाभ मुद्रा",
            schedule: { quotes: "भाव", trade: "ट्रेड" },
            sector: "क्षेत्र",
            spread: "स्प्रेड",
            stopsLevel: "स्टॉप के स्तर",
            swapLong: "स्वैप लॉन्ग",
            swapShort: "स्वैप शॉर्ट",
            swapType: "स्वैप प्रकार",
            title: "{symbol}अनुबंध विनिर्देश",
            tradeMode: "ट्रेड",
            volumeStep: "वॉल्यूम चरण",
            volumeLimit: "आयतन सीमा",
            tickSize: "टिक आकार",
            tickValue: "टिक मूल्य",
            marginInitial: "आरंभिक मार्जिन",
            marginHedged: "हेज किया गया मार्जिन",
            commission: {
              daily: {
                volume: "लॉट में दैनिक मात्रा",
                turnoverVolume: "लॉट में दैनिक टर्नओवर",
                turnoverMoney: "राशि में दैनिक टर्नओवर",
                value: "डील का दैनिक मूल्य",
                profit: "दैनिक लाभ",
              },
              monthly: {
                volume: "लॉट में मासिक मात्रा",
                turnoverVolume: "लॉट में मासिक टर्नओवर",
                turnoverMoney: "राशि में मासिक टर्नओवर",
                value: "डील का मासिक मूल्य",
                profit: "मासिक लाभ",
              },
              instant: {
                volume: "डील मात्रा द्वारा तत्काल",
                value: "डील मूल्य द्वारा तत्काल",
                profit: "डील लाभ से तत्काल",
              },
              entry: {
                in: "डील में",
                out: "डील से बाहर",
                all: "सौदों में/सौदों से बाहर",
              },
              tier: {
                mode: {
                  pips: "अंक",
                  percent: "% में {currency}",
                  percentProfit: "% लाभ का {currency}",
                },
                type: { perDeal: "प्रति सौदा", perLot: "प्रति लॉट" },
              },
              header: "कमीशन",
            },
          },
          tree: {
            close: "बंद",
            empty: "आपके पास चार्ट पर कोई वस्तु नहीं है",
            lock: "लॉक करें",
            remove: "हटाये",
            settings: "सेटिंग",
            title: "रेखाचित्र प्रबंधित करें",
            unlock: "अनलॉक करें",
          },
          types: {
            area: "क्षेत्र",
            line: "लाइन",
            bars: "बार",
            candlestick: "कैंडल्सस्टिक",
          },
          volumeTypes: {
            tickVolumes: "टिक वॉल्यूम",
            volumes: "वॉल्यूम",
            withoutVolumes: "वॉल्यूम के बिना",
            realVolumes: "वास्तविक वॉल्यूम",
          },
          zoom: { in: "ज़ूम इन ", out: "ज़ूम आउट" },
          hotkeys: {
            arrowLine: "एरोड रेखा ",
            chartTypeArea: "एरिया चार्ट",
            chartTypeLine: "लाइन चार्ट",
            chartTypeBar: "बार चार्ट",
            chartTypeCandle: "कैंडल चार्ट",
            crossLine: "क्रॉस लाइन",
            extendedLine: "विस्तारित रेखा",
            horizontalLine: "क्षैतिज रेखा",
            infoLine: "जानकारी रेखा",
            rayLine: "किरण",
            realVolumes: "वास्तविक मात्रा",
            tickVolumes: "टिक वॉल्यूम",
            trendline: "ट्रेन्डलाइन",
            verticalLine: "ऊर्ध्वाधर रेखा",
            sections: {
              chartType: "चार्ट प्रकार",
              drawing: "रेखाचित्र",
              volume: "वॉल्यूम",
            },
            crosshairRuler: "क्रॉसहायर रूलर",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "अपने अकाउंट के साथ शुरू करें",
            newAccountOpened: "नया अकाउंट ओपन हुआ",
          },
          brokerInformation: {
            company: "कंपनी",
            email: "ईमेल",
            phone: "फोन",
            registrationAddress: "पंजीकरण पता",
            title: "कंपनी की जानकारी",
            website: "वेबसाइट",
          },
          changePassword: {
            btnChange: "पासवर्ड बदलें",
            confirmPassword: "पासवर्ड की पुष्टि करें",
            newPassword: "नया पासवर्ड",
            title: "पासवर्ड बदलें",
          },
          connect: {
            btnConnect: "अकाउंट से कनेक्ट करें",
            contactBroker: "संपर्क कंपनी",
            forgotPassword: "पासवर्ड भूल गए?",
            loginPlaceholder: "लॉगिन दर्ज करें",
            passwordPlaceholder: "पासवर्ड दर्ज करें",
            savePassword: "पासवर्ड सेव करें",
            title: "अकाउंट से कनेक्ट करें",
          },
          copyToClipboard: {
            copy: "क्लिपबोर्ड पर कॉपी करें",
            unsupported: "कॉपी करना समर्थित नहीं है",
          },
          demo: {
            accountOpeningWarning:
              "एक अकाउंट खोलकर, आप अकाउंट खोलने की शर्तों और {brokerName} की डेटा सुरक्षा नीति से सहमत होते हैं",
            btnOpenDemo: "डेमो अकाउंट खोलें",
            title: "डेमो अकाउंट खोलें",
            tradeWithRealMoney:
              "वास्तविक धन के साथ ट्रेड करने के लिए, आपको एक वित्तीय सेवा कंपनी के साथ एक अलग समझौता करना होगा।",
          },
          disclaimer: {
            btnAccept: "स्वीकार करें",
            headerTitle: "MetaTrader 5 में आपका स्वागत है",
            text: 'MetaQuotes Ltd एक सॉफ्टवेयर डेवलपमेंट कंपनी है और कोई वित्तीय, निवेश, ब्रोकरेज, ट्रेडिंग या डेटा फीड सेवाएं प्रदान नहीं करती है, न ही यह किसी ट्रेडिंग ऑपरेशन से संबंधित कमीशन-आधारित भुगतान में शामिल होती है।<br /><br />स्वीकार करें बटन दबाकर मैं <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">EULA के नियमों और शर्तों</a>, <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">गोपनीयता नीति</a> और अस्वीकरण से सहमत हूँ।<br /><br /> एप्लिकेशन में उपलब्ध कोई भी जानकारी निवेश सलाह के रूप में नहीं है। ट्रेडिंग के लिए इस एप्लिकेशन का उपयोग करने से पहले, आपको एक योग्य और पंजीकृत प्रतिभूति पेशेवर की सलाह लेनी चाहिए और अपनी ओर उचित जांच करनी चाहिए।',
            title: "अस्वीकरण",
          },
          errors: {
            error: "त्रुटि",
            invalidCode: "अमान्य कोड",
            invalidEmail: "अमान्य ईमेल",
            invalidPhone: "अमान्य फ़ोन",
            unknownError: "अज्ञात त्रुटि",
          },
          form: {
            accountType: "खाता प्ररूप",
            address: "पता",
            addressPlaceholder: "अपना पता दर्ज करें",
            annualDeposit: "वार्षिक जमा राशि",
            annualIncome: "वार्षिक आय",
            broker: "कंपनी",
            btn: {
              back: "पीछे",
              cancel: "रद्द करें",
              next: "आगे",
              openAccount: "अकाउंट खोलें",
              remove: "हटाये",
              signOut: "साइन आउट",
            },
            city: "शहर",
            cityPlaceholder: "अपना शहर दर्ज करें",
            country: "देश",
            dateBirth: "जन्म तिथि",
            deposit: "जमा",
            education: "शिक्षा",
            email: {
              address: "ईमेल",
              code: "ईमेल से कोड",
              placeholder: "ईमेल दर्ज करें",
              title: "ईमेल",
            },
            employement: "रोज़गार",
            forex: "फोरेक्स",
            futures: "फ्यूचर्स",
            gender: { female: "महिला", male: "पुरुष", title: "लिंग" },
            identity: "पहचान",
            imageOrPdfFile: "छवि या पीडीएफ फाइल",
            investor: "निवेशक",
            language: "भाषा",
            leverage: "लेवरेज",
            login: "लॉगिन",
            min5chars: "न्यूनतम 5 वर्ण",
            name: {
              middle: "नाम के बीच का अक्षर",
              surname: "उपनाम",
              title: "नाम",
              yourName: "आपका नाम",
            },
            nationality: "राष्ट्रीयता",
            netWorth: "शुद्ध मूल्य",
            optional: "वैकल्पिक",
            password: "पासवर्ड",
            passwordReadOnly: "केवल पढ़ें पासवर्ड",
            phone: {
              mobile: "मोबाइल फ़ोन",
              number: "फ़ोन नंबर",
              sms: "SMS से कोड",
            },
            pleaseSelect: "कृपया चयन करें",
            policyCheckbox:
              "मैं खाता खोलने और डेटा संरक्षण नीति के नियमों और शर्तों के साथ सहमत हूँ",
            server: "सर्वर",
            side: { back: "पिछला भाग", front: "अगला भाग" },
            sourceWealth: "संपत्ति का स्रोत",
            state: "स्थिति",
            status: "स्थिति",
            stocks: "स्टॉक्स",
            taxID: "टैक्स आईडी",
            type: "प्रकार",
            useHedge: "व्यापार में बचाव का प्रयोग करें",
            verificationCodes: {
              email: "हमने आपके ईमेल पर एक सत्यापन कोड भेजा है",
              phone: "हमने आपके फ़ोन पर एक सत्यापन कोड भेजा है",
              phoneEmail: "हमने आपके फ़ोन और ईमेल पर सत्यापन कोड भेज दिए हैं",
            },
            zipCode: "ज़िप कोड",
          },
          mainForm: {
            title: "ट्रेडिंग अकाउंट",
            titleWithName: "ट्रेडिंग खाते:{brokerName}",
          },
          otp: {
            disable2FA: "2FA/TOTP अक्षम करें",
            disable2FAAccount: "अकाउंट {login} के लिए 2FA/TOTP अक्षम करें",
            disableEnterCode:
              "2FA/TOTP को अक्षम करने के लिए, कृपया प्रमाणक द्वारा जनरेट किया गया अपना अकाउंट कोड दर्ज करें।",
            downloadApp:
              "कृपया अपने मोबाइल उपकरण पर Google Authenticator / Microsoft Authenticator / Authy ऐप डाउनलोड करें और QR कोड स्कैन करें:",
            enable2FA: "2FA/TOTP सक्षम करें",
            enable2FAAccount: "अकाउंट {login} के लिए 2FA/TOTP सक्षम करें",
            enterCode:
              "प्रमाणीकरणकर्ता कार्रवाई की जाँच करने के लिए, ऐप द्वारा उत्पन्न अपना खाता कोड दर्ज करें।",
            oneTimePassword: "वन टाइम पासवर्ड:",
            placeholder: "अकाउंट OTP दर्ज करें",
            required: "अतिरिक्त खाता सुरक्षा के लिए 2FA प्रमाणीकरण आवश्यक है।",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "बैंक विवरण",
              utilityBill: "जनोपयोगी सेवा बिल",
            },
            conditionsForUploadingFiles: {
              documents:
                "कुछ प्रकार के दस्तावेज़ों के लिए दो फ़ोटो की आवश्यकता होती है: आगे और पीछे का भाग",
              proofAddress:
                "पते के प्रमाण के रूप में मोबाइल सेवाओं के बिल स्वीकार नहीं किए जाते हैं",
              utilityBill:
                "यूटिलिटी बिल में आपका नाम और पता होना चाहिए और 3 महीने से अधिक पुराना नहीं होना चाहिए",
            },
            documentType: {
              driverLicense: "ड्राइविंग लइसेंस",
              idCard: "पहचान पत्र",
              passport: "पासपोर्ट",
              residencePermit: "निवास की अनुमति",
            },
            educationLevel: {
              bachelor: "स्नातक अथवा समतुल्य",
              highScholl: "हाई स्कूल",
              master: "मास्टर डिग्री अथवा समतुल्य",
              none: "कोई नहीं",
              other: "अन्य",
              phd: "पीएचडी अथवा समतुल्य",
            },
            employment: {
              employed: "रोजगार में",
              other: "अन्य",
              retired: "सेवानिवृत्त",
              selfEmployed: "व्यापारी या स्व-रोजगार",
              student: "छात्र",
              unemployed: "बेरोजगार",
            },
            experience: "वास्तविक ट्रेडिंग अनुभव:",
            experienceLevel: {
              above3: "> 3 वर्ष",
              form1to3: "1 से 3 वर्ष",
              less1: "< 1 वर्ष",
            },
            industry: {
              agriculture: "कृषि",
              communication: "कला, आडियो/वीडियो टेक्नोलॉजी तथा कम्यूनिकेशन",
              construction: "आर्किटेक्चर एवं विनिर्माण",
              education: "शिक्षा",
              engineering: "इंजीनियरिंग एवं गणित",
              government: "सरकार एवं लोक प्रशासन",
              healthcare: "स्वास्‍थ्‍य देखभाल",
              it: "सूचना प्रौद्योगिकी",
              management: "व्यवसाय प्रबंधन तथा प्रशासन",
              manufacturing: "मैनुफैक्चरिंग",
              marketing: "मार्केटिंग एवं सेल्स",
              none: "कोई नहीं",
              other: "अन्य",
              science: "विज्ञान एवं प्रौद्योगिकी",
              security: "विधिक, जन संरक्षा, सुधार और सुरक्षा",
              tourism: "आतिथ्य एवं पर्यटन",
              transport: "परिवहन, संवितरण एवं लॉजिस्टिक्स",
            },
            policy:
              "ट्रेड अकाउंट ओपन करने के लिए व्यक्तिगत विवरण का उपयोग किया जाता है, जो किसी थर्ड पार्टी को पास नहीं किया जाता। जानकारी को सुरक्षित और गोपनीय रखा जाता है।",
            takePhoto:
              "कृपया, अपने दस्तावेज़ों की फ़ोटो लें और उन्हें बिना किसी संपादन के यहाँ अपलोड करें",
            title: "रियल अकाउंट खोलें",
            wealthSource: {
              employment: "रोजगार",
              inheritance: "उपहार अथवा विरासत",
              other: "अन्य",
              savings: "बचत अथवा निवेश",
            },
          },
          saveAccountData: "कृपया अपना लॉगिन और पासवर्ड सुरक्षित स्थान पर रखें",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "बंद",
            empty: "हमारे पास इस प्रतीक के लिए वॉल्यूम डेटा मौजूद नहीं है",
            extendedBook: {
              hide: "एक्सटेंडेड बुक छुपाएं",
              show: "एक्सटेंडेड बुक दिखाएं",
            },
            menu: {
              amount: "लॉट्स की जगह राशि",
              extended: "विस्तृत",
              spread: "स्प्रेड",
            },
            spread: { hide: "स्प्रेड छुपाएं", show: "स्प्रेड दिखाएँ" },
            stopLoss: "स्टॉप लॉस",
            takeProfit: "प्रॉफिट लें",
            title: "डेप्थ ऑफ़ मार्किट(बाजार की गहराई)",
          },
          errors: {
            accepted: "स्वीकृत",
            allowedOnlyLongPositions: "केवल लंबी पॉजिशन की ही अनुमति है",
            allowedOnlyPositionsClosing:
              "केवल पॉजिशन क्‍लोजिंग की ही अनुमति है",
            allowedOnlyShortPositions: "केवल छोटी पॉजिशन की ही अनुमति है",
            automatedTradingDisabledClient:
              "ग्राहक टर्मिनल पर स्वचालित ट्रेडिंग अक्षम की गई",
            automatedTradingDisabledServer:
              "सर्वर साइड पर स्वचालित ट्रेडिंग अक्षम की गई",
            canceled: "रद्द किया गया",
            common: "साधारण त्रुटि",
            demoAllocationDisabled: "डेमो अकाउंट आवंटन अक्षम है",
            done: "किया हुआ",
            donePartially: "आंशिक रूप से हुआ",
            frequentRequests: "अत्यधिक अनुरोध",
            invalidExpiration: "अमान्य समयसीमा समाप्ति",
            invalidOrderType: "अमान्य ऑर्डर प्रकार",
            invalidParameters: "अमान्य पैरामीटर",
            invalidPrices: "अमान्य भाव",
            invalidSLTP: "अमान्य S/L या T/P ",
            invalidVolume: "अमान्य वॉल्यूम",
            manyTradeRequests: "बहुत अधिक ट्रेड अनुरोध",
            marketClosed: "बाजार बंद",
            modificationFailed:
              "संशोधन विफल रहा क्योंकि ऑर्डर बाज़ार भाव के समीप है.",
            networkProblem: "नेटवर्क समस्या",
            noConnection: "कोई कनेक्शन नहीं",
            notEnoughMoney: "पर्याप्त राशि नहीं",
            offQuotes: "भाव से बाहर",
            ok: "ठीक है",
            onTheWay: "रास्ते में",
            orderChanged: "आदेश पहले ही बदला जा चूका है",
            orderClosePositionExists:
              "इस स्थिति को बंद करने के लिए आदेश पहले से ही मौजूद है",
            ordersLimitReached: "आदेश संख्या सीमा पहुंच गई",
            permissions: "पर्याप्त अनुमति नहीं",
            placed: "रखा गया",
            positionCloseProhibitedByFIFO: "FIFO नियम से निषिद्ध पोजीशन",
            positionClosed: "पोजीशन पहले ही बंद की गई",
            positionsLimitReached: "पोजीशन के अंत तक पहुँच",
            priceChanged: "भाव बदलाव",
            prices: "भाव",
            processed: "संसाधित हो चुका है",
            rejected: "अस्वीकृत किया गया",
            requestRejectedOrderWillCanceled: "अनुरोध अस्वीकृत, आदेश रद्द",
            requoted: "पुन भाव",
            serverProblem: "सर्वर तकनीकी समस्या",
            timeout: "समय समाप्त",
            tradeDisabled: "ट्रेड अक्षम है",
            unsupportedFillingMode: "असमर्थित पूर्ती प्रणाली ",
            volumeLimitReached: "वॉल्यूम सीमा पहुंच गई",
          },
          form: {
            acceptNewQuotes: "क्या आपको ये नए भाव स्वीकार हैं?",
            btnOpen: {
              hide: "ट्रेड फॉर्म छुपाएं",
              show: "ट्रेड फॉर्म दिखाएं",
              title: "नया आदेश",
            },
            buttons: {
              accept: "स्वीकार करें",
              delete: "मिटायें",
              modify: "संशोधित करें",
              ok: "ठीक है",
              placeOrder: "आर्डर करें",
              reject: "अस्वीकृत",
              request: "अनुरोध",
              requestPrice: "मूल्य का अनुरोध करें",
            },
            close: "बंद",
            execution: {
              fillOrKill: "पूर्ति करें या रद्द करें",
              immediateOrCancel: "तत्काल या रद्द",
              bookOrCancel: "बुक करें या रद्द करें",
              label: "नीति भरें",
              return: "वापस लौटें",
            },
            executionMode: {
              exchange: "एक्सचेंज निष्पादन",
              instant: "तात्कालिक निष्पादन",
              market: "बाजार निष्पादन",
              request: "अनुरोध निष्पादन",
            },
            expiration: {
              date: "समाप्ति तिथि",
              label: "समयसीमा समाप्ति",
              types: {
                specified: "निर्दिष्ट",
                specifiedDay: "निर्दिष्ट दिन",
                today: "आज",
              },
            },
            fields: {
              closeBy: "पास में",
              comment: "टिप्पणी",
              price: "भाव",
              stopLoss: "स्टॉप लॉस",
              takeProfit: "प्रॉफिट लें",
              volume: "वॉल्यूम",
              errors: {
                volume: {
                  min: "न्यूनतम मात्रा है {min}",
                  max: "अधिकतम मात्रा है {max}",
                  required: "Volume is required",
                  step: "इन चरण के साथ वॉल्यूम सेट किया जा सकता है {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "इतिहास",
            deals: {
              columns: {
                comment: "टिप्पणी",
                commission: "कमीशन",
                direction: "दिशा निर्देश",
                fee: "शुल्क",
                order: "आदेश",
                price: "भाव",
                profit: "लाभ",
                swap: "स्वैप",
                symbol: "प्रतीक",
                ticket: "टिकट",
                time: "समय",
                type: "प्रकार",
                volume: "वॉल्यूम",
              },
            },
            empty: "आपके पास अभी तक कोई ट्रेडिंग इतिहास नहीं है",
            menu: {
              columns: {
                horizontalScroll: "क्षैतिज स्क्रॉल",
                resetAll: "सभी रीसेट करें",
                title: "कॉलम",
              },
              deals: "सौदे",
              orders: "आदेश",
              period: {
                all: "पूरा इतिहास",
                last3Months: "पिछले 3 महीने",
                last6months: "पिछले 6 महीने",
                lastMonth: "पिछले महीने",
                title: "अवधि",
                customPeriod: "कस्टम अवधि",
                lastYear: "पिछले वर्ष",
                lastWeek: "पिछले सप्ताह",
                today: "आज",
              },
              positions: "पोजीशन",
              chart: "चार्ट",
              newOrder: "नया आदेश",
            },
            orders: {
              columns: {
                comment: "टिप्पणी",
                price: "भाव",
                slDescription: "स्टॉप लॉस",
                state: "स्थिति",
                symbol: "प्रतीक",
                ticket: "टिकट",
                timeDone: "समय",
                timeSetup: "समय",
                tpDescription: "प्रॉफिट लें",
                type: "प्रकार",
                volume: "वॉल्यूम",
                timeSetupDescription: "खुलने का समय",
                timeDoneDescription: "बंद होने का समय",
              },
              total: {
                title: "कुल",
                filled: "भर दिया गया",
                canceled: "रद्द हो गया",
                rejected: "अस्वीकृत",
              },
            },
            positions: {
              columns: {
                commission: "कमीशन",
                fee: "शुल्क",
                priceClose: "भाव",
                priceCloseDescription: "मूल्य बंद",
                priceOpen: "भाव",
                priceOpenDescription: "मूल्य खुला",
                profit: "लाभ",
                slDescription: "स्टॉप लॉस",
                swap: "स्वैप",
                symbol: "प्रतीक",
                ticket: "टिकट",
                timeClose: "समय",
                timeCloseDescription: "बंद होने का समय",
                timeOpen: "समय",
                timeOpenDescription: "खुलने का समय",
                tpDescription: "प्रॉफिट लें",
                type: "प्रकार",
                volume: "वॉल्यूम",
                comment: "टिप्पणी",
              },
            },
            columns: { default: "डिफ़ॉल्ट रूप से" },
            total: {
              profit: "लाभ",
              credit: "क्रेडिट",
              deposit: "डिपॉजिट",
              withdrawal: "निकासी",
              balance: "बैलेंस",
              commission: "कमीशन",
              fee: "शुल्क",
              swap: "स्वैप",
              grossProfit: "सकल लाभ",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "ट्रेड इतिहास",
                orders: "ट्रेड आर्डर",
                position: "ट्रेड पोजीशन",
                sltp: "SL/TP स्तर",
              },
              notification: "ट्रेड अधिसूचना",
            },
            oneClick: "एक क्लिक ट्रेडिंग",
            tags: { demo: "डेमो", readonly: "केवल पढ़ने के लिए" },
            oneClickBottom: "सबसे नीचे वन क्लिक पैनल",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "मैं इन नियमों और शर्तों को स्वीकार करता हूं",
            btnAccept: "स्वीकार करें",
            btnCancel: "रद्द करें",
            text: 'आप वन क्लिक ट्रेडिंग मोड को सक्रिय करने वाले हैं। नीचे दिए गए "मैं इन नियमों और शर्तों को स्वीकार करता हूँ" पर क्लिक करके, आप स्वीकार करते हैं कि आपने निम्नलिखित नियमों और शर्तों को पढ़ और समझ लिया है, और आप इनका पालन करने के लिए सहमत हैं।<br /><br />आप अपने वेब टर्मिनल के मेनू से वन क्लिक ट्रेडिंग मोड को सक्रिय या निष्क्रिय कर सकते हैं।<br /><br />ऑर्डर जमा करने के लिए वन क्लिक ट्रेडिंग मोड एक-चरणीय प्रक्रिया है। आपका ऑर्डर तब सबमिट किया जाएगा जब आप: - चार्ट के वन क्लिक ट्रेडिंग पैनल पर या तो बोली (SELL) या पूछें (BUY) बटन टैप करते हैं - मार्केट विंडो के डेप्थ में बटनों को बेचना, बंद करना, खरीदना या ऑर्डर करना टैप करते हैं - बंद करें ट्रेड टैब में ऑर्डर पोजीशन या डिलीट करते हैं<br /><br />आपके द्वारा क्लिक करने के लिए बाद में पुष्टि का कोई संकेत नहीं होगा। एक बार क्लिक करने के बाद आप अपना ऑर्डर वापस लेने या बदलने में सक्षम नहीं होंगे। सामान्य बाजार स्थितियों और प्रणाली के प्रदर्शन के तहत, एक मार्केट आर्डर जमा करने के बाद तुरंत भर दिया जाएगा और आप बाध्यकारी लेनदेन में प्रवेश करेंगे।<br /><br />आप वन क्लिक ट्रेडिंग मोड के उपयोग से जुड़े सभी जोखिमों को स्वीकार करने के लिए सहमत हैं, जिसमें बिना किसी सीमा के, ऐसे ऑर्डर सबमिट करने में हुई त्रुटियों, चूक या गलतियों का जोखिम शामिल है।<br /><br />आप किसी भी या सभी नुकसानों, लागतों और खर्चों से पूरी तरह से क्षतिपूर्ति से {companyName}से हानिरहित रखने के लिए सहमत हैं, जो आपके या आपकी ओर से ट्रेड करने वाले किसी अन्य व्यक्ति द्वारा ऐसी किसी भी त्रुटि, चूक या गलतियों के परिणामस्वरूप हो सकते हैं।',
            title: "वन क्लिक ट्रेडिंग - अस्वीकरण",
          },
          quickTrade: {
            hide: "वन क्लिक ट्रेडिंग पैनल छुपाएं",
            show: "वन क्लिक ट्रेडिंग पैनल दिखाएं",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "मैं ऊपर दिए गए बयान के बारे में जानता हूं और मैं उच्च जोखिम वाले निवेश उत्पादों में ट्रेड करने की इच्छा रखता हूं",
            btnAccept: "स्वीकार करें",
            btnCancel: "रद्द करें",
            text: "हम आपको सूचित करना चाहते हैं कि आगे इस ट्रेडिंग प्लेटफॉर्म का उपयोग करने से आपको लीवरेज्ड उच्च जोखिम वाले निवेश उत्पादों तक पहुंच प्राप्त होगी, जो आपकी पसंद के वित्तीय संस्थान द्वारा प्रदान किया जाता है। ऐसे उत्पादों में निवेश करना सभी निवेशकों के लिए उपयुक्त नहीं हो सकता है, क्योंकि इसमें जमा राशि का एक हिस्सा या पूरी जमा राशि खोने का जोखिम शामिल होता है।<br /><br />उच्च जोखिम वाले निवेश उत्पादों का ट्रेड करने का निर्णय लेने से पहले आपको अपने निवेश उद्देश्यों, अनुभव के स्तर और स्वीकार्य जोखिम पर सावधानीपूर्वक विचार करना चाहिए। संभावना यह है कि आप अपने शुरुआती निवेश से अधिक नुकसान उठा सकते हैं और इसलिए आपको उतने पैसे का निवेश नहीं करना चाहिए जिसे आप खोना वहन नहीं कर सकते।<br /><br />हम आपको उन सभी जोखिम कारकों के बारे में अपने ज्ञान को बढ़ाने के लिए आमंत्रित करते हैं जो संबंधित हैं इन उत्पादों में निवेश करें, और यदि आपको कोई संदेह हो तो किसी पेशेवर वित्तीय सलाहकार से सलाह लें।",
            title: "उच्च जोखिम निवेश चेतावनी",
          },
          table: {
            btnOpen: "ट्रेड",
            columns: {
              comment: "टिप्पणी",
              priceClose: "भाव",
              priceCloseDescription: "बंद मूल्य",
              priceOpen: "भाव",
              priceOpenDescription: "खुलने का मूल्य",
              profit: "लाभ",
              slDescription: "स्टॉप लॉस",
              swap: "स्वैप",
              symbol: "प्रतीक",
              ticket: "टिकट",
              time: "समय",
              tpDescription: "प्रॉफिट लें",
              type: "प्रकार",
              volume: "वॉल्यूम",
            },
            emptyPlug: {
              btnNewOrder: "नया आर्डर बनाएँ",
              title: "आपके पास कोई पोजीशन नहीं है",
            },
            menu: {
              chart: "चार्ट",
              closePosition: "पोजीशन बंद करें",
              columns: "कॉलम",
              modifyOrder: "आदेश संशोधित करें",
              modifyPosition: "पोजीशन संशोधित करें",
              newOrder: "नया आदेश",
              resetAll: "सभी रीसेट करें",
              deleteOrder: "आदेश मिटायें",
            },
            oneClick: { deleteOrder: "मिटायें" },
            sections: {
              collateralPositions: "कलैटरल पोजीशन",
              orders: "आदेश",
              positions: "पोजीशन",
            },
            total: {
              assets: "संपत्ति",
              balance: "शेष बकाया",
              collateral: "सहायक",
              commission: "कमीशन",
              credit: "क्रेडिट",
              equity: "निष्पक्षता",
              liabilities: "देयताएं",
              margin: "मार्जिन",
              marginFree: "मुक्त मार्जिन",
              marginLevel: "स्तर",
            },
          },
          timer: {
            marketWillOpen: "मार्केट खुलने में शेष समय {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} दिन",
            oneDay: "{numberOfDays} दिन",
          },
          tradeIsDisabled: {
            account: "इस अकाउंट के लिए ट्रेडिंग सर्वर पर अक्षम है",
            collateral: "ट्रेड उपलब्ध नहीं है, क्योंकि यह प्रतीक कलैटरल है",
            disabled: "ट्रेड अक्षम है",
            investor:
              "ट्रेडिंग उपलब्ध नहीं है, क्योंकि आप एक निवेशक पासवर्ड से जुड़े हुए हैं",
            readOnly:
              "ट्रेडिंग उपलब्ध नहीं है, क्योंकि आपने जोखिम की चेतावनी को स्वीकार नहीं किया है",
            symbol: "इस प्रतीक के लिए ट्रेड अक्षम है",
          },
          hotkeys: {
            historyPanel: "इतिहास पैनल",
            journalPanel: "रोजनामचा",
            marketWatch: "बाज़ार देखें",
            quickTrade: "एक क्लिक ट्रेडिंग",
            tradeForm: "नया आदेश",
            tradePanel: "ट्रेड पैनल",
          },
          marketOpen: {
            time: "मार्केट बंद है - खुलने का समय {time}",
            afterSeconds: "मार्केट बंद है - खुलने में शेष समय {time} सेकंड",
          },
          expiredTimer: { seconds: "समाप्त होने में शेष समय {time} सेकंड" },
          corporateLink: {
            type: {
              clientAgreement: "ग्राहक अनुबंध",
              riskDisclosure: "जोखिम प्रकटीकरण",
              fdmDisclaimer: "FDM अस्वीकरण",
              clientAgreementAndRiskDisclosure:
                "ग्राहक अनुबंध एवं जोखिम प्रकटीकरण",
              complaintsHandlingProcedure: "शिकायत निवारण प्रक्रिया",
              orderExecutionPolicy: "आर्डर एक्जीक्यूशन नीति",
              clientCategorisationNotice: "ग्राहक श्रेणीकरण नोटिस",
              conflictsOfInterestPolicy: "हितों के टकराव की नीति",
              dataProtectionPolicy: "डेटा संरक्षण नीति",
            },
          },
          margin: {
            floating: "फ्लोटिंग",
            mode: { marketBuy: "बाजार खरीद", marketSell: "बाजार बिक्री" },
            rangeMode: {
              value: "सांकेतिक मान",
              valuePerSymbol: "प्रति प्रतीक सांकेतिक मान",
              volume: "वॉल्यूम",
              volumePerSymbol: "प्रति प्रतीक वॉल्यूम",
            },
            showValue: "इसमें मान दिखाएँ {currency} प्रति लॉट",
            rates: "मार्जिन दर:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "पूर्ण स्क्रीन अक्षम करें",
            enable: "पूर्ण स्क्रीन सक्षम करें",
          },
          journal: {
            btnOpen: "रोजनामचा",
            columns: {
              message: "मेसेज / संदेश भेजें",
              source: "स्त्रोत",
              time: "समय",
            },
            menu: {
              clear: "साफ",
              debugMode: "डिबग मोड",
              exportFile: "फ़ाइल में एक्स्पोर्ट करें",
            },
          },
          menu: {
            about: "प्रोग्राम के बारे में",
            contact: "संपर्क करें",
            brokerInformation: "कंपनी की जानकारी",
            chartSettings: {
              controls: "चार्ट कंट्रोल",
              grid: "ग्रिड",
              ohlc: "ओएचएलसी(OHLC) दिखाएँ",
              title: "चार्ट सेटिंग",
              askPrice: "पूछें कीमत",
              crosshair: "क्रॉसहायर कर्सर",
            },
            connect: "अकाउंट से कनेक्ट करें",
            language: {
              title: "भाषा",
              search: "खोज",
              nothingFound: "भाषा नहीं मिली",
            },
            openDemo: "डेमो अकाउंट खोलें",
            openReal: "रियल अकाउंट खोलें",
            settings: "सेटिंग",
            shortcuts: "शॉर्टकट",
            theme: {
              blackWhite: "ब्लैक एंड वाइट",
              blueRed: "नीला और लाल",
              dark: "डार्क थीम",
              editor: "थीम संपादक",
              greenRed: "हरा और लाल",
              light: "लाइट थीम",
              neutral: "तटस्थ",
              templates: "कलर टेम्पलेट्स",
            },
            title: "मेन्यू",
            tradingAccount: "ट्रेडिंग अकाउंट",
            terms: "नियम एवं शर्तें",
            desktopPlatforms: "डेस्कटॉप प्लेटफॉर्म",
            qrCode: {
              install: "{store} से इंस्टॉल करने के लिए स्कैन करें",
              downloadApk: "Android APK फ़ाइल के लिए स्कैन करें",
            },
            economicCalendar: "आर्थिक कैलेंडर",
          },
          screen: { back: "पीछे" },
          mobile: { bottomNav: { quotes: "भाव" } },
          hotkeys: {
            sections: { navigation: "नेविगेशन", view: "अवलोकन करें" },
            escape: "रद्द करें",
            indicators: "सूचक/इंडीकेटर्स",
            depthOfMarket: "डेप्थ ऑफ़ मार्किट(बाजार की गहराई)",
            objectTreePanel: "ऑब्जेक्ट ट्री",
            scrollRight: "अगला कैंडल",
            scrollToStart: "शुरू करने के लिए चार्ट स्क्रॉल करें",
            scrollLeft: "पिछला कैंडल",
            scrollToEnd: "चार्ट को अंत तक स्क्रॉल करें",
            resetChartView: "चार्ट रीसेट करें",
            zoomIn: "ज़ूम इन ",
            zoomOut: "ज़ूम आउट",
            fullScreen: "फुल स्क्रीन",
            screenshot: "चार्ट को छवि के रूप में सहेजें",
            title: "शॉर्टकट",
          },
          timezone: {
            title: "समय क्षेत्र",
            city: {
              cairo: "काहिरा",
              casablanca: "कैसाब्लांका",
              johannesburg: "जोहानसबर्ग",
              lagos: "लागोस",
              nairobi: "नैरोबी",
              tunis: "ट्यूनिस",
              anchorage: "लंगर गाह",
              bogota: "बोगोटा",
              buenosAires: "ब्यूनस आयर्स",
              caracas: "कराकास",
              chicago: "शिकागो",
              denver: "डेनवर",
              elSalvador: "अल साल्वाडोर",
              juneau: "जूनो",
              lima: "लीमा",
              losAngeles: "लॉस एंजिल्स",
              mexicoCity: "मेक्सिको सिटी",
              newYork: "न्यूयॉर्क",
              phoenix: "अचंभा",
              santiago: "सेंटियागो",
              saoPaulo: "साओ पाउलो",
              toronto: "टोरंटो",
              vancouver: "वैंकूवर",
              almaty: "अल्माटी",
              ashgabat: "अश्गाबात",
              bahrain: "बहरीन",
              bangkok: "बैंकाक",
              kolkata: "कोलकाता",
              colombo: "कोलंबो",
              dhaka: "ढाका",
              dubai: "दुबई",
              hongKong: "हांगकांग",
              jakarta: "जकार्ता",
              jerusalem: "यरूशलेम",
              karachi: "कराची",
              kathmandu: "काठमांडू",
              kuwait: "कुवैट",
              manila: "मनीला",
              muscat: "मस्कट",
              nicosia: "निकोसिया",
              qatar: "कतर",
              rangoon: "रंगून",
              riyadh: "रियाद",
              saigon: "Saigon",
              seoul: "सोल",
              shanghai: "शंघाई",
              singapore: "सिंगापुर",
              taipei: "ताइपे",
              tehran: "तेहरान",
              tokyo: "टोक्यो",
              reykjavik: "रिक्जेविक",
              adelaide: "एडीलेड",
              brisbane: "ब्रिस्बेन",
              perth: "पर्थ",
              sydney: "सिडनी",
              amsterdam: "एम्स्टर्डम",
              athens: "एथेंस",
              belgrade: "बेलग्रेड",
              berlin: "बर्लिन",
              bratislava: "ब्रैटिस्लावा",
              brussels: "ब्रसेल्स",
              bucharest: "बुकुरेस्टी",
              budapest: "बुडापेस्ट",
              copenhagen: "कोपेनहेगन",
              dublin: "डबलिन",
              helsinki: "हेलसिंकी",
              istanbul: "इस्तांबुल",
              lisbon: "लिस्बन",
              london: "लंडन",
              luxembourg: "लक्समबर्ग",
              madrid: "मैड्रिड",
              malta: "माल्टा",
              moscow: "मास्को",
              oslo: "ओस्लो",
              paris: "पेरिस",
              prague: "प्राहा",
              riga: "रीगा",
              rome: "रोम",
              stockholm: "स्टॉकहोम",
              tallinn: "तेलिन",
              vienna: "वियना",
              vilnius: "विनियस",
              warsaw: "वारसा",
              zurich: "ज्यूरिक",
              auckland: "ऑकलैंड",
              chatham: "चैथम",
              fakaofo: "फ़ाकाओफ़ो",
              honolulu: "होनोलूलू",
              norfolk: "नॉरफ़ॉक",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e as h };
