const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Lähennä",
            zoomOut: "Loitonna",
          },
          crosshair: "Kohdistusristikko ",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Lisää indikaattori",
            btnOpenPopup: "Add Indicator",
            close: "Sulje",
            form: {
              applyTo: "Sovella seuraavaan",
              background: {
                title: "Tausta",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Poikkeama",
              enterDistance: "Jakso",
              enterShift: "Vaihdos",
              fastEma: "Nopea EMA",
              slowEma: "Hidas EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Maksimi",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Yksinkertainen ",
                smoothed: "Smoothed",
                title: "Metodi",
              },
              opacity: "Opacity",
              period: {
                jaws: "Leuka kausi",
                lips: "Huulet kausi",
                teeth: "Hampaat kausi",
                title: "Jakso",
                dPercent: "%D ajanjakso",
                kPercent: "%K ajanjakso",
              },
              selectApplyTo: "Valitse",
              selectVolumesType: "Select volume type",
              shift: "Vaihdos",
              showTimeframes: "Näytä kaikissa aikakehyksissä",
              slowing: "Hidastus",
              step: "Vaihe",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Tyyli",
                up: "Up style",
                rvi: "RVI style",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Volyymi",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Hinta",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Haku",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Kaikki",
              billWilliams: "Bill Williams",
              oscillators: "Oskillaattorit",
              trend: "Suuntaus",
              volumes: "Volyymi",
            },
            title: "Select indicator",
            up: "Ylös",
            down: "Alas",
            chartControls: {
              show: "Näytä",
              hide: "Piilottaa",
              settings: "Asetukset",
              remove: "Poista",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Päätöshinta",
              dailyChange: "Päivittäinen muutos",
              openPrice: "Avaushinta",
              spread: "Hajonta",
              symbol: "Symboli",
              time: "Aika",
              high: "Korkea",
              low: "Matala",
              last: "Viimeinen",
              lastHigh: "Viimeinen, korkea",
              lastLow: "Viimeinen, matala",
              highLow: "High/Low",
              bidLow: "Tarjous, matala",
              bidHigh: "Tarjous, korkea",
              askHigh: "Pyyntö, korkea",
              askLow: "Pyyntö, matala",
              bid: "Tarjous",
              ask: "Pyyntö",
              title: "Sarakkeet",
            },
            menu: {
              chart: "Kaavio",
              columns: "Pylväät",
              dom: "Markkinan Syvyys",
              hide: "Piilottaa",
              newOrder: "Uusi Tilaus",
              specification: "Määrittely",
            },
            search: "Haku",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Nuolet",
              showAlways: "Show always",
              angle: "Angle",
              distance: "Distance",
              bar: "Bar",
              price: "Hinta",
              prices: "Hinnat",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Näytä kaikissa aikakehyksissä",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Tekstisi",
              props: "Ominaisuudet",
              style: "Tyyli",
              rays: "Rays",
              background: "Tausta",
              extends: "Extension",
              extended: "laajennettu",
              pipsPerBar: "Pips per baari",
              gannAngle: "Gann-kulma",
              deviations: "Poikkeamat",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Päivitys", cancel: "Peruuta" },
              tabs: {
                style: "Tyyli",
                coordinates: "Coordinates",
                visualization: "Visualisointi",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Vasen",
                right: "Oikea",
                center: "Keski",
                top: "Yläosa",
                middle: "Middle",
                bottom: "Alaosa",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Fibonacci Haarukka",
            equidistantChannel: "Equidistant Kanava",
            regressionChannel: "Regressio Kanava",
            stdDevChannel: "Keskihajonta Kanava",
            fibonacciRetracement: "Fibonacci Käänne",
            gannFan: "Gann Fan",
            gannGrid: "Gann Ristikko",
            gannLine: "Gann Linja",
            arrowLine: "Nuoliviiva",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Vaakasuora viiva",
            infoLine: "Info Line",
            rayLine: "Säde",
            trendAngle: "Trendi kulman mukaan",
            trendline: "Trendiviiva",
            verticalLine: "Pystysuora Line",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Suorakulmio",
            circle: "Circle",
            triangle: "Kolmio",
            ellipse: "Ellipsi",
            text: "Teksti",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "Päivittäin",
              H1: "1 tunti",
              H4: "4 tuntia",
              M1: "1 minuutti",
              M15: "15 minuuttia",
              M30: "30 minuuttia",
              M5: "5 minuuttia",
              MN: "Kuukausittain",
              Unknown: "Unknown",
              W1: "Viikoittain",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "GTC-tila",
            calculation: "Laskelma",
            chartMode: "Kaavio-muoto",
            contractSize: "Sopimus koko",
            days: {
              friday: "perjantai",
              monday: "maanantai",
              saturday: "lauantai",
              sunday: "sunnuntai",
              thursday: "torstai",
              tuesday: "tiistai",
              wednesday: "keskiviikko",
            },
            digits: "Numerot",
            empty: "No symbol selected",
            execution: "Suoritus",
            expiration: "Päättymispäivä",
            filling: "Täyttö",
            initial: "perus",
            maintenance: "Ylläpito",
            marginCurrency: "Marginaali valuutta",
            marginRate: "Marginaali kurssi",
            maxVolume: "Maksimaalinen volyymi",
            minVolume: "Minimi volyymi",
            orders: "Tilaukset ",
            profitCurrency: "Voitto valuutta",
            schedule: { quotes: "Hintatarjoukset", trade: "Kauppa" },
            sector: "Sektori",
            spread: "Hajonta",
            stopsLevel: "Pysäytys taso",
            swapLong: "Swap-pitkä",
            swapShort: "Swap-lyhyt",
            swapType: "Swap-tyyppi",
            title: "{symbol} contract specification",
            tradeMode: "Kauppa",
            volumeStep: "Volyymi askel",
            volumeLimit: "Volyymi raja",
            tickSize: "Rasti koko",
            tickValue: "Rasti arvo",
            marginInitial: "Alkumarginaali",
            marginHedged: "Suojattu marginaali",
            commission: {
              daily: {
                volume: "Päivittäinen erien määrä",
                turnoverVolume: "Päivittäinen liikevaihto erissä",
                turnoverMoney: "Päivittäinen liikevaihto rahana",
                value: "Kauppojen päivittäinen arvo",
                profit: "Päivittäinen tuotto",
              },
              monthly: {
                volume: "Kuukausittainen erien määrä",
                turnoverVolume: "Kuukausittainen liikevaihto erissä",
                turnoverMoney: "Kuukausittainen liikevaihto rahana",
                value: "Kauppojen kuukausittainen arvo",
                profit: "Kuukausittainen tuotto",
              },
              instant: {
                volume: "Välitön palkkio kauppamäärän perusteella",
                value: "Välitön palkkio kaupan arvon perusteella",
                profit: "Välitön palkkio kaupan tuoton perusteella",
              },
              entry: {
                in: "sisään kaupat",
                out: "ulos kaupat",
                all: "sisään/ulos kaupat",
              },
              tier: {
                mode: {
                  pips: "pistettä",
                  percent: "% sisään {currency}",
                  percentProfit: "% tuottoa {currency}",
                },
                type: { perDeal: "per kauppa", perLot: "per erä" },
              },
              header: "Palkkiot",
            },
          },
          tree: {
            close: "Sulje",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Poista",
            settings: "Asetukset",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Pylväät",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Rasti volyymit",
            volumes: "Volyymi",
            withoutVolumes: "Without Volumes",
            realVolumes: "Todelliset volyymit",
          },
          zoom: { in: "Lähennä", out: "Loitonna" },
          hotkeys: {
            arrowLine: "Nuoliviiva",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Viivakaavio",
            chartTypeBar: "Pylväskaavio",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Vaakasuora viiva",
            infoLine: "Info Line",
            rayLine: "Säde",
            realVolumes: "Real Volumes",
            tickVolumes: "Rasti volyymit",
            trendline: "Trendiviiva",
            verticalLine: "Pystysuora Line",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Volyymi",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Uusi tili avattu",
          },
          brokerInformation: {
            company: "Yhtiö",
            email: "Sähköposti",
            phone: "Puhelin",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Vaihda salasana",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Vaihda salasana",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Tallenna salasana",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Hyväksy",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "Vastuuvapauslauseke",
          },
          errors: {
            error: "Virhe",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Tilityyppi",
            address: "Osoite",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Vuotuinen talletus",
            annualIncome: "Vuositulot",
            broker: "Yhtiö",
            btn: {
              back: "Takaisin",
              cancel: "Peruuta",
              next: "Seuraava",
              openAccount: "Open Account",
              remove: "Poista",
              signOut: "Sign out",
            },
            city: "Kaupunki",
            cityPlaceholder: "Enter your city",
            country: "Maa",
            dateBirth: "Syntymäaika",
            deposit: "Talletus",
            education: "Education",
            email: {
              address: "Sähköposti",
              code: "Code from email",
              placeholder: "Enter email",
              title: "Sähköposti",
            },
            employement: "Employement",
            forex: "Forex",
            futures: "Futuurit",
            gender: { female: "Nainen", male: "Mies", title: "Sukupuoli" },
            identity: "Henkilöllisyys",
            imageOrPdfFile: "Image or PDF file",
            investor: "Sijoittaja",
            language: "Kieli",
            leverage: "Vipuvoima",
            login: "Kirjaudu sisään",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Nimi",
              yourName: "Your Name",
            },
            nationality: "Kansallisuus",
            netWorth: "Nettovarallisuus",
            optional: "Optional",
            password: "Salasana",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Hyväksyn tilin avaamisen ja tietosuojan käyttöehdot",
            server: "Palvelin",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Omaisuuden lähde",
            state: "Tila",
            status: "Tila",
            stocks: "Osakkeet",
            taxID: "Verotunnus",
            type: "Tyyppi",
            useHedge: "Käytä hedge-suojausta kaupankäynnissä",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "Poista 2FA/TOTP käytöstä",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "Ota 2FA/TOTP käyttöön",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Tarkastaaksesi Autenthicatorin toiminnan, syötä sovelluksen luoma tilikoodi.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "Kaksivaiheista tunnistautumista vaaditaan tilin lisäsuojaamiseen.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: { bankStatement: "Tiliote", utilityBill: "Lasku" },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Ajokortti",
              idCard: "Henkilökortti",
              passport: "Passi",
              residencePermit: "Oleskelulupa",
            },
            educationLevel: {
              bachelor: "Kandidaatin tutkinto tai vastaava",
              highScholl: "Lukio",
              master: "Maisterin tutkinto tai vastaava",
              none: "Ei ole",
              other: "Muu",
              phd: "PHD tai vastaava",
            },
            employment: {
              employed: "Työllistetty",
              other: "Muu",
              retired: "eläkkeellä",
              selfEmployed:
                "Yrityksen omistaja tai itsenäinen ammatinharjoittaja",
              student: "Opiskelija",
              unemployed: "Työtön",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "> 3 vuotta",
              form1to3: "1 - 3 vuotta",
              less1: "< 1 vuosi",
            },
            industry: {
              agriculture: "Maatalous-, elintarvike- ja Luonnonvarat",
              communication: "Taide, audio/videotekniikka ja viestintä",
              construction: "Arkkitehtuuri ja rakennus",
              education: "Koulutus",
              engineering: "insinööripalvelut ja matematiikka",
              government: "Hallitus ja julkinen hallinto",
              healthcare: "Terveydenhuolto",
              it: "Tietotekniikka",
              management: "Liikkeenjohto ja hallinto",
              manufacturing: "Teollisuus",
              marketing: "Markkinointi ja myynti",
              none: "Ei ole",
              other: "Muu",
              science: "Tiede ja teknologia",
              security: "Oikeudellinen, yleinen turvallisuus",
              tourism: "Vieraanvaraisuus ja matkailu",
              transport: "Kuljetus, jakelu ja logistiikka",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Työllisyyden tai liiketoiminnan tuotot",
              inheritance: "Lahjat tai perintö",
              other: "Muu",
              savings: "Säästöt tai sijoitukset",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Sulje",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Määrä erien sijasta",
              extended: "laajennettu",
              spread: "Hajonta",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Pysäytä tappio",
            takeProfit: "Ota voitto",
            title: "Markkinan Syvyys",
          },
          errors: {
            accepted: "Hyväksytty",
            allowedOnlyLongPositions: "Vain pitkät positiot ovat sallituja",
            allowedOnlyPositionsClosing: "Vain positioiden sulku on sallittu",
            allowedOnlyShortPositions: "Vain lyhyet positiot ovat sallittuja",
            automatedTradingDisabledClient:
              "Automaattinen kaupankäynti poistettu käytöstä asiakaspäätelaitteen puolella",
            automatedTradingDisabledServer:
              "Automaattinen kaupankäynti poistettu käytöstä palvelimen puolella",
            canceled: "Peruttu",
            common: "Yleinen virhe",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Valmis",
            donePartially: "Tehty osittain",
            frequentRequests: "Liian monta pyyntöä",
            invalidExpiration: "Virheellinen päättymisaika      ",
            invalidOrderType: "Virheellinen järjestys tyyppi",
            invalidParameters: "Kelvoton versio",
            invalidPrices: "Virheelliset hinnat",
            invalidSLTP: "Virheellinen S/L tai T/P",
            invalidVolume: "Virheellinen tilavuus",
            manyTradeRequests: "Liian monta kauppa pyyntöä",
            marketClosed: "Markkina suljettu",
            modificationFailed:
              "Muutos epäonnistui koska tilaus tai asema on liian lähellä markkina tilaa.",
            networkProblem: "verkko-virhe",
            noConnection: "Ei yhteyttä",
            notEnoughMoney: "Ei tarpeeksi rahaa",
            offQuotes: "Poisto kurssit",
            ok: "OK",
            onTheWay: "Tulossa",
            orderChanged: "Tilausta on jo muokattu",
            orderClosePositionExists:
              "Tilaus suljetaan koska positio on jo varattu",
            ordersLimitReached: "Tilauksen raja saavutettu",
            permissions: "Ei riittävät käyttöoikeudet",
            placed: "Sijoitettu",
            positionCloseProhibitedByFIFO:
              "Position sulku kielletty FIFO-säännöllä",
            positionClosed: "Positio/Sijoitus on jo suljettu",
            positionsLimitReached: "Positio määräraja saavutettu",
            priceChanged: "Hinta muuttunut",
            prices: "Hinnat",
            processed: "Käsitelty",
            rejected: "Hylätty",
            requestRejectedOrderWillCanceled:
              "Pyyntö hylättiin, tilaus peruutettiin",
            requoted: "Uusi hintatarjous",
            serverProblem: "Palvelimen tekninen virhe",
            timeout: "Timeout",
            tradeDisabled: "Kauppa on poistettu käytöstä",
            unsupportedFillingMode: "Ei tuettu täyttö tila",
            volumeLimitReached: "Volyymin raja saavutettu",
          },
          form: {
            acceptNewQuotes: "Hyväksytkö nämä uudet hintatarjoukset?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Uusi Tilaus",
            },
            buttons: {
              accept: "Hyväksy",
              delete: "Poista",
              modify: "Muokkaa",
              ok: "OK",
              placeOrder: "Place order",
              reject: "Hylkää",
              request: "Pyyntö",
              requestPrice: "Request Price",
            },
            close: "Sulje",
            execution: {
              fillOrKill: "Täytä tai tapa",
              immediateOrCancel: "Välitön tai Peruuta ",
              bookOrCancel: "Kirjaa tai peruuta",
              label: "Täyttö käytäntö",
              return: "Palautus",
            },
            executionMode: {
              exchange: "Vaihto toteutus",
              instant: "Pika toteutus",
              market: "Markkina toteutus",
              request: "Pyyntö toteutu",
            },
            expiration: {
              date: "Expiration Date",
              label: "Päättymispäivä",
              types: {
                specified: "Määritetty",
                specifiedDay: "Specified Day",
                today: "Tänään",
              },
            },
            fields: {
              closeBy: "Close by",
              comment: "Kommentti",
              price: "Hinta",
              stopLoss: "Pysäytä tappio",
              takeProfit: "Ota voitto",
              volume: "Volyymi",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Historia",
            deals: {
              columns: {
                comment: "Kommentti",
                commission: "Palkkio",
                direction: "Suunta",
                fee: "Palkkio",
                order: "Tilaus",
                price: "Hinta",
                profit: "Voitto",
                swap: "Swap",
                symbol: "Symboli",
                ticket: "Lippu ",
                time: "Aika",
                type: "Tyyppi",
                volume: "Volyymi",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Pylväät",
              },
              deals: "Kaupat",
              orders: "Tilaukset ",
              period: {
                all: "Kaikki historia",
                last3Months: "Viime 3 kuukautta",
                last6months: "Viime 6 kuukautta",
                lastMonth: "Viime kuukausi",
                title: "Jakso",
                customPeriod: "Mukautettu ajanjakso",
                lastYear: "Viime vuosi",
                lastWeek: "Viime viikko",
                today: "Tänään",
              },
              positions: "Position",
              chart: "Kaavio",
              newOrder: "Uusi Tilaus",
            },
            orders: {
              columns: {
                comment: "Kommentti",
                price: "Hinta",
                slDescription: "Pysäytä tappio",
                state: "Tila",
                symbol: "Symboli",
                ticket: "Lippu ",
                timeDone: "Aika",
                timeSetup: "Aika",
                tpDescription: "Ota voitto",
                type: "Tyyppi",
                volume: "Volyymi",
                timeSetupDescription: "Aukioloaika",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Kaikki yhteensä",
                filled: "Täytetty",
                canceled: "Peruttu",
                rejected: "Hylätty",
              },
            },
            positions: {
              columns: {
                commission: "Palkkio",
                fee: "Palkkio",
                priceClose: "Hinta",
                priceCloseDescription: "Sulku-hinta",
                priceOpen: "Hinta",
                priceOpenDescription: "Avaushinta",
                profit: "Voitto",
                slDescription: "Pysäytä tappio",
                swap: "Swap",
                symbol: "Symboli",
                ticket: "Lippu ",
                timeClose: "Aika",
                timeCloseDescription: "Close Time",
                timeOpen: "Aika",
                timeOpenDescription: "Aukioloaika",
                tpDescription: "Ota voitto",
                type: "Tyyppi",
                volume: "Volyymi",
                comment: "Kommentti",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Voitto",
              credit: "Luotto",
              deposit: "Talletus",
              withdrawal: "Nosto",
              balance: "Saldo",
              commission: "Provisio",
              fee: "Palkkio",
              swap: "Vaihto",
              grossProfit: "Bruttovoitto",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Kaupankäyntihistoria",
                orders: "Trade Orders",
                position: "Trade Positions",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Yhden Napsautuksen Kauppa",
            tags: { demo: "Demo", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Hyväksyn nämä ehdot",
            btnAccept: "Hyväksy",
            btnCancel: "Peruuta",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Olen tietoinen edellä esitetystä ja haluan käydä kauppaa korkean riskin sijoitustuotteilla",
            btnAccept: "Hyväksy",
            btnCancel: "Peruuta",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Korkean riskin investointi varoitus",
          },
          table: {
            btnOpen: "Kauppa",
            columns: {
              comment: "Kommentti",
              priceClose: "Hinta",
              priceCloseDescription: "Päätöshinta",
              priceOpen: "Hinta",
              priceOpenDescription: "Avaushinta",
              profit: "Voitto",
              slDescription: "Pysäytä tappio",
              swap: "Swap",
              symbol: "Symboli",
              ticket: "Lippu ",
              time: "Aika",
              tpDescription: "Ota voitto",
              type: "Tyyppi",
              volume: "Volyymi",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Kaavio",
              closePosition: "Suljettu Positio",
              columns: "Pylväät",
              modifyOrder: "Muokkaa tilaus",
              modifyPosition: "Muokkaa Positio",
              newOrder: "Uusi Tilaus",
              resetAll: "Reset all",
              deleteOrder: "Poista tilaus",
            },
            oneClick: { deleteOrder: "Poista" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Tilaukset ",
              positions: "Position",
            },
            total: {
              assets: "Varat",
              balance: "Vaaka",
              collateral: "Lisävakuus",
              commission: "Palkkio",
              credit: "Luotto",
              equity: "Oma pääoma",
              liabilities: "Velat",
              margin: "Marginaali",
              marginFree: "Vapaa marginaali",
              marginLevel: "Taso",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Lehti",
            marketWatch: "Markkinaseuranta",
            quickTrade: "Yhden Napsautuksen Kauppa",
            tradeForm: "Uusi Tilaus",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Asiakassopimus",
              riskDisclosure: "Riskien julkistaminen",
              fdmDisclaimer: "FDM vastuunvapauslauseke",
              clientAgreementAndRiskDisclosure:
                "Asiakassopimus ja riskien julkistaminen",
              complaintsHandlingProcedure: "Valitusten käsittely",
              orderExecutionPolicy: "Tilauksen toteuttamiskäytäntö",
              clientCategorisationNotice: "Asiakasluokitusta koskeva ilmoitus",
              conflictsOfInterestPolicy: "Eturistiriidat",
              dataProtectionPolicy: "Tietosuojakäytäntö",
            },
          },
          margin: {
            floating: "kelluva",
            mode: { marketBuy: "Markkinaosto", marketSell: "Markkinamyynti" },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Poista Koko Näyttö",
            enable: "Mahdollista koko näytöllä",
          },
          journal: {
            btnOpen: "Lehti",
            columns: { message: "Viesti", source: "Lähde", time: "Aika" },
            menu: {
              clear: "Tyhjennä",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Ruudukko",
              ohlc: "Näytä OHLC",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Kieli",
              search: "Haku",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Asetukset",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Käyttöehdot",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Economic Calendar",
          },
          screen: { back: "Takaisin" },
          mobile: { bottomNav: { quotes: "Hintatarjoukset" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Näkymä" },
            escape: "Peruuta",
            indicators: "Indikaattorit",
            depthOfMarket: "Markkinan Syvyys",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Lähennä",
            zoomOut: "Loitonna",
            fullScreen: "Full Screen",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, a as b, i as c, e as f };
