const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Томруулах",
            zoomOut: "Жижигрүүлэх",
          },
          crosshair: "Утсан хэрээс",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Индикатор нэмэх",
            btnOpenPopup: "Add Indicator",
            close: "Хаах",
            form: {
              applyTo: "Ашиглах",
              background: {
                title: "Арын хэсэг",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Хазайлт",
              enterDistance: "Цагийн хүрээ",
              enterShift: "Шилжих",
              fastEma: "Хурдан EMA",
              slowEma: "Удаан EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Хамгийн их",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Энгийн",
                smoothed: "Smoothed",
                title: "Аргачлал",
              },
              opacity: "Opacity",
              period: {
                jaws: "Эрүүний хугацаа",
                lips: "Уруулын хугацаа",
                teeth: "Шүдний хугацаа",
                title: "Цагийн хүрээ",
                dPercent: "%D хамрах хугацаа",
                kPercent: "%K хамрах хугацаа",
              },
              selectApplyTo: "Сонгох",
              selectVolumesType: "Select volume type",
              shift: "Шилжих",
              showTimeframes: "Бүх хугацааны хамрах хүрээ дээр харуулах",
              slowing: "Удаашруулж байна",
              step: "Алхам",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Хэлбэр",
                up: "Up style",
                rvi: "RVI хэлбэр",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Хэмжээ",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Үнэ",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Хайлт",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Бүгд",
              billWilliams: "Билл Уильямс",
              oscillators: "Хэлбэлзэгч",
              trend: "Хандлага",
              volumes: "Хэмжээ",
            },
            title: "Select indicator",
            up: "Дээшээ",
            down: "Доошоо",
            chartControls: {
              show: "Харуулах",
              hide: "Нуух",
              settings: "Тохиргоо",
              remove: "Арилгах",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Хаалтын Ханш",
              dailyChange: "Өдөр тутмын өөрчлөлт",
              openPrice: "Нээлтийн Ханш",
              spread: "Тархац",
              symbol: "Шинж тэмдэг",
              time: "Хугацаа",
              high: "Дээд",
              low: "Доод",
              last: "Сүүлийн ханш",
              lastHigh: "Сүүлийн Дээд ханш",
              lastLow: "Сүүлийн Доод ханш",
              highLow: "Дээд/Доод",
              bidLow: "Авах Доод ханш",
              bidHigh: "Авах Дээд ханш",
              askHigh: "Зарах Дээд ханш",
              askLow: "Зарах Доод ханш",
              bid: "Авах ханш",
              ask: "Зарах ханш",
              title: "Баганууд",
            },
            menu: {
              chart: "Чарт",
              columns: "Баганууд",
              dom: "Маркетийн эрч",
              hide: "Нуух",
              newOrder: "Шинэ захиалга",
              specification: "Тодорхойлолт",
            },
            search: "Хайлт",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Сум",
              showAlways: "Show always",
              angle: "Єнцєг",
              distance: "Distance",
              bar: "Бар",
              price: "Үнэ",
              prices: "Үнэ",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Бүх хугацааны хамрах хүрээ дээр харуулах",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Таны текст",
              props: "Төлөв байдал",
              style: "Хэлбэр",
              rays: "Rays",
              background: "Арын хэсэг",
              extends: "Extension",
              extended: "Өргөтгөсөн",
              pipsPerBar: "Пип (бар тутамд)",
              gannAngle: "Ганнийн өнцөг",
              deviations: "Хазайлтууд",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Шинэчлэх", cancel: "Цуцлах" },
              tabs: {
                style: "Хэлбэр",
                coordinates: "Coordinates",
                visualization: "Дүрслэл",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Зүүн",
                right: "Баруун",
                center: "Гол",
                top: "Таг",
                middle: "Middle",
                bottom: "Доод",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Эндрюгийн Сэрээ",
            equidistantChannel: "Ижил Хэмжээтэй Зам",
            regressionChannel: "Регрессийн Суваг",
            stdDevChannel: "Стандарт Хазайлтын Суваг",
            fibonacciRetracement: "Фибоначчийн Буцалт",
            gannFan: "Ганнийн Дэвүүр",
            gannGrid: "Ганнийн Координат",
            gannLine: "Ганнийн Шулуун",
            arrowLine: "Сумтай Шулуун",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Хэвтээ шугам",
            infoLine: "Info Line",
            rayLine: "Туяа",
            trendAngle: "Өнцөгт Хандлагын Шулуун",
            trendline: "Хандлагын шугам",
            verticalLine: "Босоо шугам",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Тэгш Єнцєгт",
            circle: "Circle",
            triangle: "Гурвалжин",
            ellipse: "Эллипс",
            text: "Текст",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "Өдөр бүр",
              H1: "1 цаг",
              H4: "4 цаг",
              M1: "1 минут",
              M15: "15 минут",
              M30: "30 минут",
              M5: "5 минут",
              MN: "Сар бүр",
              Unknown: "Unknown",
              W1: "Долоо хоног бүр",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "GTC горим",
            calculation: "Тооцоолол",
            chartMode: "Хүснэгтэн горим",
            contractSize: "Гэрээний хэмжээ",
            days: {
              friday: "Баасан",
              monday: "Даваа",
              saturday: "Бямба",
              sunday: "Ням",
              thursday: "Пүрэв",
              tuesday: "Мягмар",
              wednesday: "Лхагва",
            },
            digits: "Орон",
            empty: "No symbol selected",
            execution: "Гүйцэтгэл",
            expiration: "Дуусах Хугацаа",
            filling: "Бөглөлт",
            initial: "Эхний",
            maintenance: "Үйлчиилгээ",
            marginCurrency: "Унацийн валют",
            marginRate: "Унацын түвшин",
            maxVolume: "Хамгийн их хэмжээ",
            minVolume: "Хамгийн бага хэмжээ",
            orders: "Захиалга",
            profitCurrency: "Ашгийн валют",
            schedule: { quotes: "Квот", trade: "Арилжаа" },
            sector: "Салбар",
            spread: "Тархац",
            stopsLevel: "Түвшнийг зогсоох",
            swapLong: "Своп урт",
            swapShort: "Своп богино",
            swapType: "Свопын төрөл",
            title: "{symbol} contract specification",
            tradeMode: "Арилжаа",
            volumeStep: "Хэмжээний алхам",
            volumeLimit: "Хэмжээний хязгаар",
            tickSize: "Тикийн хэмжээ",
            tickValue: "Тикийн үнэ",
            marginInitial: "Анхны маржин",
            marginHedged: "Хедж хийгдсэн маржин",
            commission: {
              daily: {
                volume: "Лотын өдрийн хэмжээ",
                turnoverVolume: "Өдөр тутмын эргэлтийн тоогоор",
                turnoverMoney: "Өдөр тутмын мөнгөний тоогоор",
                value: "Хэлэлцээрийн өдөр тутмын үнэ",
                profit: "Өдөр тутмын ашиг",
              },
              monthly: {
                volume: "Лотын сарын хэмжээ",
                turnoverVolume: "Сар тутмын эргэлтийн тоогоор",
                turnoverMoney: "Сар тутмын мөнгөний тоогоор",
                value: "Хэлэлцээрийн сар тутмын үнэ цэнэ",
                profit: "Сар тутмын ашиг",
              },
              instant: {
                volume: "Хэлэлцээрийн хэмжээгээр шууд",
                value: "Хэлэлцээрийн үнээр шууд",
                profit: "Хэлэлцээрийн шууд ашиг",
              },
              entry: {
                in: "орох гүйлгээний",
                out: "гарах гүйлгээний",
                all: "орох/гарах гүйлгээний",
              },
              tier: {
                mode: {
                  pips: "цэг",
                  percent: "% дотор {currency}",
                  percentProfit: "% ашгийн {currency}",
                },
                type: { perDeal: "худалдаа бүрт", perLot: "захиалга бүрт" },
              },
              header: "Шимтгэлүүд",
            },
          },
          tree: {
            close: "Хаах",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Арилгах",
            settings: "Тохиргоо",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Барууд",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Тикийн Хэмжээ",
            volumes: "Хэмжээ",
            withoutVolumes: "Without Volumes",
            realVolumes: "Бодит хэмжээнүүдийг ",
          },
          zoom: { in: "Томруулах", out: "Жижигрүүлэх" },
          hotkeys: {
            arrowLine: "Сумтай Шулуун",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Шулуун Чарт",
            chartTypeBar: "Бар Чарт",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Хэвтээ шугам",
            infoLine: "Info Line",
            rayLine: "Туяа",
            realVolumes: "Real Volumes",
            tickVolumes: "Тикийн Хэмжээ",
            trendline: "Хандлагын шугам",
            verticalLine: "Босоо шугам",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Хэмжээ",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Шинэ данс нээлээ",
          },
          brokerInformation: {
            company: "Компани",
            email: "Ц-Шуудан",
            phone: "Утас",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Нууц үг өөрчлөх",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Нууц үг өөрчлөх",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Нууц үг хадгалах",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Зөвшөөрөх",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "Татгалзал",
          },
          errors: {
            error: "Алдаа",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Дансны төрөл",
            address: "Хаяг",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Жилийн депозит",
            annualIncome: "Жилийн орлого",
            broker: "Компани",
            btn: {
              back: "Буцах",
              cancel: "Цуцлах",
              next: "Дараах",
              openAccount: "Open Account",
              remove: "Арилгах",
              signOut: "Sign out",
            },
            city: "Хот",
            cityPlaceholder: "Enter your city",
            country: "Улс",
            dateBirth: "Төрсөн огноо",
            deposit: "Депозит",
            education: "Education",
            email: {
              address: "Ц-Шуудан",
              code: "Code from email",
              placeholder: "Enter email",
              title: "Ц-Шуудан",
            },
            employement: "Employement",
            forex: "Форекс",
            futures: "Фьючерс",
            gender: { female: "Эмэгтэй", male: "Эрэгтэй", title: "Хүйс" },
            identity: "Тодорхойлолт",
            imageOrPdfFile: "Image or PDF file",
            investor: "Хөрөнгө оруулагч",
            language: "Хэл",
            leverage: "Хөшүүрэг",
            login: "Нэвтрэх",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Нэр",
              yourName: "Your Name",
            },
            nationality: "Үндэс угсаа",
            netWorth: "Цэвэр хөрөнгө",
            optional: "Optional",
            password: "Нууц үг",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Би данс нээх нөхцөл, шаардлага болон өгөгдөл хамгааллын бодлогыг зөвшөөрч байна",
            server: "Сервер",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Орлогын эх үүсвэр",
            state: "Төлөв",
            status: "Төлөв",
            stocks: "Хувьцаа",
            taxID: "Татварын ID",
            type: "Төрөл",
            useHedge: "Арилжаанд хедж ашиглах",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "2FA/TOTP идэвхгүй болгох",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "2FA/TOTP идэвхжүүлэх",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Authenticator-ийн ажиллагааг шалгахын тулд App-с үүсгэсэн бүртгэлийн кодоо оруулна уу.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "Бүртгэлийн нэмэлт аюулгүй байдлыг хангахын тулд 2FA баталгаажуулалт шаардлагатай.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Банкны хуулга",
              utilityBill: "Төлбөр тооцооны баримт",
            },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Жолооны үнэмлэх",
              idCard: "ID карт",
              passport: "Паспорт",
              residencePermit: "Оршин суух зөвшөөрлийн үнэмлэх",
            },
            educationLevel: {
              bachelor: "Бакалавр ба түүнтэй адил зэрэгтэй",
              highScholl: "Ахлах сургууль",
              master: "Магистр буюу түүнтэй адил зэрэгтэй",
              none: "Хоосон",
              other: "Бусад",
              phd: "Доктор буюу түүнтэй адил зэрэгтэй",
            },
            employment: {
              employed: "Ажил эрхэлж байгаа",
              other: "Бусад",
              retired: "Тэтгэвэрт гарсан",
              selfEmployed: "Бизнес эрхлэгч эсвэл хувиараа хөдөлмөр эрхлэгч",
              student: "Оюутан",
              unemployed: "Ажилгүй",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "> 3-с дээш жил",
              form1to3: "1-с 3 жил",
              less1: "< 1 жил",
            },
            industry: {
              agriculture: "Хүнс, хөдөө аж ахуй болон байгалийн нөөц",
              communication: "Урлаг, аудио/видео технологи, харилцаа холбоо",
              construction: "Барилга, архитектур",
              education: "Боловсрол ба сургалт",
              engineering: "Инженер, математик",
              government: "Засгийн газар, төрийн захиргааны байгууллага",
              healthcare: "Эрүүлийг хамгаалах",
              it: "Мэдээллийн технологи",
              management: "Захиргаа, бизнесийн удирдлага",
              manufacturing: "Үйлдвэрлэл",
              marketing: "Маркетинг болон борлуулалт",
              none: "Хоосон",
              other: "Бусад",
              science: "Шинжлэх ухаан, технологи",
              security: "Хууль эрх зүй, нийгмийн аюулгүй байдал",
              tourism: "Аялал жуулчлал",
              transport: "Тээвэрлэлт, түгээлт болон логистик",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Ажил эрхлэлт, бизнесийн орлого",
              inheritance: "Бэлэг эсвэл өв залгамжлал",
              other: "Бусад",
              savings: "Хадгаламж буюу хөрөнгө оруулалт",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Хаах",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Багцын оронд Дүн",
              extended: "Өргөтгөсөн",
              spread: "Тархац",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Стоп Лосс",
            takeProfit: "Тейк Профит",
            title: "Маркетийн эрч",
          },
          errors: {
            accepted: "Зөвшөөрөгдсөн",
            allowedOnlyLongPositions: "Зөвхөн урт байдал зөвшөөрөгдөнө",
            allowedOnlyPositionsClosing: "Зөвхөн позиц хаахыг зөвшөөрнө",
            allowedOnlyShortPositions:
              "Зөвхөн худалдан авах чиглэлтэй шорт позиц зөвшөөрнө",
            automatedTradingDisabledClient:
              "Клиентийн терминалд автомат арилжаааг хаасан байна",
            automatedTradingDisabledServer:
              "Сервер талд автомат арилжааг хаасан байна",
            canceled: "Цуцлагдсан",
            common: "Түгээмэл дутагдал",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Гүйцсэн",
            donePartially: "Хэсэгчлэн биелэгдсэн",
            frequentRequests: "Хэт олон удаагийн хүсэлтүүд",
            invalidExpiration: "Дуусах хугацаа буруу",
            invalidOrderType: "Захиалгын төрөл бруу",
            invalidParameters: "Хүчингүй параметрүүд",
            invalidPrices: "Хүчингүй үнэ",
            invalidSLTP: "Хүчингүй S/L эсвэл T/P",
            invalidVolume: "Хүчингүй хэмжээ",
            manyTradeRequests: "Хэт олон арилжаа хийх хүсэлтүүд",
            marketClosed: "Зах зээл хаагдсан",
            modificationFailed:
              "Позиц зах зээлийн ханштай ойр байгаа учир өөрчлөлт хийх боломжгүй",
            networkProblem: "Сүлжээний асуудал",
            noConnection: "Холболтгүй",
            notEnoughMoney: "Хангалтгүй мөнгө",
            offQuotes: "Хаалттай үнэ тогтоолт",
            ok: "OK",
            onTheWay: "Замдаа",
            orderChanged: "Захиалга аль хэдийн өөрчлөгдсөн байна",
            orderClosePositionExists:
              "Энэ байршилтай ойр захиалга аль хэдийн хийгдсэн байна",
            ordersLimitReached: "Захиалгын хязгаар гүйцсэн байна",
            permissions: "Эрхгүй байна",
            placed: "Байрласан",
            positionCloseProhibitedByFIFO:
              "FIFO-ийн дүрмээр хориглосон байрлалыг хаах",
            positionClosed: "Позиц аль хэдийн хаагдсан",
            positionsLimitReached: "Байршлын дээд хэмжээнд хүрлээ",
            priceChanged: "Үнэ өөрчлөгдсөн",
            prices: "Үнэ",
            processed: "Боловсруулагдсан",
            rejected: "Заазлагдсан",
            requestRejectedOrderWillCanceled:
              "Хүсэлт татгалзав, захиалга цуцлагдав",
            requoted: "Дахин үнэлэгдсэн",
            serverProblem: "Серверийн техникийн асуудал",
            timeout: "Завсарлага",
            tradeDisabled: "Арилжаа идэвхгүй байна",
            unsupportedFillingMode: "Дэмжигдээгүй дүүргэх горим",
            volumeLimitReached: "Хэмжээ хязгаартаа хүрсэн",
          },
          form: {
            acceptNewQuotes: "Та эдгээр шинэ үнийг зөвшөөрч байна уу?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Шинэ захиалга",
            },
            buttons: {
              accept: "Зөвшөөрөх",
              delete: "Устгах",
              modify: "Өөрчлөх",
              ok: "OK",
              placeOrder: "Place order",
              reject: "Татгалзах",
              request: "Хүсэлт",
              requestPrice: "Request Price",
            },
            close: "Хаах",
            execution: {
              fillOrKill: "Бөглөх эсвэл Устгах",
              immediateOrCancel: "Яаралтай эсвэл Цуцлах",
              bookOrCancel: "Захиалах эсвэл Цуцлах",
              label: "Дүүргэх бодлого",
              return: "Өгөөж",
            },
            executionMode: {
              exchange: "Биржийн Гүйцэтгэл",
              instant: "Шуурхай гүйцэтгэл",
              market: "Маркет гүйцэтгэл",
              request: "Хүсэлтийн гүйцэтгэл",
            },
            expiration: {
              date: "Expiration Date",
              label: "Дуусах Хугацаа",
              types: {
                specified: "Тодорхойлсон",
                specifiedDay: "Specified Day",
                today: "Єнєєдєр",
              },
            },
            fields: {
              closeBy: "Хаах",
              comment: "Санал хүсэлт",
              price: "Үнэ",
              stopLoss: "Стоп Лосс",
              takeProfit: "Тейк Профит",
              volume: "Хэмжээ",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Түүх",
            deals: {
              columns: {
                comment: "Санал хүсэлт",
                commission: "Шимтгэл",
                direction: "Чиглэл",
                fee: "Хураамж",
                order: "Захиалга",
                price: "Үнэ",
                profit: "Ашиг",
                swap: "Своп",
                symbol: "Шинж тэмдэг",
                ticket: "Тасалбар",
                time: "Хугацаа",
                type: "Төрөл",
                volume: "Хэмжээ",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Баганууд",
              },
              deals: "Арилжаа",
              orders: "Захиалга",
              period: {
                all: "Бүх түүх",
                last3Months: "Сүүлийн 3 сар",
                last6months: "Сүүлийн 6 сар",
                lastMonth: "Сүүлийн сар",
                title: "Цагийн хүрээ",
                customPeriod: "Дурын Хугацааны",
                lastYear: "Өнгөрсөн жил",
                lastWeek: "Өнгөрсөн долоо хоногт",
                today: "Өнөөдөр",
              },
              positions: "Позицууд",
              chart: "Чарт",
              newOrder: "Шинэ захиалга",
            },
            orders: {
              columns: {
                comment: "Санал хүсэлт",
                price: "Үнэ",
                slDescription: "Стоп Лосс",
                state: "Төлөв",
                symbol: "Шинж тэмдэг",
                ticket: "Тасалбар",
                timeDone: "Хугацаа",
                timeSetup: "Хугацаа",
                tpDescription: "Тейк Профит",
                type: "Төрөл",
                volume: "Хэмжээ",
                timeSetupDescription: "Нээсэн Цаг",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Нийт",
                filled: "Бөглөгдсөн",
                canceled: "Цуцлагдсан",
                rejected: "Заазлагдсан",
              },
            },
            positions: {
              columns: {
                commission: "Шимтгэл",
                fee: "Хураамж",
                priceClose: "Үнэ",
                priceCloseDescription: "Хаалтын Ханш",
                priceOpen: "Үнэ",
                priceOpenDescription: "Нээлтийн Ханш",
                profit: "Ашиг",
                slDescription: "Стоп Лосс",
                swap: "Своп",
                symbol: "Шинж тэмдэг",
                ticket: "Тасалбар",
                timeClose: "Хугацаа",
                timeCloseDescription: "Close Time",
                timeOpen: "Хугацаа",
                timeOpenDescription: "Нээсэн Цаг",
                tpDescription: "Тейк Профит",
                type: "Төрөл",
                volume: "Хэмжээ",
                comment: "Тайлбар",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Ашиг",
              credit: "Кредит",
              deposit: "Хадгаламж",
              withdrawal: "Татаж авах",
              balance: "Баланс",
              commission: "Шимтгэл",
              fee: "Хураамж",
              swap: "Своп",
              grossProfit: "Нийт Ашиг",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Арилжааны түүх",
                orders: "Trade Orders",
                position: "Арилжааны Позицууд",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Шууд хийх арилжаа",
            tags: { demo: "Демо", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Би эдгээр нөхцөл, болзлуудыг зөвшөөрч байна",
            btnAccept: "Зөвшөөрөх",
            btnCancel: "Цуцлах",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Би дээрх мэдэгдлийг ухамсарлаж байгаа бөгөөд өндөр эрсдэлтэй хөрөнгө оруулалтын бүтээгдэхүүнийг арилжаалахыг хүсэж байна",
            btnAccept: "Зөвшөөрөх",
            btnCancel: "Цуцлах",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Өндөр эрсдэлтэй хөрөнгө оруулалтын анхааруулга",
          },
          table: {
            btnOpen: "Арилжаа",
            columns: {
              comment: "Санал хүсэлт",
              priceClose: "Үнэ",
              priceCloseDescription: "Хаалтын Ханш",
              priceOpen: "Үнэ",
              priceOpenDescription: "Нээлтийн Ханш",
              profit: "Ашиг",
              slDescription: "Стоп Лосс",
              swap: "Своп",
              symbol: "Шинж тэмдэг",
              ticket: "Тасалбар",
              time: "Хугацаа",
              tpDescription: "Тейк Профит",
              type: "Төрөл",
              volume: "Хэмжээ",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Чарт",
              closePosition: "Позицыг Хаах",
              columns: "Баганууд",
              modifyOrder: "Захиалгыг өөрчлөх",
              modifyPosition: "Позиц Өөрчлөх",
              newOrder: "Шинэ захиалга",
              resetAll: "Reset all",
              deleteOrder: "Захиалгыг устгах",
            },
            oneClick: { deleteOrder: "Устгах" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Захиалга",
              positions: "Позицууд",
            },
            total: {
              assets: "Актив",
              balance: "Тэнцэл",
              collateral: "Колатерал",
              commission: "Шимтгэл",
              credit: "Кредит",
              equity: "Өмч",
              liabilities: "Өр төлбөр",
              margin: "Маржин",
              marginFree: "Сул Маржин",
              marginLevel: "Түвшин",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Сэтгүүл",
            marketWatch: "Маркет ажиглалт",
            quickTrade: "Шууд хийх арилжаа",
            tradeForm: "Шинэ захиалга",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Үйлчлүүлэгчийн гэрээ",
              riskDisclosure: "Эрсдлийн тодруулга",
              fdmDisclaimer: "FDM Хариуцлагаас татгалзах мэдэгдэл",
              clientAgreementAndRiskDisclosure:
                "Харилцагчийн гэрээ ба эрсдлийн тодруулга",
              complaintsHandlingProcedure: "Гомдол барагдуулах журам",
              orderExecutionPolicy: "Захиалгын гүйцэтгэлийн бодлого",
              clientCategorisationNotice: "Үйлчлүүлэгчийн ангиллын мэдэгдэл",
              conflictsOfInterestPolicy: "Сонирхлын бодлогын зөрчил",
              dataProtectionPolicy: "Өгөгдөл хамгааллын бодлого",
            },
          },
          margin: {
            floating: "хөвөгч",
            mode: { marketBuy: "Маркет buy", marketSell: "Маркет sell" },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Бүтэн дэлгэцийг идэвхгүй болгох",
            enable: "Бүтэн дэлгэцийг идэвхжүүлэх",
          },
          journal: {
            btnOpen: "Сэтгүүл",
            columns: { message: "Зурвас", source: "Сурвалж", time: "Хугацаа" },
            menu: {
              clear: "Цэвэрлэх",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Тор сүлжээ",
              ohlc: "OHLC-ыг харуулах",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Хэл",
              search: "Хайлт",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Тохиргоо",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Ерөнхий нөхцөл",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Эдийн засгийн календар",
          },
          screen: { back: "Буцах" },
          mobile: { bottomNav: { quotes: "Квот" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Харах" },
            escape: "Цуцлах",
            indicators: "Үзүүлэлтүүд",
            depthOfMarket: "Маркетийн эрч",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Томруулах",
            zoomOut: "Жижигрүүлэх",
            fullScreen: "Дэлгэц дvvрэн",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { o as a, t as b, a as c, e as m };
