const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Ereignisse des Kalenders auf dem Chart ausblenden",
              show: "Ereignisse des Kalenders auf dem Chart anzeigen",
            },
          },
          controls: {
            reset: "Chart zurücksetzen",
            scrollEnd: "Zum Ende scrollen",
            scrollLeft: "Nach links scrollen",
            scrollRight: "Nach rechts scrollen",
            zoomIn: "Vergrößern",
            zoomOut: "Verkleinern",
          },
          crosshair: "Fadenkreuz",
          delay: "{delay} min verzögert",
          indicators: {
            btnAddIndicator: "Indikator hinzufügen ",
            btnOpenPopup: "Indikator hinzufügen",
            close: "Schließen",
            form: {
              applyTo: "Anwenden auf",
              background: {
                title: "Hintergrund",
                down: "Hintergrund für fallenden Kumo",
                up: "Hintergrund für steigenden Kumo",
              },
              deviation: "Abweichung",
              enterDistance: "Periode",
              enterShift: "Versatz",
              fastEma: "Schnelle EMA",
              slowEma: "Langsame EMA",
              line: {
                base: "Basislinie",
                down: "Abwärtslinie",
                minusDI: "-DI-Linie",
                null: "Nulllinie",
                plusDI: "+DI-Linie",
                style: "Linienart",
                cci: "CCI-Line",
                up: "Aufwärtslinie",
                fi: "FI-Linie",
              },
              maximum: "Maximum",
              method: {
                exponential: "Exponentiell",
                linearWeighted: "Linear gewichtet",
                simple: "Einfach",
                smoothed: "Geglättet",
                title: "Methode",
              },
              opacity: "Deckkraft",
              period: {
                jaws: "Jaws Periode",
                lips: "Lips Periode",
                teeth: "Teeth Periode",
                title: "Periode",
                dPercent: "%D Periode",
                kPercent: "%K Periode",
              },
              selectApplyTo: "Auswählen",
              selectVolumesType: "Volumentyp auswählen",
              shift: "Versatz",
              showTimeframes: "In allen Zeitrahmen anzeigen",
              slowing: "Verlangsamung",
              step: "Schritt",
              style: {
                down: "Abwärtsstil",
                jaws: "Jaws-Stil",
                lips: "Lips-Stil",
                main: "Hauptlinie",
                signal: "Signallinie",
                teeth: "Teeth-Stil",
                title: "Stil",
                up: "Aufwärtsstil",
                rvi: "RVI Stil",
              },
              volume: { down: "Abwärtsvolumen", up: "Auswärtsvolumen" },
              volumes: "Volumen",
              mfiUp: "MFI steigt",
              mfiDown: "MFI fällt",
              price: {
                title: "Preis",
                select: "Preis wählen",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "Keine Elemente gefunden",
              title: "Suche",
              tryAnother: "Bitte versuchen Sie eine andere Abfrage",
            },
            tabs: {
              all: "Alles",
              billWilliams: "Bill Williams",
              oscillators: "Oszillatoren",
              trend: "Trend",
              volumes: "Volumen",
            },
            title: "Indikator wählen",
            up: "Nach oben",
            down: "nach unten",
            chartControls: {
              show: "Anzeigen",
              hide: "Verbergen",
              settings: "Einstellungen",
              remove: "Löschen",
            },
          },
          loading: "Lade",
          marketWatch: {
            btnOpen: {
              hide: "Market Watch ausblenden",
              show: "Market Watch anzeigen",
            },
            columns: {
              closePrice: "Schlusskurs",
              dailyChange: "Tägliche Änderungen",
              openPrice: "Eröffnungspreis",
              spread: "Spread",
              symbol: "Symbol",
              time: "Zeit",
              high: "Hoch",
              low: "Tief",
              last: "Letzter Preis",
              lastHigh: "Letztes Hoch",
              lastLow: "Letztes Tief",
              highLow: "Hoch/Tief",
              bidLow: "Bid Tief",
              bidHigh: "Bid Hoch",
              askHigh: "Ask Hoch",
              askLow: "Ask Tief",
              bid: "Bid",
              ask: "Ask",
              title: "Spalten",
            },
            menu: {
              chart: "Chart",
              columns: "Spalten",
              dom: "Markttiefe",
              hide: "Verbergen",
              newOrder: "Neue Order",
              specification: "Kontraktspezifikation",
            },
            search: "Suche",
            searchSymbol: "Symbol suchen",
            nothingFound: "Keine Symbole gefunden",
          },
          objects: {
            form: {
              statistics: "Statistiken",
              arrows: "Pfeile",
              showAlways: "Immer anzeigen",
              angle: "Winkel",
              distance: "Abstand",
              bar: "Kerze",
              price: "Preis",
              prices: "Preise",
              showPrice: "Preis anzeigen",
              showText: "Text anzeigen",
              showDate: "Zeitpunkt anzeigen",
              showTime: "Zeit anzeigen",
              showAllTimeframes: "In allen Zeitrahmen anzeigen",
              showPearsonR: "Pearsons R anzeigen",
              showLabels: "Kennung anzeigen",
              yourText: "Ihr Text",
              props: "Eigenschaften",
              style: "Stil",
              rays: "Strahlen",
              background: "Hintergrund",
              extends: "Erweitern",
              extended: "Erweitert",
              pipsPerBar: "Pips pro Balken",
              gannAngle: "Gann-Winkel",
              deviations: "Abweichungen",
              labels: "Kennungen",
              reverse: "Umkehren",
              btn: { update: "Aktualisieren", cancel: "Abbrechen" },
              tabs: {
                style: "Stil",
                coordinates: "Koordinaten",
                visualization: "Visualisierung",
              },
              range: {
                price: "Preisspanne",
                bars: "Balkenspanne",
                date: "Zeitspanne",
              },
              align: {
                horizontal: "Horizontale ausrichten",
                vertical: "Verrtikal ausrichten",
                left: "Links",
                right: "Rechts",
                center: "Zentrum",
                top: "Open",
                middle: "Mitte",
                bottom: "Unten",
              },
              line: {
                style: "Linienstil",
                base: "Basislinie",
                up: "Aufwärtslinie",
                down: "Abwärtslinie",
                middle: "Mittellinie",
              },
            },
            visible: {
              hide: "Alle Objekte ausblenden",
              show: "Alle Objekte einblenden",
            },
            lock: "Alle Objekte sperren",
            unlock: "Alle Objekte entsperren",
            andrewsPitchforkChannel: "Andrews' Forke",
            equidistantChannel: "Äquidistantkanal",
            regressionChannel: "Regressionskanal",
            stdDevChannel: "Standardabweichungskanal",
            fibonacciRetracement: "Fibonacci Rücksetzungsebenen",
            gannFan: "Gann Fächer",
            gannGrid: "Gann Gitter",
            gannLine: "Gann Line",
            arrowLine: "Pfeillinie",
            crossLine: "Linienkreuz",
            extendedLine: "Verlängerte Linie",
            horizontalRay: "Waagerechter Strahl",
            horizontalLine: "Horizontale Linie",
            infoLine: "Info-Line",
            rayLine: "Strahl",
            trendAngle: "Trendlinie nach Winkel",
            trendline: "Trendlinie",
            verticalLine: "Vertikale Linie",
            disjointAngle: "Abweichender Kanal",
            flatTopBottom: "Flach oben/unten",
            rectangle: "Rechteck",
            circle: "Kreis",
            triangle: "Dreieck",
            ellipse: "Ellipse",
            text: "Text",
            rulerLine: "Lineal",
          },
          period: {
            full: {
              D1: "1 Tag",
              H1: "1 Stunde",
              H4: "4 Stunden",
              M1: "1 Minute",
              M15: "15 Minuten",
              M30: "30 Minuten",
              M5: "5 Minuten",
              MN: "1 Monat",
              Unknown: "Unbekannt",
              W1: "1 Woche",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unbekannt",
              W1: "W1",
            },
          },
          screenshot: "Chart als Bild speichern",
          symbolSpecs: {
            GTCmode: "GTC-Modus",
            calculation: "Berechnung",
            chartMode: "Chart-Modus",
            contractSize: "Kontraktgröße",
            days: {
              friday: "Freitag",
              monday: "Montag",
              saturday: "Samstag",
              sunday: "Sonntag",
              thursday: "Donnerstag",
              tuesday: "Dienstag",
              wednesday: "Mittwoch",
            },
            digits: "Genauigkeit",
            empty: "Kein Symbol ausgewählt",
            execution: "Ausführung",
            expiration: "Ablauf",
            filling: "Füllpolicy",
            initial: "Anfänglich",
            maintenance: "Aufrechterhaltung",
            marginCurrency: "Marginwährung",
            marginRate: "Margin Rate",
            maxVolume: "Maximales Volumen",
            minVolume: "Mindestvolumen",
            orders: "Order",
            profitCurrency: "Gewinnwährung",
            schedule: { quotes: "Preise", trade: "Handel" },
            sector: "Sektor",
            spread: "Spread",
            stopsLevel: "Stops-Ebene",
            swapLong: "Swap Long",
            swapShort: "Swap Short",
            swapType: "Swap-Typ",
            title: "{symbol}-Kontraktspezifikation",
            tradeMode: "Handel",
            volumeStep: "Volumenschritt",
            volumeLimit: "Volumenlimit",
            tickSize: "Tickgröße",
            tickValue: "Tickwert",
            marginInitial: "Anfängliche Margin",
            marginHedged: "Abgesicherte Marge",
            commission: {
              daily: {
                volume: "Tägliches Volumen in Losen",
                turnoverVolume: "Tagesumsatz in Lots",
                turnoverMoney: "Tagesumsatz in Geldwerten",
                value: "Täglich nach Handelswert",
                profit: "Täglicher Gewinn",
              },
              monthly: {
                volume: "Monatliches Volumen in Losen",
                turnoverVolume: "Monatsumsatz in Lotsin Lots",
                turnoverMoney: "Monatsumsatz in Geldwerten",
                value: "Monatlich nach Handelswert",
                profit: "Monatlicher Gewinn",
              },
              instant: {
                volume: "Sofort nach Transaktionsvolumen",
                value: "Sofort nach Transaktionswert",
                profit: "Sofortiger Gewinn pro Transaktion",
              },
              entry: {
                in: "Eingangs-Deals",
                out: "Ausgangs-Deals",
                all: "Ein-/Ausgangs-Deals",
              },
              tier: {
                mode: {
                  pips: "Punkte",
                  percent: "% in {currency}",
                  percentProfit: "% Gewinn {currency}",
                },
                type: { perDeal: "pro Deal", perLot: "pro Los" },
              },
              header: "Kommission",
            },
          },
          tree: {
            close: "Schließen",
            empty: "Sie haben keine Objekte auf dem Chart",
            lock: "Sperren",
            remove: "Entfernen",
            settings: "Einstellungen",
            title: "Zeichnung verwalten",
            unlock: "Entsperren",
          },
          types: {
            area: "Bereich",
            line: "Linie",
            bars: "Balken",
            candlestick: "Kerzen",
          },
          volumeTypes: {
            tickVolumes: "Tick-Volumen",
            volumes: "Volumen",
            withoutVolumes: "Ohne Volumen",
            realVolumes: "Realvolumen",
          },
          zoom: { in: "Vergrößern", out: "Verkleinern" },
          hotkeys: {
            arrowLine: "Pfeillinie",
            chartTypeArea: "Flächenchart",
            chartTypeLine: "Linienchart",
            chartTypeBar: "Balkenchart",
            chartTypeCandle: "Kerzenchart",
            crossLine: "Linienkreuz",
            extendedLine: "Verlängerte Linie",
            horizontalLine: "Horizontale Linie",
            infoLine: "Info-Line",
            rayLine: "Strahl",
            realVolumes: "Reale Volumina",
            tickVolumes: "Tick-Volumen",
            trendline: "Trendlinie",
            verticalLine: "Vertikale Linie",
            sections: {
              chartType: "Charttyp",
              drawing: "Zeichnen",
              volume: "Volumen",
            },
            crosshairRuler: "Fadenkreuz",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  n = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Erste Schritte mit Ihrem Konto",
            newAccountOpened: "Neues Konto eröffnet",
          },
          brokerInformation: {
            company: "Firma",
            email: "Email",
            phone: "Telefon",
            registrationAddress: "Registrierungsadresse",
            title: "Informationen zur Firma",
            website: "Website",
          },
          changePassword: {
            btnChange: "Passwort ändern",
            confirmPassword: "Passwort bestätigen",
            newPassword: "Neues Passwort",
            title: "Passwort ändern",
          },
          connect: {
            btnConnect: "Mit Konto verbinden",
            contactBroker: "Informationen zur Firma",
            forgotPassword: "Passwort vergessen?",
            loginPlaceholder: "Login eingeben",
            passwordPlaceholder: "Passwort eingeben",
            savePassword: "Passwort speichern",
            title: "Mit Konto verbinden",
          },
          copyToClipboard: {
            copy: "In die Zwischenablage kopieren",
            unsupported: "Kopieren wird nicht unterstützt",
          },
          demo: {
            accountOpeningWarning:
              "Mit der Eröffnung eines Kontos erklären Sie sich mit den Bedingungen für eine Kontoeröffnung und der Datenschutzpolitik von {brokerName} einverstanden.",
            btnOpenDemo: "Demo-Konto eröffnen",
            title: "Demo-Konto eröffnen",
            tradeWithRealMoney:
              "Um mit echtem Geld zu handeln, müssen Sie einen separaten Vertrag mit einem Finanzdienstleistungsunternehmen abschließen.",
          },
          disclaimer: {
            btnAccept: "Akzeptiert",
            headerTitle: "Willkommen bei MetaTrader 5",
            text: 'MetaQuotes Ltd ist ein Softwareentwicklungsunternehmen und bietet keine Finanz-, Anlage-, Makler-, Handels- oder Datenfeed-Dienstleistungen an und ist auch nicht an provisionsbasierten Zahlungen in Bezug auf Handelsgeschäfte beteiligt.<br /><br />Durch Drücken der Schaltfläche AKZEPTIERT stimme ich den <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">Nutzungsbedingungen der EULA</a>, der <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Datenschutzrichtlinie</a> und dem Haftungsausschluss zu.<br /><br /> Keine der in der Anwendung verfügbaren Informationen sind als Anlageberatung gedacht. Bevor Sie diese Anwendung für den Handel verwenden, sollten Sie den Rat eines qualifizierten und registrierten Wertpapierfachmanns einholen und Ihre eigene Due Diligence-Prüfung durchführen.',
            title: "Haftungsausschluss",
          },
          errors: {
            error: "Fehler",
            invalidCode: "Ungültige Eingabe",
            invalidEmail: "Ungültige E-Mail",
            invalidPhone: "Ungültige Telefonnummer",
            unknownError: "Unbekannter Fehler",
          },
          form: {
            accountType: "Accounttyp",
            address: "Adresse",
            addressPlaceholder: "Addresse eingeben",
            annualDeposit: "Jahreszahlung",
            annualIncome: "Jahreseinkommen",
            broker: "Firma",
            btn: {
              back: "Zurück",
              cancel: "Abbrechen",
              next: "Weiter",
              openAccount: "Konto eröffnen",
              remove: "Entfernen",
              signOut: "Abmelden",
            },
            city: "Stadt",
            cityPlaceholder: "Stadt eingeben",
            country: "Land",
            dateBirth: "Geburtsdatum",
            deposit: "Einzahlungen",
            education: "Bildung",
            email: {
              address: "Email",
              code: "Postleitzahl",
              placeholder: "E-Mail eingeben",
              title: "Email",
            },
            employement: "Beschäftigung",
            forex: "Forex",
            futures: "Futures",
            gender: {
              female: "Weiblich",
              male: "Männlich",
              title: "Geschlecht",
            },
            identity: "Identität",
            imageOrPdfFile: "Bild- oder PDF-Datei",
            investor: "Investor",
            language: "Sprache",
            leverage: "Leverage",
            login: "Login",
            min5chars: "Min. 5 Zeichen",
            name: {
              middle: "Zweiter Vorname",
              surname: "Nachname",
              title: "Name",
              yourName: "Ihr Name",
            },
            nationality: "Nationalität",
            netWorth: "Nettovermögen",
            optional: "Optional",
            password: "Passwort",
            passwordReadOnly: "Nur-Lese-Passwort",
            phone: {
              mobile: "Handynummer",
              number: "Festnetznummer",
              sms: "Code von SMS",
            },
            pleaseSelect: "Bitte wählen Sie",
            policyCheckbox:
              "Ich stimme den Bedingungen für die Kontoeröffnung und der Datenschutzrichtlinie zu",
            server: "Server",
            side: { back: "Rückseite", front: "Vorderseite" },
            sourceWealth: "Einkommensquelle",
            state: "Stand",
            status: "Status",
            stocks: "Aktien",
            taxID: "Steuer-ID",
            type: "Typ",
            useHedge: "Hedging im Trading verwenden",
            verificationCodes: {
              email:
                "Wir haben einen Verifizierungscode an Ihre E-Mail geschickt",
              phone:
                "Wir haben einen Verifizierungscode an Ihr Handy geschickt",
              phoneEmail:
                "Wir haben Verifizierungscodes an Ihr Handy und Ihre E-Mail geschickt.",
            },
            zipCode: "Postleitzahl",
          },
          mainForm: {
            title: "Handelskonten",
            titleWithName: "Handelskonten: {brokerName}",
          },
          otp: {
            disable2FA: "2FA/TOTP deaktivieren",
            disable2FAAccount: "2FA/TOTP für Konto {login}",
            disableEnterCode:
              "Um 2FA/TOTP zu deaktivieren, geben Sie bitte Ihren vom Authenticator generierten Kontocode ein.",
            downloadApp:
              "Bitte laden Sie die Google Authenticator / Microsoft Authenticator / Authy App auf Ihr Mobilgerät und scannen Sie den QR-Code:",
            enable2FA: "2FA/TOTP aktivieren",
            enable2FAAccount: "2FA/TOTP für Konto {login} aktivieren",
            enterCode:
              "Um die Funktion des Authenticators zu überprüfen, geben Sie Ihren von der App generierten Kontocode ein.",
            oneTimePassword: "Einmal-Passwort:",
            placeholder: "Einmal-PWD. für das Konto eingeben",
            required:
              "Die 2FA-Authentifizierung ist für zusätzliche Kontosicherheit erforderlich.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Kontoauszug",
              utilityBill: "Strom-/Gasrechnung",
            },
            conditionsForUploadingFiles: {
              documents:
                "Für einige Dokumente sind zwei Fotos erforderlich: Vorder- und Rückseite",
              proofAddress:
                "Rechnungen für Mobilfunkdienste werden nicht als Adressnachweis akzeptiert",
              utilityBill:
                "Die Rechnung des Versorgungsunternehmens muss Ihren Namen und Ihre Adresse enthalten und darf nicht älter als 3 Monate sein.",
            },
            documentType: {
              driverLicense: "Führerschein",
              idCard: "Personalausweis",
              passport: "Reisepass",
              residencePermit: "Aufenthaltserlaubnis",
            },
            educationLevel: {
              bachelor: "Bachelorabschluss oder Äquivalent",
              highScholl: "Hochschule",
              master: "Masterabschluss oder Äquivalent",
              none: "Nicht angegeben",
              other: "Sonstiges",
              phd: "PHD oder Äquivalent",
            },
            employment: {
              employed: "Erwerbstätig",
              other: "Sonstiges",
              retired: "Rentner",
              selfEmployed: "Selbständig",
              student: "Student",
              unemployed: "Arbeitslos",
            },
            experience: "Echte Handelserfahrung:",
            experienceLevel: {
              above3: "> 3 Jahre",
              form1to3: "1 bis 3 Jahre",
              less1: "< 1 Jahr",
            },
            industry: {
              agriculture: "Landwirtschaft",
              communication:
                "Kunst, Audio/Video-Technologien und Kommunikation",
              construction: "Architektur und Bauwesen",
              education: "Bildung",
              engineering: "Ingenieurwesen und Mathematik",
              government: "Öffentliche Verwaltung",
              healthcare: "Gesundheitswesen",
              it: "Informationstechnologien",
              management: "Business Administration",
              manufacturing: "Produktion",
              marketing: "Marketing und Sales",
              none: "Nicht angegeben",
              other: "Sonstiges",
              science: "Wissenschaft und Technologie",
              security:
                "Rechtssicherheit und öffentliche Sicherheit, Strafvollzug und Sicherheit",
              tourism: "Tourismus und Hotellerie",
              transport: "Transport, Distribution und Logistik",
            },
            policy:
              "Die persönlichen Daten werden für die Eröffnung eines Handelskontos verwendet und nicht an Dritte weitergegeben. Die Informationen werden sicher und vertraulich behandelt.",
            takePhoto:
              "Bitte fotografieren Sie Ihre Dokumente und laden Sie sie hier unbearbeitet hoch.",
            title: "Realkonto eröffnen",
            wealthSource: {
              employment: "Beschäftigung",
              inheritance: "Schenkung oder Erbe",
              other: "Sonstiges",
              savings: "Ersparnisse oder Investitionen",
            },
          },
          saveAccountData:
            "Bitte bewahren Sie Ihr Login und Passwort an einem sicheren Ort auf.",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Schließen",
            empty: "Wir haben keine Volumendaten für dieses Symbol.",
            extendedBook: {
              hide: "Extended Book ausblenden",
              show: "Extended Book anzeigen",
            },
            menu: {
              amount: "Eine Einheit statt Lots ",
              extended: "Erweitert",
              spread: "Spread",
            },
            spread: { hide: "Spread ausblenden", show: "Spread anzeigen" },
            stopLoss: "Stop Loss",
            takeProfit: "Take Profit",
            title: "Markttiefe",
          },
          errors: {
            accepted: "Akzeptiert",
            allowedOnlyLongPositions: "Nur Long-Positionen erlaubt",
            allowedOnlyPositionsClosing:
              "Nur das Schließen von Postionen erlaubt",
            allowedOnlyShortPositions: "Nur Short-Positionen erlaubt",
            automatedTradingDisabledClient:
              "AutoTrading auf dem Client-Terminal deaktiviert",
            automatedTradingDisabledServer:
              "AutoTrading auf dem Server deaktiviert",
            canceled: "Annulliert",
            common: "Allgemeiner Fehler",
            demoAllocationDisabled: "Demokonto-Zuweisung ist deaktiviert",
            done: "Fertig",
            donePartially: "Teilweise erledigt",
            frequentRequests: "Zu häufige Anfragen",
            invalidExpiration: "Ungültiger Ablauf",
            invalidOrderType: "Ungültiger Ordertyp",
            invalidParameters: "Ungültige Parameter",
            invalidPrices: "Ungültige Preise",
            invalidSLTP: "S/L oder T/P ungültig",
            invalidVolume: "Ungültiges Volumen",
            manyTradeRequests: "Zu viele Handelanfragen",
            marketClosed: "Der Markt ist geschlossen",
            modificationFailed:
              "Order oder Position zu nah am Marktpreis, Modifizierung fehlgeschlagen",
            networkProblem: "Netzwerkproblem",
            noConnection: "Keine Verbindung",
            notEnoughMoney: "Zu wenig Geld",
            offQuotes: "Keine Preise",
            ok: "OK",
            onTheWay: "Ist abgesandt",
            orderChanged: "Die Order ist bereits geändert",
            orderClosePositionExists:
              "Order zum Schließen dieser Position ist bereits vorhanden",
            ordersLimitReached: "Ordernlimit erreicht",
            permissions: "Nicht erlaubt",
            placed: "Platziert",
            positionCloseProhibitedByFIFO:
              "Schließen der Position verboten wegen der FIFO-Regel",
            positionClosed: "Position bereits geschlossen",
            positionsLimitReached: "Maximale Anzahl von Positionen erreicht",
            priceChanged: "Preis verändert",
            prices: "Preise",
            processed: "Berarbeitet",
            rejected: "Abgelehnt",
            requestRejectedOrderWillCanceled:
              "Anfrage abgelehnt, Order annulliert",
            requoted: "Requote",
            serverProblem: "Technisches Problem des Servers",
            timeout: "Timeout",
            tradeDisabled: "Handel ist deaktiviert",
            unsupportedFillingMode: "Füllmodus nicht unterstützt",
            volumeLimitReached: "Volumenlimit erreicht",
          },
          form: {
            acceptNewQuotes: "Neuen Preis akzeptieren?",
            btnOpen: {
              hide: "Handelsformular ausblenden",
              show: "Handelsformular anzeigen",
              title: "Neue Order",
            },
            buttons: {
              accept: "Akzeptieren",
              delete: "Löschen",
              modify: "Ändern",
              ok: "OK",
              placeOrder: "Auftrag platzieren",
              reject: "Ablehnen",
              request: "Anforderung",
              requestPrice: "Preis anfordern",
            },
            close: "Schließen",
            execution: {
              fillOrKill: "FOK-Order",
              immediateOrCancel: "IOC-Order",
              bookOrCancel: "Buchen oder Löschen",
              label: "Füllungsart",
              return: "Zurückkehren",
            },
            executionMode: {
              exchange: "Börseausführung",
              instant: "Sofortige Ausführung",
              market: "Marktausführung",
              request: "Ausführung anfordern",
            },
            expiration: {
              date: "Ablaufdatum",
              label: "Ablauf",
              types: {
                specified: "Datum und Uhrzeit",
                specifiedDay: "Angegebener Tag",
                today: "Heute",
              },
            },
            fields: {
              closeBy: "Schließen mit",
              comment: "Kommentar",
              price: "Preis",
              stopLoss: "Stop Loss",
              takeProfit: "Take Profit",
              volume: "Volumen",
              errors: {
                volume: {
                  min: "Minimalvolumen ist {min}",
                  max: "Maximalvolumen ist {max}",
                  required: "Volume is required",
                  step: "Das Volumen kann mit einer Schrittweite von {step} eingestellt werden.",
                },
              },
            },
          },
          history: {
            btnOpen: "Historie",
            deals: {
              columns: {
                comment: "Kommentar",
                commission: "Kommission",
                direction: "Richtung",
                fee: "Gebühr",
                order: "Order",
                price: "Preis",
                profit: "Profit",
                swap: "Swap",
                symbol: "Symbol",
                ticket: "Ticket",
                time: "Zeit",
                type: "Typ",
                volume: "Volumen",
              },
            },
            empty: "Sie haben noch keine Handelshistorie",
            menu: {
              columns: {
                horizontalScroll: "Horizontales Scrollen",
                resetAll: "Alles zurücksetzen",
                title: "Spalten",
              },
              deals: "Deals",
              orders: "Order",
              period: {
                all: "Komplette Historie",
                last3Months: "Letzte 3 Monate",
                last6months: "Letzte 6 Monate",
                lastMonth: "Letzter Monat",
                title: "Periode",
                customPeriod: "Zeitraum anpassen",
                lastYear: "Letztes Jahr",
                lastWeek: "Letzte Woche",
                today: "Heute",
              },
              positions: "Positionen",
              chart: "Chart",
              newOrder: "Neue Order",
            },
            orders: {
              columns: {
                comment: "Kommentar",
                price: "Preis",
                slDescription: "Stop Loss",
                state: "Stand",
                symbol: "Symbol",
                ticket: "Ticket",
                timeDone: "Zeit",
                timeSetup: "Zeit",
                tpDescription: "Take Profit",
                type: "Typ",
                volume: "Volumen",
                timeSetupDescription: "Eröffnungszeit",
                timeDoneDescription: "Schlusszeit",
              },
              total: {
                title: "Gesamt",
                filled: "Gefüllt",
                canceled: "Annulliert",
                rejected: "Abgelehnt",
              },
            },
            positions: {
              columns: {
                commission: "Kommission",
                fee: "Gebühr",
                priceClose: "Preis",
                priceCloseDescription: "Schlusskurs",
                priceOpen: "Preis",
                priceOpenDescription: "Eröffnungspreis",
                profit: "Profit",
                slDescription: "Stop Loss",
                swap: "Swap",
                symbol: "Symbol",
                ticket: "Ticket",
                timeClose: "Zeit",
                timeCloseDescription: "Schließzeit",
                timeOpen: "Zeit",
                timeOpenDescription: "Eröffnungszeit",
                tpDescription: "Take Profit",
                type: "Typ",
                volume: "Volumen",
                comment: "Kommentar",
              },
            },
            columns: { default: "Standard" },
            total: {
              profit: "Gewinn",
              credit: "Kredit/Bonus",
              deposit: "Einlage",
              withdrawal: "Auszahlung",
              balance: "Kontostand",
              commission: "Kommission",
              fee: "Kosten",
              swap: "Swap",
              grossProfit: "Bruttogewinn",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Handelshistorie",
                orders: "Handelsaufträge",
                position: "Positionen",
                sltp: "SL/TP-Level",
              },
              notification: "Handelsmeldung",
            },
            oneClick: "Handel mit einem Klick",
            tags: { demo: "Demo", readonly: "Nur Lesen" },
            oneClickBottom: "Ein-Klick-Panel unten",
          },
          oneClickDisclaimer: {
            acceptCheckbox:
              "Ich akzeptiere die Allgemeinen Geschäftsbedingungen",
            btnAccept: "Akzeptieren",
            btnCancel: "Abbrechen",
            text: 'Sie sind dabei, den Ein-Klick-Handelsmodus zu aktivieren. Indem Sie unten auf "Ich akzeptiere diese Allgemeinen Geschäftsbedingungen" klicken, bestätigen Sie, dass Sie die folgenden Allgemeinen Geschäftsbedingungen gelesen und verstanden haben, und erklären sich damit einverstanden, das insgesamt zu akzeptieren.<br /><br />Sie können den Ein-Klick-Handelsmodus aktivieren oder deaktivieren, wenn Sie im Menü Ihres Webterminals auf Handelsmodus klicken.<br /><br />Der Ein-Klick-Handelsmodus für die Übermittlung von Aufträgen ist ein einstufiger Prozess. Ihre Aufträge werden gesendet, wenn Sie: &mdash; Im Ein-Klick-Handelsbereich eines Charts entweder auf die Schaltfläche für Bid-Preis (SELL) oder Ask-Preis (BUY) tippen. &mdash;  Im Fenster Markttiefe auf die Schaltflächen Sell, Schließen, Buy oder den für einen schwebenden Auftrag klicken. &mdash; Schließen Sie Positionen oder löschen Sie schwebenden Aufträge in der Registerkarte Handel.<br /><br />ES ERFOLGT KEINE ANSCHLIESSENDE BESTÄTIGUNGSAUFFORDERUNG, AUF DIE SIE KLICKEN MÜSSTEN. SIE KÖNNEN IHREN AUFTRAG NACH IHREM KLICK NICHT MEHR WIDERRUFEN ODER ÄNDERN. UNTER NORMALEN MARKTBEDINGUNGEN UND SYSTEMLEISTUNG WIRD EINE MARKET-ORDER UNMITTELBAR NACH DER AUFTRAGSERTEILUNG DURCHGEFÜHRT UND SIE WERDEN EINE VERBINDLICHE TRANSAKTION ABSCHLIESSEN.<br /><br />Sie stimmen zu, alle mit der Nutzung des Ein-Klick-Handelsmodus verbundenen Risiken zu akzeptieren, einschließlich, aber nicht beschränkt auf das Risiko von Fehlern, Auslassungen oder Fehlern, die bei der Übermittlung solcher Aufträge gemacht werden.<br /><br />Sie stimmen zu, {companyName} von allen Verlusten, Kosten und Ausgaben freizustellen und schadlos zu halten, die möglicherweise auftreten infolge solcher Fehler, Auslassungen oder Irrtümer von Ihnen oder einer anderen Person, die in Ihrem Namen handelt, entstehen.',
            title: "Ein-Klick-Handel - Haftungsausschluss",
          },
          quickTrade: {
            hide: "Ein-Klick-Handelspanel ausblenden",
            show: "Ein-Klick-Handelspanel anzeigen",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Ich verstehe die obige Warnung und ich wünsche hoch-risikante Investitionsprodukte handeln ",
            btnAccept: "Akzeptieren",
            btnCancel: "Abbrechen",
            text: "Wir möchten Sie darüber informieren, dass Sie durch die weitere Nutzung dieser Handelsplattform Zugang zu gehebelten Anlageprodukten mit hohem Risiko haben, die von dem Finanzinstitut Ihrer Wahl bereitgestellt werden. Die Investition in solche Produkte ist möglicherweise nicht für alle Anleger geeignet, da sie das Risiko birgt, einen Teil oder den gesamten eingezahlten Betrag zu verlieren.<br /><br />Bevor Sie sich für den Handel mit risikoreichen Anlageprodukten entscheiden, sollten Sie Ihre Anlageziele sorgfältig prüfen. Erfahrungsniveau und akzeptables Risiko. Es besteht die Möglichkeit, dass Sie einen Verlust erleiden, der höher ist als Ihre ursprüngliche Investition, und daher sollten Sie kein Geld investieren, dessen Verlust Sie sich nicht leisten können.<br /><br />Wir laden Sie ein, Ihr Wissen über alle Risikofaktoren zu erweitern, die mit der Anlage in diese Produkte verbunden sind, und sich im Zweifelsfall von einem professionellen Finanzberater beraten zu lassen.",
            title: "Warnung vor risikobehaftete Investitionen",
          },
          table: {
            btnOpen: "Handel",
            columns: {
              comment: "Kommentar",
              priceClose: "Preis",
              priceCloseDescription: "Schlusspreis",
              priceOpen: "Preis",
              priceOpenDescription: "Eröffnungspreis",
              profit: "Profit",
              slDescription: "Stop Loss",
              swap: "Swap",
              symbol: "Symbol",
              ticket: "Ticket",
              time: "Zeit",
              tpDescription: "Take Profit",
              type: "Typ",
              volume: "Volumen",
            },
            emptyPlug: {
              btnNewOrder: "Erstellen eines neuen Auftrags",
              title: "Sie haben keine Positionen",
            },
            menu: {
              chart: "Chart",
              closePosition: "Position schließen",
              columns: "Spalten",
              modifyOrder: "Order ändern",
              modifyPosition: "Position ändern",
              newOrder: "Neue Order",
              resetAll: "Alles zurücksetzen",
              deleteOrder: "Order löschen",
            },
            oneClick: { deleteOrder: "Löschen" },
            sections: {
              collateralPositions: "Besicherte Positionen",
              orders: "Order",
              positions: "Positionen",
            },
            total: {
              assets: "Aktiva",
              balance: "Kontostand",
              collateral: "Collateral",
              commission: "Kommission",
              credit: "Kredit",
              equity: "Kapital",
              liabilities: "Verbindlichkeiten",
              margin: "Margin",
              marginFree: "Freie Margin",
              marginLevel: "Ebene",
            },
          },
          timer: {
            marketWillOpen: "Der Markt öffnet in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} Tage",
            oneDay: "{numberOfDays} Tag",
          },
          tradeIsDisabled: {
            account:
              "Der Handel für dieses Konto ist auf dem Server deaktiviert.",
            collateral:
              "Der Handel ist nicht möglich, da es sich bei diesem Symbol um Sicherheiten handelt.",
            disabled: "Handel ist deaktiviert.",
            investor:
              "Der Handel ist nicht möglich, da Sie mit dem Investor-Passwort verbunden sind.",
            readOnly:
              "Der Handel ist nicht möglich, weil Sie die Risikowarnung nicht akzeptiert haben.",
            symbol: "Der Handel für dieses Symbol ist deaktiviert.",
          },
          hotkeys: {
            historyPanel: "Historien Panel",
            journalPanel: "Journal",
            marketWatch: "Marktübersicht",
            quickTrade: "Handel mit einem Klick",
            tradeForm: "Neue Order",
            tradePanel: "Handelspanel",
          },
          marketOpen: {
            time: "Markt geschlossen - öffnet um {time}",
            afterSeconds: "Markt geschlossen - öffnet in {time} Sek.",
          },
          expiredTimer: { seconds: "Läuft in {time} Sek. ab" },
          corporateLink: {
            type: {
              clientAgreement: "Kundenbedingungen",
              riskDisclosure: "Risikoaufklärung",
              fdmDisclaimer: "FDM Haftungsausschluss",
              clientAgreementAndRiskDisclosure:
                "Kundenbedingungen und Risikoaufklärung",
              complaintsHandlingProcedure:
                "Verfahren der Bearbeitung von Beschwerden",
              orderExecutionPolicy: "Regeln der Orderausführung",
              clientCategorisationNotice:
                "Hinweis zur Kategorisierung von Kunden",
              conflictsOfInterestPolicy: "Regelungen zu Interessenkonflikten",
              dataProtectionPolicy: "Datenschutzrichtlinie",
            },
          },
          margin: {
            floating: "schwebend",
            mode: { marketBuy: "Markt Buy", marketSell: "Markt Sell" },
            rangeMode: {
              value: "Nominalwert",
              valuePerSymbol: "Nominalwert pro Symbol",
              volume: "Volumen",
              volumePerSymbol: "Volumen pro Symbol",
            },
            showValue: "Anzeige der Werte in {currency} pro Los",
            rates: "Margin-Satz:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Vollbildmodus deaktivieren",
            enable: "Vollbildmodus aktivieren",
          },
          journal: {
            btnOpen: "Journal",
            columns: { message: "Nachricht", source: "Quelle", time: "Zeit" },
            menu: {
              clear: "Leeren",
              debugMode: "Debug-Modus",
              exportFile: "Exportieren in Datei",
            },
          },
          menu: {
            about: "Über Programm",
            contact: "Kontaktiere uns",
            brokerInformation: "Informationen zur Firma",
            chartSettings: {
              controls: "Chart-Einstellung",
              grid: "Raster",
              ohlc: "OHLC anzeigen",
              title: "Charteinstellungen",
              askPrice: "Ask Preis",
              crosshair: "Fadenkreuz-Kursor",
            },
            connect: "Mit Konto verbinden",
            language: {
              title: "Sprache",
              search: "Suche",
              nothingFound: "Sprache nicht gefunden",
            },
            openDemo: "Demo-Konto eröffnen",
            openReal: "Real-Konto eröffnen",
            settings: "Einstellungen",
            shortcuts: "Tastaturkürzel",
            theme: {
              blackWhite: "Schwarz-Weiß",
              blueRed: "Blau-Rot",
              dark: "Dunkles Theme",
              editor: "Theme-Editor",
              greenRed: "Grün-Rot",
              light: "Helles Theme",
              neutral: "Neutral",
              templates: "Frbvorlagen",
            },
            title: "Menü",
            tradingAccount: "Handelskonten",
            terms: "Nutzungsbedingungen",
            desktopPlatforms: "Desktop-Terminals",
            qrCode: {
              install: "Scan zur Installation von {store}",
              downloadApk: "Scannen, um Android APK-Datei zu erhalten",
            },
            economicCalendar: "Wirtschaftskalender",
          },
          screen: { back: "Zurück" },
          mobile: { bottomNav: { quotes: "Quoten" } },
          hotkeys: {
            sections: { navigation: "Navigieren", view: "Ansicht" },
            escape: "Abbrechen",
            indicators: "Indikatoren",
            depthOfMarket: "Markttiefe",
            objectTreePanel: "Objektbaum",
            scrollRight: "Nächste Kerze",
            scrollToStart: "Zum Chartanfang scrollen",
            scrollLeft: "Vorherige Kerze",
            scrollToEnd: "Zum Chartende scrollen",
            resetChartView: "Chart zurücksetzen",
            zoomIn: "Vergrößern",
            zoomOut: "Verkleinern",
            fullScreen: "Vollbild",
            screenshot: "Chart als Bild speichern",
            title: "Tastaturkürzel",
          },
          timezone: {
            title: "Zeitzone",
            city: {
              cairo: "Kairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexiko-Stadt",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hongkong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nikosia",
              qatar: "Katar",
              rangoon: "Rangun",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapur",
              taipei: "Taipeh",
              tehran: "Teheran",
              tokyo: "Tokio",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athen",
              belgrade: "Belgrad",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brüssel",
              bucharest: "Bukarest",
              budapest: "Budapest",
              copenhagen: "Kopenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lissabon",
              london: "London",
              luxembourg: "Luxemburg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moskau",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prag",
              riga: "Riga",
              rome: "Rom",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Wien",
              vilnius: "Vilnius",
              warsaw: "Warschau",
              zurich: "Zürich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { n as a, i as b, t as c, e as d };
