const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Приховати події економічного календаря на графіку",
              show: "Показати події економічного календаря на графіку",
            },
          },
          controls: {
            reset: "Скинути графік",
            scrollEnd: "Прокрутити до кінця",
            scrollLeft: "Прокрутити вліво",
            scrollRight: "Прокрутити вправо",
            zoomIn: "Збільшити",
            zoomOut: "Зменшити",
          },
          crosshair: "Перехрестя",
          delay: "затримка {delay} хв",
          indicators: {
            btnAddIndicator: "Додати індикатор",
            btnOpenPopup: "Додати індикатор",
            close: "Закрити",
            form: {
              applyTo: "Застосувати до",
              background: {
                title: "Фон",
                down: "Фон down kumo",
                up: "Фон up kumo",
              },
              deviation: "Відхилення",
              enterDistance: "Період",
              enterShift: "Зсув",
              fastEma: "Швидке EMA",
              slowEma: "Повільне EMA",
              line: {
                base: "Базова лінія",
                down: "Нижня лінія",
                minusDI: "Лінія -DI",
                null: "Нульова лінія",
                plusDI: "Лінія +DI",
                style: "Стиль ліній",
                cci: "Лінія CCI",
                up: "Верхня лінія",
                fi: "Лінія FI",
              },
              maximum: "Максимум",
              method: {
                exponential: "Експоненціальне",
                linearWeighted: "Лінійно-зважений",
                simple: "Просто",
                smoothed: "Згладжене",
                title: "Метод",
              },
              opacity: "Прозорість",
              period: {
                jaws: "Період щелеп",
                lips: "Період губ",
                teeth: "Період зубів",
                title: "Період",
                dPercent: "Період %D",
                kPercent: "Період %K",
              },
              selectApplyTo: "Вибрати",
              selectVolumesType: "Оберіть тип об'єму",
              shift: "Зміщення",
              showTimeframes: "Показувати на всіх таймфреймах",
              slowing: "Уповільнення",
              step: "Крок",
              style: {
                down: "Стиль низхідного",
                jaws: "Стиль Щелеп",
                lips: "Стиль Губ",
                main: "Основний стиль",
                signal: "Стиль сигнальної линії",
                teeth: "Стиль Зуб",
                title: "Стиль",
                up: "Стиль вгору",
                rvi: "Стиль RVI",
              },
              volume: { down: "Об'єм донизу", up: "Об'єм доверху" },
              volumes: "Об'єми",
              mfiUp: "MFI доверху",
              mfiDown: "MFI донизу",
              price: {
                title: "Ціна",
                select: "Оберіть ціну",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "Нічого не знайдено",
              title: "Пошук",
              tryAnother: "Спробуйте інший запит",
            },
            tabs: {
              all: "Усі",
              billWilliams: "Білла Вільямса",
              oscillators: "Осцилятори",
              trend: "Трендові",
              volumes: "Об'єми",
            },
            title: "Оберіть індикатор",
            up: "Вгору",
            down: "Вниз",
            chartControls: {
              show: "Показати",
              hide: "Приховати",
              settings: "Установки",
              remove: "Видалити",
            },
          },
          loading: "Завантаження",
          marketWatch: {
            btnOpen: {
              hide: 'Приховати "Огляд ринку"',
              show: 'Показати "Огляд ринку"',
            },
            columns: {
              closePrice: "Ціна закриття",
              dailyChange: "Денна зміна",
              openPrice: "Ціна відкриття",
              spread: "Спред",
              symbol: "Символ",
              time: "Час",
              high: "High",
              low: "Low",
              last: "Остання",
              lastHigh: "Остання High",
              lastLow: "Остання Low",
              highLow: "High/Low",
              bidLow: "Мінімальний Bid",
              bidHigh: "Максимальний Bid",
              askHigh: "Максимальний Ask",
              askLow: "Мінімальний Ask",
              bid: "Bid",
              ask: "Ask",
              title: "Колонки",
            },
            menu: {
              chart: "Чарт",
              columns: "Стовпці",
              dom: "Стакан цін",
              hide: "Приховати",
              newOrder: "Новий ордер",
              specification: "Специфікація",
            },
            search: "Пошук",
            searchSymbol: "Знайти символ",
            nothingFound: "Символи не знайдені",
          },
          objects: {
            form: {
              statistics: "Статистика",
              arrows: "Стрілки",
              showAlways: "Показувати завжди",
              angle: "Кут",
              distance: "Відстань",
              bar: "Бар",
              price: "Ціна",
              prices: "Ціни",
              showPrice: "Показувати ціну",
              showText: "Показувати текст",
              showDate: "Показувати дату",
              showTime: "Показувати час",
              showAllTimeframes: "Показувати на всіх таймфреймах",
              showPearsonR: "Показувати коефіцієнт Пірсона",
              showLabels: "Показувати підписи",
              yourText: "Ваш текст",
              props: "Властивості",
              style: "Стиль",
              rays: "Промені",
              background: "Фон",
              extends: "Продовження",
              extended: "Розширений",
              pipsPerBar: "піпсов на бар",
              gannAngle: "Кут Ганна",
              deviations: "Відхилення",
              labels: "Підписи",
              reverse: "Розгорнути",
              btn: { update: "Оновити", cancel: "Відміна" },
              tabs: {
                style: "Стиль",
                coordinates: "Координати",
                visualization: "Відображення",
              },
              range: {
                price: "Діапозон цін",
                bars: "Діапазон баров",
                date: "Діапазон дат",
              },
              align: {
                horizontal: "Вирівняти по горизонталі",
                vertical: "Вирівняти по вертикалі",
                left: "Ліворуч",
                right: "Праворуч",
                center: "По центру",
                top: "Зверху",
                middle: "Посередині",
                bottom: "Знизу",
              },
              line: {
                style: "Стиль лінії",
                base: "Базова лінія",
                up: "Верхня лінія",
                down: "Нижня лінія",
                middle: "Середня лінія",
              },
            },
            visible: {
              hide: "Приховати всі об'єкти",
              show: "Показати всі об'єкти",
            },
            lock: "Заблокувати всі об'єтки",
            unlock: "Розблокувати всі об'єкти",
            andrewsPitchforkChannel: "Вили Ендрюса",
            equidistantChannel: "Рівновіддалений канал",
            regressionChannel: "Канал регресії",
            stdDevChannel: "Канал стандартних відхилень",
            fibonacciRetracement: "Лінії Фібоначчі",
            gannFan: "Віяло Ганна",
            gannGrid: "Сітка Ганна",
            gannLine: "Лінія Ганна",
            arrowLine: "Лінія зі стрілкою",
            crossLine: "Пересічні лінії",
            extendedLine: "Розширена лінія",
            horizontalRay: "Горизонтальний промінь",
            horizontalLine: "Горизонтальна лінія",
            infoLine: "Лінія даних",
            rayLine: "Промінь",
            trendAngle: "Трендова лінія по куту",
            trendline: "Трендова лінія",
            verticalLine: "Вертикальна лінія",
            disjointAngle: "Розбіжний канал",
            flatTopBottom: "Плоский верх/низ",
            rectangle: "Прямокутник",
            circle: "Коло",
            triangle: "Трикутник",
            ellipse: "Еліпс",
            text: "Текст",
            rulerLine: "Вимірювальна лінія",
          },
          period: {
            full: {
              D1: "День",
              H1: "1 Година",
              H4: "4 Години",
              M1: "1 Хвилина",
              M15: "15 Хвилин",
              M30: "30 Хвилин",
              M5: "5 Хвилин",
              MN: "Місяць",
              Unknown: "Невідомий",
              W1: "Тиждень",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Невідомий",
              W1: "W1",
            },
          },
          screenshot: "Зберегти графік як зображення",
          symbolSpecs: {
            GTCmode: "Тип ордерів",
            calculation: "Розрахунок прибутку",
            chartMode: "Побудова графіків",
            contractSize: "Розмір контракту",
            days: {
              friday: "П'ятниця",
              monday: "Понеділок",
              saturday: "Субота",
              sunday: "Неділя",
              thursday: "Четвер",
              tuesday: "Вівторок",
              wednesday: "Середа",
            },
            digits: "Точність",
            empty: "Символ не вибраний",
            execution: "Виконання",
            expiration: "Експірація",
            filling: "Виконання",
            initial: "Початкова",
            maintenance: "Підтримки",
            marginCurrency: "Валюта маржі",
            marginRate: "Коефіцієнт маржі",
            maxVolume: "Максимальний об'єм",
            minVolume: "Мінімальний об'єм",
            orders: "Ордери",
            profitCurrency: "Валюта прибутку",
            schedule: { quotes: "Котирування", trade: "Торгівля" },
            sector: "Сектор",
            spread: "Спред",
            stopsLevel: "Рівень стопів",
            swapLong: "Своп довгих позицій",
            swapShort: "Своп коротких позицій",
            swapType: "Тип свопу",
            title: "Специфікація контракту {symbol}",
            tradeMode: "Торгівля",
            volumeStep: "Крок об'єму",
            volumeLimit: "Ліміт об'єму",
            tickSize: "Розмір тіка",
            tickValue: "Значення тіка",
            marginInitial: "Початкова маржа",
            marginHedged: "Хеджуюча маржа",
            commission: {
              daily: {
                volume: "Щодня за обсяг у лотах",
                turnoverVolume: "Щодня за оборот в лотах",
                turnoverMoney: "Щодня за оборот в грошах",
                value: "Щодня за вартість угод",
                profit: "Щодня за прибуток",
              },
              monthly: {
                volume: "Щомісячно за обсяг у лотах",
                turnoverVolume: "Щомісяця за оборот в лотах",
                turnoverMoney: "Щомісяця за оборот в грошах",
                value: "Щомісяця за вартість угод",
                profit: "Щомісячно за прибуток",
              },
              instant: {
                volume: "Негайно за обсяг угоди",
                value: "Негайно за вартість угоди",
                profit: "Негайно за прибуток за угодою",
              },
              entry: {
                in: "угоди входу",
                out: "угоди виходу",
                all: "угоди входу/виходу",
              },
              tier: {
                mode: {
                  pips: "пунктів",
                  percent: "% в {currency}",
                  percentProfit: "% прибутку {currency}",
                },
                type: { perDeal: "за угоду", perLot: "за лот" },
              },
              header: "Комісії",
            },
          },
          tree: {
            close: "Закрити",
            empty: "На графіку немає об'єктів",
            lock: "Заблокувати",
            remove: "Видалити",
            settings: "Установки",
            title: "Управління об'єктами",
            unlock: "Разблокувати",
          },
          types: {
            area: "Область",
            line: "Лінійний",
            bars: "Бари",
            candlestick: "Японські свічки",
          },
          volumeTypes: {
            tickVolumes: "Тікові об'єми",
            volumes: "Об'єми",
            withoutVolumes: "Без об'ємів",
            realVolumes: "Реальні обсяги",
          },
          zoom: { in: "Збільшити", out: "Зменшити" },
          hotkeys: {
            arrowLine: "Лінія зі стрілкою",
            chartTypeArea: "Графік з областями",
            chartTypeLine: "Лінійний графік",
            chartTypeBar: "Бари",
            chartTypeCandle: "Графік зі свічками",
            crossLine: "Пересічні лінії",
            extendedLine: "Розширена лінія",
            horizontalLine: "Горизонтальна лінія",
            infoLine: "Лінія даних",
            rayLine: "Промінь",
            realVolumes: "Реальні об'єми",
            tickVolumes: "Тікові об'єми",
            trendline: "Трендова лінія",
            verticalLine: "Вертикальна лінія",
            sections: {
              chartType: "Тип графіка",
              drawing: "Розмітка",
              volume: "Об'єм",
            },
            crosshairRuler: "Лінійка-перехрестя",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Розпочніть роботу з вашим рахунком",
            newAccountOpened: "Новий рахунок відкритий",
          },
          brokerInformation: {
            company: "Компанія",
            email: "Email",
            phone: "Телефон",
            registrationAddress: "Адреса реєстрації",
            title: "Інформація про компаканію",
            website: "Сайт",
          },
          changePassword: {
            btnChange: "Змінити пароль",
            confirmPassword: "Підтвердити пароль",
            newPassword: "Новий пароль",
            title: "Змінити пароль",
          },
          connect: {
            btnConnect: "Підключитися до рахунку",
            contactBroker: "Звернутися до компанії",
            forgotPassword: "Забули пароль?",
            loginPlaceholder: "Введіть логін",
            passwordPlaceholder: "Введіть пароль",
            savePassword: "Запам'ятати пароль",
            title: "Підключитися до рахунку",
          },
          copyToClipboard: {
            copy: "Скопіювати в буфер",
            unsupported: "Копіювання не підтримується",
          },
          demo: {
            accountOpeningWarning:
              "Відкриваючи рахунок, ви погоджуєтесь з умовами відкриття рахунку та політикою захисту даних {brokerName}",
            btnOpenDemo: "Відкрити демо-рахунок",
            title: "Відкрити демо-рахунок",
            tradeWithRealMoney:
              "Для торгівлі реальними грошима вам потрібно укласти окрему угоду з компанією, яка надає фінансові послуги.",
          },
          disclaimer: {
            btnAccept: "Прийняти",
            headerTitle: "Ласкаво просимо в MetaTrader 5",
            text: 'MetaQuotes Ltd — компанія з розробки програмного забезпечення, яка не надає фінансових, інвестиційних, брокерських та торгових послуг, а також трансляції даних. Компанія не проводить платежі на комісійній основі з метою здійснення торгових операцій. <br /><br />Натискаючи кнопку "ПРИНЯТИ", ви погоджуєтесь з <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">умовами та положеннями EULA</a>, <a href="https://www.metaquotes.net/ua/legal/policies" target="_blank">Політикою конфіденційності</a> та Відмовою від відповідальності.<br /><br /> Жодна інформація в додатку не є рекомендацією щодо інвестування. Перед використанням цієї програми для торгівлі зверніться за консультацією до кваліфікованих зареєстрованих фахівців з цінних паперів та виявіть належну відповідальність.',
            title: "Відмова від відповідальності",
          },
          errors: {
            error: "Помилка",
            invalidCode: "Невірний код",
            invalidEmail: "Невірний email",
            invalidPhone: "Невірний телефон",
            unknownError: "Невідома помилка",
          },
          form: {
            accountType: "Тип рахунку",
            address: "Адреса",
            addressPlaceholder: "Введіть вашу адресу",
            annualDeposit: "Річний депозит",
            annualIncome: "Річний дохід",
            broker: "Компанія",
            btn: {
              back: "Назад",
              cancel: "Скасування",
              next: "Далі",
              openAccount: "Відкрити рахунок",
              remove: "Видалити",
              signOut: "Вийти",
            },
            city: "Місто",
            cityPlaceholder: "Вкажіть ваше місто",
            country: "Країна",
            dateBirth: "Дата народження",
            deposit: "Депозит",
            education: "Освіта",
            email: {
              address: "Email",
              code: "Код із листа",
              placeholder: "Вкажіть email",
              title: "Email",
            },
            employement: "Зайнятість",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Жіноча", male: "Чоловіча", title: "Пол" },
            identity: "Особистість",
            imageOrPdfFile: "Зображення або PDF-файл",
            investor: "Інвестор",
            language: "Мова",
            leverage: "Плече",
            login: "Логін",
            min5chars: "Мінімум 5 символів",
            name: {
              middle: "По батькові",
              surname: "Прізвище",
              title: "Ім'я",
              yourName: "Ваше ім'я",
            },
            nationality: "Громадянство",
            netWorth: "Чисті активи",
            optional: "Не обов'язково",
            password: "Пароль",
            passwordReadOnly: "Пароль тільки для перегляду",
            phone: {
              mobile: "Мобільний телефон",
              number: "Номер телефону",
              sms: "Код із SMS",
            },
            pleaseSelect: "Виберіть",
            policyCheckbox:
              "Я підтверджую згоду з умовами відкриття рахунку і політикою захисту даних",
            server: "Сервер",
            side: { back: "Зворотній бік", front: "Лицьова сторона" },
            sourceWealth: "Джерело коштів",
            state: "Стан",
            status: "Стан",
            stocks: "Акції",
            taxID: "Податковий ID",
            type: "Тип",
            useHedge: "Використовувати хеджування при торгівлі",
            verificationCodes: {
              email: "Код підтвердження надіслано на ваш email",
              phone: "Код підтвердження надіслано на ваш телефон",
              phoneEmail:
                "Коди підтвердження надіслані на ваш email та телефон",
            },
            zipCode: "Індекс",
          },
          mainForm: {
            title: "Торгові рахунки",
            titleWithName: "Торгові рахунки: {brokerName}",
          },
          otp: {
            disable2FA: "Вимкніть 2FA/TOTP",
            disable2FAAccount: "Вимкнути 2FA/TOTP для рахунку {login}",
            disableEnterCode:
              "Для відключення 2FA-автентифікації введіть код, згенерований у Authenticator для вашого рахунку.",
            downloadApp:
              "Встановіть на телефон програму Google Authenticator / Microsoft Authenticator / Authy та відскануйте QR-код:",
            enable2FA: "Увімкніть 2FA/TOTP",
            enable2FAAccount: "Увімкнути 2FA/TOTP для рахунку {login}",
            enterCode:
              "Щоб перевірити роботу Authenticator, введіть згенерований програмою код свого облікового запису.",
            oneTimePassword: "Одноразовий пароль:",
            placeholder: "Введіть ОТР для рахунку",
            required:
              "Аутентифікація 2FA потрібна для додаткової безпеки облікового запису.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Виписка з банку",
              utilityBill: "Рахунок за комунальні послуги",
            },
            conditionsForUploadingFiles: {
              documents:
                "Для деяких типів документів потрібно два фото: для лицьової та зворотної сторони",
              proofAddress:
                "Рахунки за послуги мобільного зв'язку не приймаються як підтвердження адреси проживання",
              utilityBill:
                "Комунальний рахунок повинен містити ваше ім'я та адресу, і бути не старше трьох місяців",
            },
            documentType: {
              driverLicense: "Водійське посвідчення",
              idCard: "Посвідчення особи",
              passport: "Паспорт",
              residencePermit: "Вид на проживання",
            },
            educationLevel: {
              bachelor: "Ступінь бакалавра або еквівалент",
              highScholl: "Середня загальна",
              master: "Ступінь магістра або еквівалент",
              none: "Не заданий",
              other: "Інше",
              phd: "Кандидат наук або еквівалент",
            },
            employment: {
              employed: "Працевлаштован(а)",
              other: "Інше",
              retired: "На пенсії",
              selfEmployed: "Підприємець або самозайнят(ий/а)",
              student: "Учень/Учениця",
              unemployed: "Безробітн(ий/а)",
            },
            experience: "Досвід реальної торгівлі",
            experienceLevel: {
              above3: "> 3 років",
              form1to3: "1 - 3 роки",
              less1: "< 1 року",
            },
            industry: {
              agriculture: "Сільське господарство",
              communication: "Мистецтво, аудіо/відео технології і комунікація",
              construction: "Архітектура і будівництво",
              education: "Освіта",
              engineering: "Інженерія та математика",
              government: "Державне і адміністративне управління",
              healthcare: "Охорона здоров'я",
              it: "Інформаційні технології",
              management: "Адміністрування та управління бізнесом",
              manufacturing: "Виробництво",
              marketing: "Маркетинг і продажі",
              none: "Не заданий",
              other: "Інше",
              science: "Наука і технології",
              security:
                "Правова і громадська безпека, послуги корекції і захисту",
              tourism: "Туризм і готельна справа",
              transport: "Транспортування, поширення і логістика",
            },
            policy:
              "Персональні дані використовуються для реєстрації торгового рахунку і не передаються третім особам. Обробка даних здійснюється конфіденційно і захищено.",
            takePhoto:
              "Зробіть фотографії ваших документів та завантажте їх сюди без будь-яких змін",
            title: "Відкрити реальний рахунок",
            wealthSource: {
              employment: "Зайнятість",
              inheritance: "Дар або спадок",
              other: "Інше",
              savings: "Накопичення або інвестиції",
            },
          },
          saveAccountData: "Зберігайте ваш логін та пароль у надійному місці",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Закрити",
            empty: "Дані про обсяги недоступні для цього символу",
            extendedBook: {
              hide: "Приховати розширений стакан",
              show: "Показати розширений стакан",
            },
            menu: {
              amount: "Одиниці замість лотів",
              extended: "Розширений",
              spread: "Спред",
            },
            spread: { hide: "Приховати спред", show: "Показати спред" },
            stopLoss: "Стоп Лосс",
            takeProfit: "Тейк Профіт",
            title: "Стакан цін",
          },
          errors: {
            accepted: "Прийнятий",
            allowedOnlyLongPositions: "Дозволені лише довгі позиції",
            allowedOnlyPositionsClosing: "Дозволено тільки закривати позиції",
            allowedOnlyShortPositions: "Дозволені лише короткі позиції",
            automatedTradingDisabledClient:
              "Авто-торгівля відключена в клієнтському терміналі",
            automatedTradingDisabledServer:
              "Авто-торгівля відключена на сервері",
            canceled: "Скасовано",
            common: "Загальна помилка",
            demoAllocationDisabled: "Виділення демо-рахунків вимкнено",
            done: "Готово",
            donePartially: "Виконано частково",
            frequentRequests: "Занадто часті запити",
            invalidExpiration: "Неприпустима експірація",
            invalidOrderType: "Невірний тип ордера",
            invalidParameters: "Неприпустимі параметри",
            invalidPrices: "Неприпустимі ціни",
            invalidSLTP: "Неприпустимий S/L або T/P",
            invalidVolume: "Неприпустимий Об'єм",
            manyTradeRequests: "Занадто багато торгових запитів",
            marketClosed: "Ринок закритий",
            modificationFailed:
              "Не вдалося виконати модифікацію, т.щ. ордер або позиція розташовані близько до ринкової ціни",
            networkProblem: "Мережева проблема",
            noConnection: "Немає підключення",
            notEnoughMoney: "Недостатньо грошей",
            offQuotes: "Немає котирувань",
            ok: "OK",
            onTheWay: "Відправлений",
            orderChanged: "Ордер вже був змінений",
            orderClosePositionExists:
              "Ордер на закриття зазначеної позиції вже існує",
            ordersLimitReached: "Досягнута межа ордерів",
            permissions: "Недостатньо прав",
            placed: "Розміщений",
            positionCloseProhibitedByFIFO:
              "Закриття позиції заборонено за правилом FIFO",
            positionClosed: "Позиція вже закрита",
            positionsLimitReached: "Досягнуто ліміт кількості позицій",
            priceChanged: "Ціна змінилася",
            prices: "Ціна:",
            processed: "Опрацьовано",
            rejected: "Відхилений",
            requestRejectedOrderWillCanceled: "Запит відхилено, ордер знятий",
            requoted: "Реквотован",
            serverProblem: "Технічна проблема сервера",
            timeout: "Таймаут",
            tradeDisabled: "Торгівля відключена",
            unsupportedFillingMode: "Непідтримуваний режим виконання",
            volumeLimitReached: "Досягнута межа об'єму",
          },
          form: {
            acceptNewQuotes: "Прийняти нові ціни?",
            btnOpen: {
              hide: "Приховати торгову форму",
              show: "Показати торгову форму",
              title: "Новий ордер",
            },
            buttons: {
              accept: "Прийняти",
              delete: "Видалити",
              modify: "Змінити",
              ok: "OK",
              placeOrder: "Розмістити ордер",
              reject: "Відхилити",
              request: "Запит",
              requestPrice: "Запит ціни",
            },
            close: "Закрити",
            execution: {
              fillOrKill: "Все/Нічого",
              immediateOrCancel: "Все/Частково",
              bookOrCancel: "Бронювати або скасувати",
              label: "Виконання",
              return: "Повернути",
            },
            executionMode: {
              exchange: "Біржове виконання",
              instant: "Негайне виконання",
              market: "Виконання за ринком",
              request: "Виконання за запитом",
            },
            expiration: {
              date: "Дата закінчення",
              label: "Експірація",
              types: {
                specified: "Дата та час",
                specifiedDay: "Вказаний день",
                today: "Сьогодня",
              },
            },
            fields: {
              closeBy: "Закрити зустрічною",
              comment: "Коментар",
              price: "Ціна",
              stopLoss: "Стоп Лосс",
              takeProfit: "Тейк Профіт",
              volume: "Об'єм",
              errors: {
                volume: {
                  min: "Мінімальний об'єм – {min}",
                  max: "Максимальний об'єм – {max}",
                  required: "Volume is required",
                  step: "Об'єм можна задавати з кроком {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Історія",
            deals: {
              columns: {
                comment: "Коментар",
                commission: "Комісія",
                direction: "Напрямок",
                fee: "Збір",
                order: "Ордер",
                price: "Ціна",
                profit: "Прибуток",
                swap: "Своп",
                symbol: "Символ",
                ticket: "Тікет",
                time: "Час",
                type: "Тип",
                volume: "Об'єм",
              },
            },
            empty: "У вас поки немає торгової історії",
            menu: {
              columns: {
                horizontalScroll: "Горизонтальне прокручування",
                resetAll: "Скинути все",
                title: "Стовпці",
              },
              deals: "Угоди",
              orders: "Ордери",
              period: {
                all: "Вся історія",
                last3Months: "Останні 3 місяці",
                last6months: "Останні 6 місяців",
                lastMonth: "Останній місяць",
                title: "Період",
                customPeriod: "Вибрати період",
                lastYear: "Останній рік",
                lastWeek: "Останній тиждень",
                today: "Сьогодня",
              },
              positions: "Позиції",
              chart: "Графік",
              newOrder: "Новий ордер",
            },
            orders: {
              columns: {
                comment: "Коментар",
                price: "Ціна",
                slDescription: "Стоп Лосс",
                state: "Стан",
                symbol: "Символ",
                ticket: "Тікет",
                timeDone: "Час",
                timeSetup: "Час",
                tpDescription: "Тейк Профіт",
                type: "Тип",
                volume: "Об'єм",
                timeSetupDescription: "Час відкриття",
                timeDoneDescription: "Час закриття",
              },
              total: {
                title: "Усього",
                filled: "Заповнено",
                canceled: "Скасовано",
                rejected: "Відхилено",
              },
            },
            positions: {
              columns: {
                commission: "Комісія",
                fee: "Збір",
                priceClose: "Ціна",
                priceCloseDescription: "Ціна закриття",
                priceOpen: "Ціна",
                priceOpenDescription: "Ціна відкриття",
                profit: "Прибуток",
                slDescription: "Стоп Лосс",
                swap: "Своп",
                symbol: "Символ",
                ticket: "Тікет",
                timeClose: "Час",
                timeCloseDescription: "Час закриття",
                timeOpen: "Час",
                timeOpenDescription: "Час відкриття",
                tpDescription: "Тейк Профіт",
                type: "Тип",
                volume: "Об'єм",
                comment: "Коментар",
              },
            },
            columns: { default: "За замовчуванням" },
            total: {
              profit: "Прибуток",
              credit: "Кредит",
              deposit: "Поповнення",
              withdrawal: "Зняття",
              balance: "Баланс",
              commission: "Комісія",
              fee: "Збір",
              swap: "Своп",
              grossProfit: "Загальний прибуток",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Торгівельна історія",
                orders: "Торгові ордери",
                position: "Торгові позиції",
                sltp: "Рівні СЛ/ТП",
              },
              notification: "Торгові повідомлення",
            },
            oneClick: "Торгівля в один клік",
            tags: { demo: "Демо", readonly: "Тільки перегляд" },
            oneClickBottom: "Панель торгівлі в один клік під графіком",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Я приймаю ці умови",
            btnAccept: "Прийняти",
            btnCancel: "Скасування",
            text: 'Ви збираєтесь активувати режим "Торгівля в один клік". Натиснувши "Я приймаю ці умови", вы тім самим підтверджуєте, що прочитали, зрозуміли і погоджуєтеся з усіма нижченаведеними умовами.<br /><br />Ви можете включити або відключити режим "Торгівля в один клік" у меню веб-терміналу.<br /><br />Режим відправки торгових наказів "Торгівля в один клік" складається з одного етапу. Ваш торговий наказ буде надіслано одразу: &mdash; при натисканні кнопок з ціною пропозиції (SELL) або купівлі (BUY) на панелі торгівлі в один клік на графіку &mdash; при натисканні кнопок "Sell", "Buy", "Закрыть" та команд встановлення ордерів в вікні "Стакан цін" &mdash; при закритті позиції та видаленні ордерів на вкладці "Торгівля"<br /><br />ВАМ НЕ БУДЕ ПРОПОНОВАНО ПІДТВЕРДИТИ ТОРГОВИЙ НАКАЗ. ВИ НЕ ЗМОЖЕТЕ СКАСУВАТИ АБО ЗМІНЮВАТИ СВІЙ ОРДЕР ПІСЛЯ НАТИСКАННЯ. ЗА НОРМАЛЬНИХ РИНКОВИХ УМОВ ТА ПРОДУКТИВНОСТІ СИСТЕМИ РИНКОВИЙ НАКАЗ БУДЕТ ОПЕРАТИВНО ВИКОНАНИЙ ПІСЛЯ ВІДПРАВКИ НАКАЗУ, ТА ПІСЛЯ ЦЬОГО ВИ БУДЕТЕ ЗВ\'ЯЗАНІ ЗОБОВ\'ЯЗАННЯМИ УГОДИ.<br /><br />Ви згодні прийняти всі ризики, пов\'язані з використанням режиму "Торгівля в один клік", зокрема, без обмеження всі ризики помилок, упущень чи прорахунків, допущених під час відправлення такого торгівельного наказу.<br /><br />Ви згодні повною мірою захистити {companyName} від будь-яких збитків та витрат, які можуть бути понесені внаслідок таких помилок, упущень чи прорахунків, допущених вами чи будь-якою іншою людиною, що торгує від вашого імені.',
            title: "Торгівля в один клік - Відмова від відповідальності",
          },
          quickTrade: {
            hide: "Сховати панель торгівлі в один клік",
            show: "Показати панель торгівлі в один клік",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Я усвідомлюю ризики і хочу торгувати інвестиційними продуктами",
            btnAccept: "Прийняти",
            btnCancel: "Скасування",
            text: "Інформуємо вас про те, що подальше використання цієї торгівельної платформи передбачає доступ до високоризикованих  інвестиційних продуктів, що надаються фінансовим інститутом на ваш вибір. Інвестування у такі продукти може не підходити для всіх інвесторів, оскільки несе в собі ризик часткової або повної втрати депозиту.<br /><br />Перш ніж вирішити торгувати  високоризикованими інвестиційними продуктами, вам слід уважно оцінити свої інвестиційні цілі, рівень підготовки та допустимі ризики. існує ймовірність втрати коштів, що перевищує ваші початкові інвестиції, тому вам не слід інвестувати кошти, які ви не можете собі дозволити втратити.<br /><br />Закликаємо вас розширити свій кругозір щодо всіх факторів ризику, пов'язаних з інвестуванням у такі продукти, а також у разі будь-яких сумнівів проконсультуватися з професійним фінансовим радником.",
            title: "Попередження про ризики інвестора",
          },
          table: {
            btnOpen: "Торгівля",
            columns: {
              comment: "Коментар",
              priceClose: "Ціна",
              priceCloseDescription: "Ціна закриття",
              priceOpen: "Ціна",
              priceOpenDescription: "Ціна відкриття",
              profit: "Прибуток",
              slDescription: "Стоп Лосс",
              swap: "Своп",
              symbol: "Символ",
              ticket: "Тікет",
              time: "Час",
              tpDescription: "Тейк Профіт",
              type: "Тип",
              volume: "Об'єм",
            },
            emptyPlug: {
              btnNewOrder: "Створити новий ордер",
              title: "У вас немає позицій",
            },
            menu: {
              chart: "Чарт",
              closePosition: "Закрити позицію",
              columns: "Стовпці",
              modifyOrder: "Змінити ордер",
              modifyPosition: "Змінити позицію",
              newOrder: "Новий ордер",
              resetAll: "Скинути все",
              deleteOrder: "Видалити ордер",
            },
            oneClick: { deleteOrder: "Видалити" },
            sections: {
              collateralPositions: "Collateral-позиції",
              orders: "Ордери",
              positions: "Позиції",
            },
            total: {
              assets: "Активи",
              balance: "Баланс",
              collateral: "Collateral",
              commission: "Комісія",
              credit: "Кредит",
              equity: "Кошти",
              liabilities: "Зобов'язання",
              margin: "Маржа",
              marginFree: "Вільна маржа",
              marginLevel: "Рівень",
            },
          },
          timer: {
            marketWillOpen: "Ринок відкриється через {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} днів",
            oneDay: "{numberOfDays} день",
          },
          tradeIsDisabled: {
            account: "Для вашого рахунку торгівлю відключено на сервері",
            collateral: "Для collateral-інструментів торгівля недоступна",
            disabled: "Торгівля відключена",
            investor:
              "Торгівля недоступна, оскільки ви підключені з інвестиційним паролем",
            readOnly:
              "Торгівля недоступна, оскільки ви не прийняли угоду про ризики",
            symbol: "Торгівля для цього символу відключена",
          },
          hotkeys: {
            historyPanel: "Панель історії",
            journalPanel: "Журнал",
            marketWatch: "Огляд ринку",
            quickTrade: "Торгівля в один клік",
            tradeForm: "Новий ордер",
            tradePanel: "Торгова панель",
          },
          marketOpen: {
            time: "Ринок закритий - відкриття {time}",
            afterSeconds: "Ринок закритий - відкриття через {time} сек",
          },
          expiredTimer: { seconds: "Спливає через {time} сек" },
          corporateLink: {
            type: {
              clientAgreement: "Угода з клієнтом",
              riskDisclosure: "Повідомлення про ризики",
              fdmDisclaimer: "Відмова від відповідальності FDM",
              clientAgreementAndRiskDisclosure:
                "Угода з клієнтом і повідомлення про ризики",
              complaintsHandlingProcedure: "Процедура обробки скарг",
              orderExecutionPolicy: "Політика виконання ордерів",
              clientCategorisationNotice: "Порядок категоризації клієнтів",
              conflictsOfInterestPolicy: "Положення про конфлікт інтересів",
              dataProtectionPolicy: "Політика захисту даних",
            },
          },
          margin: {
            floating: "плаваюча",
            mode: {
              marketBuy: "Ринковий ордер Buy",
              marketSell: "Ринковий ордер Sell",
            },
            rangeMode: {
              value: "номінальна вартість",
              valuePerSymbol: "номінальна вартість за символом",
              volume: "обсяг",
              volumePerSymbol: "обсяг за символом",
            },
            showValue: "Показувати значення в {currency} за лот",
            rates: "Маржа:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Відключити повноекранний режим",
            enable: "Включити повноекранний режим",
          },
          journal: {
            btnOpen: "Журнал",
            columns: {
              message: "Повідомлення",
              source: "Джерело",
              time: "Час",
            },
            menu: {
              clear: "Очистити",
              debugMode: "Режим налагодження",
              exportFile: "Експортувати у файл",
            },
          },
          menu: {
            about: "Про додаток",
            contact: "Зв'яжіться з нами",
            brokerInformation: "Інформація про компанію",
            chartSettings: {
              controls: "Управління графіком",
              grid: "Сітка",
              ohlc: "Показувати OHLC",
              title: "Налаштування графіка",
              askPrice: "Ціна Ask",
              crosshair: "Курсор з перехрестям",
            },
            connect: "Підключитись до рахунку",
            language: {
              title: "Мова",
              search: "Пошук",
              nothingFound: "Мову не знайдено",
            },
            openDemo: "Відкрити демо-рахунок",
            openReal: "Відкрити реальний рахунок",
            settings: "Установки",
            shortcuts: "Гарячі клавіші",
            theme: {
              blackWhite: "Чорно-біла",
              blueRed: "Синьо-червона",
              dark: "Темна тема",
              editor: "Редактор тем",
              greenRed: "Зелено-червона",
              light: "Світла тема",
              neutral: "Нейтральна",
              templates: "Колірні схеми",
            },
            title: "Меню",
            tradingAccount: "Торгові рахунки",
            terms: "Умови та положення",
            desktopPlatforms: "Десктопні платформи",
            qrCode: {
              install: "Відскануйте для встановлення з {store}",
              downloadApk: "Відскануйте для отримання файлу APK для Android",
            },
            economicCalendar: "Календар",
          },
          screen: { back: "Назад" },
          mobile: { bottomNav: { quotes: "Котирування" } },
          hotkeys: {
            sections: { navigation: "Навігація", view: "Вид" },
            escape: "Відміна",
            indicators: "Індикатори",
            depthOfMarket: "Стакан цін",
            objectTreePanel: "Дерево об'єктів",
            scrollRight: "Наступна свічка",
            scrollToStart: "Прокрутити графік до початку",
            scrollLeft: "Попередня свічка",
            scrollToEnd: "Прокрутити графік до кінця",
            resetChartView: "Скинути графік",
            zoomIn: "Збільшити",
            zoomOut: "Зменшити",
            fullScreen: "Повний екран",
            screenshot: "Зберегти графік як зображення",
            title: "Гарячі клавіші",
          },
          timezone: {
            title: "Часовий пояс",
            city: {
              cairo: "Каїр",
              casablanca: "Касабланка",
              johannesburg: "Йоганнесбург",
              lagos: "Лагос",
              nairobi: "Найробі",
              tunis: "Туніс",
              anchorage: "Анкоридж",
              bogota: "Богота",
              buenosAires: "Буенос-Айрес",
              caracas: "Каракас",
              chicago: "Чикаго",
              denver: "Денвер",
              elSalvador: "Сальвадор",
              juneau: "Джуно",
              lima: "Ліма",
              losAngeles: "Лос-Анджелес",
              mexicoCity: "Мехіко",
              newYork: "Нью-Йорк",
              phoenix: "Фенікс",
              santiago: "Сантьяго",
              saoPaulo: "Сан-Паулу",
              toronto: "Торонто",
              vancouver: "Ванкувер",
              almaty: "Алмати",
              ashgabat: "Ашхабад",
              bahrain: "Бахрейн",
              bangkok: "Бангкок",
              kolkata: "Колката",
              colombo: "Коломбо",
              dhaka: "Дакка",
              dubai: "Дубай",
              hongKong: "Гонконг",
              jakarta: "Джакарта",
              jerusalem: "Єрусалим",
              karachi: "Карачі",
              kathmandu: "Катманду",
              kuwait: "Кувейт",
              manila: "Маніла",
              muscat: "Мускатний",
              nicosia: "Нікосія",
              qatar: "Катар",
              rangoon: "Рангун",
              riyadh: "Ер-Ріяд",
              saigon: "Сайгон",
              seoul: "Сеул",
              shanghai: "Шанхай",
              singapore: "Сінгапур",
              taipei: "Тайбей",
              tehran: "Тегеран",
              tokyo: "Токіо",
              reykjavik: "Рейк'явік",
              adelaide: "Аделаїда",
              brisbane: "Брісбен",
              perth: "Перт",
              sydney: "Сідней",
              amsterdam: "Амстердам",
              athens: "Афіни",
              belgrade: "Белград",
              berlin: "Берлін",
              bratislava: "Братислава",
              brussels: "Брюссель",
              bucharest: "Бухарест",
              budapest: "Будапешт",
              copenhagen: "Копенгаген",
              dublin: "Дублін",
              helsinki: "Гельсінкі",
              istanbul: "Стамбул",
              lisbon: "Лісабон",
              london: "Лондон",
              luxembourg: "Люксембург",
              madrid: "Мадрид",
              malta: "Мальта",
              moscow: "Москва",
              oslo: "Осло",
              paris: "Париж",
              prague: "Прага",
              riga: "Рига",
              rome: "Рим",
              stockholm: "Стокгольм",
              tallinn: "Таллінн",
              vienna: "Відень",
              vilnius: "Вільнюс",
              warsaw: "Варшава",
              zurich: "Цюріх",
              auckland: "Окленд",
              chatham: "Чатем",
              fakaofo: "Факаофо",
              honolulu: "Гонолулу",
              norfolk: "Норфолк",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e as u };
