const a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Sembunyikan Peristiwa Kalender Ekonomi dari Grafik",
              show: "Tampilkan Peristiwa Kalender Ekonomi di Grafik",
            },
          },
          controls: {
            reset: "Atur Ulang Grafik",
            scrollEnd: "Gulir ke Akhir",
            scrollLeft: "Gulir ke Kiri",
            scrollRight: "Gulir ke Kanan",
            zoomIn: "Perbesar",
            zoomOut: "Perkecil",
          },
          crosshair: "Crosshair",
          delay: "{delay} menit penundaan",
          indicators: {
            btnAddIndicator: "Tambah indikator",
            btnOpenPopup: "Tambah Indikator",
            close: "Tutup",
            form: {
              applyTo: "Aplikasikan pada",
              background: {
                title: "Latar Belakang",
                down: "Latar belakang kumo bawah",
                up: "Latar belakang kumo atas",
              },
              deviation: "Selisih",
              enterDistance: "Periode",
              enterShift: "Geser",
              fastEma: "EMA Cepat",
              slowEma: "EMA Lambat",
              line: {
                base: "Garis dasar",
                down: "Garis bawah",
                minusDI: "Garis -DI",
                null: "Garis nol",
                plusDI: "Garis +DI",
                style: "Gaya garis",
                cci: "Jalur CCI",
                up: "Garis atas",
                fi: "Jalur FI",
              },
              maximum: "Maksimal",
              method: {
                exponential: "Eksponensial",
                linearWeighted: "Berbobot Linier",
                simple: "Sederhana",
                smoothed: "Perhalus",
                title: "Metode",
              },
              opacity: "Kegelapan",
              period: {
                jaws: "Periode Jaws",
                lips: "Periode Lips",
                teeth: "Periode Teeth",
                title: "Periode",
                dPercent: "Periode %D",
                kPercent: "Periode %K",
              },
              selectApplyTo: "Memilih",
              selectVolumesType: "Pilih jenis volume",
              shift: "Pergeseran",
              showTimeframes: "Tampilkan Semua frame waktu",
              slowing: "Perlahan",
              step: "Langkah",
              style: {
                down: "Gaya turun",
                jaws: "Gaya Jaws",
                lips: "Gaya Lips",
                main: "Gaya utama",
                signal: "Gaya sinyal",
                teeth: "Gaya Teeth",
                title: "Gaya",
                up: "Gaya naik",
                rvi: "Gaya RVI ",
              },
              volume: { down: "Volume Turun", up: "Volume Naik" },
              volumes: "Volume",
              mfiUp: "MFI Naik",
              mfiDown: "MFI Turun",
              price: {
                title: "Harga",
                select: "Pilih harga",
                lowHigh: "Rendah/Tinggi",
                closeClose: "Tutup/Tutup",
              },
            },
            search: {
              empty: "Tidak ada item yang ditemukan",
              title: "Mencari",
              tryAnother: "Silahkan coba kueri lain",
            },
            tabs: {
              all: "Semua",
              billWilliams: "Bill Williams",
              oscillators: "Oscillator",
              trend: "Tren",
              volumes: "Volume",
            },
            title: "Pilih indikator",
            up: "Naik",
            down: "Turun",
            chartControls: {
              show: "Tampilkan",
              hide: "Sembunyikan",
              settings: "Pengaturan",
              remove: "Hapus",
            },
          },
          loading: "Memuat",
          marketWatch: {
            btnOpen: {
              hide: "Sembunyikan Market Watch",
              show: "Tunjukkan Market Watch",
            },
            columns: {
              closePrice: "Harga Penutupan",
              dailyChange: "Perubahan Harian",
              openPrice: "Harga Buka",
              spread: "Sebaran",
              symbol: "Simbol",
              time: "Waktu",
              high: "Tinggi",
              low: "Rendah",
              last: "Terakhir",
              lastHigh: "Tertinggi Terakhir",
              lastLow: "Terendah Terakhir",
              highLow: "Tinggi/Rendah",
              bidLow: "Penawaran Terendah",
              bidHigh: "Penawaran Tertinggi",
              askHigh: "Permintaan Tertinggi",
              askLow: "Permintaan Terendah",
              bid: "Penawaran",
              ask: "Permintaan",
              title: "Kolom",
            },
            menu: {
              chart: "Grafik",
              columns: "kolom",
              dom: "Kedalaman Pasar",
              hide: "Sembunyikan",
              newOrder: "Order Baru",
              specification: "Properties",
            },
            search: "Pencarian",
            searchSymbol: "Simbol pencarian",
            nothingFound: "Tidak ditemukan simbol",
          },
          objects: {
            form: {
              statistics: "Statistik",
              arrows: "Panah",
              showAlways: "Selalu tampilkan",
              angle: "Sudut",
              distance: "Jarak",
              bar: "Batang",
              price: "Harga",
              prices: "Harga",
              showPrice: "Tampilkan harga",
              showText: "Tampilkan teks",
              showDate: "Tampilkan tanggal",
              showTime: "Tampilkan waktu",
              showAllTimeframes: "Tampilkan Semua frame waktu",
              showPearsonR: "Tampilkan R Pearson",
              showLabels: "Tampilkan label",
              yourText: "Teks anda",
              props: "Properti",
              style: "Gaya",
              rays: "Sinar",
              background: "Latar Belakang",
              extends: "Perpanjangan",
              extended: "Perpanjangan",
              pipsPerBar: "Pip per bar",
              gannAngle: "Sudut Gann",
              deviations: "Selisih",
              labels: "Label",
              reverse: "Membalikkan",
              btn: { update: "Pembaharuan", cancel: "Batal" },
              tabs: {
                style: "Gaya",
                coordinates: "Koordinat",
                visualization: "Penampilan",
              },
              range: {
                price: "Kisaran harga",
                bars: "Kisaran batang",
                date: "Kisaran tanggal",
              },
              align: {
                horizontal: "Penjajaran datar",
                vertical: "Penjajaran vertikal",
                left: "Kiri",
                right: "kanan",
                center: "Tengah",
                top: "Atas",
                middle: "Tengah",
                bottom: "Bawah",
              },
              line: {
                style: "Gaya garis",
                base: "Garis dasar",
                up: "Garis atas",
                down: "Garis bawah",
                middle: "Garis tengah",
              },
            },
            visible: {
              hide: "Sembunyikan Semua Objek",
              show: "Tampilkan Semua Objek",
            },
            lock: "Kunci Semua Objek",
            unlock: "Buka Kunci Semua Objek",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Saluran Equidistand",
            regressionChannel: "Regression Channel",
            stdDevChannel: "Standard Deviation Channel",
            fibonacciRetracement: "Fibonacci Retracement",
            gannFan: "Gann Fan",
            gannGrid: "Gann Grid",
            gannLine: "Garis Gann",
            arrowLine: "Garis Panah",
            crossLine: "Garis Silang",
            extendedLine: "Garis Perpanjangan",
            horizontalRay: "Sinar Datar",
            horizontalLine: "Garis Datar",
            infoLine: "Garis Info",
            rayLine: "Ray",
            trendAngle: "Tren bedasar sudut",
            trendline: "Garis tren",
            verticalLine: "Garis Tegak",
            disjointAngle: "Pisahkan Saluran",
            flatTopBottom: "Datar Atas/Bawah",
            rectangle: "Kotak",
            circle: "Lingkaran",
            triangle: "Segitiga",
            ellipse: "Lingkaran",
            text: "Teks",
            rulerLine: "Garis Mistar",
          },
          period: {
            full: {
              D1: "Harian",
              H1: "1 Jam",
              H4: "4 Jam",
              M1: "1 Menit",
              M15: "15 Menit",
              M30: "30 Menit",
              M5: "5 Menit",
              MN: "Bulanan",
              Unknown: "Tidak dikenal",
              W1: "Mingguan",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Tidak dikenal",
              W1: "W1",
            },
          },
          screenshot: "Simpan Grafik sebagai Gambar",
          symbolSpecs: {
            GTCmode: "Mode GTC",
            calculation: "Kalkulasi",
            chartMode: "Mode grafik",
            contractSize: "Besar kontrak",
            days: {
              friday: "Jumat",
              monday: "Senin",
              saturday: "Sabtu",
              sunday: "Minggu",
              thursday: "Kamis",
              tuesday: "Selasa",
              wednesday: "Rabu",
            },
            digits: "Digit",
            empty: "Tidak ada simbol yang dipilih",
            execution: "Pelaksanaan",
            expiration: "Masa Berakhir",
            filling: "Kebijakan Pengisian",
            initial: "Awal",
            maintenance: "Perawatan",
            marginCurrency: "Margin mata uang",
            marginRate: "Nilai Margin",
            maxVolume: "Volume maksimal",
            minVolume: "Volume minimal",
            orders: "Order",
            profitCurrency: "Keuntungan mata uan",
            schedule: { quotes: "Quotes", trade: "Trade" },
            sector: "Sektor",
            spread: "Sebaran",
            stopsLevel: "Level Stop",
            swapLong: "Swap lama",
            swapShort: "Swap singkat",
            swapType: "Tipe swap",
            title: "{symbol} spesifikasi kontrak",
            tradeMode: "Trade",
            volumeStep: "Tahapan volume",
            volumeLimit: "Batas volume",
            tickSize: "Ukuran tick",
            tickValue: "Nilai Tick",
            marginInitial: "Margin awal",
            marginHedged: "Margin lindung nilai",
            commission: {
              daily: {
                volume: "Volume harian dalam lot",
                turnoverVolume: "Omset harian dalam lot",
                turnoverMoney: "Omset harian dalam uang",
                value: "Nilai transaksi harian",
                profit: "Keuntungan harian",
              },
              monthly: {
                volume: "Volume bulanan dalam lot",
                turnoverVolume: "Omset bulanan dalam lot",
                turnoverMoney: "Omset bulanan dalam uang",
                value: "Nilai transaksi bulanan",
                profit: "Keuntungan bulanan",
              },
              instant: {
                volume: "Instan dengan volume transaksi",
                value: "Instan dengan nilai transaksi",
                profit: "Instan dengan keuntungan transaksi",
              },
              entry: {
                in: "di dalam kesepakatan",
                out: "di luar kesepakatan",
                all: "di dalam/di luar kesepakatan",
              },
              tier: {
                mode: {
                  pips: "point",
                  percent: "% dalam {currency}",
                  percentProfit: "% dari keuntungan {currency}",
                },
                type: { perDeal: "per kesepakatan", perLot: "per lot" },
              },
              header: "Komisi",
            },
          },
          tree: {
            close: "Tutup",
            empty: "Anda tidak memiliki objek apapun di grafik",
            lock: "Mengunci",
            remove: "Hapus",
            settings: "Pengaturan",
            title: "Kelola Gambar",
            unlock: "Membuka kunci",
          },
          types: {
            area: "Bidang",
            line: "Garis",
            bars: "Batang",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Volume Tick",
            volumes: "Volume",
            withoutVolumes: "Tanpa Volume",
            realVolumes: "Volume sebenarnya",
          },
          zoom: { in: "Perbesar", out: "Perkecil" },
          hotkeys: {
            arrowLine: "Garis Panah",
            chartTypeArea: "Grafik Area",
            chartTypeLine: "Grafik Garis",
            chartTypeBar: "Chart Bar",
            chartTypeCandle: "Grafik Lilin",
            crossLine: "Garis Silang",
            extendedLine: "Garis Perpanjangan",
            horizontalLine: "Garis Datar",
            infoLine: "Garis Info",
            rayLine: "Ray",
            realVolumes: "Volume Nyata",
            tickVolumes: "Volume Tick",
            trendline: "Garis tren",
            verticalLine: "Garis Tegak",
            sections: {
              chartType: "Jenis Grafik",
              drawing: "Menggambar",
              volume: "Volume",
            },
            crosshairRuler: "Garis tanda silang",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Mulailah dengan akun anda",
            newAccountOpened: "Akun baru dibuka",
          },
          brokerInformation: {
            company: "Perusahaan",
            email: "Email",
            phone: "Telephone",
            registrationAddress: "Alamat Pendaftaran",
            title: "Informasi Perusahaan",
            website: "Situs web",
          },
          changePassword: {
            btnChange: "Ubah Kata Kunci",
            confirmPassword: "Konfirmasi Kata Sandi",
            newPassword: "Kata Sandi Baru",
            title: "Ubah Kata Sandi",
          },
          connect: {
            btnConnect: "Hubungkan ke akun",
            contactBroker: "Hubungi perusahaan",
            forgotPassword: "Tidak ingat kata sandi?",
            loginPlaceholder: "Masukkan Login",
            passwordPlaceholder: "Masukkan Kata Sandi",
            savePassword: "Simpan kata kunci",
            title: "Hubungkan ke akun",
          },
          copyToClipboard: {
            copy: "Salin ke clipboard",
            unsupported: "Menyalin tidak didukung",
          },
          demo: {
            accountOpeningWarning:
              "Dengan membuka akun, anda menyetujui persyaratan pembukaan akun dan kebijakan perlindungan data {brokerName}",
            btnOpenDemo: "Buka akun Demo",
            title: "Buka akun Demo",
            tradeWithRealMoney:
              "Untuk trading dengan uang sungguhan, anda harus membuat perjanjian terpisah dengan perusahaan jasa keuangan.",
          },
          disclaimer: {
            btnAccept: "Terima",
            headerTitle: "Selamat datang di MetaTrader 5",
            text: 'MetaQuotes Ltd adalah perusahaan pengembang perangkat lunak dan tidak menyediakan layanan keuangan, investasi, broker, trading, atau data feed, juga tidak terlibat dalam pembayaran berbasis komisi terkait operasi trading apapun.<br /><br /> Dengan menekan tombol TERIMA, saya menyetujui dengan <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">syarat dan ketentuan EULA</a>, <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Kebijakan Privasi</a> dan Penafian.<br /><br /> Tidak ada informasi yang tersedia dalam aplikasi yang dimaksudkan sebagai nasihat investasi. Sebelum menggunakan aplikasi ini untuk trading, anda harus meminta saran dari profesional sekuritas yang berkualifikasi dan terdaftar dan melakukan uji tuntas anda sendiri.',
            title: "Sangkalan",
          },
          errors: {
            error: "Kesalahan",
            invalidCode: "Kode salah",
            invalidEmail: "Email salah",
            invalidPhone: "Telepon tidak valid",
            unknownError: "Kesalahan tidak diketahui",
          },
          form: {
            accountType: "Tipe Akun",
            address: "Alamat",
            addressPlaceholder: "Masukkan alamat anda",
            annualDeposit: "Deposit tahunan",
            annualIncome: "Gaji tahunan",
            broker: "Perusahaan",
            btn: {
              back: "Kembali",
              cancel: "Batal",
              next: "Berikutnya",
              openAccount: "Buka Akun",
              remove: "Hapus",
              signOut: "Keluar",
            },
            city: "Kota",
            cityPlaceholder: "Masukkan kota anda",
            country: "Negara",
            dateBirth: "Tanggal lahir",
            deposit: "Deposito",
            education: "Pendidikan",
            email: {
              address: "Email",
              code: "Kode dari email",
              placeholder: "Masukan email",
              title: "Email",
            },
            employement: "Pekerjaan",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Wanita", male: "Pria", title: "Jenis kelamin" },
            identity: "Identitas",
            imageOrPdfFile: "Dokumen gambar atau PDF",
            investor: "Investor",
            language: "Bahasa",
            leverage: "Leverage",
            login: "Login",
            min5chars: "Min 5 karakter",
            name: {
              middle: "Nama tengah",
              surname: "Nama Panggilan",
              title: "Nama",
              yourName: "Nama Anda",
            },
            nationality: "Kewarganegaraan",
            netWorth: "Nilai bersih",
            optional: "Opsional",
            password: "Kata kunci",
            passwordReadOnly: "Kata Sandi baca saja",
            phone: {
              mobile: "Ponsel seluler",
              number: "Nomor telepon",
              sms: "Kode dari SMS",
            },
            pleaseSelect: "Silahkan pilih",
            policyCheckbox:
              "Saya setuju dengan syarat dan ketentuan untuk membuka akun dan kebijakan perlindungan data",
            server: "Server",
            side: { back: "Sisi belakang", front: "Sisi depan" },
            sourceWealth: "Sumber kekayaan",
            state: "Kondisi",
            status: "Status",
            stocks: "Saham",
            taxID: "Identitas pajak",
            type: "Tipe",
            useHedge: "Menggunakan hedge dalam transaksi",
            verificationCodes: {
              email: "Kami telah mengirimkan kode verifikasi ke email anda",
              phone: "Kami telah mengirimkan kode verifikasi ke ponsel anda",
              phoneEmail:
                "Kami telah mengirimkan kode verifikasi ke ponsel dan email anda",
            },
            zipCode: "Kode Pos",
          },
          mainForm: {
            title: "Akun trading",
            titleWithName: "Akun trading: {brokerName}",
          },
          otp: {
            disable2FA: "Nonaktifkan 2FA/TOTP",
            disable2FAAccount: "Nonaktifkan 2FA/TOTP untuk akun {login}",
            disableEnterCode:
              "Untuk menonaktifkan 2FA/TOTP, masukkan kode akun anda yang dibuat oleh Authenticator.",
            downloadApp:
              "Silakan unduh Aplikasi Google Authenticator / Microsoft Authenticator / Authy ke perangkat seluler anda dan pindai kode QR:",
            enable2FA: "Aktifkan 2FA/TOTP",
            enable2FAAccount: "Aktifkan 2FA/TOTP untuk akun {login}",
            enterCode:
              "Untuk memeriksa operasi Authenticator, masukkan kode akun anda yang dibuat oleh Aplikasi.",
            oneTimePassword: "Kata sandi satu kali:",
            placeholder: "Masukkan OTP akun",
            required: "Otentikasi 2FA diperlukan untuk keamanan akun tambahan.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Laporan bank",
              utilityBill: "Tagihan utilitas",
            },
            conditionsForUploadingFiles: {
              documents:
                "Beberapa jenis dokumen memerlukan dua foto: sisi depan dan belakang",
              proofAddress:
                "Tagihan untuk layanan seluler tidak diterima sebagai bukti alamat",
              utilityBill:
                "Tagihan utilitas harus berisi nama dan alamat anda dan tidak lebih dari 3 bulan",
            },
            documentType: {
              driverLicense: "SIM",
              idCard: "Kartu identitas",
              passport: "Paspor",
              residencePermit: "Ijin tinggal",
            },
            educationLevel: {
              bachelor: "Sarjana atau sederajat",
              highScholl: "Sekolah Menengah Atas",
              master: "Gelar master atau sederajat",
              none: "Tidak ada",
              other: "Lainnya",
              phd: "Gelar profesi atau sederajat",
            },
            employment: {
              employed: "Bekerja",
              other: "Lainnya",
              retired: "Pensiunan",
              selfEmployed: "Pemilik bisnis atau wiraswasta",
              student: "Pelajar",
              unemployed: "Pengangguran",
            },
            experience: "Pengalaman trading real:",
            experienceLevel: {
              above3: "> 3 tahun",
              form1to3: "1 sampai 3 tahun",
              less1: "< 1 tahun",
            },
            industry: {
              agriculture: "Pertanian",
              communication: "Seni, Teknologi Audio/Video dan Komunikasi",
              construction: "Arsitektur dan Konstruksi",
              education: "Pendidikan",
              engineering: "Teknik dan Matematika",
              government: "Pemerintahan dan Administrasi Publik",
              healthcare: "Kesehatan",
              it: "Teknologi Informasi",
              management: "Manajemen dan administrasi bisnis",
              manufacturing: "Manufaktur",
              marketing: "Pemasaran dan Penjualan",
              none: "Tidak ada",
              other: "Lainnya",
              science: "Ilmu pengetahuan dan teknologi",
              security: "Hukum, Keamanan umum, dan Satpam",
              tourism: "Perhotelan dan Pariwisata",
              transport: "Transportasi, Distribusi dan Logistik",
            },
            policy:
              "Informasi pribadi digunakan untuk membuka akun Trading dan tidak dilewatkan ke pihak ketiga manapun. Informasi tersebut ditangani secara aman dan rahasia.",
            takePhoto:
              "Silahkan, ambil foto dokumen anda dan unggah di sini tanpa pengeditan apapun",
            title: "Buka akun real",
            wealthSource: {
              employment: "Pekerjaan",
              inheritance: "Hadiah atau Warisan",
              other: "Lainnya",
              savings: "Tabungan atau Investasi",
            },
          },
          saveAccountData:
            "Harap simpan login dan kata sandi anda di tempat yang aman",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  n = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Tutup",
            empty: "Kami tidak memiliki data volume untuk simbol ini",
            extendedBook: {
              hide: "Sembunyikan Buku yang Diperpanjang",
              show: "Tampilkan Buku yang Diperpanjang",
            },
            menu: {
              amount: "Jumlah Lots yang dibuka",
              extended: "Perpanjangan",
              spread: "Sebaran",
            },
            spread: { hide: "Sembunyikan Sebaran", show: "Tampilkan Sebaran" },
            stopLoss: "Stop Rugi",
            takeProfit: "Ambil Keuntungan",
            title: "Kedalaman Pasar",
          },
          errors: {
            accepted: "Diterima",
            allowedOnlyLongPositions: 'Hanya posisi "long" yang diperbolehkan',
            allowedOnlyPositionsClosing:
              "Hanya posisi tertutup yang diperbolehkan",
            allowedOnlyShortPositions:
              'Hanya posisi "short" yang diperbolehkan',
            automatedTradingDisabledClient:
              "Trading Otomatis tidak diaktifkan di terminal klien",
            automatedTradingDisabledServer:
              "Trading Otomatis di non aktifkan oleh pihak server",
            canceled: "Dibatalkan",
            common: "Kesalahan Umum",
            demoAllocationDisabled: "Alokasi akun demo dinonaktifkan",
            done: "Selesai",
            donePartially: "Selesai secara parsial",
            frequentRequests: "Permintaan terlalu sering",
            invalidExpiration: "Waktu berakhir salah",
            invalidOrderType: "Tipe order salah",
            invalidParameters: "Parameter salah",
            invalidPrices: "Harga salah",
            invalidSLTP: "S/L atau T/P salah",
            invalidVolume: "Volume salah",
            manyTradeRequests: "Terlalu banyak permintaan trade",
            marketClosed: "Pasar ditutup",
            modificationFailed:
              "Modifikasi gagal karena order atau posisi terlalu dekat dengan pasar",
            networkProblem: "Jaringan Bermasalah",
            noConnection: "Tidak ada hubungan",
            notEnoughMoney: "Dana tidak mencukupi",
            offQuotes: "Off quotes",
            ok: "OKE",
            onTheWay: "Dalam perjalanan",
            orderChanged: "order telah diubah",
            orderClosePositionExists:
              "Sudah ada perintah tutup untuk pesanan ini",
            ordersLimitReached: "Batas order telah tercapai",
            permissions: "Ijin tidak mencukupi",
            placed: "Ditempatkan",
            positionCloseProhibitedByFIFO:
              "Posisi tertutup dilarang oleh aturan FIFO",
            positionClosed: "Posisi telah tertutup",
            positionsLimitReached: "Batas posisi tercapai",
            priceChanged: "Harga telah berubah",
            prices: "Harga",
            processed: "Diproses",
            rejected: "Telah ditolak",
            requestRejectedOrderWillCanceled:
              "Permintaan di tolak, order dibatalkan",
            requoted: "Quote ulang",
            serverProblem: "Masalah teknis server",
            timeout: "Batas Waktu",
            tradeDisabled: "Trade di nonaktifkan",
            unsupportedFillingMode: "Mode pengisian tidak terdukung",
            volumeLimitReached: "Batas volume tercapai",
          },
          form: {
            acceptNewQuotes: "Apa anda menerima quotes baru?",
            btnOpen: {
              hide: "Sembunyikan Formulir Trading",
              show: "Tampilkan Formulir Trading",
              title: "Order Baru",
            },
            buttons: {
              accept: "Terima",
              delete: "Hapus",
              modify: "Ubah",
              ok: "OKE",
              placeOrder: "Tempatkan pesanan",
              reject: "Ditolak",
              request: "Permintaan",
              requestPrice: "Harga Permintaan",
            },
            close: "Tutup",
            execution: {
              fillOrKill: "Fill atau Kill",
              immediateOrCancel: "Segera atau Batal",
              bookOrCancel: "Pesan atau Batalkan",
              label: "Isi kebijakan",
              return: "Kembali",
            },
            executionMode: {
              exchange: "Bursa Eksekusi",
              instant: "Eksekusi Cepat",
              market: "Eksekusi Pasar",
              request: "Permintaan Eksekusi",
            },
            expiration: {
              date: "Tanggal Kadaluwarsa",
              label: "Masa Berakhir",
              types: {
                specified: "Spesifikasi",
                specifiedDay: "Hari yang Ditentukan",
                today: "Hari ini",
              },
            },
            fields: {
              closeBy: "Tutup Saat",
              comment: "Komentar",
              price: "Harga",
              stopLoss: "Stop Rugi",
              takeProfit: "Ambil Keuntungan",
              volume: "Volume",
              errors: {
                volume: {
                  min: "Volume minimum adalah {min}",
                  max: "Volume maksimum adalah {max}",
                  required: "Volume is required",
                  step: "Volume dapat diatur dalam kelipatan {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Riwayat",
            deals: {
              columns: {
                comment: "Komentar",
                commission: "Komisi",
                direction: "Arah",
                fee: "Biaya",
                order: "Order",
                price: "Harga",
                profit: "keuntungan",
                swap: "Swap",
                symbol: "Simbol",
                ticket: "Tiket",
                time: "Waktu",
                type: "Tipe",
                volume: "Volume",
              },
            },
            empty: "Anda belum memiliki riwayat trading",
            menu: {
              columns: {
                horizontalScroll: "Gulir Horisontal",
                resetAll: "Atur ulang semua",
                title: "kolom",
              },
              deals: "Persetujuan",
              orders: "Order",
              period: {
                all: "Semua Riwayat",
                last3Months: "3 Bulan Terakhir",
                last6months: "6 Bulan Terakhir",
                lastMonth: "Bulan Lalu",
                title: "Periode",
                customPeriod: "Periode Tertentu",
                lastYear: "Tahun Lalu",
                lastWeek: "Minggu Lalu",
                today: "Hari ini",
              },
              positions: "Posisi",
              chart: "Chart",
              newOrder: "Order Baru",
            },
            orders: {
              columns: {
                comment: "Komentar",
                price: "Harga",
                slDescription: "Stop Rugi",
                state: "Kondisi",
                symbol: "Simbol",
                ticket: "Tiket",
                timeDone: "Waktu",
                timeSetup: "Waktu",
                tpDescription: "Ambil Keuntungan",
                type: "Tipe",
                volume: "Volume",
                timeSetupDescription: "Waktu Buka",
                timeDoneDescription: "Waktu Penutupan",
              },
              total: {
                title: "Total",
                filled: "Memenuhi",
                canceled: "Dibatalkan",
                rejected: "Ditolak",
              },
            },
            positions: {
              columns: {
                commission: "Komisi",
                fee: "Biaya",
                priceClose: "Harga",
                priceCloseDescription: "Harga Penutupan",
                priceOpen: "Harga",
                priceOpenDescription: "Harga Pembukaan",
                profit: "keuntungan",
                slDescription: "Stop Rugi",
                swap: "Swap",
                symbol: "Simbol",
                ticket: "Tiket",
                timeClose: "Waktu",
                timeCloseDescription: "Waktu Penutupan",
                timeOpen: "Waktu",
                timeOpenDescription: "Waktu buka",
                tpDescription: "Ambil Keuntungan",
                type: "Tipe",
                volume: "Volume",
                comment: "Komentar",
              },
            },
            columns: { default: "Secara Default" },
            total: {
              profit: "Keuntungan",
              credit: "Kredit",
              deposit: "Setoran",
              withdrawal: "Penarikan",
              balance: "Saldo",
              commission: "Komisi",
              fee: "Biaya",
              swap: "Nilai Inap",
              grossProfit: "Keuntungan Kotor",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Sejarah Trading",
                orders: "Order Trading",
                position: "Posisi Trade",
                sltp: "Tingkat SL/TP",
              },
              notification: "Pemberitahuan Trading",
            },
            oneClick: "Trading Satu Klik",
            tags: { demo: "Demo", readonly: "Hanya baca" },
            oneClickBottom: "Panel Satu Klik di Bagian Bawah",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Saya menerima syarat dan ketentuan ini",
            btnAccept: "Terima",
            btnCancel: "Batal",
            text: 'Anda akan mengaktifkan mode Trading Satu Klik. Dengan mengklik "Saya Menerima Syarat dan Ketentuan ini" di bawah, anda mengakui bahwa anda telah membaca dan memahami syarat dan ketentuan berikut, dan anda setuju untuk terikat dengan ini.<br /><br />Anda dapat mengaktifkan atau menonaktifkan mode Trading Satu Klik dari menu terminal web anda.<br /><br />Mode Trading Satu Klik untuk pengiriman order adalah proses satu langkah. Order anda akan dikirimkan saat anda: &mdash; ketuk salah satu tombol penawaran (JUAL) atau permintaan (BELI) harga pada panel Trading Satu Klik pada grafik &mdash; ketuk Jual, Tutup, Beli, atau tombol penempatan order di jendela Kedalaman Pasar &mdash; tutup posisi atau hapus order di tab Trading<br /><br />TIDAK ADA PROMPT KONFIRMASI BERIKUTNYA UNTUK ANDA KLIK. ANDA TIDAK AKAN DAPAT MENARIK ATAU MENGUBAH ORDER SETELAH ANDA KLIK. DALAM KONDISI PASAR NORMAL DAN KINERJA SISTEM, ORDER PASAR AKAN SEGERA DIISI SETELAH PENGAJUAN DAN ANDA AKAN MELAKUKAN TRANSAKSI YANG MENGIKAT. <br /><br />Anda setuju untuk menerima semua resiko yang terkait dengan penggunaan mode Trading Satu Klik, termasuk, tanpa batasan, resiko kesalahan, kelalaian atau kesalahan yang dibuat dalam mengirimkan order tersebut. <br /><br />Anda setuju untuk sepenuhnya mengganti rugi dan membebaskan {NamaPerusahaan} dari setiap dan semua kerugian, biaya, dan pengeluaran yang mungkin timbul sebagai akibat dari kesalahan, kelalaian, atau kesalahan apapun oleh anda, atau orang lain yang trading atas nama anda.',
            title: "Trading Satu Klik - Penafian",
          },
          quickTrade: {
            hide: "Sembunyikan Panel Trading Satu Klik",
            show: "Tampilkan Panel Trading Satu Klik",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Saya menyadari peryataan diatas dan saya berharap dapat bertransaksi pada produk investasi resiko tinggi",
            btnAccept: "Terima",
            btnCancel: "Batal",
            text: "Kami ingin memberi tahu anda bahwa dengan menggunakan platform trading ini lebih lanjut, anda akan memiliki akses ke produk investasi berisiko tinggi yang diungkit, yang disediakan oleh lembaga keuangan pilihan anda. Berinvestasi dalam produk semacam itu mungkin tidak cocok untuk semua investor, karena berisiko kehilangan sebagian atau seluruh jumlah yang disimpan. <br /><br />Sebelum memutuskan untuk trading produk investasi berisiko tinggi, anda harus mempertimbangkan dengan cermat tujuan investasi, tingkat pengalaman, dan risiko yang dapat diterima. Ada kemungkinan bahwa anda dapat mempertahankan kerugian lebih tinggi dari investasi awal anda dan oleh karena itu anda sebaiknya tidak menginvestasikan uang yang anda tidak mampu kehilangannya. <br /><br />Kami mengundang anda untuk memperluas pengetahuan anda tentang semua faktor risiko yang berkaitan dengan berinvestasi pada produk ini, dan mencari saran dari penasihat keuangan profesional jika anda ragu.",
            title: "Peringatan Investasi Berisiko Tinggi",
          },
          table: {
            btnOpen: "Trade",
            columns: {
              comment: "Komentar",
              priceClose: "Harga",
              priceCloseDescription: "Harga Tutup",
              priceOpen: "Harga",
              priceOpenDescription: "Harga Buka",
              profit: "keuntungan",
              slDescription: "Stop Rugi",
              swap: "Swap",
              symbol: "Simbol",
              ticket: "Tiket",
              time: "Waktu",
              tpDescription: "Ambil Keuntungan",
              type: "Tipe",
              volume: "Volume",
            },
            emptyPlug: {
              btnNewOrder: "Buat Orde Baru",
              title: "Anda tidak memiliki posisi apapun",
            },
            menu: {
              chart: "Grafik",
              closePosition: "Posisi Tutup",
              columns: "kolom",
              modifyOrder: "Ubah Order",
              modifyPosition: "Ubah Posisi",
              newOrder: "Order Baru",
              resetAll: "Atur ulang semua",
              deleteOrder: "Hapus Order",
            },
            oneClick: { deleteOrder: "Hapus" },
            sections: {
              collateralPositions: "Posisi Agunan",
              orders: "Order",
              positions: "Posisi",
            },
            total: {
              assets: "Aset",
              balance: "Saldo",
              collateral: "Collateral",
              commission: "Komisi",
              credit: "Kredit",
              equity: "Ekuitas",
              liabilities: "Liabilitas",
              margin: "Margin",
              marginFree: "Margin Bebas",
              marginLevel: "Tingkat",
            },
          },
          timer: {
            marketWillOpen: "Pasar akan dibuka dalam {hari} {waktutersisa}",
            moreThenOneDay: "{jumlahHari} hari",
            oneDay: "{jumlahHari} hari",
          },
          tradeIsDisabled: {
            account: "Trading untuk akun ini dinonaktifkan di server",
            collateral:
              "Trading tidak tersedia, karena simbol ini adalah jaminan",
            disabled: "Trading di nonaktifkan",
            investor:
              "Trading tidak tersedia, karena anda terhubung dengan kata sandi investor",
            readOnly:
              "Trading tidak tersedia, karena anda belum menerima peringatan resiko",
            symbol: "Trading dinonaktifkan untuk simbol ini",
          },
          hotkeys: {
            historyPanel: "Panel Riwayat",
            journalPanel: "Jurnal",
            marketWatch: "Amati Pasar",
            quickTrade: "Trading Satu Klik",
            tradeForm: "Order Baru",
            tradePanel: "Panel Trading",
          },
          marketOpen: {
            time: "Pasar ditutup - akan dibuka pada {time}",
            afterSeconds: "Pasar ditutup - akan dibuka dalam {time} detik",
          },
          expiredTimer: { seconds: "Berakhir dalam {time} dtk" },
          corporateLink: {
            type: {
              clientAgreement: "Perjanjian klien",
              riskDisclosure: "Pengungkapan resiko",
              fdmDisclaimer: "Penafian FDM",
              clientAgreementAndRiskDisclosure:
                "Perjanjian klien dan pengungkapan resiko",
              complaintsHandlingProcedure: "Prosedur penanganan keluhan",
              orderExecutionPolicy: "Kebijakan eksekusi order",
              clientCategorisationNotice: "Pemberitahuan kategorisasi klien",
              conflictsOfInterestPolicy: "Kebijakan konflik kepentingan",
              dataProtectionPolicy: "Kebijakan Perlindungan Data",
            },
          },
          margin: {
            floating: "mengambang",
            mode: { marketBuy: "Pasar beli", marketSell: "Pasar jual" },
            rangeMode: {
              value: "nilai nosional",
              valuePerSymbol: "nilai nosional per simbol",
              volume: "volume",
              volumePerSymbol: "volume per simbol",
            },
            showValue: "Tunjukkan nilai di {currency} per lot",
            rates: "Tingkat margin:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Non aktifkan tampilan peuh",
            enable: "Aktifkan tampilan penuh",
          },
          journal: {
            btnOpen: "Jurnal",
            columns: { message: "Pesan", source: "Sumber", time: "Waktu" },
            menu: {
              clear: "Bersihkan",
              debugMode: "Mode debug",
              exportFile: "Ekspor ke Dokumen",
            },
          },
          menu: {
            about: "Tentang program",
            contact: "Hubungi kami",
            brokerInformation: "Informasi perusahaan",
            chartSettings: {
              controls: "Kontrol Grafik",
              grid: "Grid",
              ohlc: "Tampilkan OHLC",
              title: "Pengaturan grafik",
              askPrice: "Harga Permintaan",
              crosshair: "Kursor tanda silang",
            },
            connect: "Hubungkan ke akun",
            language: {
              title: "Bahasa",
              search: "Pencarian",
              nothingFound: "Bahasa tidak ditemukan",
            },
            openDemo: "Buka akun Demo",
            openReal: "Buka akun real",
            settings: "Pengaturan",
            shortcuts: "Pintasan",
            theme: {
              blackWhite: "Hitam & Putih",
              blueRed: "Biru & Merah",
              dark: "Tema Gelap",
              editor: "Editor Tema",
              greenRed: "Hijau & Merah",
              light: "Tema Terang",
              neutral: "Netral",
              templates: "Template Warna",
            },
            title: "Menu",
            tradingAccount: "Akun trading",
            terms: "Syarat & Ketentuan",
            desktopPlatforms: "Platform desktop",
            qrCode: {
              install: "Pindai untuk menginstal dari {store}",
              downloadApk: "Pindai untuk mendapatkan dokumen Android APK",
            },
            economicCalendar: "Kalender Ekonomi",
          },
          screen: { back: "Kembali" },
          mobile: { bottomNav: { quotes: "Quotes" } },
          hotkeys: {
            sections: { navigation: "Navigasi", view: "Lihat" },
            escape: "Batal",
            indicators: "Indikator",
            depthOfMarket: "Kedalaman Pasar",
            objectTreePanel: "Pohon Objek",
            scrollRight: "Lilin Selanjutnya",
            scrollToStart: "Gulir Grafik untuk Memulai",
            scrollLeft: "Lilin Sebelumnya",
            scrollToEnd: "Gulir Grafik ke Akhir",
            resetChartView: "Atur Ulang Grafik",
            zoomIn: "Perbesar",
            zoomOut: "Perkecil",
            fullScreen: "Layar penuh",
            screenshot: "Simpan Grafik sebagai Gambar",
            title: "Pintasan",
          },
          timezone: {
            title: "Zona waktu",
            city: {
              cairo: "Kairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunisia",
              anchorage: "Pelabuhan",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Karakas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Kota Meksiko",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Kolombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hongkong",
              jakarta: "Jakarta",
              jerusalem: "Yerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muskat",
              nicosia: "Nikosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapura",
              taipei: "Taipei",
              tehran: "Teheran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sidney",
              amsterdam: "Amsterdam",
              athens: "Athena",
              belgrade: "Beograd",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussel",
              bucharest: "Bukares",
              budapest: "Budapest",
              copenhagen: "Kopenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istambul",
              lisbon: "Lisboa",
              london: "London",
              luxembourg: "Luksemburg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moskow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Praha",
              riga: "Riga",
              rome: "Roma",
              stockholm: "Stockholm",
              tallinn: "Tallin",
              vienna: "Wina",
              vilnius: "Vilnius",
              warsaw: "Warsawa",
              zurich: "Zürich",
              auckland: "Auckland",
              chatham: "Obrolan",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { e as a, n as b, i as c, a as i };
