const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Скрыть события экономического календаря с графика",
              show: "Показать события экономического календаря на графике",
            },
          },
          controls: {
            reset: "Сбросить график",
            scrollEnd: "Прокрутить до конца",
            scrollLeft: "Прокрутить влево",
            scrollRight: "Прокрутить вправо",
            zoomIn: "Увеличить",
            zoomOut: "Уменьшить",
          },
          crosshair: "Перекрестие",
          delay: "задержка {delay} мин",
          indicators: {
            btnAddIndicator: "Добавить индикатор",
            btnOpenPopup: "Добавить индикатор",
            close: "Закрыть",
            form: {
              applyTo: "Применить к",
              background: {
                title: "Фон",
                down: "Фон down kumo",
                up: "Фон up kumo",
              },
              deviation: "Отклонение",
              enterDistance: "Период",
              enterShift: "Смещение",
              fastEma: "Быстрая EMA",
              slowEma: "Медленная EMA",
              line: {
                base: "Базовая линия",
                down: "Нижняя линия",
                minusDI: "Линия -DI",
                null: "Нулевая линия",
                plusDI: "Линия +DI",
                style: "Стиль линии",
                cci: "Линия CCI",
                up: "Верхняя линия",
                fi: "Линия FI",
              },
              maximum: "Максимум",
              method: {
                exponential: "Экспоненциальный",
                linearWeighted: "Линейно-взвешенный",
                simple: "Простой",
                smoothed: "Сглаженный",
                title: "Метод",
              },
              opacity: "Прозрачность",
              period: {
                jaws: "Период челюстей",
                lips: "Период губ",
                teeth: "Период зубов",
                title: "Период",
                dPercent: "Период %D",
                kPercent: "Период %K",
              },
              selectApplyTo: "Выберите",
              selectVolumesType: "Выберите тип объема",
              shift: "Смещение",
              showTimeframes: "Показывать на всех таймфреймах",
              slowing: "Замедление",
              step: "Шаг",
              style: {
                down: "Стиль нисходящего",
                jaws: "Стиль челюстей",
                lips: "Стиль губ",
                main: "Основной стиль",
                signal: "Стиль сигнальной",
                teeth: "Стиль зубов",
                title: "Стиль",
                up: "Стиль восходящего",
                rvi: "Стиль RVI",
              },
              volume: { down: "Объем вниз", up: "Объем вверх" },
              volumes: "Объемы",
              mfiUp: "MFI вверх",
              mfiDown: "MFI вниз",
              price: {
                title: "Цена",
                select: "Выберите цену",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "Ничего не найдено",
              title: "Поиск",
              tryAnother: "Попробуйте другой запрос",
            },
            tabs: {
              all: "Все",
              billWilliams: "Билл Вильямс",
              oscillators: "Осцилляторы",
              trend: "Трендовые",
              volumes: "Объемы",
            },
            title: "Выберите индикатор",
            up: "Вверх",
            down: "Вниз",
            chartControls: {
              show: "Показать",
              hide: "Скрыть",
              settings: "Настройки",
              remove: "Удалить",
            },
          },
          loading: "Загрузка",
          marketWatch: {
            btnOpen: {
              hide: 'Скрыть "Обзор рынка"',
              show: 'Показать "Обзор рынка"',
            },
            columns: {
              closePrice: "Цена закрытия",
              dailyChange: "Дневное изменение",
              openPrice: "Цена открытия",
              spread: "Спред",
              symbol: "Символ",
              time: "Время",
              high: "Максимум",
              low: "Минимум",
              last: "Последняя",
              lastHigh: "Last High",
              lastLow: "Last Low",
              highLow: "Максимум/Минимум",
              bidLow: "Bid Low",
              bidHigh: "Bid High",
              askHigh: "Ask High",
              askLow: "Ask Low",
              bid: "Bid",
              ask: "Ask",
              title: "Колонки",
            },
            menu: {
              chart: "График",
              columns: "Столбцы",
              dom: "Стакан цен",
              hide: "Скрыть",
              newOrder: "Новый ордер",
              specification: "Спецификация",
            },
            search: "Поиск",
            searchSymbol: "Найти символ",
            nothingFound: "Символы не найдены",
          },
          objects: {
            form: {
              statistics: "Статистика",
              arrows: "Стрелки",
              showAlways: "Показывать всегда",
              angle: "Угол",
              distance: "Расстояние",
              bar: "Бар",
              price: "Цена",
              prices: "Цены",
              showPrice: "Показывать цену",
              showText: "Показывать текст",
              showDate: "Показывать дату",
              showTime: "Показывать время",
              showAllTimeframes: "Показывать на всех таймфреймах",
              showPearsonR: "Показывать коэффициент Пирсона",
              showLabels: "Показывать подписи",
              yourText: "Ваш текст",
              props: "Свойства",
              style: "Стиль",
              rays: "Лучи",
              background: "Фон",
              extends: "Продолжение",
              extended: "Продолжить линии",
              pipsPerBar: "Пипсов на бар",
              gannAngle: "Угол Ганна",
              deviations: "Отклонения",
              labels: "Подписи",
              reverse: "Развернуть",
              btn: { update: "Обновить", cancel: "Отмена" },
              tabs: {
                style: "Стиль",
                coordinates: "Координаты",
                visualization: "Визуализация",
              },
              range: {
                price: "Диапазон цен",
                bars: "Диапазон баров",
                date: "Диапазон дат",
              },
              align: {
                horizontal: "Выравнивание по горизонтали",
                vertical: "Выравнивание по вертикали",
                left: "Влево",
                right: "Вправо",
                center: "По центру",
                top: "По верху",
                middle: "Посередине",
                bottom: "По низу",
              },
              line: {
                style: "Стиль линии",
                base: "Базовая линия",
                up: "Верхняя линия",
                down: "Нижняя линия",
                middle: "Средняя линия",
              },
            },
            visible: {
              hide: "Скрыть все объекты",
              show: "Показать все объекты",
            },
            lock: "Заблокировать все объекты",
            unlock: "Разблокировать все объекты",
            andrewsPitchforkChannel: "Вилы Эндрюса",
            equidistantChannel: "Равноудаленный канал",
            regressionChannel: "Канал регрессии",
            stdDevChannel: "Канал стандартных отклонений",
            fibonacciRetracement: "Линии Фибоначчи",
            gannFan: "Веер Ганна",
            gannGrid: "Сетка Ганна",
            gannLine: "Линия Ганна",
            arrowLine: "Линия со стрелкой",
            crossLine: "Пересекающиеся линии",
            extendedLine: "Расширенная линия",
            horizontalRay: "Горизонтальный луч",
            horizontalLine: "Горизонтальная линия",
            infoLine: "Линия данных",
            rayLine: "Луч",
            trendAngle: "Трендовая линия по углу",
            trendline: "Трендовая линия",
            verticalLine: "Вертикальная линия",
            disjointAngle: "Расходящийся канал",
            flatTopBottom: "Плоский верх/низ",
            rectangle: "Прямоугольник",
            circle: "Круг",
            triangle: "Треугольник",
            ellipse: "Эллипс",
            text: "Текст",
            rulerLine: "Измерительная линия",
          },
          period: {
            full: {
              D1: "Дневной",
              H1: "1 час",
              H4: "4 часа",
              M1: "1 минута",
              M15: "15 минут",
              M30: "30 минут",
              M5: "5 минут",
              MN: "Месячный",
              Unknown: "Неизвестный",
              W1: "Недельный",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Неизвестный",
              W1: "W1",
            },
          },
          screenshot: "Сохранить график как изображение",
          symbolSpecs: {
            GTCmode: "Тип ордеров",
            calculation: "Расчет",
            chartMode: "Построение графиков",
            contractSize: "Размер контракта",
            days: {
              friday: "Пятница",
              monday: "Понедельник",
              saturday: "Суббота",
              sunday: "Воскресенье",
              thursday: "Четверг",
              tuesday: "Вторник",
              wednesday: "Среда",
            },
            digits: "Точность",
            empty: "Символ не выбран",
            execution: "Исполнение",
            expiration: "Истечение",
            filling: "Заполнение",
            initial: "Начальная",
            maintenance: "Поддерживающая",
            marginCurrency: "Валюта маржи",
            marginRate: "Курс маржи",
            maxVolume: "Максимальный объем",
            minVolume: "Минимальный объем",
            orders: "Ордера",
            profitCurrency: "Валюта прибыли",
            schedule: { quotes: "Котировки", trade: "Торговля" },
            sector: "Сектор",
            spread: "Спред",
            stopsLevel: "Уровень стопов",
            swapLong: "Длинный своп",
            swapShort: "Короткий своп",
            swapType: "Тип свопа",
            title: "Спецификация контракта {symbol}",
            tradeMode: "Торговля",
            volumeStep: "Шаг объема",
            volumeLimit: "Лимит объема",
            tickSize: "Размер тика",
            tickValue: "Цена тика",
            marginInitial: "Начальная маржа",
            marginHedged: "Хеджированная маржа",
            commission: {
              daily: {
                volume: "Ежедневно за объем в лотах",
                turnoverVolume: "Ежедневно за оборот в лотах",
                turnoverMoney: "Ежедневно за оборот в деньгах",
                value: "Ежедневно за стоимость сделок",
                profit: "Ежедневно за прибыль",
              },
              monthly: {
                volume: "Ежемесячно за объем в лотах",
                turnoverVolume: "Ежемесячно за оборот в лотах",
                turnoverMoney: "Ежемесячно за оборот в деньгах",
                value: "Ежемесячно за стоимость сделок",
                profit: "Ежемесячно за прибыль",
              },
              instant: {
                volume: "Немедленно за объем сделки",
                value: "Немедленно за стоимость сделки",
                profit: "Немедленно за прибыль по сделке",
              },
              entry: {
                in: "сделки входа",
                out: "сделки выхода",
                all: "сделки входа/выхода",
              },
              tier: {
                mode: {
                  pips: "пунктов",
                  percent: "% в {currency}",
                  percentProfit: "% of profit {currency}",
                },
                type: { perDeal: "за сделку", perLot: "за лот" },
              },
              header: "Комиссии",
            },
          },
          tree: {
            close: "Закрыть",
            empty: "На графике нет объектов",
            lock: "Заблокировать",
            remove: "Удалить",
            settings: "Настройки",
            title: "Управление объектами",
            unlock: "Разблокировать",
          },
          types: {
            area: "Область",
            line: "Линейный",
            bars: "Бары",
            candlestick: "Свечи",
          },
          volumeTypes: {
            tickVolumes: "Тиковые объемы",
            volumes: "Объемы",
            withoutVolumes: "Без объемов",
            realVolumes: "Реальные объемы",
          },
          zoom: { in: "Увеличить", out: "Уменьшить" },
          hotkeys: {
            arrowLine: "Линия со стрелкой",
            chartTypeArea: "График с областями",
            chartTypeLine: "Линейный график",
            chartTypeBar: "График с барами",
            chartTypeCandle: "График со свечами",
            crossLine: "Пересекающиеся линии",
            extendedLine: "Расширенная линия",
            horizontalLine: "Горизонтальная линия",
            infoLine: "Линия данных",
            rayLine: "Луч",
            realVolumes: "Реальные объемы",
            tickVolumes: "Тиковые объемы",
            trendline: "Трендовая линия",
            verticalLine: "Вертикальная линия",
            sections: {
              chartType: "Тип графика",
              drawing: "Разметка",
              volume: "Объем",
            },
            crosshairRuler: "Линейка-перекрестие",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Начните работу с вашим счетом",
            newAccountOpened: "Новый счет открыт",
          },
          brokerInformation: {
            company: "Компания",
            email: "Email",
            phone: "Телефон",
            registrationAddress: "Адрес регистрации",
            title: "Информация о компании",
            website: "Сайт",
          },
          changePassword: {
            btnChange: "Изменить пароль",
            confirmPassword: "Подтвердите пароль",
            newPassword: "Новый пароль",
            title: "Изменение пароля",
          },
          connect: {
            btnConnect: "Подключиться к счету",
            contactBroker: "Обратитесь к компании",
            forgotPassword: "Забыли пароль?",
            loginPlaceholder: "Введите логин",
            passwordPlaceholder: "Введите пароль",
            savePassword: "Сохранить пароль",
            title: "Подключение к счету",
          },
          copyToClipboard: {
            copy: "Скопировать в буфер обмена",
            unsupported: "Копирование не поддерживается",
          },
          demo: {
            accountOpeningWarning:
              "Открывая счет, вы соглашаетесь с условиями открытия счета и политикой защиты данных {brokerName}",
            btnOpenDemo: "Открыть демо-счет",
            title: "Открыть демо-счет",
            tradeWithRealMoney:
              "Для торговли реальными деньгами вам необходимо заключить отдельное соглашение с компанией, предоставляющей финансовые услуги.",
          },
          disclaimer: {
            btnAccept: "Принять",
            headerTitle: "Добро пожаловать в MetaTrader 5",
            text: 'MetaQuotes Ltd — компания по разработке программного обеспечения, которая не предоставляет финансовых, инвестиционных, брокерских и торговых услуг, а также услуг по трансляции данных. Компания не проводит платежи на комиссионной основе в целях совершения торговых операций. <br /><br />Нажимая кнопку "ПРИНЯТЬ", вы соглашаетесь с <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">условиями и положениями EULA</a>, <a href="https://www.metaquotes.net/ru/legal/policies" target="_blank">Политикой конфиденциальности</a> и Отказом от ответственности.<br /><br /> Никакая информация в приложении не является рекомендацией по инвестированию. Перед использованием этого приложения для торговли обратитесь за консультацией к квалифицированным зарегистрированным специалистам по ценным бумагам и проявите должную ответственность.',
            title: "Отказ от ответственности",
          },
          errors: {
            error: "Ошибка",
            invalidCode: "Неверный код",
            invalidEmail: "Неверный email",
            invalidPhone: "Неверный телефон",
            unknownError: "Неизвестная ошибка",
          },
          form: {
            accountType: "Тип счета",
            address: "Адрес",
            addressPlaceholder: "Введите ваш адрес",
            annualDeposit: "Годовой депозит",
            annualIncome: "Годовой доход",
            broker: "Компания",
            btn: {
              back: "Назад",
              cancel: "Отмена",
              next: "Далее",
              openAccount: "Открыть счет",
              remove: "Удалить",
              signOut: "Выйти",
            },
            city: "Город",
            cityPlaceholder: "Укажите ваш город",
            country: "Страна",
            dateBirth: "Дата рождения",
            deposit: "Депозит",
            education: "Образование",
            email: {
              address: "Email",
              code: "Код из письма",
              placeholder: "Укажите email",
              title: "Email",
            },
            employement: "Занятость",
            forex: "Forex",
            futures: "Фьючерсы",
            gender: { female: "Женский", male: "Мужской", title: "Пол" },
            identity: "Личность",
            imageOrPdfFile: "Изображение или файл PDF",
            investor: "Инвестор",
            language: "Язык",
            leverage: "Плечо",
            login: "Логин",
            min5chars: "Минимум 5 символов",
            name: {
              middle: "Отчество",
              surname: "Фамилия",
              title: "Имя",
              yourName: "Ваше имя",
            },
            nationality: "Гражданство",
            netWorth: "Чистые активы",
            optional: "Необязательно",
            password: "Пароль",
            passwordReadOnly: "Пароль только для просмотра",
            phone: {
              mobile: "Мобильный телефон",
              number: "Номер телефона",
              sms: "Код из SMS",
            },
            pleaseSelect: "Выберите",
            policyCheckbox:
              "Я подтверждаю согласие с условиями открытия счета и политикой защиты данных",
            server: "Сервер",
            side: { back: "Обратная сторона", front: "Лицевая сторона" },
            sourceWealth: "Источник средств",
            state: "Область",
            status: "Статус",
            stocks: "Акции",
            taxID: "ИНН",
            type: "Тип",
            useHedge: "Использовать хеджирование при торговле",
            verificationCodes: {
              email: "Код подтверждения отправлен на ваш email",
              phone: "Код подтверждения отправлен на ваш телефон",
              phoneEmail:
                "Коды подтверждения отправлены на ваш email и телефон",
            },
            zipCode: "Индекс",
          },
          mainForm: {
            title: "Торговые счета",
            titleWithName: "Торговые счета: {brokerName}",
          },
          otp: {
            disable2FA: "Отключить 2FA/TOTP",
            disable2FAAccount: "Отключить 2FA/TOTP для счета {login}",
            disableEnterCode:
              "Для отключения 2FA-аутентификации введите код, сгенерированный в приложении Authenticator для вашего счета.",
            downloadApp:
              "Установите на телефон приложение Google Authenticator / Microsoft Authenticator / Authy и отсканируйте QR-код:",
            enable2FA: "Включить 2FA/TOTP",
            enable2FAAccount: "Включить 2FA/TOTP для счета {login}",
            enterCode:
              "Чтобы проверить работу аутентификации, введите сгенерированный код из приложения.",
            oneTimePassword: "Одноразовый пароль:",
            placeholder: "Введите OTP для счета",
            required:
              "2FA-аутентификация нужна для дополнительной безопасности счета.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Выписка из банка",
              utilityBill: "Счет за коммунальные услуги",
            },
            conditionsForUploadingFiles: {
              documents:
                "Для некоторых типов документов требуется два фото: для лицевой и оборотной стороны",
              proofAddress:
                "Счета за услуги мобильной связи не принимаются в качестве подтверждения адреса проживания",
              utilityBill:
                "Коммунальный счет должен содержать ваше имя и адрес, и быть не старше трех месяцев",
            },
            documentType: {
              driverLicense: "Водительское удостоверение",
              idCard: "Удостоверение личности",
              passport: "Паспорт",
              residencePermit: "Вид на жительство",
            },
            educationLevel: {
              bachelor: "Степень бакалавра или эквивалентное",
              highScholl: "Среднее общее",
              master: "Степень магистра или эквивалентное",
              none: "Отсутствует",
              other: "Другое",
              phd: "Кандидат наук или эквивалентное",
            },
            employment: {
              employed: "Трудоустроен(а)",
              other: "Другое",
              retired: "На пенсии",
              selfEmployed: "Предприниматель или самозанятый(ая)",
              student: "Учащийся/Учащаяся",
              unemployed: "Безработный(ая)",
            },
            experience: "Опыт реальной торговли",
            experienceLevel: {
              above3: "> 3 лет",
              form1to3: "1 - 3 года",
              less1: "< 1 года",
            },
            industry: {
              agriculture:
                "Сельское хозяйство, продовольствие и природные ресурсы",
              communication: "Искусство, аудио/видео технологии и коммуникация",
              construction: "Архитектура и строительство",
              education: "Образование и обучение",
              engineering: "Инженерное дело и математика",
              government: "Государственное и административное управление",
              healthcare: "Здравоохранение",
              it: "Информационные технологии",
              management: "Администрирование и управление бизнесом",
              manufacturing: "Производство",
              marketing: "Маркетинг и продажи",
              none: "Не задан",
              other: "Другое",
              science: "Наука и технологии",
              security:
                "Правовая и общественная безопасность, услуги коррекции и защиты",
              tourism: "Туризм и гостеприимство",
              transport: "Транспортировка, распространение и логистика",
            },
            policy:
              "Персональные данные используются для регистрации торгового счета и не передаются третьим лицам. Обработка данных осуществляется конфиденциально и защищенно.",
            takePhoto:
              "Сделайте фотографии ваших документов и загрузите их сюда без каких-либо изменений",
            title: "Открыть реальный счет",
            wealthSource: {
              employment: "Трудовая/предпринимательская деятельность",
              inheritance: "Дар или наследство",
              other: "Другой",
              savings: "Накопления или инвестиции",
            },
          },
          saveAccountData: "Храните ваш логин и пароль в надежном месте",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Аккаунты", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Закрыть",
            empty: "Данные по объемам недоступны для этого символа",
            extendedBook: {
              hide: "Скрыть расширенный стакан",
              show: "Показать расширенный стакан",
            },
            menu: {
              amount: "Единицы вместо лотов",
              extended: "Расширенный режим",
              spread: "Спред",
            },
            spread: { hide: "Скрыть спред", show: "Показать спред" },
            stopLoss: "Стоп Лосс",
            takeProfit: "Тейк Профит",
            title: "Стакан цен",
          },
          errors: {
            accepted: "Принят",
            allowedOnlyLongPositions: "Разрешены только длинные позиции",
            allowedOnlyPositionsClosing: "Разрешено только закрывать позиции",
            allowedOnlyShortPositions: "Разрешены только короткие позиции",
            automatedTradingDisabledClient:
              "Автоматическая торговля отключена в клиентском терминале",
            automatedTradingDisabledServer:
              "Автоматическая торговля отключена на сервере.",
            canceled: "Отменен",
            common: "Общая ошибка",
            demoAllocationDisabled: "Выделение демо-счетов отключено",
            done: "Готово",
            donePartially: "Выполнен частично",
            frequentRequests: "Слишком частые запросы",
            invalidExpiration: "Недопустимое истечение",
            invalidOrderType: "Неправильный тип ордера",
            invalidParameters: "Недопустимые параметры",
            invalidPrices: "Недопустимые цены",
            invalidSLTP: "Недопустимый S/L или T/P",
            invalidVolume: "Недопустимый объем",
            manyTradeRequests: "Слишком много торговых запросов",
            marketClosed: "Рынок закрыт",
            modificationFailed:
              "Не удалось выполнить изменение, т.к. ордер или позиция расположены близко к рыночной цене",
            networkProblem: "Сетевая проблема",
            noConnection: "Нет подключения",
            notEnoughMoney: "Недостаточно денег",
            offQuotes: "Нет котировок",
            ok: "OK",
            onTheWay: "Отправлен",
            orderChanged: "Ордер уже был изменен",
            orderClosePositionExists:
              "Ордер на закрытие указанной позиции уже существует",
            ordersLimitReached: "Достигнут предел ордеров",
            permissions: "Недостаточно прав",
            placed: "Установлен",
            positionCloseProhibitedByFIFO:
              "Закрытие позиции запрещено по правилу FIFO",
            positionClosed: "Позиция уже закрыта",
            positionsLimitReached: "Достигнут лимит количества позиций",
            priceChanged: "Цена изменилась",
            prices: "Цены",
            processed: "Обработано",
            rejected: "Отклонен",
            requestRejectedOrderWillCanceled: "Запрос отклонен, ордер снят",
            requoted: "Реквотирован",
            serverProblem: "Техническая проблема сервера",
            timeout: "Таймаут",
            tradeDisabled: "Торговля отключена",
            unsupportedFillingMode: "Неподдерживаемый режим исполнения",
            volumeLimitReached: "Достигнут предел объема",
          },
          form: {
            acceptNewQuotes: "Принять новые цены?",
            btnOpen: {
              hide: "Скрыть торговую форму",
              show: "Показать торговую форму",
              title: "Новый ордер",
            },
            buttons: {
              accept: "Принять",
              delete: "Удалить",
              modify: "Изменить",
              ok: "OK",
              placeOrder: "Разместить ордер",
              reject: "Отклонить",
              request: "Запрос",
              requestPrice: "Запросить цену",
            },
            close: "Закрыть",
            execution: {
              fillOrKill: "Все/Ничего",
              immediateOrCancel: "Все/Частично",
              bookOrCancel: "Пассивная",
              label: "Заполнение",
              return: "Вернуть",
            },
            executionMode: {
              exchange: "Биржевое исполнение",
              instant: "Немедленное исполнение",
              market: "Исполнение по рынку",
              request: "Исполнение по запросу",
            },
            expiration: {
              date: "Дата истечения",
              label: "Истечение",
              types: {
                specified: "Дата и время",
                specifiedDay: "Указанный день",
                today: "Сегодня",
              },
            },
            fields: {
              closeBy: "Закрыть встречной",
              comment: "Комментарий",
              price: "Цена",
              stopLoss: "Стоп Лосс",
              takeProfit: "Тейк Профит",
              volume: "Объем",
              errors: {
                volume: {
                  min: "Минимальный объем — {min}",
                  max: "Максимальный объем — {max}",
                  required: "Volume is required",
                  step: "Объем можно задавать с шагом {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "История",
            deals: {
              columns: {
                comment: "Комментарий",
                commission: "Комиссия",
                direction: "Направление",
                fee: "Сбор",
                order: "Ордер",
                price: "Цена",
                profit: "Прибыль",
                swap: "Своп",
                symbol: "Символ",
                ticket: "Тикет",
                time: "Время",
                type: "Тип",
                volume: "Объем",
              },
            },
            empty: "У вас пока нет торговой истории",
            menu: {
              columns: {
                horizontalScroll: "Горизонтальная прокрутка",
                resetAll: "Сбросить все",
                title: "Колонки",
              },
              deals: "Сделки",
              orders: "Ордеры",
              period: {
                all: "Вся история",
                last3Months: "Последние 3 месяца",
                last6months: "Последние 6 месяцев",
                lastMonth: "Последний месяц",
                title: "Период",
                customPeriod: "Выбрать период",
                lastYear: "Последний год",
                lastWeek: "Последняя неделя",
                today: "Сегодня",
              },
              positions: "Позиции",
              chart: "Чарт",
              newOrder: "Новый ордер",
            },
            orders: {
              columns: {
                comment: "Комментарий",
                price: "Цена",
                slDescription: "Стоп Лосс",
                state: "Состояние",
                symbol: "Символ",
                ticket: "Тикет",
                timeDone: "Время",
                timeSetup: "Время",
                tpDescription: "Тейк Профит",
                type: "Тип",
                volume: "Объем",
                timeSetupDescription: "Время открытия",
                timeDoneDescription: "Время закрытия",
              },
              total: {
                title: "Всего",
                filled: "Выполнено",
                canceled: "Отменено",
                rejected: "Отклонено",
              },
            },
            positions: {
              columns: {
                commission: "Комиссия",
                fee: "Сбор",
                priceClose: "Цена",
                priceCloseDescription: "Цена закрытия",
                priceOpen: "Цена",
                priceOpenDescription: "Цена открытия",
                profit: "Прибыль",
                slDescription: "Стоп Лосс",
                swap: "Своп",
                symbol: "Символ",
                ticket: "Тикет",
                timeClose: "Время",
                timeCloseDescription: "Время закрытия",
                timeOpen: "Время",
                timeOpenDescription: "Время открытия",
                tpDescription: "Тейк Профит",
                type: "Тип",
                volume: "Объем",
                comment: "Комментарий",
              },
            },
            columns: { default: "По умолчанию" },
            total: {
              profit: "Прибыль",
              credit: "Кредит",
              deposit: "Пополнение",
              withdrawal: "Снятие",
              balance: "Баланс",
              commission: "Комиссия",
              fee: "Сбор",
              swap: "Своп",
              grossProfit: "Общая прибыль",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Торговая история",
                orders: "Торговые ордера",
                position: "Торговые позиции",
                sltp: "Уровни СЛ/ТП",
              },
              notification: "Торговые уведомления",
            },
            oneClick: "Торговля в один клик",
            tags: { demo: "Демо", readonly: "Только просмотр" },
            oneClickBottom: "Панель торговли в один клик под графиком",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Я принимаю эти условия",
            btnAccept: "Принять",
            btnCancel: "Отмена",
            text: 'Вы собираетесь активировать режим "Торговля в один клик". Нажав "Я принимаю эти условия", вы тем самым подтверждаете, что прочитали, поняли и согласны со всеми нижеизложенными условиями.<br /><br />Вы можете включить или отключить режим "Торговля в один клик" в меню веб-терминала.<br /><br />Режим отправки торговых приказов "Торговля в один клик" состоит из одного этапа. Ваш торговый приказ будет отправлен сразу: &mdash; при нажатии кнопок с ценой предложения (SELL) или покупки (BUY) на панели торговли в один клик на графике &mdash; при нажатии кнопок "Sell", "Buy", "Закрыть" и команд выставления ордеров в окне "Стакан цен" &mdash; при закрытии позиции и удалении ордеров во вкладке "Торговля"<br /><br />ВАМ НЕ БУДЕТ ПРЕДЛОЖЕНО ПОДТВЕРДИТЬ ТОРГОВЫЙ ПРИКАЗ. ВЫ НЕ СМОЖЕТЕ ОТМЕНИТЬ ИЛИ ИЗМЕНИТЬ СВОЙ ОРДЕР ПОСЛЕ НАЖАТИЯ. ПРИ НОРМАЛЬНЫХ РЫНОЧНЫХ УСЛОВИЯХ И ПРОИЗВОДИТЕЛЬНОСТИ СИСТЕМЫ РЫНОЧНЫЙ ОРДЕР БУДЕТ ОПЕРАТИВНО ИСПОЛНЕН ПОСЛЕ ОТПРАВКИ ПРИКАЗА, И ПОСЛЕ ЭТОГО ВЫ БУДЕТЕ СВЯЗАНЫ ОБЯЗАТЕЛЬСТВАМИ СДЕЛКИ.<br /><br />Вы согласны принять все риски, связанные с использованием режима "Торговля в один клик", в том числе, без ограничения все риски ошибок, упущений или просчетов, допущенных при отправке такого торгового приказа.<br /><br />Вы согласны в полной мере оградить {companyName} от любых убытков, затрат и расходов, которые могут быть понесены в результате таких ошибок, упущений или просчетов, допущенных вами или любым другим человеком, торгующим от вашего имени.',
            title: "Торговля в один клик - Отказ от ответственности",
          },
          quickTrade: {
            hide: "Скрыть панель торговли в один клик",
            show: "Показать панель торговли в один клик",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Я осознаю риски и хочу торговать инвестиционными продуктами",
            btnAccept: "Принять",
            btnCancel: "Отмена",
            text: "Информируем вас о том, что дальнейшее использование данной торговой платформы подразумевает доступ к высокорискованным инвестиционным продуктам, предоставляемым финансовым институтом по вашему выбору. Инвестирование в такие продукты может не подходить для всех инвесторов, поскольку несет в себе риск частичной или полной потери депозита.<br /><br />Прежде чем решить торговать высокорискованными инвестиционными продуктами, вам следует внимательно оценить свои инвестиционные цели, уровень подготовки и допустимые риски. Существует вероятность потери средств, превышающей ваши первоначальные инвестиции, поэтому вам не следует инвестировать средства, которые вы не можете себе позволить потерять.<br /><br />Призываем вас расширить свой кругозор относительно всех факторов риска, связанных с инвестированием в такие продукты, а также, в случае любых сомнений, проконсультироваться с профессиональным финансовым советником.",
            title: "Предупреждение о рисках инвестора",
          },
          table: {
            btnOpen: "Торговля",
            columns: {
              comment: "Комментарий",
              priceClose: "Цена",
              priceCloseDescription: "Цена закрытия",
              priceOpen: "Цена",
              priceOpenDescription: "Цена открытия",
              profit: "Прибыль",
              slDescription: "Стоп Лосс",
              swap: "Своп",
              symbol: "Символ",
              ticket: "Тикет",
              time: "Время",
              tpDescription: "Тейк Профит",
              type: "Тип",
              volume: "Объем",
            },
            emptyPlug: {
              btnNewOrder: "Создать новый ордер",
              title: "У вас нет позиций",
            },
            menu: {
              chart: "Чарт",
              closePosition: "Закрыть позицию",
              columns: "Колонки",
              modifyOrder: "Изменить ордер",
              modifyPosition: "Изменить позицию",
              newOrder: "Новый ордер",
              resetAll: "Сбросить все",
              deleteOrder: "Удалить ордер",
            },
            oneClick: { deleteOrder: "Удалить" },
            sections: {
              collateralPositions: "Collateral-позиции",
              orders: "Ордеры",
              positions: "Позиции",
            },
            total: {
              assets: "Активы",
              balance: "Баланс",
              collateral: "Collateral",
              commission: "Комиссия",
              credit: "Кредит",
              equity: "Средства",
              liabilities: "Обязательства",
              margin: "Маржа",
              marginFree: "Свободная маржа",
              marginLevel: "Уровень",
            },
          },
          timer: {
            marketWillOpen: "Рынок откроется через {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} дней",
            oneDay: "{numberOfDays} день",
          },
          tradeIsDisabled: {
            account: "Для вашего счета торговля отключена на сервере",
            collateral: "Для collateral-инструментов торговля недоступна",
            disabled: "Торговля отключена",
            investor:
              "Торговля недоступна, поскольку вы подключены с инвесторским паролем",
            readOnly:
              "Торговля недоступна, поскольку вы не приняли соглашение о рисках",
            symbol: "Торговля для этого символа отключена",
          },
          hotkeys: {
            historyPanel: "Панель истории",
            journalPanel: "Журнал",
            marketWatch: "Обзор рынка",
            quickTrade: "Торговля в один клик",
            tradeForm: "Новый ордер",
            tradePanel: "Торговая панель",
          },
          marketOpen: {
            time: "Рынок закрыт - открытие в {time}",
            afterSeconds: "Рынок закрыт - открытие через {time} сек",
          },
          expiredTimer: { seconds: "Истекает через {time} сек" },
          corporateLink: {
            type: {
              clientAgreement: "Соглашение с клиентом",
              riskDisclosure: "Уведомление о рисках",
              fdmDisclaimer: "Отказ от ответственности FDM",
              clientAgreementAndRiskDisclosure:
                "Соглашение с клиентом и уведомление о рисках",
              complaintsHandlingProcedure: "Процедура обработки жалоб",
              orderExecutionPolicy: "Политика исполнения ордеров",
              clientCategorisationNotice: "Порядок категоризации клиентов",
              conflictsOfInterestPolicy: "Положение о конфликте интересов",
              dataProtectionPolicy: "Политика защиты данных",
            },
          },
          margin: {
            floating: "плавающая",
            mode: {
              marketBuy: "Рыночный ордер Buy",
              marketSell: "Рыночный ордер Sell",
            },
            rangeMode: {
              value: "номинальная стоимость",
              valuePerSymbol: "номинальная стоимость по символу",
              volume: "объем",
              volumePerSymbol: "объем по символу",
            },
            showValue: "Показывать значения в {currency} за лот",
            rates: "Маржа",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Отключить полноэкранный режим",
            enable: "Включить полноэкранный режим",
          },
          journal: {
            btnOpen: "Журнал",
            columns: {
              message: "Сообщение",
              source: "Источник",
              time: "Время",
            },
            menu: {
              clear: "Очистить",
              debugMode: "Режим отладки",
              exportFile: "Экспортировать в файл",
            },
          },
          menu: {
            about: "О программе",
            contact: "Свяжитесь с нами",
            brokerInformation: "Информация о компании",
            chartSettings: {
              controls: "Управление графиком",
              grid: "Сетка",
              ohlc: "Показывать OHLC",
              title: "Настройки графика",
              askPrice: "Цена Ask",
              crosshair: "Курсор с перекрестием",
            },
            connect: "Подключиться к счету",
            language: {
              title: "Язык",
              search: "Поиск",
              nothingFound: "Язык не найден",
            },
            openDemo: "Открыть демо-счет",
            openReal: "Открыть реальный счет",
            settings: "Настройки",
            shortcuts: "Горячие клавиши",
            theme: {
              blackWhite: "Черно-белая",
              blueRed: "Сине-красная",
              dark: "Темная тема",
              editor: "Редактор тем",
              greenRed: "Зелено-красная",
              light: "Светлая тема",
              neutral: "Нейтральная",
              templates: "Цветовые схемы",
            },
            title: "Меню",
            tradingAccount: "Торговые счета",
            terms: "Условия использования",
            desktopPlatforms: "Десктопные платформы",
            qrCode: {
              install: "Отсканируйте для установки из {store}",
              downloadApk: "Отсканируйте для получения файла APK для Android",
            },
            economicCalendar: "Экономический календарь",
          },
          screen: { back: "Назад" },
          mobile: { bottomNav: { quotes: "Котировки" } },
          hotkeys: {
            sections: { navigation: "Навигация", view: "Вид" },
            escape: "Отмена",
            indicators: "Индикаторы",
            depthOfMarket: "Стакан цен",
            objectTreePanel: "Дерево объектов",
            scrollRight: "Следующая свеча",
            scrollToStart: "Прокрутить график до начала",
            scrollLeft: "Предыдущая свеча",
            scrollToEnd: "Прокрутить график до конца",
            resetChartView: "Сбросить график",
            zoomIn: "Увеличить",
            zoomOut: "Уменьшить",
            fullScreen: "Полный экран",
            screenshot: "Сохранить график как изображение",
            title: "Горячие клавиши",
          },
          timezone: {
            title: "Часовой пояс",
            city: {
              cairo: "Каир",
              casablanca: "Касабланка",
              johannesburg: "Йоханнесбург",
              lagos: "Лагос",
              nairobi: "Найроби",
              tunis: "Тунис",
              anchorage: "Анкоридж",
              bogota: "Богота",
              buenosAires: "Буэнос айрес",
              caracas: "Каракас",
              chicago: "Чикаго",
              denver: "Денвер",
              elSalvador: "Сальвадор",
              juneau: "Джуно",
              lima: "Лима",
              losAngeles: "Лос-Анджелес",
              mexicoCity: "Мехико",
              newYork: "Нью-Йорк",
              phoenix: "Феникс",
              santiago: "Сантьяго",
              saoPaulo: "Сан-Паулу",
              toronto: "Торонто",
              vancouver: "Ванкувер",
              almaty: "Алматы",
              ashgabat: "Ашхабад",
              bahrain: "Бахрейн",
              bangkok: "Бангкок",
              kolkata: "Калькутта",
              colombo: "Коломбо",
              dhaka: "Дакка",
              dubai: "Дубай",
              hongKong: "Гонконг",
              jakarta: "Джакарта",
              jerusalem: "Иерусалим",
              karachi: "Карачи",
              kathmandu: "Катманду",
              kuwait: "Кувейт",
              manila: "Манила",
              muscat: "Маскат",
              nicosia: "Никосия",
              qatar: "Катар",
              rangoon: "Рангун",
              riyadh: "Эр-Рияд",
              saigon: "Сайгон",
              seoul: "Сеул",
              shanghai: "Шанхай",
              singapore: "Сингапур",
              taipei: "Тайбэй",
              tehran: "Тегеран",
              tokyo: "Токио",
              reykjavik: "Рейкьявик",
              adelaide: "Аделаида",
              brisbane: "Брисбен",
              perth: "Перт",
              sydney: "Сидней",
              amsterdam: "Амстердам",
              athens: "Афины",
              belgrade: "Белград",
              berlin: "Берлин",
              bratislava: "Братислава",
              brussels: "Брюссель",
              bucharest: "Бухарест",
              budapest: "Будапешт",
              copenhagen: "Копенгаген",
              dublin: "Дублин",
              helsinki: "Хельсинки",
              istanbul: "Стамбул",
              lisbon: "Лиссабон",
              london: "Лондон",
              luxembourg: "Люксембург",
              madrid: "Мадрид",
              malta: "Мальта",
              moscow: "Москва",
              oslo: "Осло",
              paris: "Париж",
              prague: "Прага",
              riga: "Рига",
              rome: "Рим",
              stockholm: "Стокгольм",
              tallinn: "Таллинн",
              vienna: "Вена",
              vilnius: "Вильнюс",
              warsaw: "Варшава",
              zurich: "Цюрих",
              auckland: "Окленд",
              chatham: "Чатем",
              fakaofo: "Факаофо",
              honolulu: "Гонолулу",
              norfolk: "Норфолк",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e as r };
