const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "経済指標カレンダーのイベントをチャートで非表示にする",
              show: "経済指標カレンダーのイベントをチャートで表示する",
            },
          },
          controls: {
            reset: "チャートをリセット",
            scrollEnd: "最後までスクロール",
            scrollLeft: "左にスクロール",
            scrollRight: "右にスクロール",
            zoomIn: "拡大",
            zoomOut: "縮小",
          },
          crosshair: "クロスヘアー",
          delay: "{delay}分の遅延",
          indicators: {
            btnAddIndicator: "インディケータを追加する",
            btnOpenPopup: "インディケータ追加",
            close: "決済",
            form: {
              applyTo: "適用先",
              background: {
                title: "背景",
                down: "ダウン雲背景",
                up: "アップ雲背景",
              },
              deviation: "スリッページ",
              enterDistance: "期間",
              enterShift: "シフト",
              fastEma: "短期 EMA",
              slowEma: "長期 EMA",
              line: {
                base: "ベースライン",
                down: "ダウンライン",
                minusDI: "-DIライン",
                null: "Nullライン",
                plusDI: "+DIライン",
                style: "ラインスタイル",
                cci: "CCIライン",
                up: "アップライン",
                fi: "FIライン",
              },
              maximum: "最大",
              method: {
                exponential: "指数",
                linearWeighted: "線形加重",
                simple: "シンプル",
                smoothed: "平滑",
                title: "メソッド",
              },
              opacity: "不透明度",
              period: {
                jaws: "ジョウズ期間",
                lips: "リップス期間",
                teeth: "ティース期間",
                title: "期間",
                dPercent: "%D 期間",
                kPercent: "%K 期間",
              },
              selectApplyTo: "選択",
              selectVolumesType: "ボリュームタイプを選択",
              shift: "シフト",
              showTimeframes: "すべての時間軸に表示する",
              slowing: "スローイング",
              step: "ステップ",
              style: {
                down: "ダウンスタイル",
                jaws: "顎スタイル",
                lips: "唇スタイル",
                main: "メインスタイル",
                signal: "シグナルスタイル",
                teeth: "歯スタイル",
                title: "スタイル",
                up: "アップスタイル",
                rvi: "RVI スタイル",
              },
              volume: { down: "ボリュームダウン", up: "ボリュームアップ" },
              volumes: "ボリューム",
              mfiUp: "MFIアップ",
              mfiDown: "MFIダウン",
              price: {
                title: "価格",
                select: "価格を選択",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "アイテムが見つかりませんでした",
              title: "検索",
              tryAnother: "別のクエリを試してください",
            },
            tabs: {
              all: "全て",
              billWilliams: "ビル･ウィリアムズ",
              oscillators: "オシレータ",
              trend: "トレンド",
              volumes: "ボリューム",
            },
            title: "インジケータを選択",
            up: "上昇",
            down: "下",
            chartControls: {
              show: "表示",
              hide: "隠す",
              settings: "設定",
              remove: "削除",
            },
          },
          loading: "読み込み中",
          marketWatch: {
            btnOpen: {
              hide: "気配値表示を非表示にする",
              show: "気配値表示を表示する",
            },
            columns: {
              closePrice: "終値",
              dailyChange: "毎日の変化",
              openPrice: "始値",
              spread: "スプレッド",
              symbol: "シンボル",
              time: "時間",
              high: "高値",
              low: "安値",
              last: "最終更新時間",
              lastHigh: "直近高値",
              lastLow: "直近安値",
              highLow: "高値/安値",
              bidLow: "買安値",
              bidHigh: "買高値",
              askHigh: "売高値",
              askLow: "売安値",
              bid: "売気配(Bid)",
              ask: "買気配(Ask)",
              title: "列",
            },
            menu: {
              chart: "チャート",
              columns: "列",
              dom: "板注文画面",
              hide: "非表示にする",
              newOrder: "新規注文",
              specification: "仕様 ",
            },
            search: "検索",
            searchSymbol: "銘柄を検索",
            nothingFound: "銘柄がみつかりません",
          },
          objects: {
            form: {
              statistics: "マーケット統計情報",
              arrows: "矢印類",
              showAlways: "常に表示",
              angle: "角度",
              distance: "距離",
              bar: "日足データ",
              price: "価格",
              prices: "価格",
              showPrice: "価格を表示",
              showText: "テキストを表示",
              showDate: "日にちを表示",
              showTime: "時刻を表示",
              showAllTimeframes: "すべての時間軸に表示",
              showPearsonR: "ピアソンのRを表示",
              showLabels: "ラベルを表示",
              yourText: "貴方の入力したテキスト",
              props: "プロパティ",
              style: "スタイル",
              rays: "半直線",
              background: "背景",
              extends: "半直線",
              extended: "拡張モード",
              pipsPerBar: "バーあたりピップス",
              gannAngle: "ギャン角度",
              deviations: "偏差",
              labels: "ラベル",
              reverse: "反転",
              btn: { update: "更新", cancel: "キャンセル" },
              tabs: {
                style: "スタイル",
                coordinates: "座標",
                visualization: "表示選択",
              },
              range: {
                price: "価格範囲",
                bars: "バー範囲",
                date: "日にちの範囲",
              },
              align: {
                horizontal: "水平方向の配置",
                vertical: "垂直方向の配置",
                left: "左",
                right: "右",
                center: "中央",
                top: "上",
                middle: "中",
                bottom: "下",
              },
              line: {
                style: "ラインスタイル",
                base: "ベースライン",
                up: "アップライン",
                down: "ダウンライン",
                middle: "ミドルライン",
              },
            },
            visible: {
              hide: "すべてのオブジェクトを非表示にする",
              show: "すべてのオブジェクトを表示",
            },
            lock: "すべてのオブジェクトをロック",
            unlock: "すべてのオブジェクトをアンロック",
            andrewsPitchforkChannel: "アンドリューピッチフォーク",
            equidistantChannel: "平行チャンネル",
            regressionChannel: "回帰チャンネル",
            stdDevChannel: "標準偏差チャンネル",
            fibonacciRetracement: "フィボナッチリトレースメント",
            gannFan: "ギャンファン",
            gannGrid: "ギャングリッド",
            gannLine: "ギャンライン",
            arrowLine: "矢印線",
            crossLine: "クロスライン",
            extendedLine: "拡張ライン",
            horizontalRay: "水平半直線",
            horizontalLine: "水平線",
            infoLine: "情報線",
            rayLine: "延長",
            trendAngle: "アングルトレンド",
            trendline: "トレンドライン",
            verticalLine: "垂直線",
            disjointAngle: "ディスジョイントチャンネル",
            flatTopBottom: "フラットトップ/ボトム",
            rectangle: "長方形",
            circle: "丸",
            triangle: "三角形",
            ellipse: "楕円",
            text: "テキスト",
            rulerLine: "定規の線",
          },
          period: {
            full: {
              D1: "日足",
              H1: "1時間足",
              H4: "4時間足",
              M1: "1分足",
              M15: "15分足",
              M30: "30分足",
              M5: "5分足",
              MN: "月足",
              Unknown: "不明",
              W1: "週足",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "不明",
              W1: "W1",
            },
          },
          screenshot: "チャートを画像として保存",
          symbolSpecs: {
            GTCmode: "GTCモード",
            calculation: "計算",
            chartMode: "チャートモード",
            contractSize: "取引単位",
            days: {
              friday: "金曜日",
              monday: "月曜日",
              saturday: "土曜日",
              sunday: "日曜日",
              thursday: "木曜日",
              tuesday: "火曜日",
              wednesday: "水曜日",
            },
            digits: "桁",
            empty: "銘柄が選択されていません",
            execution: "実行",
            expiration: "有効期限",
            filling: "約定形式",
            initial: "基本",
            maintenance: "必要",
            marginCurrency: "証拠金通貨",
            marginRate: "証拠金率",
            maxVolume: "最大数量",
            minVolume: "最小数量",
            orders: "オーダー",
            profitCurrency: "損益通貨",
            schedule: { quotes: "気配値", trade: "トレード" },
            sector: "セクター",
            spread: "スプレッド",
            stopsLevel: "ストップレベル",
            swapLong: "買スワップ",
            swapShort: "売スワップ",
            swapType: "スワップタイプ",
            title: "{銘柄}契約仕様",
            tradeMode: "トレード",
            volumeStep: "数量最小単位",
            volumeLimit: "数量制限",
            tickSize: "ティックサイズ",
            tickValue: "ティックバリュー",
            marginInitial: "必要証拠金",
            marginHedged: "ヘッジ対象マージン",
            commission: {
              daily: {
                volume: "1日のボリューム(ロット単位)",
                turnoverVolume: "1日の反転(ロット)",
                turnoverMoney: "1日の反転(金額)",
                value: "1日の取引額",
                profit: "1日の利益",
              },
              monthly: {
                volume: "月間ボリューム(ロット単位)",
                turnoverVolume: "1ヶ月の反転(ロット)",
                turnoverMoney: "1ヶ月の反転(金額)",
                value: "1か月の取引額",
                profit: "1か月の利益",
              },
              instant: {
                volume: "即時(取引ボリュームによる)",
                value: "即時(取引額による)",
                profit: "即時(取引利益による)",
              },
              entry: {
                in: "イン取引",
                out: "アウト取引",
                all: "イン/アウト取引",
              },
              tier: {
                mode: {
                  pips: "ポイント",
                  percent: "% {currency}",
                  percentProfit: "% 利益の {currency}",
                },
                type: { perDeal: "取引毎", perLot: "ロット毎" },
              },
              header: "手数料",
            },
          },
          tree: {
            close: "決済",
            empty: "チャートにオブジェクトがありません",
            lock: "ロック",
            remove: "削除",
            settings: "設定",
            title: "描画を管理",
            unlock: "アンロック",
          },
          types: {
            area: "エリア",
            line: "線",
            bars: "チャートバー",
            candlestick: "ローソク足",
          },
          volumeTypes: {
            tickVolumes: "ティックボリューム",
            volumes: "ボリューム",
            withoutVolumes: "ボリュームなし",
            realVolumes: "実ボリューム",
          },
          zoom: { in: "拡大", out: "縮小" },
          hotkeys: {
            arrowLine: "矢印線",
            chartTypeArea: "面グラフ",
            chartTypeLine: "折れ線グラフ",
            chartTypeBar: "棒グラフ",
            chartTypeCandle: "ローソク足チャート",
            crossLine: "クロスライン",
            extendedLine: "拡張ライン",
            horizontalLine: "水平線",
            infoLine: "情報線",
            rayLine: "延長",
            realVolumes: "実際の出来高",
            tickVolumes: "ティックボリューム",
            trendline: "トレンドライン",
            verticalLine: "垂直線",
            sections: {
              chartType: "チャートの種類",
              drawing: "描画",
              volume: "ボリューム",
            },
            crosshairRuler: "十字定規",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "口座を始める",
            newAccountOpened: "新規口座開設",
          },
          brokerInformation: {
            company: "会社名",
            email: "Eメール",
            phone: "電話",
            registrationAddress: "登録住所",
            title: "企業情報",
            website: "Webサイト",
          },
          changePassword: {
            btnChange: "パスワードの変更",
            confirmPassword: "パスワード(再入力)",
            newPassword: "新しいパスワード",
            title: "パスワードの変更",
          },
          connect: {
            btnConnect: "口座に接続",
            contactBroker: "企業に連絡",
            forgotPassword: "パスワードをお忘れの場合",
            loginPlaceholder: "ログイン名を入力",
            passwordPlaceholder: "パスワードを入力",
            savePassword: "パスワードを保存",
            title: "口座に接続",
          },
          copyToClipboard: {
            copy: "クリップボードにコピー",
            unsupported: "コピーはサポートされていません",
          },
          demo: {
            accountOpeningWarning:
              "口座を開設することにより、口座開設条件と{brokerName}のデータ保護ポリシーに同意したことになります",
            btnOpenDemo: "デモ口座を開設",
            title: "デモ口座を開設",
            tradeWithRealMoney:
              "実際に資金で取引するには、金融サービス会社と別の契約を結ぶ必要があります。",
          },
          disclaimer: {
            btnAccept: "承認",
            headerTitle: "MetaTrader 5へようこそ",
            text: 'MetaQuotes Ltdはソフトウェア開発会社であり、金融、投資、仲介、取引、データフィードサービスは提供していません。また、取引操作に関する手数料ベースの支払いにも関与していません。<br /><br />[同意する]ボタンを押下することによって、私は<a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">EULA の利用規約</a>、<a href="https://www.metaquotes.net/ja/legal/policies" target="_blank">プライバシーポリシー</a>および免責事項に同意します。<br /><br />アプリケーションで利用可能な情報は、投資アドバイスとして意図されたものではありません。このアプリケーションを取引に使用する前に、資格のある登録済みの証券専門家のアドバイスを求め、ご自身で十分な注意を払ってください。',
            title: "免責事項",
          },
          errors: {
            error: "エラー",
            invalidCode: "コードが無効です",
            invalidEmail: "メールが無効です",
            invalidPhone: "無効な電話",
            unknownError: "不明なエラー",
          },
          form: {
            accountType: "口座タイプ",
            address: "アドレス",
            addressPlaceholder: "アドレスを入力",
            annualDeposit: "年入金",
            annualIncome: "年収",
            broker: "会社",
            btn: {
              back: "戻る",
              cancel: "取消",
              next: "次",
              openAccount: "口座開設",
              remove: "削除",
              signOut: "ログアウト",
            },
            city: "市町村",
            cityPlaceholder: "市区町村を入力",
            country: "国",
            dateBirth: "生年月日",
            deposit: "入金",
            education: "教育",
            email: {
              address: "Eメール",
              code: "メールからのコード",
              placeholder: "メールを入力",
              title: "Eメール",
            },
            employement: "職業",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "女性", male: "男性", title: "性別" },
            identity: "身元",
            imageOrPdfFile: "画像またはPDFファイル",
            investor: "閲覧専用",
            language: "言語",
            leverage: "レバレッジ",
            login: "ログイン",
            min5chars: "最低5チャート",
            name: {
              middle: "ミドルネーム",
              surname: "苗字",
              title: "名前",
              yourName: "氏名",
            },
            nationality: "国籍",
            netWorth: "純資産",
            optional: "オプション",
            password: "パスワード",
            passwordReadOnly: "読み込み専用パスワード",
            phone: {
              mobile: "携帯電話",
              number: "固定電話",
              sms: "SMSからのコード",
            },
            pleaseSelect: "選択してください",
            policyCheckbox:
              "私は口座開設の利用規約とデータ保護ポリシーに同意します",
            server: "サーバ",
            side: { back: "裏", front: "表" },
            sourceWealth: "収入源",
            state: "状況",
            status: "ステータス",
            stocks: "株式",
            taxID: "納税者番号",
            type: "タイプ",
            useHedge: "取引にヘッジを使用する",
            verificationCodes: {
              email: "メールに確認コードを送信しました",
              phone: "電話に確認コードを送信しました",
              phoneEmail: "電話とメールに確認コードを送信しました",
            },
            zipCode: "郵便番号",
          },
          mainForm: {
            title: "取引口座",
            titleWithName: "取引口座: {brokerName}",
          },
          otp: {
            disable2FA: "2FA/TOTPを無効化",
            disable2FAAccount: "アカウントの2FA/TOTPを無効化: {login}",
            disableEnterCode:
              "2FA/TOTPを無効化するには、アプリによって生成されたアカウントコードを入力してください。",
            downloadApp:
              "Google Authenticator / Microsoft Authenticator / Authyアプリをモバイルデバイスにダウンロードして、QRコードをスキャンしてください。",
            enable2FA: "2FA/TOTPを有効化",
            enable2FAAccount: "アカウントの2FA/TOTPを有効化: {login}",
            enterCode:
              "Authenticatorの動作を確認するには、アプリによって生成されたアカウントコードを入力します。",
            oneTimePassword: "ワンタイムパスワード:",
            placeholder: "アカウントのOTPを入力",
            required:
              "アカウントのセキュリティを強化するには、2FA認証が必要です。",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "銀行取引明細書",
              utilityBill: "公共料金請求書",
            },
            conditionsForUploadingFiles: {
              documents:
                "書類によっては、表面と裏面の2枚の写真が必要な場合があります",
              proofAddress:
                "モバイルサービスの請求書は、住所の証明として認められません",
              utilityBill:
                "公共料金の請求書は、名前と住所が記載されていて、3か月以内のものでなければなりません",
            },
            documentType: {
              driverLicense: "運転免許証",
              idCard: "IDカード",
              passport: "パスポート",
              residencePermit: "居住許可証",
            },
            educationLevel: {
              bachelor: "学士号または同等の学位",
              highScholl: "高校",
              master: "修士号または同等の学位",
              none: "無し",
              other: "その他",
              phd: "博士号または同等の学位",
            },
            employment: {
              employed: "雇用",
              other: "その他",
              retired: "退職",
              selfEmployed: "事業主または自営業",
              student: "学生",
              unemployed: "失業",
            },
            experience: "実際の取引経験:",
            experienceLevel: {
              above3: "3年以上",
              form1to3: "1～3年",
              less1: "1年未満",
            },
            industry: {
              agriculture: "農業",
              communication: "芸術/オーディオ/ビデオ技術/コミュニケーション",
              construction: "建築業/建設業",
              education: "教育",
              engineering: "工学/数学",
              government: "政府関係/行政",
              healthcare: "ヘルスケア",
              it: "情報技術",
              management: "経営/事業管理",
              manufacturing: "製造業",
              marketing: "マーケティング/販売業",
              none: "無し",
              other: "その他",
              science: "科学/技術",
              security: "法律/公安/更生/セキュリティ",
              tourism: "ホスピタリティ/観光",
              transport: "輸送業/流通業/物流業",
            },
            policy:
              "個人情報は取引口座の開設に使用され、第三者に渡されることはありません。情報は安全かつ機密に扱われます。",
            takePhoto:
              "書類の写真を撮り、編集せずにここにアップロードしてください",
            title: "リアル口座を開設",
            wealthSource: {
              employment: "雇用",
              inheritance: "贈与または相続",
              other: "その他",
              savings: "貯蓄または投資",
            },
          },
          saveAccountData:
            "ログイン名とパスワードは安全な場所に保管してください",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "決済",
            empty: "この銘柄の出来高データはありません",
            extendedBook: {
              hide: "拡張ブックを非表示にする",
              show: "拡張ブックを表示",
            },
            menu: {
              amount: "ロットの代わりの単位",
              extended: "拡張モード",
              spread: "スプレッド",
            },
            spread: {
              hide: "スプレッドを非表示にする",
              show: "スプレッドを表示",
            },
            stopLoss: "ストップロス",
            takeProfit: "テイクプロフィット",
            title: "板注文画面",
          },
          errors: {
            accepted: "承認済",
            allowedOnlyLongPositions: "買いポジションのみ可能",
            allowedOnlyPositionsClosing: "ポジション決済のみ可能",
            allowedOnlyShortPositions: "売りポジションのみ可能",
            automatedTradingDisabledClient: "自動売買は無効化されています。",
            automatedTradingDisabledServer:
              "サーバ側で自動売買が無効化されています。",
            canceled: "取消済",
            common: "エラー",
            demoAllocationDisabled: "デモ口座の割り当てが無効になっています",
            done: "完了",
            donePartially: "一部完了しました",
            frequentRequests: "要求が多過ぎます",
            invalidExpiration: "無効な有効期限",
            invalidOrderType: "無効な注文タイプ",
            invalidParameters: "無効なパラメータ",
            invalidPrices: "無効な価格",
            invalidSLTP: "無効な S/L または T/P",
            invalidVolume: "無効な数量",
            manyTradeRequests: "取引注文が多過ぎます",
            marketClosed: "取引終了しています",
            modificationFailed:
              "注文またはポジションが市場に近いため、変更できませんでした",
            networkProblem: "ネットワークに問題があります",
            noConnection: "未接続",
            notEnoughMoney: "証拠金不足です",
            offQuotes: "売買不成立",
            ok: "OK",
            onTheWay: "途上",
            orderChanged: "注文は変更済みです",
            orderClosePositionExists:
              "このポジションを決済するための注文は既に存在します",
            ordersLimitReached: "注文制限数に達しました",
            permissions: "利用権限がありません",
            placed: "注文済み",
            positionCloseProhibitedByFIFO: "FIFOルールによるポジション決済禁止",
            positionClosed: "ポジションは既にクローズされました",
            positionsLimitReached: "ポジションの上限に達しました",
            priceChanged: "価格変更しました",
            prices: "価格",
            processed: "処理済",
            rejected: "拒否された",
            requestRejectedOrderWillCanceled:
              "リクエストは拒否され、注文はキャンセルされました",
            requoted: "再クォート",
            serverProblem: "サーバ内に技術的問題があります",
            timeout: "時間切れ",
            tradeDisabled: "取引はできません",
            unsupportedFillingMode: "サポート外の約定モード",
            volumeLimitReached: "最大取引量に達しました",
          },
          form: {
            acceptNewQuotes: "新しい価格で注文しますか?",
            btnOpen: {
              hide: "取引フォームを非表示にする",
              show: "取引フォームを表示",
              title: "新規注文",
            },
            buttons: {
              accept: "承認",
              delete: "削除",
              modify: "注文変更",
              ok: "OK",
              placeOrder: "注文を出す",
              reject: "拒否",
              request: "リクエスト",
              requestPrice: "リクエスト価格",
            },
            close: "決済",
            execution: {
              fillOrKill: "FOK注文 (全量約定または全量取消注文)",
              immediateOrCancel: "IOC注文 (部分約定時に未決済分取消注文)",
              bookOrCancel: "BOC (Book or Cancel)",
              label: "執行条件",
              return: "Return (部分約定時に未決済分注文)",
            },
            executionMode: {
              exchange: "取引所注文",
              instant: "ストリーミング注文",
              market: "成行注文",
              request: "リクエスト注文",
            },
            expiration: {
              date: "有効期限",
              label: "有効期限",
              types: {
                specified: "指定された",
                specifiedDay: "指定日",
                today: "当日",
              },
            },
            fields: {
              closeBy: "指定対象玉との両建てを解除",
              comment: "コメント",
              price: "価格",
              stopLoss: "ストップロス",
              takeProfit: "テイクプロフィット",
              volume: "ボリューム",
              errors: {
                volume: {
                  min: "最小ボリュームは{min}",
                  max: "最大ボリュームは{max}",
                  required: "Volume is required",
                  step: "ボリュームは{step}単位で設定できます",
                },
              },
            },
          },
          history: {
            btnOpen: "履歴",
            deals: {
              columns: {
                comment: "コメント",
                commission: "手数料",
                direction: "方向",
                fee: "手数料",
                order: "注文",
                price: "価格",
                profit: "損益",
                swap: "スワップ",
                symbol: "銘柄",
                ticket: "チケット",
                time: "時間",
                type: "タイプ",
                volume: "ボリューム",
              },
            },
            empty: "取引履歴はまだありません",
            menu: {
              columns: {
                horizontalScroll: "水平方向のスクロール",
                resetAll: "すべてリセット",
                title: "列",
              },
              deals: "約定",
              orders: "注文",
              period: {
                all: "全履歴",
                last3Months: "3ヶ月",
                last6months: "過去6ヶ月",
                lastMonth: "1ヶ月",
                title: "期間",
                customPeriod: "期間指定",
                lastYear: "昨年",
                lastWeek: "先週",
                today: "今日",
              },
              positions: "ポジション",
              chart: "チャート",
              newOrder: "新規注文",
            },
            orders: {
              columns: {
                comment: "コメント",
                price: "価格",
                slDescription: "ストップロス",
                state: "状況",
                symbol: "銘柄",
                ticket: "チケット",
                timeDone: "時間",
                timeSetup: "時間",
                tpDescription: "テイクプロフィット",
                type: "タイプ",
                volume: "ボリューム",
                timeSetupDescription: "約定時刻",
                timeDoneDescription: "決済時刻",
              },
              total: {
                title: "トータル",
                filled: "約定済",
                canceled: "キャンセル",
                rejected: "拒否されました",
              },
            },
            positions: {
              columns: {
                commission: "手数料",
                fee: "手数料",
                priceClose: "価格",
                priceCloseDescription: "終値",
                priceOpen: "価格",
                priceOpenDescription: "始値",
                profit: "損益",
                slDescription: "ストップロス",
                swap: "スワップ",
                symbol: "銘柄",
                ticket: "チケット",
                timeClose: "時間",
                timeCloseDescription: "決済時間",
                timeOpen: "時間",
                timeOpenDescription: "約定時刻",
                tpDescription: "テイクプロフィット",
                type: "タイプ",
                volume: "ボリューム",
                comment: "コメント (C)",
              },
            },
            columns: { default: "デフォルト" },
            total: {
              profit: "損益",
              credit: "クレジット",
              deposit: "入金",
              withdrawal: "出金",
              balance: "残高",
              commission: "手数料",
              fee: "料金",
              swap: "スワップ",
              grossProfit: "総利益",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "取引履歴",
                orders: "トレード注文",
                position: "トレードポジション",
                sltp: "SL/TPレベル",
              },
              notification: "取引通知",
            },
            oneClick: "ワンクリック取引",
            tags: { demo: "デモ", readonly: "読み取り専用" },
            oneClickBottom: "下部のワンクリックパネル",
          },
          oneClickDisclaimer: {
            acceptCheckbox: " これらの規約に同意する",
            btnAccept: "承認",
            btnCancel: "取消",
            text: "ワンクリック取引モードを有効にしようとしています。下の[利用規約に同意します]をクリックすると、次の利用規約を読んで理解したことを認め、ここに拘束されることに同意したことになります。<br /><br />ワンクリック取引モードはWebターミナルのメニューから有効または無効にすることができます。<br /><br />注文提出のためのワンクリック取引モードは、1ステップのプロセスです。注文は次の場合に送信されます: チャートのワンクリック取引パネルで、ビッド(SELL)またはアスク(BUY)価格ボタンをタップする。板情報ウィンドウで [売り]、[決済]、[買い]、[注文]のいずれかのボタンをタップする。[取引]タブでポジションを決済または注文を削除する。<br /><br />その後、クリックできる確認プロンプトは表示されません。一度クリックすると、注文を撤回または変更することはできません。通常の市場条件およびシステムパフォーマンスの下では、成行注文は送信後すぐに約定され、拘束力のある取引が開始されます。<br /><br />お客様は、ワンクリック取引モードの使用に関連するすべてのリスクを受け入れることに同意するものとします。これには、そのような注文を送信する際のエラー、省略、または誤りのリスクが含まれますが、これらに限定されません。<br /><br />お客様は、お客様またはお客様に代わって取引を行う他の人物によるそのようなエラー、省略、または間違いの結果として発生する可能性のあるすべての損失、費用、および費用から、{companyName}を完全に補償し、無害に保つことに同意するものとします。",
            title: "ワンクリック取引 - 免責事項",
          },
          quickTrade: {
            hide: "ワンクリック取引パネルを非表示にする",
            show: "ワンクリック取引パネルを表示",
          },
          riskDisclaimer: {
            acceptCheckbox: "上記の警告を理解し、高リスク投資商品を取引します",
            btnAccept: "承認",
            btnCancel: "取消",
            text: "この取引プラットフォームをさらに使用することで、選択した金融機関が提供するレバレッジの高いリスクの高い投資商品にアクセスできるようになります。このような商品への投資は、すべての投資家に適しているとは限りません。預金額の一部または全部を失うリスクがあるためです。<br /><br />リスクの高い投資商品の取引を決定する前に、ご自分の投資目的、経験レベルと許容可能なリスクを慎重に検討してください。初期投資よりも大きな損失を被る可能性があるため、失うわけにはいかない資金を投資するべきではありません。<br /><br />これらの商品への投資に関連するすべてのリスク要因について知識を広げ、疑問がある場合は専門のファイナンシャルアドバイザーにアドバイスを求めることをお勧めします。",
            title: "高リスク投資警告 ",
          },
          table: {
            btnOpen: "トレード",
            columns: {
              comment: "コメント",
              priceClose: "価格",
              priceCloseDescription: "決済価格",
              priceOpen: "価格",
              priceOpenDescription: "約定価格",
              profit: "損益",
              slDescription: "ストップロス",
              swap: "スワップ",
              symbol: "銘柄",
              ticket: "チケット",
              time: "時間",
              tpDescription: "テイクプロフィット",
              type: "タイプ",
              volume: "ボリューム",
            },
            emptyPlug: {
              btnNewOrder: "注文を新規作成",
              title: "ポジションがありません",
            },
            menu: {
              chart: "チャート",
              closePosition: "決済",
              columns: "列",
              modifyOrder: "注文変更",
              modifyPosition: "ポジション変更",
              newOrder: "新規注文",
              resetAll: "すべてリセット",
              deleteOrder: "注文削除",
            },
            oneClick: { deleteOrder: "削除" },
            sections: {
              collateralPositions: "担保ポジション",
              orders: "注文",
              positions: "ポジション",
            },
            total: {
              assets: "保有資産",
              balance: "残高",
              collateral: "担保",
              commission: "手数料",
              credit: "クレジット",
              equity: "有効証拠金",
              liabilities: "負債",
              margin: "証拠金",
              marginFree: "可能額",
              marginLevel: "現在値との差",
            },
          },
          timer: {
            marketWillOpen: "市場はあと{days}{leftTime}で開きます",
            moreThenOneDay: "{numberOfDays}日",
            oneDay: "{numberOfDays}日",
          },
          tradeIsDisabled: {
            account: "この口座の取引はサーバ上で無効になっています",
            collateral: "この銘柄は担保であるため、取引は利用できません",
            disabled: "取引はできません",
            investor:
              "投資家パスワードで接続されているため、取引は利用できません",
            readOnly: "リスク警告を受け入れていないため、取引は利用できません",
            symbol: "この銘柄の取引はできません",
          },
          hotkeys: {
            historyPanel: "履歴パネル",
            journalPanel: "ログ表示",
            marketWatch: "気配値表示",
            quickTrade: "ワンクリック取引",
            tradeForm: "新規注文",
            tradePanel: "取引パネル",
          },
          marketOpen: {
            time: "市場が閉まっています。{time}に開きます",
            afterSeconds: "市場が閉まっています。{time}秒後に開きます",
          },
          expiredTimer: { seconds: "{time}秒で期限切れ" },
          corporateLink: {
            type: {
              clientAgreement: "クライアント契約",
              riskDisclosure: "リスク開示",
              fdmDisclaimer: "FDM免責事項",
              clientAgreementAndRiskDisclosure: "クライアント契約とリスク開示",
              complaintsHandlingProcedure: "苦情処理手続き",
              orderExecutionPolicy: "注文実行ポリシー",
              clientCategorisationNotice: "クライアント分類通知",
              conflictsOfInterestPolicy: "利害相反ポリシー",
              dataProtectionPolicy: "データ保護ポリシー",
            },
          },
          margin: {
            floating: "浮動",
            mode: { marketBuy: "成り行き買い", marketSell: "成り行き売り" },
            rangeMode: {
              value: "想定元本額",
              valuePerSymbol: "銘柄別想定元本額",
              volume: "ボリューム",
              volumePerSymbol: "銘柄別ボリューム",
            },
            showValue: "表示単位：{currency}ロット毎",
            rates: "証拠金率:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "全画面表示モードを無効にする",
            enable: "全画面表示モードを有効にする",
          },
          journal: {
            btnOpen: "ログ表示",
            columns: { message: "メッセージ", source: "ソース", time: "時間" },
            menu: {
              clear: "クリア",
              debugMode: "デバッグモード",
              exportFile: "ファイルにエクスポート",
            },
          },
          menu: {
            about: "プログラムについて",
            contact: "お問い合わせ",
            brokerInformation: "企業情報",
            chartSettings: {
              controls: "チャートコントロール",
              grid: "グリッド",
              ohlc: "四本値表示",
              title: "チャート設定",
              askPrice: "買い気配値",
              crosshair: "十字カーソル",
            },
            connect: "口座に接続",
            language: {
              title: "言語",
              search: "検索",
              nothingFound: "言語が見つかりません",
            },
            openDemo: "デモ口座を開設",
            openReal: "リアル口座を開設",
            settings: "設定",
            shortcuts: "ショートカット",
            theme: {
              blackWhite: "白黒",
              blueRed: "青と赤",
              dark: "ダークテーマ",
              editor: "テーマエディタ",
              greenRed: "緑と赤",
              light: "ライトテーマ",
              neutral: "ニュートラル",
              templates: "カラーテンプレート",
            },
            title: "メニュー",
            tradingAccount: "取引口座",
            terms: "利用規約",
            desktopPlatforms: "デスクトッププラットフォーム",
            qrCode: {
              install: "スキャンして{store}からインストール",
              downloadApk: "スキャンしてAndroid APKファイルを取得",
            },
            economicCalendar: "経済指標カレンダー",
          },
          screen: { back: "戻る" },
          mobile: { bottomNav: { quotes: "相場情報" } },
          hotkeys: {
            sections: { navigation: "ナビゲーション", view: "表示" },
            escape: "キャンセル",
            indicators: "インジケータ",
            depthOfMarket: "板注文画面",
            objectTreePanel: "オブジェクトツリー",
            scrollRight: "次のローソク足",
            scrollToStart: "チャートを最初までスクロール",
            scrollLeft: "前のローソク足",
            scrollToEnd: "チャートを最後までスクロール",
            resetChartView: "チャートをリセット",
            zoomIn: "拡大",
            zoomOut: "縮小",
            fullScreen: "全画面",
            screenshot: "チャートを画像として保存",
            title: "ショートカット",
          },
          timezone: {
            title: "タイムゾーン",
            city: {
              cairo: "カイロ",
              casablanca: "カサブランカ",
              johannesburg: "ヨハネスブルグ",
              lagos: "ラゴス",
              nairobi: "ナイロビ",
              tunis: "チュニス",
              anchorage: "アンカレッジ",
              bogota: "ボゴタ",
              buenosAires: "ブエノスアイレス",
              caracas: "カラカス",
              chicago: "シカゴ",
              denver: "デンバー",
              elSalvador: "エルサルバドル",
              juneau: "ジュノー",
              lima: "リマ",
              losAngeles: "ロサンゼルス",
              mexicoCity: "メキシコシティ",
              newYork: "ニューヨーク",
              phoenix: "フェニックス",
              santiago: "サンティアゴ",
              saoPaulo: "サンパウロ",
              toronto: "トロント",
              vancouver: "バンクーバー",
              almaty: "アルマトイ",
              ashgabat: "アシガバート",
              bahrain: "バーレーン",
              bangkok: "バンコク",
              kolkata: "コルカタ",
              colombo: "コロンボ",
              dhaka: "ダッカ",
              dubai: "ドバイ",
              hongKong: "香港",
              jakarta: "ジャカルタ",
              jerusalem: "エルサレム",
              karachi: "カラチ",
              kathmandu: "カトマンズ",
              kuwait: "クウェート",
              manila: "マニラ",
              muscat: "マスカット",
              nicosia: "ニコシア",
              qatar: "カタール",
              rangoon: "ラングーン",
              riyadh: "リヤド",
              saigon: "サイゴン",
              seoul: "ソウル",
              shanghai: "上海",
              singapore: "シンガポール",
              taipei: "台北",
              tehran: "テヘラン",
              tokyo: "東京",
              reykjavik: "レイキャビク",
              adelaide: "アデレード",
              brisbane: "ブリスベン",
              perth: "パース",
              sydney: "シドニー",
              amsterdam: "アムステルダム",
              athens: "アテネ",
              belgrade: "ベオグラード",
              berlin: "ベルリン",
              bratislava: "ブラチスラバ",
              brussels: "ブリュッセル",
              bucharest: "ブカレスト",
              budapest: "ブダペスト",
              copenhagen: "コペンハーゲン",
              dublin: "ダブリン",
              helsinki: "ヘルシンキ",
              istanbul: "イスタンブール",
              lisbon: "リスボン",
              london: "ロンドン",
              luxembourg: "ルクセンブルク",
              madrid: "マドリッド",
              malta: "マルタ",
              moscow: "モスクワ",
              oslo: "オスロ",
              paris: "パリ",
              prague: "プラハ",
              riga: "リガ",
              rome: "ローマ",
              stockholm: "ストックホルム",
              tallinn: "タリン",
              vienna: "ウィーン",
              vilnius: "ビリニュス",
              warsaw: "ワルシャワ",
              zurich: "チューリッヒ",
              auckland: "オークランド",
              chatham: "チャタム",
              fakaofo: "ファカオフォ",
              honolulu: "ホノルル",
              norfolk: "ノーフォーク",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e as j };
