const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Απόκρυψη συμβάντων οικονομικού ημερολογίου από το γράφημα",
              show: "Εμφάνιση συμβάντων οικονομικού ημερολογίου στο γράφημα",
            },
          },
          controls: {
            reset: "Επαναφορά γραφήματος",
            scrollEnd: "Κύλιση στο τέλος",
            scrollLeft: "Κύλιση προς τα αριστερά",
            scrollRight: "Κύλιση προς τα δεξιά",
            zoomIn: "Μεγέθυνση",
            zoomOut: "Σμίκρυνση",
          },
          crosshair: "Σταυρόνημα",
          delay: "{delay} ελάχιστη καθυστέρηση",
          indicators: {
            btnAddIndicator: "Προσθήκη δείκτη",
            btnOpenPopup: "Προσθήκη δείκτη",
            close: "Κλείσιμο",
            form: {
              applyTo: "Εφαρμογή σε",
              background: {
                title: "Φόντο",
                down: "Κάτω φόντο kumo",
                up: "Πάνω φόντο kumo",
              },
              deviation: "Απόκλιση",
              enterDistance: "Περίοδος",
              enterShift: "Αλλαγή",
              fastEma: "Γρήγορη EMA",
              slowEma: "Αργή EMA",
              line: {
                base: "Γραμμή Βάσης",
                down: "Κάτω γραμμή",
                minusDI: "Γραμμή -DI",
                null: "Μηδενική γραμμή",
                plusDI: "Γραμμή +DI",
                style: "Στύλ γραμμής",
                cci: "Γραμμή CCI",
                up: "Άνω γραμμή",
                fi: "Γραμμή FI",
              },
              maximum: "Μέγιστο",
              method: {
                exponential: "Εκθετική",
                linearWeighted: "Γραμμική Ζυγισμένη",
                simple: "Απλό",
                smoothed: "Εξομαλυμένη",
                title: "Μέθοδος",
              },
              opacity: "Αδιαφάνεια",
              period: {
                jaws: "Περίοδος Jaws",
                lips: "Περίοδος Lips",
                teeth: "Περίοδος teeth",
                title: "Περίοδος",
                dPercent: "%D περίοδος",
                kPercent: "%K περίοδος",
              },
              selectApplyTo: "Επιλογή",
              selectVolumesType: "Επιλέξτε τύπο όγκου",
              shift: "Μετακίνηση",
              showTimeframes: "Εμφάνιση όλων των χρονικών πλαισίων",
              slowing: "Επιβράδυνση",
              step: "Βήμα",
              style: {
                down: "Κάτω στύλ",
                jaws: "Τύπος Μπλέ Γραμμής",
                lips: "Τύπος Πράσινης Γραμμής",
                main: "Κύριο στύλ",
                signal: "Στύλ σήματος",
                teeth: "Τύπος Κόκκινης Γραμμής",
                title: "Μορφή",
                up: "Πάνω στύλ",
                rvi: "RVI στυλ",
              },
              volume: { down: "Άυξηση όγκου", up: "Μείωση όγκου" },
              volumes: "Όγκοι",
              mfiUp: "MFI Up",
              mfiDown: "MFI Κάτω",
              price: {
                title: "Τιμή",
                select: "Επιλέξτε τιμή",
                lowHigh: "Χαμηλή/Υψηλή",
                closeClose: "Κλείσιμο/Κλείσιμο",
              },
            },
            search: {
              empty: "Δεν βρέθηκαν αντικείμενα",
              title: "Αναζήτηση",
              tryAnother: "Δοκιμάστε ένα άλλο ερώτημα",
            },
            tabs: {
              all: "Όλα",
              billWilliams: "Bill Williams",
              oscillators: "Ταλαντωντές",
              trend: "Τάση",
              volumes: "Όγκοι",
            },
            title: "Επιλέξτε ένδειξη",
            up: "Πάνω",
            down: "Κάτω",
            chartControls: {
              show: "Εμφάνιση",
              hide: "Απόκρυψη",
              settings: "Ρυθμίσεις",
              remove: "Αφαίρεση",
            },
          },
          loading: "Φόρτωση",
          marketWatch: {
            btnOpen: {
              hide: "Απόκρυψη Market Watch",
              show: "Προβολή Market Watch",
            },
            columns: {
              closePrice: "Τιμή κλεισίματος",
              dailyChange: "Ημερήσια Αλλαγή",
              openPrice: "Τιμή ανοίγματος",
              spread: "Περιθώριο",
              symbol: "Σύμβολο",
              time: "Ώρα",
              high: "Υψηλή",
              low: "Χαμηλή",
              last: "Τελευταία",
              lastHigh: "Τελευταίο Υψηλό",
              lastLow: "Τελευταίο Χαμηλό",
              highLow: "Υψηλή/Χαμηλή",
              bidLow: "Προσφορά Χαμηλά",
              bidHigh: "Προσφορή Ψηλά",
              askHigh: "Ζήτηση Ψηλά",
              askLow: "Ζήτηση Χαμηλά",
              bid: "Προσφορά",
              ask: "Ζήτηση",
              title: "Στήλες",
            },
            menu: {
              chart: "Διάγραμα",
              columns: "Στήλες",
              dom: "Βάθος αγοράς",
              hide: "Απόκρυψη",
              newOrder: "Νέα Εντολή",
              specification: "Προδιαγραφές",
            },
            search: "Αναζήτηση",
            searchSymbol: "Σύμβολο αναζήτησης",
            nothingFound: "Δεν βρέθηκαν σύμβολα",
          },
          objects: {
            form: {
              statistics: "Στατιστικά",
              arrows: "Τόξα",
              showAlways: "Δείξτε πάντα",
              angle: "Προοπτική",
              distance: "Απόσταση",
              bar: "Γραμμή",
              price: "Τιμή",
              prices: "Τιμές",
              showPrice: "Εμφάνιση τιμής",
              showText: "Εμφάνιση κειμένου",
              showDate: "Εμφάνιση ημερομηνίας",
              showTime: "Εμφάνιση ώρας",
              showAllTimeframes: "Εμφάνιση όλων των χρονικών πλαισίων",
              showPearsonR: "Εμφάνιση Pearson's R",
              showLabels: "Εμφάνιση ετικετών",
              yourText: "Το κείμενό σας",
              props: "Ιδιότητες",
              style: "Μορφή",
              rays: "Ακτίνες",
              background: "Φόντο",
              extends: "Επέκταση",
              extended: "Επεκτάθηκε",
              pipsPerBar: "Pips ανά γραμμή",
              gannAngle: "Γωνία Gann",
              deviations: "Αποκλίσεις",
              labels: "Ετικέτες",
              reverse: "Αντίστροφο",
              btn: { update: "Ενημέρωση", cancel: "Ακύρωση" },
              tabs: {
                style: "Μορφή",
                coordinates: "Συντεταγμένες",
                visualization: "Απεικόνιση",
              },
              range: {
                price: "Eύρος τιμών",
                bars: "Eύρος ιστών",
                date: "Eύρος ημερομηνιών",
              },
              align: {
                horizontal: "Οριζόντια ευθυγράμμιση",
                vertical: "Κατακόρυφη στοίχιση",
                left: "Αριστερά",
                right: "Δεξιά",
                center: "Κέντρο",
                top: "Πάνω",
                middle: "Μέση",
                bottom: "Κατώτατο",
              },
              line: {
                style: "Στύλ γραμμής",
                base: "Γραμμή βάσης",
                up: "Άνω γραμμή",
                down: "Κάτω γραμμή",
                middle: "Μεσαία γραμμή",
              },
            },
            visible: {
              hide: "Απόκρυψη όλων των αντικειμένων",
              show: "Εμφάνιση όλων των αντικειμένων",
            },
            lock: "Κλείδωμα όλων των αντικειμένων",
            unlock: "Ξεκλείδωμα όλων των αντικειμένων",
            andrewsPitchforkChannel: "Andrews Pitchfork",
            equidistantChannel: "Ισαπέχων Κανάλι",
            regressionChannel: "Κανάλι παλινδρόμησης",
            stdDevChannel: "Κανάλι Τυπικής Απόκλισης",
            fibonacciRetracement: "Επαναφορά Fibonacci",
            gannFan: "Gann Fan",
            gannGrid: "Gann Grid",
            gannLine: "Gann Line",
            arrowLine: "Γραμμή με Βέλη",
            crossLine: "Σταυρογραμμή",
            extendedLine: "Εκτεταμένη Γραμμή",
            horizontalRay: "Οριζόντια Ακτίνα",
            horizontalLine: "Οριζόντια Γραμμή",
            infoLine: "Γραμμή πληροφοριών",
            rayLine: "Ακτίνα",
            trendAngle: "Τάση υπό Γωνία",
            trendline: "Γραμμή Τάσης",
            verticalLine: "Κάθετη Γραμμή",
            disjointAngle: "Κανάλι Disjoint",
            flatTopBottom: "Επίπεδo πάνω/κάτω",
            rectangle: "Ορθογώνιο Παραλληλόγραμμο",
            circle: "Κύκλος",
            triangle: "Τρίγωνο",
            ellipse: "Ελλειψη",
            text: "Κείμενο",
            rulerLine: "Γραμμή Χάρακα",
          },
          period: {
            full: {
              D1: "Ημέρα",
              H1: "1 Ωρα",
              H4: "4 Ωρες",
              M1: "1 Λεπτό",
              M15: "15 Λεπτά",
              M30: "30 Λεπτά",
              M5: "5 Λεπτά",
              MN: "Μήνας",
              Unknown: "Άγνωστο",
              W1: "Εβδομάδα",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Άγνωστο",
              W1: "W1",
            },
          },
          screenshot: "Αποθήκευση γραφήματος ως εικόνα",
          symbolSpecs: {
            GTCmode: "GTC κατάσταση",
            calculation: "Υπολογισμός",
            chartMode: "Λειτουργία γραφήματος",
            contractSize: "Μέγεθος συμβολαίου",
            days: {
              friday: "Παρασκευή",
              monday: "Δευτέρα",
              saturday: "Σάββατο",
              sunday: "Κυριακή",
              thursday: "Πέμπτη",
              tuesday: "Τρίτη",
              wednesday: "Τετάρτη",
            },
            digits: "Ψηφία",
            empty: "Δεν έχει επιλεγεί σύμβολο",
            execution: "Εκτέλεση",
            expiration: "Λήξη",
            filling: "Πολιτική ολοκλήρωσης",
            initial: "Αρχικό",
            maintenance: "Διατήρηση",
            marginCurrency: "Νόμισμα περιθωρίου",
            marginRate: "Ποσοστό περιθωρίου",
            maxVolume: "Μέγιστος όγκος",
            minVolume: "Ελάχιστος όγκος",
            orders: "Εντολές",
            profitCurrency: "Νόμισμα κέρδους",
            schedule: { quotes: "Τιμές", trade: "Συναλλαγή" },
            sector: "Τομέας",
            spread: "Περιθώριο",
            stopsLevel: "Επίπεδο στοπ",
            swapLong: "Ανταλλαγή αγοράς",
            swapShort: "Ανταλλαγή πώλησης ",
            swapType: "Τύπος ανταλλαγής",
            title: "{symbol} προδιαγραφή σύμβασης",
            tradeMode: "Συναλλαγή",
            volumeStep: "Βήμα όγκου",
            volumeLimit: "Όριο Όγκου",
            tickSize: "Μέγεθος ελάχιστης μεταβολής",
            tickValue: "Τιμή ελάχιστης μεταβολής",
            marginInitial: "Αρχικό περιθώριο",
            marginHedged: "Αντισταθμιζόμενο περιθώριο κέρδους",
            commission: {
              daily: {
                volume: "Ημερήσιος όγκος σε παρτίδες",
                turnoverVolume: "Ημερήσιος κύκλος εργασιών σε lots",
                turnoverMoney: "Ημερήσιος κύκλος εργασιών σε χρήματα",
                value: "Ημερήσια αξία των προσφορών",
                profit: "Καθημερινό κέρδος",
              },
              monthly: {
                volume: "Μηνιαίος όγκος σε παρτίδες",
                turnoverVolume: "Mηνιαίος κύκλος εργασιών σε lots",
                turnoverMoney: "Μηνιαίος κύκλος εργασιών σε χρήματα",
                value: "Μηνιαία αξία των προσφορών",
                profit: "Μηνιαίο κέρδος",
              },
              instant: {
                volume: "Άμεσος όγκος ανά συναλλαγή",
                value: "Άμεση αξία ανά συναλλαγή",
                profit: "Άμεσο κέρδος ανά συναλλαγή",
              },
              entry: {
                in: "συναλλαγές εισόδου",
                out: "συναλλαγές εξόδου",
                all: "συναλλαγές εισόδου/εξόδου",
              },
              tier: {
                mode: {
                  pips: "σημεία",
                  percent: "% σε {currency}",
                  percentProfit: "% του κέρδους {currency}",
                },
                type: { perDeal: "ανά συναλλαγή", perLot: "ανά lot" },
              },
              header: "Προμήθειες",
            },
          },
          tree: {
            close: "Κλείσιμο",
            empty: "Δεν έχετε κανένα αντικείμενο στο γράφημα",
            lock: "Κλείδωμα",
            remove: "Αφαίρεση",
            settings: "Ρυθμίσεις",
            title: "Διαχείριση Σχεδίων",
            unlock: "Ξεκλείδωμα",
          },
          types: {
            area: "Περιοχή",
            line: "Γραμμή",
            bars: "Ράβδοι",
            candlestick: "Κηροπήγιο",
          },
          volumeTypes: {
            tickVolumes: "Όγκοι ελάχιστης μεταβολής",
            volumes: "Όγκοι",
            withoutVolumes: "Χωρίς Όγκους",
            realVolumes: "Πραγματικοί όγκοι",
          },
          zoom: { in: "Μεγέθυνση", out: "Σμίκρυνση" },
          hotkeys: {
            arrowLine: "Γραμμή με Βέλη",
            chartTypeArea: "Διάγραμμα Περιοχής",
            chartTypeLine: "Γραμμικό Γράφημα",
            chartTypeBar: "Διάγραμμα Ράβδων",
            chartTypeCandle: "Διάγραμμα Κεριών",
            crossLine: "Σταυρογραμμή",
            extendedLine: "Εκτεταμένη Γραμμή",
            horizontalLine: "Οριζόντια Γραμμή",
            infoLine: "Γραμμή πληροφοριών",
            rayLine: "Ακτίνα",
            realVolumes: "Πραγματικοί Όγκοι",
            tickVolumes: "Όγκοι ελάχιστης μεταβολής",
            trendline: "Γραμμή Τάσης",
            verticalLine: "Κάθετη Γραμμή",
            sections: {
              chartType: "Τύπος Γραφήματος",
              drawing: "Σχέδιο",
              volume: "Όγκος",
            },
            crosshairRuler: "Χάρακας Σταυρού",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  t = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Ξεκινήστε με τον λογαριασμό σας",
            newAccountOpened: "Δημιουργήθηκε νέος λογαριασμός",
          },
          brokerInformation: {
            company: "Εταιρεία",
            email: "Ηλεκτρονικό ταχυδρομείο",
            phone: "Τηλέφωνο",
            registrationAddress: "Διεύθυνση Εγγραφής",
            title: "Στοιχεία της εταιρείας",
            website: "Διαδικτυακός Τόπος",
          },
          changePassword: {
            btnChange: "Αλλαγή Κωδικού",
            confirmPassword: "Επιβεβαίωση Κωδικού",
            newPassword: "Νέος Κωδικός",
            title: "Αλλαγή κωδικού",
          },
          connect: {
            btnConnect: "Σύνδεση με λογαριασμό",
            contactBroker: "Επικοινωνήστε με την εταιρεία",
            forgotPassword: "Ξεχάσατε τον κωδικό;",
            loginPlaceholder: "Εισαγάγετε Σύνδεση",
            passwordPlaceholder: "Εισάγετε τον κωδικό πρόσβασης",
            savePassword: "Αποθήκευση κωδικού",
            title: "Σύνδεση με λογαριασμό",
          },
          copyToClipboard: {
            copy: "Αντιγραφή στο πρόχειρο",
            unsupported: "Η αντιγραφή δεν υποστηρίζεται",
          },
          demo: {
            accountOpeningWarning:
              "Ανοίγοντας λογαριασμό, συμφωνείτε με τους όρους ανοίγματος λογαριασμού και με την πολιτική προστασίας δεδομένων του {brokerName}",
            btnOpenDemo: "Ανοίξτε δοκιμαστικό λογαριασμό",
            title: "Ανοίξτε δοκιμαστικό λογαριασμό",
            tradeWithRealMoney:
              "Για να κάνετε συναλλαγές με πραγματικά χρήματα, πρέπει να συνάψετε ξεχωριστή συμφωνία με μια εταιρεία χρηματοοικονομικών υπηρεσιών.",
          },
          disclaimer: {
            btnAccept: "Αποδοχή",
            headerTitle: "Καλώς ήρθατε στο MetaTrader 5",
            text: 'Η MetaQuotes Ltd είναι εταιρεία ανάπτυξης λογισμικού και δεν παρέχει χρηματοοικονομικές, επενδυτικές, χρηματιστηριακές, εμπορικές ή υπηρεσίες τροφοδοσίας δεδομένων, ούτε εμπλέκεται σε πληρωμές βάσει προμήθειας σχετικά με οποιεσδήποτε συναλλαγές.<br /><br />Πατώντας το Κουμπί ΑΠΟΔΟΧΗ Συμφωνώ με τους <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">όρους και τις προϋποθέσεις της EULA</a>, τους <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Πολιτική απορρήτου</a> και με τη δήλωση αποποίησης ευθύνης.<br /><br /> Καμία από τις πληροφορίες που διατίθονται στην εφαρμογή δεν προορίζεται ως επενδυτική συμβουλή. Πριν χρησιμοποιήσετε αυτήν την εφαρμογή για συναλλαγές, θα πρέπει να ζητήσετε τη συμβουλή ενός ειδικευμένου και εγγεγραμμένου επαγγελματία αξιών και να αναλάβετε τη δική σας δέουσα επιμέλεια.',
            title: "Αποποίηση Ευθυνών",
          },
          errors: {
            error: "Σφάλμα",
            invalidCode: "Μη έγκυρος κωδικός",
            invalidEmail: "Μη έγκυρη  διεύθυνση ηλεκτρονικού ταχυδρομείου",
            invalidPhone: "Μη έγκυρο τηλέφωνο",
            unknownError: "Άγνωστο λάθος",
          },
          form: {
            accountType: "Τύπος Λογ",
            address: "Διεύθυνση",
            addressPlaceholder: "Εισαγάγετε τη διεύθυνσή σας",
            annualDeposit: "Ετήσιο κατάθεση",
            annualIncome: "Ετήσιο εισόδημα",
            broker: "Εταιρεία",
            btn: {
              back: "Πίσω",
              cancel: "Ακύρωση",
              next: "Επόμενο",
              openAccount: "Ανοίξτε Λογαριασμό",
              remove: "Αφαίρεση",
              signOut: "Αποσύνδεση",
            },
            city: "Πόλη",
            cityPlaceholder: "Εισαγάγετε την πόλη σας",
            country: "Χώρα",
            dateBirth: "Γέννηση",
            deposit: "Κατάθεση",
            education: "Εκπαίδευση",
            email: {
              address: "Ηλεκτρονικό ταχυδρομείο",
              code: "Κωδικός από ηλεκτρονικό ταχυδρομείο",
              placeholder: "Εισάγετε ηλεκτρονικό ταχυδρομείο",
              title: "Ηλεκτρονικό ταχυδρομείο",
            },
            employement: "Εργασία",
            forex: "Forex",
            futures: "Futures",
            gender: { female: "Θηλυκό", male: "Αρσενικό", title: "Φύλο" },
            identity: "Ταυτότητα:",
            imageOrPdfFile: "Αρχείο εικόνας ή PDF",
            investor: "Κωδικός Επενδυτή",
            language: "Γλώσσα",
            leverage: "Μόχλευση",
            login: "Είσοδος",
            min5chars: "Ελάχιστο 5 χαρακτήρες",
            name: {
              middle: "Μεσαίο όνομα",
              surname: "Επώνυμο",
              title: "Όνομα",
              yourName: "Το όνομα σας",
            },
            nationality: "Ιθαγένεια",
            netWorth: "Καθαρή αξία",
            optional: "Προαιρετικό",
            password: "Κωδικός",
            passwordReadOnly: "Κωδικός πρόσβασης μόνο για ανάγνωση",
            phone: {
              mobile: "Κινητό τηλέφωνο",
              number: "Tηλέφωνο",
              sms: "Κωδικός από SMS",
            },
            pleaseSelect: "Παρακαλώ Eπιλέξτε",
            policyCheckbox:
              "Συμφωνώ με τους όρους για το άνοιγμα λογαριασμού και την πολιτική προστασίας δεδομένων",
            server: "Διακομιστής",
            side: { back: "Πίσω Πλευρά", front: "Μπροστινή Πλευρά" },
            sourceWealth: "Πηγή πλούτου",
            state: "Κατάσταση",
            status: "Κατάσταση",
            stocks: "Stocks",
            taxID: "ΑΦΜ",
            type: "Τύπος",
            useHedge:
              "Χρησιμοποιήστε την μέθοδο αντιστάθμισης στις συναλλαγές σας",
            verificationCodes: {
              email:
                "Έχουμε στείλει κωδικό επαλήθευσης στο ηλεκτρονικό ταχυδρομείο σας",
              phone: "Έχουμε στείλει κωδικό επαλήθευσης στο τηλέφωνό σας",
              phoneEmail:
                "Έχουμε στείλει κωδικούς επαλήθευσης στο τηλέφωνο και στο ηλεκτρονικό ταχυδρομείο σας",
            },
            zipCode: "Ταχυδρομικός Kώδικας",
          },
          mainForm: {
            title: "Εμπορικοί Λογαριασμοί",
            titleWithName: "Εμπορικοί Λογαριασμοί: {brokerName}",
          },
          otp: {
            disable2FA: "Απενεργοποίηση 2FA/TOTP",
            disable2FAAccount: "Απενεργοποίηση 2FA/TOTP για λογαριασμό {login}",
            disableEnterCode:
              "Για να απενεργοποιήσετε το 2FA/TOTP, εισαγάγετε τον κωδικό του λογαριασμού σας που δημιουργήθηκε από τον Επαληθευτή.",
            downloadApp:
              "Κάντε λήψη της εφαρμογής Google Authenticator / Microsoft Authenticator / Authy στην κινητή συσκευή σας και σαρώστε τον κωδικό QR:",
            enable2FA: "Ενεργοποίηση 2FA/TOTP",
            enable2FAAccount: "Ενεργοποίηση 2FA/TOTP για λογαριασμό {login}",
            enterCode:
              "Για να ελέγξετε τη λειτουργία του Επαληθευτή, εισαγάγετε τον κωδικό του λογαριασμού σας που δημιουργήθηκε από την εφαρμογή.",
            oneTimePassword: "Κωδικός μιάς χρήσης:",
            placeholder: "Εισαγάγετε το OTP του λογαριασμού",
            required:
              "Απαιτείται έλεγχος ταυτότητας 2FA για πρόσθετη ασφάλεια λογαριασμού.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Τραπεζική δήλωση",
              utilityBill: "Λογαριασμός ΥΚΩ",
            },
            conditionsForUploadingFiles: {
              documents:
                "Ορισμένοι τύποι εγγράφων απαιτούν δύο φωτογραφίες: μπροστινή και πισινή όψη",
              proofAddress:
                "Οι λογαριασμοί για υπηρεσίες κινητής τηλεφωνίας δεν γίνονται δεκτοί ως απόδειξη διεύθυνσης",
              utilityBill:
                "Ο λογαριασμός υπηρεσίας πρέπει να περιέχει το όνομα και τη διεύθυνσή σας και να μην είναι παλαιότερος από 3 μήνες",
            },
            documentType: {
              driverLicense: "Άδεια οδήγησης",
              idCard: "Δελτίο ταυτότητας",
              passport: "Διαβατήριο",
              residencePermit: "Άδεια παραμονής",
            },
            educationLevel: {
              bachelor: "Πτυχίο πανεπιστημίου ή ισοδύναμο",
              highScholl: "Λύκειο",
              master: "Master βαθμό ή ισοδύναμο",
              none: "Κανένας",
              other: "'Αλλα",
              phd: "Διδακτορικό ή ισοδύναμο",
            },
            employment: {
              employed: "Εργοδοτούμενος",
              other: "'Αλλα",
              retired: "Συνταξιούχος",
              selfEmployed: "Ιδιοκτήτης επιχείρησης ή αυτοαπασχολούμενος",
              student: "Μαθητης σχολειου",
              unemployed: "Άνεργος",
            },
            experience: "Πραγματική εμπειρία συναλλαγών:",
            experienceLevel: {
              above3: "> 3 χρόνια",
              form1to3: "1 έως 3 έτη",
              less1: "< 1 έτος",
            },
            industry: {
              agriculture: "Γεωργία",
              communication:
                "Τέχνες, τεχνολογία ήχου και εικόνας και επικοινωνία",
              construction: "Αρχιτεκτονική και Κατασκευή",
              education: "Εκπαίδευση",
              engineering: "Μηχανική και τα Μαθηματικά",
              government: "Κυβέρνηση και Δημόσια Διοίκηση",
              healthcare: "Φροντίδα υγείας",
              it: "Τεχνολογία πληροφοριών",
              management: "Διαχείριση και διοίκηση επιχειρήσεων",
              manufacturing: "Βιομηχανοποίηση",
              marketing: "Προώθηση και πωλήσεις",
              none: "Κανένας",
              other: "'Αλλα",
              science: "Επιστήμη και Τεχνολογία",
              security: "Νομική, Δημόσια ασφάλεια, Διορθώσεις και Ασφάλεια",
              tourism: "Φιλοξενία και Τουρισμός",
              transport: "Μεταφορές, διανομή και εφοδιαστική",
            },
            policy:
              "Τα προσωπικά στοιχεία χρησιμοποιούνται για το άνοιγμα ενός εμπορικού λογαριασμού και δεν μεταβιβάζονται σε τρίτους. Οι πληροφορίες αντιμετωπίζονται με ασφάλεια και εμπιστευτικότητα.",
            takePhoto:
              "Παρακαλώ τραβήξτε φωτογραφίες των εγγράφων σας και ανεβάστε εδώ χωρίς καμία επεξεργασία",
            title: "Ανοίξτε πραγματικό λογαριασμό",
            wealthSource: {
              employment: "Απασχόληση",
              inheritance: "Δώρα ή Κληρονομιά",
              other: "'Αλλα",
              savings: "Αποταμιεύσεις ή Επενδύσεις",
            },
          },
          saveAccountData:
            "Κρατήστε τα στοιχεία σύνδεσης και τον κωδικό πρόσβασής σας σε ασφαλές μέρος",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Κλείσιμο",
            empty: "Δεν έχουμε δεδομένα όγκου για αυτό το σύμβολο",
            extendedBook: {
              hide: "Απόκρυψη Εκτεταμένου Βιβλίου",
              show: "Εμφάνιση Εκτεταμένου Βιβλίου",
            },
            menu: {
              amount: "Ποσότητα αντί παρτίδες (Lots)",
              extended: "Επέκταση",
              spread: "Περιθώριο",
            },
            spread: { hide: "Απόκρυψη Διασποράς", show: "Εμφάνιση Διασποράς" },
            stopLoss: "Τιμή ελαχιστοποίησης ζημιάς",
            takeProfit: "Εξασφάλιση κέρδους",
            title: "Βάθος αγοράς",
          },
          errors: {
            accepted: "Έγινε αποδοχή",
            allowedOnlyLongPositions: "Μόνο οι μακριές θέσεις επιτρέπονται ",
            allowedOnlyPositionsClosing: "Μόνο το κλείσιμο θέσης επιτρέπεται",
            allowedOnlyShortPositions: "Μόνο βραχείες θέσεις επιτρέπονται",
            automatedTradingDisabledClient:
              "Η δυνατότητα αυτοματοποιημένης διαπραγμάτευσης είναι απενεργοποιημένη από το τερματικό του επενδυτή",
            automatedTradingDisabledServer:
              "Η δυνατότητα αυτοματοποιημένης διαπραγμάτευσης είναι απενεργοποιημένη από την πλευρά του διακομιστή",
            canceled: "Ακυρωμένο",
            common: "Σύνηθες λάθος",
            demoAllocationDisabled:
              "Η εκχώρηση λογαριασμού επίδειξης είναι απενεργοποιημένη",
            done: "Ολοκληρώθηκε",
            donePartially: "Ολοκληρώθηκε εν μέρει",
            frequentRequests: "Πολύ συχνά αιτήματα",
            invalidExpiration: "Ακατάλληλη λήξη",
            invalidOrderType: "Ακατάλληλος τύπος εντολής",
            invalidParameters: "Ακατάλληλες παράμετροι",
            invalidPrices: "Ακατάλληλες τιμές",
            invalidSLTP: "Ακατάλληλες τιμές S/L ή T/P",
            invalidVolume: "Ακατάλληλος όγκος",
            manyTradeRequests: "Πάρα πολλά αιτήματα",
            marketClosed: "Η αγορά είναι κλειστή",
            modificationFailed:
              "Η τροποποίηση απέτυχε λόγω του ότι η εντολή είναι πολύ κοντά στην τιμή της αγοράς",
            networkProblem: "Πρόβλημα δικτύου",
            noConnection: "Δεν υπάρχει σύνδεση",
            notEnoughMoney: "Δεν έχετε αρκετά χρήματα",
            offQuotes: "τιμές εκτός",
            ok: "OK",
            onTheWay: "Έρχεται",
            orderChanged: "Η εντολή έχει ήδη αλλαχθεί",
            orderClosePositionExists:
              "Η εντολή για να κλείσει η θέση αυτή υπάρχει ήδη",
            ordersLimitReached: "Έχετε φτάσει το όριο εντολών",
            permissions: "Δεν υπάρχουν αρκετά δικαιώματα",
            placed: "Τοποθετήθηκε",
            positionCloseProhibitedByFIFO:
              "Κλείσιμο θέσης απαγορεύεται λόγω κανονισμού FIFO",
            positionClosed: "Η θέσης έχει ήδη κλείσει",
            positionsLimitReached: "Το όριο Θέσεων έχει επιτευχθεί",
            priceChanged: "Η τιμή άλλαξε",
            prices: "Τιμές",
            processed: "Επεξεργάστηκε",
            rejected: "Απορρίφθηκε",
            requestRejectedOrderWillCanceled:
              "Η αίτηση έχει απορριφθεί, η εντολή ακυρώθηκε",
            requoted: "Νέες τιμές δόθηκαν",
            serverProblem: "Τεχνικό πρόβλημα διακομιστή ",
            timeout: "Λήξη χρονικού περιθωρίου",
            tradeDisabled: "Οι συναλλαγές δεν επιτρέπονται",
            unsupportedFillingMode: "Μη υποστηριζόμενος τύπος πλήρωσης",
            volumeLimitReached: "Έχετε φτάσει το μέγιστο επιτρεπόμενο όγκο",
          },
          form: {
            acceptNewQuotes: "Δέχεστε αυτές τις νέες τιμές;",
            btnOpen: {
              hide: "Απόκρυψη Φόρμας Συναλλαγών",
              show: "Εμφάνιση Φόρμας Συναλλαγών",
              title: "Νέα Εντολή",
            },
            buttons: {
              accept: "Αποδοχή",
              delete: "Διαγραφή",
              modify: "Τροποποιήστε",
              ok: "OK",
              placeOrder: "Εκτέλεση Εντολής",
              reject: "Απόρριψη",
              request: "Αίτημα",
              requestPrice: "Αίτηση Τιμής",
            },
            close: "Κλείσιμο",
            execution: {
              fillOrKill: "Ολοκλήρωση ή Ακύρωση",
              immediateOrCancel: "Άμεσα ή Ακύρωση",
              bookOrCancel: "Κάντε κράτηση ή ακύρωση",
              label: "Πολιτική συμπληρωσης",
              return: "Επιστροφή",
            },
            executionMode: {
              exchange: "Εκτέλεση εντολής Χρηματιστηρίου",
              instant: "Άμεση Εκτέλεση",
              market: "Εκτέλεση στην τιμή αγοράς",
              request: "Αίτημα εκτέλεσης",
            },
            expiration: {
              date: "Ημερομηνία Λήξης",
              label: "Λήξη",
              types: {
                specified: "Συγκεκριμένα",
                specifiedDay: "Καθορισμένη Ημέρα",
                today: "Σήμερα",
              },
            },
            fields: {
              closeBy: "Κλείσιμο από",
              comment: "Σχόλια",
              price: "Τιμή",
              stopLoss: "Τιμή ελαχιστοποίησης ζημιάς",
              takeProfit: "Εξασφάλιση κέρδους",
              volume: "Όγκος",
              errors: {
                volume: {
                  min: "Η ελάχιστη ποσότητα είναι {min}",
                  max: "Η μέγιστη ποσότητα είναι {max}",
                  required: "Volume is required",
                  step: "Η ποσότητα μπορεί να ρυθμιστεί με ένα βήμα {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Ιστορικό",
            deals: {
              columns: {
                comment: "Σχόλια",
                commission: "Προμήθεια",
                direction: "Κατεύθυνση",
                fee: "Τέλη",
                order: "Εντολή",
                price: "Τιμή",
                profit: "Κέρδος",
                swap: "Ανταλλαγή",
                symbol: "Σύμβολο",
                ticket: "Εισιτήριο",
                time: "Ώρα",
                type: "Τύπος",
                volume: "Όγκος",
              },
            },
            empty: "Δεν έχετε ακόμη ιστορικό συναλλαγών",
            menu: {
              columns: {
                horizontalScroll: "Οριζόντια Κύλιση",
                resetAll: "Επαναφορά Όλων",
                title: "Στήλες",
              },
              deals: "Συναλλαγές",
              orders: "Εντολές",
              period: {
                all: "Ολο το Ιστορικό",
                last3Months: "Τελευταίοι 3 Μήνες",
                last6months: "Τελευταίοι 6 Μήνες",
                lastMonth: "Τελευταίος Μήνας",
                title: "Περίοδος",
                customPeriod: "Προσαρμοσμένη Περίοδος",
                lastYear: "Τελευταίος Χρόνος",
                lastWeek: "Τελευταία Εβδομάδα",
                today: "Σήμερα",
              },
              positions: "Θέσεις",
              chart: "Διάγραμμα",
              newOrder: "Νέα Εντολή",
            },
            orders: {
              columns: {
                comment: "Σχόλια",
                price: "Τιμή",
                slDescription: "Τιμή ελαχιστοποίησης ζημιάς",
                state: "Κατάσταση",
                symbol: "Σύμβολο",
                ticket: "Εισιτήριο",
                timeDone: "Ώρα",
                timeSetup: "Ώρα",
                tpDescription: "Εξασφάλιση κέρδους",
                type: "Τύπος",
                volume: "Όγκος",
                timeSetupDescription: "Ημ/νία-Ώρα ανοίγματος",
                timeDoneDescription: "Ώρα κλεισίματος",
              },
              total: {
                title: "Σύνολο",
                filled: "Συμπληρώθηκε",
                canceled: "Ακυρώθηκε",
                rejected: "Απορρίφθηκε",
              },
            },
            positions: {
              columns: {
                commission: "Προμήθεια",
                fee: "Τέλη",
                priceClose: "Τιμή",
                priceCloseDescription: "Κλείσιμο Τιμής",
                priceOpen: "Τιμή",
                priceOpenDescription: "Άνοιγμα Τιμής",
                profit: "Κέρδος",
                slDescription: "Τιμή ελαχιστοποίησης ζημιάς",
                swap: "Ανταλλαγή",
                symbol: "Σύμβολο",
                ticket: "Εισιτήριο",
                timeClose: "Ώρα",
                timeCloseDescription: "Ώρα κλεισίματος",
                timeOpen: "Ώρα",
                timeOpenDescription: "Ημ/νία-Ώρα ανοίγματος",
                tpDescription: "Εξασφάλιση κέρδους",
                type: "Τύπος",
                volume: "Όγκος",
                comment: "Σχόλιο",
              },
            },
            columns: { default: "Από Προεπιλογή" },
            total: {
              profit: "Κέρδος",
              credit: "Πίστωση",
              deposit: "Κατάθεση",
              withdrawal: "Ανάληψη",
              balance: "Υπόλοιπο",
              commission: "Προμήθεια",
              fee: "Τέλη",
              swap: "Ανταλλαγή",
              grossProfit: "Μικτό Κέρδος",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Ιστορία Συναλλαγών",
                orders: "Εντολές Συναλλαγών",
                position: "Θέσεις Συναλλαγών",
                sltp: "Επίπεδα SL/TP",
              },
              notification: "Ειδοποίηση Συναλλαγής",
            },
            oneClick: "Συναλλαγές Ενός Κλικ",
            tags: { demo: "Επίδειξη", readonly: "Μόνο για ανάγνωση" },
            oneClickBottom: "Πίνακας με ένα κλικ στο κάτω μέρος",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Αποδέχομαι αυτούς τους Όρους και Προϋποθέσεις",
            btnAccept: "Αποδοχή",
            btnCancel: "Ακύρωση",
            text: 'Πρόκειται να ενεργοποιήσετε τη λειτουργία συναλλαγών με ένα κλικ. Κάνοντας κλικ στο "Αποδέχομαι αυτούς τους Όρους και Προϋποθέσεις" παρακάτω, αναγνωρίζετε ότι έχετε διαβάσει και κατανοήσει τους ακόλουθους όρους και προϋποθέσεις και συμφωνείτε ότι δεσμεύεστε από το παρόν.<br /><br />Μπορείτε να ενεργοποιήσετε ή να απενεργοποιήσετε το ένα κλικ στη λειτουργία συναλλαγών από το μενού του τερματικού ιστού σας.<br /><br />Η λειτουργία Συναλλαγών με ένα κλικ για την υποβολή παραγγελίας είναι μια διαδικασία ενός βήματος. Η παραγγελία σας θα υποβληθεί όταν: &mdash; πατήστε τα κουμπιά τιμής προσφοράς (ΠΩΛΗΣΗ) ή ερώτησης (ΑΓΟΡΑ) στον πίνακα Συναλλαγές με ένα κλικ ενός γραφήματος &mdash; πατήστε τα κουμπιά Πώληση, Κλείσιμο, Αγορά ή παραγγελία στο παράθυρο βάθος αγοράς &mdash; να κλείσετε θέσεις ή να διαγράψετε παραγγελίες στην καρτέλα "Εμπόριο"<br /><br />ΔΕΝ ΘΑ ΥΠΑΡΧΕΙ ΕΠΑΚΟΛΟΥΘΗ ΠΡΟΤΑΣΗ ΕΠΙΒΕΒΑΙΩΣΗΣ ΓΙΑ ΝΑ ΚΑΝΕΤΕ ΚΛΙΚ. ΔΕΝ ΘΑ ΜΠΟΡΕΙΣ ΝΑ ΑΠΟΚΡΑΤΕΙΤΕ Ή ΝΑ ΑΛΛΑΞΕΤΕ ΤΗΝ ΠΑΡΑΓΓΕΛΙΑ ΣΑΣ ΜΟΛΙΣ ΚΑΝΕΤΕ ΚΛΙΚ. ΥΠΟ ΚΑΝΟΝΙΚΕΣ ΣΥΝΘΗΚΕΣ ΑΓΟΡΑΣ ΚΑΙ ΑΠΟΔΟΣΕΙΣ ΤΟΥ ΣΥΣΤΗΜΑΤΟΣ, ΜΙΑ ΕΝΤΟΛΗ ΑΓΟΡΑΣ ΘΑ ΣΥΜΠΛΗΡΩΘΕΙ ΑΜΕΣΩΣ ΜΕΤΑ ΤΗΝ ΥΠΟΒΟΛΗ ΚΑΙ ΘΑ ΣΥΝΕΧΕΤΕ ΣΕ ΔΕΣΜΕΥΤΙΚΗ ΣΥΝΑΛΛΑΓΗ.<br /><br />Συμφωνείτε να αποδεχτείτε όλους τους κινδύνους που σχετίζονται με τη χρήση της λειτουργίας συναλλαγής με ένα κλικ , συμπεριλαμβανομένου, χωρίς περιορισμό, του κινδύνου σφαλμάτων, παραλείψεων ή λαθών που έγιναν κατά την υποβολή αυτής της παραγγελίας.<br /><br />Συμφωνείτε να αποζημιώσετε πλήρως και να διατηρήσετε αβλαβή {companyName} από οποιεσδήποτε και όλες τις απώλειες, τα κόστη και τα έξοδα που ενδέχεται να προκύψουν ως αποτέλεσμα οποιωνδήποτε τέτοιων σφαλμάτων, παραλείψεων ή λαθών από εσάς ή οποιοδήποτε άλλο άτομο που συναλλάσσεται για λογαριασμό σας.',
            title: "Συναλλαγές με ένα κλικ - Αποποίηση ευθύνης",
          },
          quickTrade: {
            hide: "Απόκρυψη του πίνακα συναλλαγών με ένα κλικ",
            show: "Εμφάνιση του πίνακα συναλλαγών με ένα κλικ",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Αντιλαμβάνομαι την παραπάνω δήλωση και θα ήθελα να προχωρήσω σε συναλλαγές επενδυτικών προϊόντων υψηλού κινδύνου",
            btnAccept: "Αποδοχή",
            btnCancel: "Ακύρωση",
            text: "Θα θέλαμε να σας ενημερώσουμε ότι χρησιμοποιώντας περαιτέρω αυτήν την πλατφόρμα συναλλαγών θα έχετε πρόσβαση σε επενδυτικά προϊόντα υψηλού κινδύνου μόχλευσης, που παρέχονται από το χρηματοπιστωτικό ίδρυμα της επιλογής σας. Η επένδυση σε τέτοια προϊόντα μπορεί να μην είναι κατάλληλη για όλους τους επενδυτές, επειδή ενέχει κίνδυνο απώλειας μέρους ή όλου του κατατεθειμένου ποσού.<br /><br />Πριν αποφασίσετε να διαπραγματευτείτε επενδυτικά προϊόντα υψηλού κινδύνου, θα πρέπει να εξετάσετε προσεκτικά τους επενδυτικούς σας στόχους, επίπεδο εμπειρίας και αποδεκτό κίνδυνο. Υπάρχει η πιθανότητα να υποστείτε ζημία μεγαλύτερη από την αρχική σας επένδυση και επομένως δεν θα πρέπει να επενδύσετε χρήματα που δεν έχετε την πολυτέλεια να χάσετε.<br /><br />Σας προσκαλούμε να διευρύνετε τις γνώσεις σας σχετικά με όλους τους παράγοντες κινδύνου που ασχολείστε με την επένδυση σε αυτά τα προϊόντα και ζητήστε συμβουλές από έναν επαγγελματία χρηματοοικονομικό σύμβουλο εάν έχετε οποιεσδήποτε αμφιβολίες.",
            title: "Προειδοποίηση Υψηλού Κινδύνου Επενδύσεων ",
          },
          table: {
            btnOpen: "Συναλλαγή",
            columns: {
              comment: "Σχόλια",
              priceClose: "Τιμή",
              priceCloseDescription: "Τιμή κλεισίματος",
              priceOpen: "Τιμή",
              priceOpenDescription: "Τιμή ανοίγματος",
              profit: "Κέρδος",
              slDescription: "Τιμή ελαχιστοποίησης ζημιάς",
              swap: "Ανταλλαγή",
              symbol: "Σύμβολο",
              ticket: "Εισιτήριο",
              time: "Ώρα",
              tpDescription: "Εξασφάλιση κέρδους",
              type: "Τύπος",
              volume: "Όγκος",
            },
            emptyPlug: {
              btnNewOrder: "Δημιουργία νέας εντολής",
              title: "Δεν έχετε θέσεις",
            },
            menu: {
              chart: "Διάγραμα",
              closePosition: "Κλείσιμο θέσης",
              columns: "Στήλες",
              modifyOrder: "Μεταβολή εντολής",
              modifyPosition: "Μεταβολή Θέσης",
              newOrder: "Νέα Εντολή",
              resetAll: "Επαναφορά όλων",
              deleteOrder: "Διαγραφή Εντολής",
            },
            oneClick: { deleteOrder: "Διαγραφή" },
            sections: {
              collateralPositions: "Εξασφαλιστικές θέσεις",
              orders: "Εντολές",
              positions: "Θέσεις",
            },
            total: {
              assets: "Ενεργητικό",
              balance: "Υπόλοιπο",
              collateral: "Collateral",
              commission: "Προμήθεια",
              credit: "Πίστωση",
              equity: "Καθαρή Αξία",
              liabilities: "Παθητικό",
              margin: "Περιθώριο",
              marginFree: "Ελεύθερο Περιθώριο",
              marginLevel: "Επίπεδο",
            },
          },
          timer: {
            marketWillOpen: "Η αγορά θα είναι ανοιχτή σε {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} ημέρες",
            oneDay: "{numberOfDays} ημέρα",
          },
          tradeIsDisabled: {
            account:
              "Οι συναλλαγές για αυτόν τον λογαριασμό είναι απενεργοποιημένες στον διακομιστή",
            collateral:
              "Η συναλλαγή  δεν είναι διαθέσιμη, επειδή αυτό το σύμβολο είναι εγγύηση",
            disabled: "Οι συναλλαγές δεν επιτρέπονται",
            investor:
              "Η συναλλαγή δεν είναι διαθέσιμη, επειδή είστε συνδεδεμένοι με κωδικό πρόσβασης επενδυτή",
            readOnly:
              "Η συναλλαγή δεν είναι διαθέσιμη, επειδή δεν έχετε αποδεχτεί την προειδοποίηση κινδύνου",
            symbol: "Οι συναλλαγές είναι απενεργοποιημένες για αυτό το σύμβολο",
          },
          hotkeys: {
            historyPanel: "Πίνακας Ιστορίας",
            journalPanel: "Ημερολόγιο",
            marketWatch: "Πεδίο Τιμών",
            quickTrade: "Συναλλαγές Ενός Κλικ",
            tradeForm: "Νέα Εντολή",
            tradePanel: "Πίνακας Εμπορίου",
          },
          marketOpen: {
            time: "Η αγορά είναι κλειστή - θα ανοίξει σε {time}",
            afterSeconds:
              "Η αγορά είναι κλειστή - θα ανοίξει σε {time} δευτερόλεπτα",
          },
          expiredTimer: { seconds: "Λήγει σε {time} δευτερόλεπτα" },
          corporateLink: {
            type: {
              clientAgreement: "Συμφωνία πελάτη",
              riskDisclosure: "Ανακοίνωση κινδύνου",
              fdmDisclaimer: "FDM αποποίηση ευθυνών",
              clientAgreementAndRiskDisclosure:
                "Συμφωνία πελάτη και αποκάλυψη κινδύνου",
              complaintsHandlingProcedure: "Διαδικασία χειρισμού παραπόνων",
              orderExecutionPolicy: "Πολιτική εκτέλεσης εντολών",
              clientCategorisationNotice: "Ειδοποίηση κατηγοριοποίησης πελατών",
              conflictsOfInterestPolicy: "Πολιτική σύγκρουσης συμφερόντων",
              dataProtectionPolicy: "Πολιτική Προστασίας Δεδομένων",
            },
          },
          margin: {
            floating: "κυμαινόμενο",
            mode: {
              marketBuy: "Αγορά στην τρέχουσα τιμή",
              marketSell: "Πώληση στην τρέχουσα τιμή",
            },
            rangeMode: {
              value: "θεωρητική αξία",
              valuePerSymbol: "θεωρητική αξία ανά σύμβολο",
              volume: "όγκος",
              volumePerSymbol: "όγκος ανά σύμβολο",
            },
            showValue: "Εμφάνιση τιμών σε {currency} ανά lot",
            rates: "Περιθώριο:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Απενεργοποιήστε Πλήρη εικόνα",
            enable: "Ενεργοποιήστε Πλήρη εικόνα",
          },
          journal: {
            btnOpen: "Ημερολόγιο",
            columns: { message: "Μήνυμα", source: "Πηγή", time: "Ώρα" },
            menu: {
              clear: "Καθαρισμός",
              debugMode: "Λειτουργία εντοπισμού σφαλμάτων",
              exportFile: "Εξαγωγή σε Αρχείο",
            },
          },
          menu: {
            about: "Σχετικά με το πρόγραμμα",
            contact: "Επικοινωνήστε μαζί μας",
            brokerInformation: "Στοιχεία της εταιρείας",
            chartSettings: {
              controls: "Στοιχεία ελέγχου γραφήματος",
              grid: "Πλέγμα",
              ohlc: "Εμφάνιση OHLC",
              title: "Ρυθμίσεις γραφήματος",
              askPrice: "Ζήτηση τιμή",
              crosshair: "Δρομέας σταυρού",
            },
            connect: "Σύνδεση με λογαριασμό",
            language: {
              title: "Γλώσσα",
              search: "Αναζήτηση",
              nothingFound: "Η γλώσσα δεν βρέθηκε",
            },
            openDemo: "Ανοίξτε λογαριασμό επίδειξης",
            openReal: "Ανοίξτε πραγματικός λογαριασμό",
            settings: "Ρυθμίσεις",
            shortcuts: "Συντομεύσεις",
            theme: {
              blackWhite: "Μαύρο & Άσπρο",
              blueRed: "Μπλε & Κόκκινο",
              dark: "Σκοτεινό Θέμα",
              editor: "Επεξεργαστής Θεμάτων",
              greenRed: "Πράσινο & Κόκκινο",
              light: "Ελαφρύ Θέμα",
              neutral: "Ουδέτερο",
              templates: "Πρότυπα Χρώματος",
            },
            title: "Μενού",
            tradingAccount: "Εμπορικοί Λογαριασμοί",
            terms: "Οροι & Προϋποθέσεις",
            desktopPlatforms: "Πλατφόρμες επιφάνειας εργασίας",
            qrCode: {
              install: "Σάρωση για εγκατάσταση από το {store}",
              downloadApk: "Σάρωση για λήψη αρχείου Android APK",
            },
            economicCalendar: "Οικονομικό Ημερολόγιο",
          },
          screen: { back: "Πίσω" },
          mobile: { bottomNav: { quotes: "Τιμές" } },
          hotkeys: {
            sections: { navigation: "Πλοήγηση", view: "Εμφάνιση" },
            escape: "Ακύρωση",
            indicators: "Δείκτες",
            depthOfMarket: "Βάθος αγοράς",
            objectTreePanel: "Δέντρο αντικειμένου",
            scrollRight: "Επόμενο Κερί",
            scrollToStart: "Κάντε κύλιση στο γράφημα για να ξεκινήσετε",
            scrollLeft: "Προηγούμενο Κερί",
            scrollToEnd: "Κύλιση γραφήματος στο τέλος",
            resetChartView: "Επαναφορά γραφήματος",
            zoomIn: "Μεγέθυνση",
            zoomOut: "Σμίκρυνση",
            fullScreen: "Πλήρης Οθόνη",
            screenshot: "Αποθήκευση γραφήματος ως εικόνα",
            title: "Συντομεύσεις",
          },
          timezone: {
            title: "Ζώνη ώρας",
            city: {
              cairo: "Κάιρο",
              casablanca: "Καζαμπλάνκα",
              johannesburg: "Γιοχάνεσμπουργκ",
              lagos: "Λάγος",
              nairobi: "Ναϊρόμπι",
              tunis: "Τυνίδος",
              anchorage: "Αγκυροβόλιο",
              bogota: "Μπογκοτά",
              buenosAires: "Μπουένος Άιρες",
              caracas: "Καράκας",
              chicago: "Σικάγο",
              denver: "Ντένβερ",
              elSalvador: "Ελ Σαλβαδόρ",
              juneau: "Τζουνό",
              lima: "Είδος φασιολού",
              losAngeles: "Λος Άντζελες",
              mexicoCity: "Πόλη του Μεξικό",
              newYork: "Νέα Υόρκη",
              phoenix: "Φοίνιξ",
              santiago: "Σαντιάγο",
              saoPaulo: "Σάο Πάολο",
              toronto: "Τορόντο",
              vancouver: "Βανκούβερ",
              almaty: "Αλμάτι",
              ashgabat: "Ασγκαμπάτ",
              bahrain: "Μπαχρέιν",
              bangkok: "Μπανγκόκ",
              kolkata: "Καλκούτα",
              colombo: "Κολόμπο",
              dhaka: "Ντάκα",
              dubai: "Ντουμπάι",
              hongKong: "Χονγκ Κονγκ",
              jakarta: "Τζακάρτα",
              jerusalem: "Ιερουσαλήμ",
              karachi: "Καράτσι",
              kathmandu: "Κατμαντού",
              kuwait: "Κουβέιτ",
              manila: "Μανίλα",
              muscat: "Μοσχοστάφυλο",
              nicosia: "Λευκωσία",
              qatar: "Κατάρ",
              rangoon: "Ρανγκούν",
              riyadh: "Ριάντ",
              saigon: "Σαϊγκόν",
              seoul: "Σεούλ",
              shanghai: "Σαγκάη",
              singapore: "Σιγκαπούρη",
              taipei: "Ταϊπέι",
              tehran: "Τεχεράνη",
              tokyo: "Τόκιο",
              reykjavik: "Ρέικιαβικ",
              adelaide: "Αδελαΐδα",
              brisbane: "Μπρίσμπεϊν",
              perth: "Περθ",
              sydney: "Σίδνεϊ",
              amsterdam: "Άμστερνταμ",
              athens: "Αθήνα",
              belgrade: "Βελιγράδιο",
              berlin: "Βερολίνο",
              bratislava: "Μπρατισλάβα",
              brussels: "Βρυξέλλες",
              bucharest: "Βουκουρέστι",
              budapest: "Βουδαπέστη",
              copenhagen: "Κοπεγχάγη",
              dublin: "Δουβλίνο",
              helsinki: "Χέλσινκι",
              istanbul: "Κωνσταντινούπολη",
              lisbon: "Λισαβόνα",
              london: "Λονδίνο",
              luxembourg: "Λουξεμβούργο",
              madrid: "Μαδρίτη",
              malta: "Μάλτα",
              moscow: "Μόσχα",
              oslo: "Άσλο",
              paris: "Παρίσι",
              prague: "Πράγα",
              riga: "Ρίγα",
              rome: "Ρώμη",
              stockholm: "Στοκχόλμη",
              tallinn: "Ταλίν",
              vienna: "Βιέννη",
              vilnius: "Βίλνιους",
              warsaw: "Βαρσοβία",
              zurich: "Ζυρίχη",
              auckland: "Ώκλαντ",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Χονολούλου",
              norfolk: "Νόρφολκ",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { t as a, o as b, i as c, e };
