const e = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        chart: {
          calendar: {
            btnOpen: {
              hide: "Hide Economic Calendar Events from Chart",
              show: "Show Economic Calendar Events on Chart",
            },
          },
          controls: {
            reset: "Reset Chart",
            scrollEnd: "Scroll to the End",
            scrollLeft: "Scroll to the Left",
            scrollRight: "Scroll to the Right",
            zoomIn: "Približaj",
            zoomOut: "Oddalji",
          },
          crosshair: "Crosshair",
          delay: "{delay} min delay",
          indicators: {
            btnAddIndicator: "Dodaj indikator",
            btnOpenPopup: "Add Indicator",
            close: "Zapri",
            form: {
              applyTo: "Uveljavi za",
              background: {
                title: "Ozadje",
                down: "Down kumo background",
                up: "Up kumo background",
              },
              deviation: "Deviacija",
              enterDistance: "Obdobje",
              enterShift: "Premik",
              fastEma: "Hiter EMA",
              slowEma: "Počasen EMA",
              line: {
                base: "Base line",
                down: "Lower line",
                minusDI: "-DI line",
                null: "Null line",
                plusDI: "+DI line",
                style: "Line style",
                cci: "CCI Line",
                up: "Upper line",
                fi: "FI Line",
              },
              maximum: "Maksimum",
              method: {
                exponential: "Exponential",
                linearWeighted: "Linear Weighted",
                simple: "Preprosto",
                smoothed: "Smoothed",
                title: "Metoda",
              },
              opacity: "Opacity",
              period: {
                jaws: "Obdobje čeljusti",
                lips: "Obdobje ustnic",
                teeth: "Obdobje zob",
                title: "Obdobje",
                dPercent: "Obdobje %D",
                kPercent: "Obdobje %K",
              },
              selectApplyTo: "Izbira",
              selectVolumesType: "Select volume type",
              shift: "Premik",
              showTimeframes: "Pokaži vse časovne okvire",
              slowing: "Upočasnjevanje",
              step: "Korak",
              style: {
                down: "Down style",
                jaws: "Jaws style",
                lips: "Lips style",
                main: "Main style",
                signal: "Signal style",
                teeth: "Teeth style",
                title: "Stil",
                up: "Up style",
                rvi: "Stil RVI",
              },
              volume: { down: "Volume Down", up: "Volume Up" },
              volumes: "Obsegi",
              mfiUp: "MFI Up",
              mfiDown: "MFI Down",
              price: {
                title: "Cena",
                select: "Select price",
                lowHigh: "Low/High",
                closeClose: "Close/Close",
              },
            },
            search: {
              empty: "No items found",
              title: "Išči",
              tryAnother: "Please try another query",
            },
            tabs: {
              all: "Vse",
              billWilliams: "Bill Williams",
              oscillators: "Oscilatorji",
              trend: "Trend",
              volumes: "Obsegi",
            },
            title: "Select indicator",
            up: "Gor",
            down: "Dol",
            chartControls: {
              show: "Pokaži",
              hide: "Skrij",
              settings: "Nastavitve",
              remove: "Odstrani",
            },
          },
          loading: "Loading",
          marketWatch: {
            btnOpen: { hide: "Hide Market Watch", show: "Show Market Watch" },
            columns: {
              closePrice: "Zaključna cena",
              dailyChange: "Dnevna sprememba",
              openPrice: "Otvoritvena cena",
              spread: "Razpon",
              symbol: "Simbol",
              time: "Čas",
              high: "Visoko",
              low: "Nizko",
              last: "Zadnje",
              lastHigh: "Najvišja zadnja cena",
              lastLow: "Najnižja zadnja cena",
              highLow: "Visoko/Nizko",
              bidLow: "Najnižja nakupna cena",
              bidHigh: "Najvišja nakupna cena",
              askHigh: "Najvišja prodajna cena",
              askLow: "Najnižja prodajna cena",
              bid: "Ponudba",
              ask: "Povpraševanje",
              title: "Stolpci",
            },
            menu: {
              chart: "Grafikon",
              columns: "Stolpci",
              dom: "Globina trga",
              hide: "Skrij",
              newOrder: "Novo naročilo",
              specification: "Specifikacija",
            },
            search: "Išči",
            searchSymbol: "Search symbol",
            nothingFound: "No symbols found",
          },
          objects: {
            form: {
              statistics: "Statistics",
              arrows: "Puščice",
              showAlways: "Show always",
              angle: "Kot",
              distance: "Distance",
              bar: "Stolpec",
              price: "Cena",
              prices: "Cene",
              showPrice: "Show price",
              showText: "Show text",
              showDate: "Show date",
              showTime: "Show time",
              showAllTimeframes: "Pokaži vse časovne okvire",
              showPearsonR: "Show Pearson's R",
              showLabels: "Show labels",
              yourText: "Vaše besedilo",
              props: "Lastnosti",
              style: "Stil",
              rays: "Rays",
              background: "Ozadje",
              extends: "Extension",
              extended: "Podaljšano",
              pipsPerBar: "Pipov na stolpec",
              gannAngle: "Gannov kot",
              deviations: "Deviacije",
              labels: "Labels",
              reverse: "Reverse",
              btn: { update: "Posodobi", cancel: "Prekliči" },
              tabs: {
                style: "Stil",
                coordinates: "Coordinates",
                visualization: "Vizualizacija",
              },
              range: {
                price: "Price range",
                bars: "Bars range",
                date: "Date range",
              },
              align: {
                horizontal: "Horizontal alignment",
                vertical: "Vertical alignment",
                left: "Levo",
                right: "Desno",
                center: "Sredina",
                top: "Najboljši",
                middle: "Middle",
                bottom: "Dno",
              },
              line: {
                style: "Line style",
                base: "Base line",
                up: "Upper line",
                down: "Lower line",
                middle: "Middle line",
              },
            },
            visible: { hide: "Hide All Objects", show: "Show All Objects" },
            lock: "Lock All Objects",
            unlock: "Unlock All Objects",
            andrewsPitchforkChannel: "Andrewsove Vile",
            equidistantChannel: "Ekvidistančni kanal",
            regressionChannel: "Kanal Regresije",
            stdDevChannel: "Standardni Kanal Deviacije",
            fibonacciRetracement: "Fibonaccijev popravek",
            gannFan: "Gannova Pahljača",
            gannGrid: "Gannova Mreža",
            gannLine: "Gannova Črta",
            arrowLine: "Črta s puščico",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalRay: "Horizontal Ray",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Žarek",
            trendAngle: "Trend po kotu",
            trendline: "Linija trenda",
            verticalLine: "Navpična linija",
            disjointAngle: "Disjoint Channel",
            flatTopBottom: "Flat Top/Bottom",
            rectangle: "Pravokotnik",
            circle: "Circle",
            triangle: "Trikotnik",
            ellipse: "Elipsa",
            text: "Tekst",
            rulerLine: "Ruler Line",
          },
          period: {
            full: {
              D1: "Dnevno",
              H1: "1 ura",
              H4: "4 ure",
              M1: "1 minuta",
              M15: "15 minut",
              M30: "30 minut",
              M5: "5 minut",
              MN: "Mesečno",
              Unknown: "Unknown",
              W1: "Tedensko",
            },
            short: {
              D1: "D1",
              H1: "H1",
              H4: "H4",
              M1: "M1",
              M15: "M15",
              M30: "M30",
              M5: "M5",
              MN: "MN",
              Unknown: "Unknown",
              W1: "W1",
            },
          },
          screenshot: "Save Chart as Image",
          symbolSpecs: {
            GTCmode: "Način GTC",
            calculation: "Kalkulacija",
            chartMode: "Izdelava grafa",
            contractSize: "Velikost pogodbe",
            days: {
              friday: "petek",
              monday: "ponedeljek",
              saturday: "sobota",
              sunday: "nedelja",
              thursday: "četrtek",
              tuesday: "torek",
              wednesday: "sreda",
            },
            digits: "Cifre",
            empty: "No symbol selected",
            execution: "Izvršitev",
            expiration: "Iztek",
            filling: "Polnjenje",
            initial: "Začetno",
            maintenance: "Vzdrževanje",
            marginCurrency: "Valuta kritja",
            marginRate: "Stopnja kritja",
            maxVolume: "Maksimalni obseg",
            minVolume: "Minimalni obseg",
            orders: "Naročila",
            profitCurrency: "Dobičkonosna valuta",
            schedule: { quotes: "Kotacije", trade: "Trgovanje" },
            sector: "Sektor",
            spread: "Razpon",
            stopsLevel: "Ravni stop",
            swapLong: "Zamenjava na dolgo",
            swapShort: "Zamenjava na kratko",
            swapType: "Vrsta zamenjave",
            title: "{symbol} contract specification",
            tradeMode: "Trgovanje",
            volumeStep: "Korak pri obsegu",
            volumeLimit: "Omejitev obsega",
            tickSize: "Velikost koraka kotacije",
            tickValue: "Vrednost koraka kotacije",
            marginInitial: "Začetno kritje",
            marginHedged: "Zavarovano kritje",
            commission: {
              daily: {
                volume: "Dnevni volumen v serijah",
                turnoverVolume: "Dnevni promet v lotih",
                turnoverMoney: "Dnevni promet v denarju",
                value: "Dnevna vrednost poslov",
                profit: "Dnevni dobiček",
              },
              monthly: {
                volume: "Mesečni obseg v lotih",
                turnoverVolume: "Mesečni promet v lotih",
                turnoverMoney: "Mesečni promet v denarju",
                value: "Mesečna vrednost poslov",
                profit: "Mesečni dobiček",
              },
              instant: {
                volume: "Takoj po obsegu posla",
                value: "Takoj po vrednosti posla",
                profit: "Takojšnji dobiček po dogovoru",
              },
              entry: {
                in: "dohodni posli",
                out: "odhodni posli",
                all: "dohodni/odhodni posli",
              },
              tier: {
                mode: {
                  pips: "točke",
                  percent: "% v {currency}",
                  percentProfit: "% od dobička {currency}",
                },
                type: { perDeal: "na posel", perLot: "na lot" },
              },
              header: "Provizije",
            },
          },
          tree: {
            close: "Zapri",
            empty: "You don't have any objects on the chart",
            lock: "Lock",
            remove: "Odstrani",
            settings: "Nastavitve",
            title: "Manage Drawings",
            unlock: "Unlock",
          },
          types: {
            area: "Area",
            line: "Line",
            bars: "Stolpci",
            candlestick: "Candlestick",
          },
          volumeTypes: {
            tickVolumes: "Obsegi tikov",
            volumes: "Obsegi",
            withoutVolumes: "Without Volumes",
            realVolumes: "Realni obsegi",
          },
          zoom: { in: "Približaj", out: "Oddalji" },
          hotkeys: {
            arrowLine: "Črta s puščico",
            chartTypeArea: "Area Chart",
            chartTypeLine: "Črtni grafikon",
            chartTypeBar: "Palični grafikon",
            chartTypeCandle: "Candle Chart",
            crossLine: "Cross Line",
            extendedLine: "Extended Line",
            horizontalLine: "Vodoravna linija",
            infoLine: "Info Line",
            rayLine: "Žarek",
            realVolumes: "Real Volumes",
            tickVolumes: "Obsegi tikov",
            trendline: "Linija trenda",
            verticalLine: "Navpična linija",
            sections: {
              chartType: "Chart Type",
              drawing: "Drawing",
              volume: "Obseg",
            },
            crosshairRuler: "Crosshair ruler",
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  o = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        login: {
          accountInfo: {
            btnStart: "Get started with your account",
            newAccountOpened: "Odprt je nov račun",
          },
          brokerInformation: {
            company: "Podjetje",
            email: "Elektronska pošta",
            phone: "Telefon",
            registrationAddress: "Registration Address",
            title: "Company Information",
            website: "Website",
          },
          changePassword: {
            btnChange: "Spremeni geslo",
            confirmPassword: "Confirm Password",
            newPassword: "New Password",
            title: "Spremeni geslo",
          },
          connect: {
            btnConnect: "Connect to account",
            contactBroker: "Contact company",
            forgotPassword: "Forgot Password?",
            loginPlaceholder: "Enter Login",
            passwordPlaceholder: "Enter Password",
            savePassword: "Shrani geslo",
            title: "Connect to account",
          },
          copyToClipboard: {
            copy: "Copy to clipboard",
            unsupported: "Copying is not supported",
          },
          demo: {
            accountOpeningWarning:
              "By opening an account, you agree to the account opening terms and to the data protection policy of {brokerName}",
            btnOpenDemo: "Open Demo account",
            title: "Open Demo account",
            tradeWithRealMoney:
              "To trade with real money, you need to enter into a separate agreement with a financial services company.",
          },
          disclaimer: {
            btnAccept: "Sprejmi",
            headerTitle: "Welcome to MetaTrader 5",
            text: 'MetaQuotes Ltd is a software development company and does not provide any financial, investment, brokerage, trading or data feed services, nor is it involved in any commission-based payments concerning any trading operations.<br /><br />By pressing the ACCEPT button I agree with the <a href="https://www.metaquotes.net/licenses/webterminal" target="_blank">terms and conditions of the EULA</a>, the <a href="https://www.metaquotes.net/en/legal/policies" target="_blank">Privacy Policy</a> and the Disclaimer.<br /><br /> None of the information available in the application is intended as an investment advice. Before using this application for trading, you should seek the advice of a qualified and registered securities professional and undertake your own due diligence.',
            title: "Izjava o omejitvi odgovornosti",
          },
          errors: {
            error: "Napaka",
            invalidCode: "Invalid code",
            invalidEmail: "Invalid email",
            invalidPhone: "Invalid phone",
            unknownError: "Unknown error",
          },
          form: {
            accountType: "Vrsta računa",
            address: "Naslov",
            addressPlaceholder: "Enter your address",
            annualDeposit: "Letni depozit",
            annualIncome: "Letni prihodek",
            broker: "Podjetje",
            btn: {
              back: "Nazaj",
              cancel: "Prekliči",
              next: "Naslednji",
              openAccount: "Open Account",
              remove: "Odstrani",
              signOut: "Sign out",
            },
            city: "Mesto",
            cityPlaceholder: "Enter your city",
            country: "Država",
            dateBirth: "Datum rojstva",
            deposit: "Depozit",
            education: "Education",
            email: {
              address: "Elektronska pošta",
              code: "Code from email",
              placeholder: "Enter email",
              title: "Elektronska pošta",
            },
            employement: "Employement",
            forex: "Forex",
            futures: "Standardizirane terminske pogodbe",
            gender: { female: "Ženski", male: "Moški", title: "Spol" },
            identity: "Identiteta",
            imageOrPdfFile: "Image or PDF file",
            investor: "Investitor",
            language: "Jazik",
            leverage: "Vzvod",
            login: "Prijava",
            min5chars: "Min 5 chars",
            name: {
              middle: "Middle Name",
              surname: "Surname",
              title: "Ime",
              yourName: "Your Name",
            },
            nationality: "Državljanstvo",
            netWorth: "Neto vrednost",
            optional: "Optional",
            password: "Geslo",
            passwordReadOnly: "Read only password",
            phone: {
              mobile: "Mobile phone",
              number: "Phone number",
              sms: "Code from SMS",
            },
            pleaseSelect: "Please Select",
            policyCheckbox:
              "Soglašam z določili in pogoji za odprtje računa in pravilnikom o varstvu podatkov",
            server: "Strežnik",
            side: { back: "Back Side", front: "Front Side" },
            sourceWealth: "Vir premoženja",
            state: "Zvezna država",
            status: "Stanje",
            stocks: "Delnice",
            taxID: "Davčna številka",
            type: "Vrsta",
            useHedge: "Pri trgovanju uporabi hedge",
            verificationCodes: {
              email: "We have sent a verification code to your email",
              phone: "We have sent a verification code to your phone",
              phoneEmail:
                "We have sent verification codes to your phone and email",
            },
            zipCode: "Zip Code",
          },
          mainForm: {
            title: "Trading accounts",
            titleWithName: "Trading accounts: {brokerName}",
          },
          otp: {
            disable2FA: "Onemogoči 2FA/TOTP",
            disable2FAAccount: "Disable 2FA/TOTP for account {login}",
            disableEnterCode:
              "To disable 2FA/TOTP, please enter your account code generated by the Authenticator.",
            downloadApp:
              "Please download the Google Authenticator / Microsoft Authenticator / Authy App to your mobile device and scan the QR code:",
            enable2FA: "Omogoči 2FA/TOTP",
            enable2FAAccount: "Enable 2FA/TOTP for account {login}",
            enterCode:
              "Če želite preveriti delovanje Authenticatorja, vnesite kodo računa, ki jo je ustvarila aplikacija.",
            oneTimePassword: "One-time password:",
            placeholder: "Enter account OTP",
            required:
              "Za dodatno varnost računa je potrebna avtentikacija 2FA.",
            secretCode: "Secret Code:",
          },
          real: {
            adressDocument: {
              bankStatement: "Bančni izpisek",
              utilityBill: "Račun za komunalne storitve",
            },
            conditionsForUploadingFiles: {
              documents:
                "Some types of documents require two photos: front and back side",
              proofAddress:
                "Bills for mobile services are not accepted as a proof of address",
              utilityBill:
                "Utility bill must containt your name and address and be no older than 3 months",
            },
            documentType: {
              driverLicense: "Vozniško dovoljenje",
              idCard: "Osebna izkaznica",
              passport: "Potni list",
              residencePermit: "Dovoljenje za bivanje",
            },
            educationLevel: {
              bachelor: "Visoka šola ali podobno",
              highScholl: "Srednja šola",
              master: "Magisterij ali podobno",
              none: "Brez",
              other: "Drugo",
              phd: "Doktorat ali podobno",
            },
            employment: {
              employed: "Zaposlen",
              other: "Drugo",
              retired: "Upokojen",
              selfEmployed: "Lastnik podjetja ali samozaposlen",
              student: "Študent",
              unemployed: "Nezaposlen",
            },
            experience: "Real trading experience:",
            experienceLevel: {
              above3: "> 3 leta",
              form1to3: "1 do 3 leta",
              less1: "< 1 leto",
            },
            industry: {
              agriculture: "Kmetijstvo, hrana in naravni viri",
              communication:
                "Umetnost, avdio/video tehnologija in komunikacije",
              construction: "Arhitektura in gradbeništvo",
              education: "Izobraževanje in usposabljanje",
              engineering: "Inženiring in matematika",
              government: "Državna in javna uprava",
              healthcare: "Skrb za zdravje",
              it: "Informacijska tehnologija",
              management: "Poslovanje in administracija",
              manufacturing: "Proizvodnja",
              marketing: "Marketing in prodaja",
              none: "Brez",
              other: "Drugo",
              science: "Znanost in tehnologija",
              security: "Pravo, javna varnost, kaznovanje in varnost",
              tourism: "Gostinstvo in turizem",
              transport: "Transport, distribucija in logistika",
            },
            policy:
              "Personal details are used for opening a trade account and are not passed to any third parties. The information is handled securely and confidentially.",
            takePhoto:
              "Please, take photos of your documents and upload them here without any editing",
            title: "Open Real account",
            wealthSource: {
              employment: "Zaposlitev ali podjetništvo",
              inheritance: "Darila ali dediščina",
              other: "Drugo",
              savings: "Prihranki ali investicije",
            },
          },
          saveAccountData:
            "Please keep your login and password in a safe place",
          licenseAgreement: "End-User License Agreement",
          tab: { accounts: "Accounts", loginRegister: "Login / Register" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  a = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        trade: {
          DOM: {
            close: "Zapri",
            empty: "We don’t have volume data for this symbol",
            extendedBook: {
              hide: "Hide Extended Book",
              show: "Show Extended Book",
            },
            menu: {
              amount: "Znesek namesto lotov",
              extended: "Podaljšano",
              spread: "Razpon",
            },
            spread: { hide: "Hide Spread", show: "Show Spread" },
            stopLoss: "Stop Loss",
            takeProfit: "Take profit",
            title: "Globina trga",
          },
          errors: {
            accepted: "Sprejeto",
            allowedOnlyLongPositions: "Dovoljene so samo dolge pozicije",
            allowedOnlyPositionsClosing: "Dovoljeno je samo zapiranje pozicij",
            allowedOnlyShortPositions: "Dovoljene so samo kratke pozicije",
            automatedTradingDisabledClient:
              "Samodejno trgovanje onemogočeno na strani terminala za stranke",
            automatedTradingDisabledServer:
              "Samodejno trgovanje onemogočeno na strani strežnika",
            canceled: "Preklicano",
            common: "Običajna napaka",
            demoAllocationDisabled: "Demo account allocation is disabled",
            done: "Končano",
            donePartially: "Delno opravljeno",
            frequentRequests: "Prepogoste zahteve",
            invalidExpiration: "Neveljaven potek",
            invalidOrderType: "Neveljavna vrsta naročila",
            invalidParameters: "Neveljavni parametri",
            invalidPrices: "Neveljavne cene",
            invalidSLTP: "Neveljaven S/L ali T/P",
            invalidVolume: "Neveljaven obseg",
            manyTradeRequests: "Preveč trgovalnih zahtev",
            marketClosed: "Trg je zaprt",
            modificationFailed:
              "Modifikacija ni uspela, ker je naročilo ali pozicija blizu trga",
            networkProblem: "Težave z omrežjem",
            noConnection: "Ni povezave",
            notEnoughMoney: "Nimate dovolj denarja",
            offQuotes: "Brez ponudb",
            ok: "V redu",
            onTheWay: "Na poti",
            orderChanged: "Naročilo je že bilo spremenjeno",
            orderClosePositionExists:
              "Naročilo za zapiranje te pozicije že obstaja",
            ordersLimitReached: "Dosežena meja naročil",
            permissions: "Nimate dovolj dovoljenj",
            placed: "Naročeno",
            positionCloseProhibitedByFIFO:
              "Zaprtje pozicije prepovedano s pravilom FIFO",
            positionClosed: "Pozicija je že zaprta",
            positionsLimitReached: "Dosežena je omejitev pozicije",
            priceChanged: "Cena se je spremenila",
            prices: "Cene",
            processed: "Obdelano",
            rejected: "Zavrnjeno",
            requestRejectedOrderWillCanceled:
              "Zahteva zavrnjena, naročilo preklicano",
            requoted: "Ponovna kotacija",
            serverProblem: "Tehnične težave serverja",
            timeout: "Iztek časa",
            tradeDisabled: "Trgovanje je onemogočeno",
            unsupportedFillingMode: "Nepodprti način izvrševanja",
            volumeLimitReached: "Dosežena meja obsega",
          },
          form: {
            acceptNewQuotes: "Ali sprejmete te nove kotacije?",
            btnOpen: {
              hide: "Hide Trade Form",
              show: "Show Trade Form",
              title: "Novo naročilo",
            },
            buttons: {
              accept: "Sprejmi",
              delete: "Izbriši",
              modify: "Spremeni",
              ok: "V redu",
              placeOrder: "Place order",
              reject: "Zavrni",
              request: "Na zahtevo",
              requestPrice: "Request Price",
            },
            close: "Zapri",
            execution: {
              fillOrKill: "Izvrši ali prekliči",
              immediateOrCancel: "Takoj ali prekliči",
              bookOrCancel: "Naročite ali Prekličite",
              label: "Politika izvrševanja",
              return: "Nazaj",
            },
            executionMode: {
              exchange: "Borzna izvršitev",
              instant: "Takojšnja izvršitev",
              market: "Tržna izvršitev",
              request: "Zahtevaj izvršitev",
            },
            expiration: {
              date: "Expiration Date",
              label: "Iztek",
              types: {
                specified: "Določeno",
                specifiedDay: "Specified Day",
                today: "Danes",
              },
            },
            fields: {
              closeBy: "Zapri pri",
              comment: "Komentar",
              price: "Cena",
              stopLoss: "Stop Loss",
              takeProfit: "Take profit",
              volume: "Obseg",
              errors: {
                volume: {
                  min: "Minimum volume is {min}",
                  max: "Maximum volume is {max}",
                  required: "Volume is required",
                  step: "Volume can be set with a step of {step}",
                },
              },
            },
          },
          history: {
            btnOpen: "Zgodovina",
            deals: {
              columns: {
                comment: "Komentar",
                commission: "Provizija",
                direction: "Smer",
                fee: "Provizija",
                order: "Naročilo",
                price: "Cena",
                profit: "Dobiček",
                swap: "Zamenjava",
                symbol: "Simbol",
                ticket: "Zaključnica",
                time: "Čas",
                type: "Vrsta",
                volume: "Obseg",
              },
            },
            empty: "You don’t have trading history yet",
            menu: {
              columns: {
                horizontalScroll: "Horizontal Scroll",
                resetAll: "Reset all",
                title: "Stolpci",
              },
              deals: "Posli",
              orders: "Naročila",
              period: {
                all: "Celotna zgodovina",
                last3Months: "Zadnji 3 meseci",
                last6months: "Zadnji 6 mesecev",
                lastMonth: "Zadnji mesec",
                title: "Obdobje",
                customPeriod: "Obdobje po meri",
                lastYear: "Zadnje leto",
                lastWeek: "Zadnji teden",
                today: "Danes",
              },
              positions: "Pozicije",
              chart: "Grafikon",
              newOrder: "Novo naročilo",
            },
            orders: {
              columns: {
                comment: "Komentar",
                price: "Cena",
                slDescription: "Stop Loss",
                state: "Zvezna država",
                symbol: "Simbol",
                ticket: "Zaključnica",
                timeDone: "Čas",
                timeSetup: "Čas",
                tpDescription: "Take profit",
                type: "Vrsta",
                volume: "Obseg",
                timeSetupDescription: "Odprti čas",
                timeDoneDescription: "Close Time",
              },
              total: {
                title: "Skupaj",
                filled: "Izvršeno",
                canceled: "Preklicano",
                rejected: "Zavrnjeno",
              },
            },
            positions: {
              columns: {
                commission: "Provizija",
                fee: "Provizija",
                priceClose: "Cena",
                priceCloseDescription: "Zaključna cena",
                priceOpen: "Cena",
                priceOpenDescription: "Odprta cena",
                profit: "Dobiček",
                slDescription: "Stop Loss",
                swap: "Zamenjava",
                symbol: "Simbol",
                ticket: "Zaključnica",
                timeClose: "Čas",
                timeCloseDescription: "Close Time",
                timeOpen: "Čas",
                timeOpenDescription: "Odprti čas",
                tpDescription: "Take profit",
                type: "Vrsta",
                volume: "Obseg",
                comment: "Komentar",
              },
            },
            columns: { default: "By Default" },
            total: {
              profit: "Dobiček",
              credit: "Kredit",
              deposit: "Depozit",
              withdrawal: "Dvtig",
              balance: "Stanje",
              commission: "Provizija",
              fee: "Provizija",
              swap: "Menjava",
              grossProfit: "Bruto dobiček",
            },
          },
          menu: {
            chartSettings: {
              marks: {
                history: "Zgodovina trgovanja",
                orders: "Trade Orders",
                position: "Trade Positions",
                sltp: "SL/TP Levels",
              },
              notification: "Trade Notification",
            },
            oneClick: "Trgovanje z enim klikom",
            tags: { demo: "Demo", readonly: "Readonly" },
            oneClickBottom: "One Click Panel at the Bottom",
          },
          oneClickDisclaimer: {
            acceptCheckbox: "Sprejemam te pogoje poslovanja",
            btnAccept: "Sprejmi",
            btnCancel: "Prekliči",
            text: 'You are about to activate One Click Trading mode. By clicking "I Accept these Terms and Conditions" below, you acknowledge that you have read and understood the following terms and conditions, and you agree to be bound hereby.<br /><br />You can activate or deactivate One Click Trading mode from the menu of your web terminal.<br /><br />The One Click Trading mode for order submission is a one-step process. Your order will be submitted when you: &mdash; tap either bid (SELL) or ask (BUY) price buttons on the One Click Trading panel of a chart &mdash; tap Sell, Close, Buy or order placing buttons in the Depth of Market window &mdash; close positions or delete orders in the Trade tab<br /><br />THERE WILL BE NO SUBSEQUENT CONFIRMATION PROMPT FOR YOU TO CLICK. YOU WILL NOT BE ABLE TO WITHDRAW OR CHANGE YOUR ORDER ONCE YOU CLICK. UNDER NORMAL MARKET CONDITIONS AND SYSTEM PERFORMANCE, A MARKET ORDER WILL BE PROMPTLY FILLED AFTER SUBMISSION AND YOU WILL ENTER INTO A BINDING TRANSACTION.<br /><br />You agree to accept all risks associated with the use of the One Click Trading mode, including, without limitation, the risk of errors, omissions or mistakes made in submitting such order.<br /><br />You agree to fully indemnify and hold harmless {companyName} from any and all losses, costs and expenses that may incur as a result of any such errors, omissions or mistakes by you, or any other person trading on your behalf.',
            title: "One Click Trading - Disclaimer",
          },
          quickTrade: {
            hide: "Hide One Click Trading Panel",
            show: "Show One Click Trading Panel",
          },
          riskDisclaimer: {
            acceptCheckbox:
              "Zavedam se zgornje izjave in bi rad trgoval s produkti visokega investicijskega tveganja",
            btnAccept: "Sprejmi",
            btnCancel: "Prekliči",
            text: "We wish to inform you that by using this trading platform further you will have access to leveraged high risk investment products, provided by the financial institution of your choice. Investing in such products might not be suitable for all investors, because it carries a risk of losing a part or all deposited amount.<br /><br />Before deciding to trade high risk investment products you should carefully consider your investment objectives, level of experience and acceptable risk. The possibility exists that you could sustain a loss higher than your initial investment and therefore you should not invest money that you cannot afford to lose.<br /><br />We invite you to widen your knowledge about all the risk factors that are concerned with investing in these products, and seek advice from a professional financial advisor if you have any doubts.",
            title: "Opozorilo o investiciji z visokim rizikom",
          },
          table: {
            btnOpen: "Trgovanje",
            columns: {
              comment: "Komentar",
              priceClose: "Cena",
              priceCloseDescription: "Zaključna cena",
              priceOpen: "Cena",
              priceOpenDescription: "Otvoritvena cena",
              profit: "Dobiček",
              slDescription: "Stop Loss",
              swap: "Zamenjava",
              symbol: "Simbol",
              ticket: "Zaključnica",
              time: "Čas",
              tpDescription: "Take profit",
              type: "Vrsta",
              volume: "Obseg",
            },
            emptyPlug: {
              btnNewOrder: "Create New Order",
              title: "You don’t have any positions",
            },
            menu: {
              chart: "Grafikon",
              closePosition: "Zapri pozicijo",
              columns: "Stolpci",
              modifyOrder: "Spremeni naročilo",
              modifyPosition: "Spremeni pozicijo",
              newOrder: "Novo naročilo",
              resetAll: "Reset all",
              deleteOrder: "Izbriši naročilo",
            },
            oneClick: { deleteOrder: "Izbriši" },
            sections: {
              collateralPositions: "Collateral Positions",
              orders: "Naročila",
              positions: "Pozicije",
            },
            total: {
              assets: "Sredstva",
              balance: "Stanje",
              collateral: "Zavarovanje",
              commission: "Provizija",
              credit: "Dobroimetje",
              equity: "Sredstva",
              liabilities: "Obveznosti",
              margin: "Razlika",
              marginFree: "Brezplačno kritje",
              marginLevel: "Raven",
            },
          },
          timer: {
            marketWillOpen: "Market will be open in {days} {leftTime}",
            moreThenOneDay: "{numberOfDays} days",
            oneDay: "{numberOfDays} day",
          },
          tradeIsDisabled: {
            account: "Trading for this account is disabled on the server",
            collateral:
              "Trading is not available, because this symbol is collateral",
            disabled: "Trading is disabled",
            investor:
              "Trading is not available, because you are connected with an investor password",
            readOnly:
              "Trading is not available, because you have not accepted the risk warning",
            symbol: "Trade is disabled for this symbol",
          },
          hotkeys: {
            historyPanel: "History Panel",
            journalPanel: "Dnevnik",
            marketWatch: "Spremljanje trga",
            quickTrade: "Trgovanje z enim klikom",
            tradeForm: "Novo naročilo",
            tradePanel: "Trade Panel",
          },
          marketOpen: {
            time: "Market closed - will open at {time}",
            afterSeconds: "Market closed - will open in {time} sec",
          },
          expiredTimer: { seconds: "Expires in {time} sec" },
          corporateLink: {
            type: {
              clientAgreement: "Sporazum s stranko",
              riskDisclosure: "Razkritje tveganja",
              fdmDisclaimer: "Izjava o zavrnitvi odgovornosti FDM",
              clientAgreementAndRiskDisclosure:
                "Sporazum s stranko in razkritje tveganja",
              complaintsHandlingProcedure: "Postopek za reševanje pritožb",
              orderExecutionPolicy: "Pravilnik o izvrševanju naročil",
              clientCategorisationNotice: "Obvestilo o kategorizaciji strank",
              conflictsOfInterestPolicy: "Pravilnik o nasprotju interesov",
              dataProtectionPolicy: "Pravilnik o varstvu podatkov",
            },
          },
          margin: {
            floating: "spremenljivo",
            mode: { marketBuy: "Market buy", marketSell: "Market sell" },
            rangeMode: {
              value: "notional value",
              valuePerSymbol: "notional value per symbol",
              volume: "volume",
              volumePerSymbol: "volume per symbol",
            },
            showValue: "Show values in {currency} per lot",
            rates: "Margin rates:",
          },
          marks: { drag: "Drag to modify" },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  ),
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ui: {
          fullScreen: {
            disable: "Onemogoči celoten zaslon",
            enable: "Omogoči celoten zaslon",
          },
          journal: {
            btnOpen: "Dnevnik",
            columns: { message: "Sporočilo", source: "Vir", time: "Čas" },
            menu: {
              clear: "Počisti",
              debugMode: "Debug mode",
              exportFile: "Export to File",
            },
          },
          menu: {
            about: "About program",
            contact: "Contact us",
            brokerInformation: "Company information",
            chartSettings: {
              controls: "Chart Controls",
              grid: "Mreža",
              ohlc: "Pokaži OHLC",
              title: "Chart settings",
              askPrice: "Ask Price",
              crosshair: "Crosshair cursor",
            },
            connect: "Connect to account",
            language: {
              title: "Jazik",
              search: "Išči",
              nothingFound: "Language not found",
            },
            openDemo: "Open Demo account",
            openReal: "Open Real account",
            settings: "Nastavitve",
            shortcuts: "Shortcuts",
            theme: {
              blackWhite: "Black & White",
              blueRed: "Blue & Red",
              dark: "Dark Theme",
              editor: "Theme Editor",
              greenRed: "Green & Red",
              light: "Light Theme",
              neutral: "Neutral",
              templates: "Color Templates",
            },
            title: "Menu",
            tradingAccount: "Trading accounts",
            terms: "Pogoji uporabe",
            desktopPlatforms: "Desktop platforms",
            qrCode: {
              install: "Scan to install from {store}",
              downloadApk: "Scan to get Android APK file",
            },
            economicCalendar: "Gospodarski koledar",
          },
          screen: { back: "Nazaj" },
          mobile: { bottomNav: { quotes: "Kotacije" } },
          hotkeys: {
            sections: { navigation: "Navigation", view: "Pogled" },
            escape: "Prekliči",
            indicators: "Kazalniki",
            depthOfMarket: "Globina trga",
            objectTreePanel: "Object Tree",
            scrollRight: "Next Candle",
            scrollToStart: "Scroll Chart to Start",
            scrollLeft: "Previous Candle",
            scrollToEnd: "Scroll Chart to End",
            resetChartView: "Reset Chart",
            zoomIn: "Približaj",
            zoomOut: "Oddalji",
            fullScreen: "Poln zaslon",
            screenshot: "Save Chart as Image",
            title: "Shortcuts",
          },
          timezone: {
            title: "Time zone",
            city: {
              cairo: "Cairo",
              casablanca: "Casablanca",
              johannesburg: "Johannesburg",
              lagos: "Lagos",
              nairobi: "Nairobi",
              tunis: "Tunis",
              anchorage: "Anchorage",
              bogota: "Bogota",
              buenosAires: "Buenos Aires",
              caracas: "Caracas",
              chicago: "Chicago",
              denver: "Denver",
              elSalvador: "El Salvador",
              juneau: "Juneau",
              lima: "Lima",
              losAngeles: "Los Angeles",
              mexicoCity: "Mexico City",
              newYork: "New York",
              phoenix: "Phoenix",
              santiago: "Santiago",
              saoPaulo: "Sao Paulo",
              toronto: "Toronto",
              vancouver: "Vancouver",
              almaty: "Almaty",
              ashgabat: "Ashgabat",
              bahrain: "Bahrain",
              bangkok: "Bangkok",
              kolkata: "Kolkata",
              colombo: "Colombo",
              dhaka: "Dhaka",
              dubai: "Dubai",
              hongKong: "Hong Kong",
              jakarta: "Jakarta",
              jerusalem: "Jerusalem",
              karachi: "Karachi",
              kathmandu: "Kathmandu",
              kuwait: "Kuwait",
              manila: "Manila",
              muscat: "Muscat",
              nicosia: "Nicosia",
              qatar: "Qatar",
              rangoon: "Rangoon",
              riyadh: "Riyadh",
              saigon: "Saigon",
              seoul: "Seoul",
              shanghai: "Shanghai",
              singapore: "Singapore",
              taipei: "Taipei",
              tehran: "Tehran",
              tokyo: "Tokyo",
              reykjavik: "Reykjavik",
              adelaide: "Adelaide",
              brisbane: "Brisbane",
              perth: "Perth",
              sydney: "Sydney",
              amsterdam: "Amsterdam",
              athens: "Athens",
              belgrade: "Belgrade",
              berlin: "Berlin",
              bratislava: "Bratislava",
              brussels: "Brussels",
              bucharest: "Bucharest",
              budapest: "Budapest",
              copenhagen: "Copenhagen",
              dublin: "Dublin",
              helsinki: "Helsinki",
              istanbul: "Istanbul",
              lisbon: "Lisbon",
              london: "London",
              luxembourg: "Luxembourg",
              madrid: "Madrid",
              malta: "Malta",
              moscow: "Moscow",
              oslo: "Oslo",
              paris: "Paris",
              prague: "Prague",
              riga: "Riga",
              rome: "Rome",
              stockholm: "Stockholm",
              tallinn: "Tallinn",
              vienna: "Vienna",
              vilnius: "Vilnius",
              warsaw: "Warsaw",
              zurich: "Zurich",
              auckland: "Auckland",
              chatham: "Chatham",
              fakaofo: "Fakaofo",
              honolulu: "Honolulu",
              norfolk: "Norfolk",
            },
          },
        },
      },
      Symbol.toStringTag,
      { value: "Module" },
    ),
  );
export { o as a, a as b, i as c, e as s };
